### ISSUE TITLE
"Extend Script" button doesn't show up in scene tree dock when it's supposed to

### ISSUE THREAD

**Issue by afterlightgames** [godotengine/godot#100074]
### Tested versions

v4.4.dev3.official [f4af8201b]
v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6603) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

I recently opened a [discussion](https://github.com/godotengine/godot-proposals/discussions/11289) suggesting to add the "extend script" button to the top of the scene tree dock and user @Flynsarmy discovered that surprisingly, the button already _does_ exist there, but for some reason never shows up. This seems like a bug, as the intended behavior seems to be to show the extend script button when selecting a custom type but that doesn't happen. (See https://github.com/godotengine/godot/blob/1f47e4c4e3a09a422e96880a7918d986dd575a63/editor/scene_tree_dock.cpp#L2802-L2810)
I'm not an expert on Godot architecture by any means, so maybe this isn't what I think it is, but I figured it was worth reporting because it's a quality of life feature I'd like to see added to the engine and it doesn't seem well known.

![Image](https://github.com/user-attachments/assets/a1aeb3e2-49ec-4fe9-9499-95c8692de333)

### Steps to reproduce

- Follow the steps to create a new plugin
- Create a script to represent a custom type and initialize it in the plugin script
- Restart the editor
- Add your custom type to the scene tree and select it
- Although the scene tree dock code suggests that the extend script button should show up, it doesn't

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/18030489/mrp.zip)

**Comment by KoBeWi** [comment]
I can't reproduce the bug. Creating a custom type properly sets the custom script. idk how you created the first instance, but another one works properly.
![image](https://github.com/user-attachments/assets/2aa72411-69ba-4a28-9070-170e0b36ec52)
Tested in dev7.

**Comment by afterlightgames** [comment]
> I can't reproduce the bug. Creating a custom type properly sets the custom script. idk how you created the first instance, but another one works properly. ![image](https://github.com/user-attachments/assets/2aa72411-69ba-4a28-9070-170e0b36ec52) Tested in dev7.

Seems to have been fixed in dev7

**Comment by Flynsarmy** [comment]
Not sure if this is the same problem, but in 4.4.dev7 I have the following and aren't seeing an Extend Script button:
foo.tscn scene which is just a Node3D with foo.gd script:
```
extends Node3D
class_name Foo
```
bar.tscn scene that has an inherited Foo child. Clicking on the child shows a detach script button but no extend script button:
![Image](https://github.com/user-attachments/assets/88124cad-0c21-434b-b0f9-0671bc133c5c)

**Comment by KoBeWi** [comment]
Note that custom types created before the custom type metadata was added will not have the base script assigned (recognized by white script icon instead of gray), so the Extend option will not show. You need to re-create them or add it manually in the file.

**Comment by Flynsarmy** [comment]
I took a screencast on 4.4.dev7 to show it still not working.
https://github.com/user-attachments/assets/8061e978-55d8-4b50-9b0a-6392c7dd954b

**Comment by afterlightgames** [comment]
@Flynsarmy As far as I can tell the feature is only supported on custom nodes added by an editor plugin via `add_custom_type()`. Showing the button for custom class_name nodes and instantiated scenes still isn't supported, but I don't think that's necessarily a bug.

**Comment by Flynsarmy** [comment]
Ah, that's what I missing. Thanks for the explanation!

**Comment by KoBeWi** [comment]
`class_name` nodes *are* supported.

**Comment by Flynsarmy** [comment]
Should this issue be reopened then? My screencast shows it not working.

**Comment by KoBeWi** [comment]
You need to create the custom node, not attach a script to it.
Make a `class_name` script and then make instance via Add Child Node or as a root of a new scene.

**Comment by Flynsarmy** [comment]
Is there a reason we wouldn't want it working with inherited nodes with scripts? The workflow in my video of making a scene, attaching a script then loading that into another scene is very common in Godot and being able to quickly extend would be very handy.

The current functionality is a little confusing IMO.

**Comment by KoBeWi** [comment]
Well, if you have custom type, it's more expected that you create instance by making a node of that type, not attaching a script to a node of a different type.
Making instance of a scene instantiates it as-is, so the script metadata is unchanged. If you created a node, but want to change it to custom type, just use Change Type, like you'd do with regular type.

**Comment by afterlightgames** [comment]
I think to ease this kind of confusion the extend script button ought to be shown if a script is present no matter what. It's not very clear why attaching a custom class to an existing node wouldn't show the extend script button as long as the node is the correct type since it would effectively behave exactly the same way as if you added it the 'expected' way.

**Comment by KoBeWi** [comment]
Whether the dock shows Extend or Detach script is determined by custom script metadata, which stores the script the node was originally created with, whwich serves the same purpose as the node's actual type. Overwriting this metadata when attaching a script would be like changing the node type by attaching a different script. Like, imagine attaching CharacterBody2D script to Node2D would change the node type to CharacterBody2D. That's not a correct behavior.

**Comment by scotmcp** [comment]
Well I can confirm the button does not appear in the toolbar despite it being present in the context menu.

Godot v4.4.dev7 - Linux Mint 22 (Wilma) on X11 - X11 display driver, Multi-window, 4 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (nvidia; 550.120) - AMD Ryzen 7 5700X 8-Core Processor (16 threads)

![Image](https://github.com/user-attachments/assets/74c69560-9d30-49a6-985d-acc093911c9e)
