### ISSUE TITLE
Performance regressions in 2D Android builds in newer dev versions

### ISSUE THREAD

**Issue by Ptkstefano** [godotengine/godot#100576]
### Tested versions

- Performance is good up to Godot 4.4 dev 3
- The problem starts in Godot 4.4 dev 4 and is still present in dev 5 and dev 6

- Problem is only noticeable in android builds of the game.

- I'm on mobile renderer

### System information

Tested on Samsung SM G996b

### Issue description

I'm developing a 2D game that uses many sprites and constant scene instantiation and no lighting at all. 4.4 dev 3 builds or previous can hold 60fps in my device until up to a certain number of objects in my game and that works for standard gameplay. Builds made in dev 4 or one of the sequent dev builds hold a lower baseline performance and performance goes down substantially once I start adding more nodes. There are noticeable stutters during gameplay and node instantiation seems to have a particular hard hit on performance that was not present before.

Because I've been having this problem in mobile builds of the game it's hard to diagnose and profile exactly what is causing these performance regressions outside of the editor. I'm going to dive deeper on it now because I was planning on staying on Dev 3, but an unrelated bugfix is important for my game so I have to upgrade.

Same scene in both versions:

![Image](https://github.com/user-attachments/assets/9b648c21-b8c4-4cf3-a28d-9b620a50229a)
Dev 3, stable 60 fps

![Image](https://github.com/user-attachments/assets/424235b1-faa2-482a-aa1f-ff74180c777c)
Dev 6, wavering 45fps and stuttering

### Steps to reproduce

I'm willing to share my project and details on it if it helps, but it's unclear to me exactly what causes it right now.

### Minimal reproduction project (MRP)

 I'm willing to share my project and details on it if it helps, but it's unclear to me exactly what causes it right now.

**Comment by clayjohn** [comment]
Sounds like a duplicate of https://github.com/godotengine/godot/issues/99420 which should be fixed in dev7

Without an MRP or any details, there really isn't anything we can do besides wait for dev 7 and see.

If you provide an MRP we can investigate further

**Comment by Ptkstefano** [comment]
> Sounds like a duplicate of [#99420](https://github.com/godotengine/godot/issues/99420) which should be fixed in dev7
> 
> Without an MRP or any details, there really isn't anything we can do besides wait for dev 7 and see.
> 
> If you provide an MRP we can investigate further
> 
> Oh, also, what device are you testing on? You forgot to fill in the system information

I'm unsure if it's related to the same issue since that was related to lighting, am I correct? My game uses no 2D lights at all. I'm going to do some more heavy lift testing later on and see if I can pinpoint the issue.

I've had the problem in all my android devices so I was unsure how to proceed with the system information.

**Comment by clayjohn** [comment]
It would be helpful for you to share the system information. We had a regression with Adreno devices that was fixed recently. So if you have only tested on Adreno devices, then we have a likely culprit.

**Comment by Ptkstefano** [comment]
> It would be helpful for you to share the system information. We had a regression with Adreno devices that was fixed recently. So if you have only tested on Adreno devices, then we have a likely culprit.

Uh oh, this could be it. My phone, where the performance is really worse, is one of those devices. I've just noticed that on my old and generic android tablet, while the game does not run great, there are no new performance issues.

**Comment by clayjohn** [comment]
In that case there is a good chance this will be fixed by https://github.com/godotengine/godot/pull/100028

Dev7 should be released this week. So please test it out and update here with the result.

**Comment by Ptkstefano** [comment]
> In that case there is a good chance this will be fixed by [#100028](https://github.com/godotengine/godot/pull/100028)
> 
> Dev7 should be released this week. So please test it out and update here with the result.

Will do, many thanks!

**Comment by Ptkstefano** [comment]
> In that case there is a good chance this will be fixed by [#100028](https://github.com/godotengine/godot/pull/100028)
> 
> Dev7 should be released this week. So please test it out and update here with the result.

The problem remains pretty much unchanged in Dev7. I tried playing around with v-sync, batching values and with the different rendering methods to no impact at all. Iit seems to me like the overhead of the engine is simply a ton more demanding on my project on the mobile build. I'm trying to profile on the editor on the PC and it seems like it's pretty similar between both versions.

Right now I'm trying to get my hand on some other android devices to see if this performance discrepance also presents on phones other than mine.

In my project on a blank map with pretty much no processing and with a minimal amount of sprites objects other than a few tilemaps and my autoload scripts my phone already struggles averaging 45fps while it could hold 60fps for a long time before. I'm having a hard time trying to figure out if it's something specific in my game causing these slowdowns, 

Is there anything I could do to help with profiling this out?

**Comment by clayjohn** [comment]
> Is there anything I could do to help with profiling this out?

Yes, you could provide us with an MRP. That way contributors can reproduce the bug and find a solution.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened

**Comment by clayjohn** [comment]
For posterity if this was indeed a duplicate of https://github.com/godotengine/godot/issues/99420, then it should also have been fixed by https://github.com/godotengine/godot/pull/101072 which was merged for Beta 1!

**Comment by Ptkstefano** [comment]
> For posterity if this was indeed a duplicate of [#99420](https://github.com/godotengine/godot/issues/99420), then it should also have been fixed by [#101072](https://github.com/godotengine/godot/pull/101072) which was merged for Beta 1!

I still have the performance problems, but I have not been able to figure out exactly what is that causes them other than that it started happening once I upgraded from 4.4 dev 3 to 4.4 dev 4. I have been developing always on the most up-to-date version since I need some of the resource loading bugfixes that affected my game in the previous versions and also because I was hoping that Beta 1 would bring some changes to this, but there have been no improvements.

What is weird to me is that I have not been able to pinpoint this to any particular element in my game. It simply is that the baseline FPS on my game running in my phone simply went down a lot even before I even start populating the game's map so if I had to guess it might have something to do with tilemaps (I'm using multiple tilemap layer nodes at all times) as it's pretty much the only element I start out with. On the editor I haven't been able to profile this issue. Once I start actually playing, having too many sprites or process logic seemed to impact the game the same regardless of engine version. 

I have not been able to completely rule it it's a problem with my android device specifically as I could not get my hands on another different devices. I have simply decided that it's more worth it to pretend it's a problem on my end right now and to keep working on the game. I did do same A/B testing between engine versions back in december and was able to confirm it's this specific version that causes issues, but I'll see if I can backport my project to dev3, just to be sure, and if I can I'll try again to analyse the profiler for changes on the PC version. I might have missed this ocurring on the PC since the baseline FPS is way higher.

I'm sorry I couldn't be of more help. I really have not been able to figure out if it's anything in my project that causes this issue. I'll take another look into this right now to see if I can bring in any more info. If there is anything specific I could do, please, let me know, many thanks!

**Comment by Ptkstefano** [comment]
Ah, so! I just tried out 4.4 beta 3 and it works flawlessly again! I skipped beta 2, but something in the past two releases has fixed the problem and it runs just as good now, without the pesky bugs that I was running into in dev 3. Thanks to the team :)

**Comment by clayjohn** [comment]
Thanks for the update! I'm glad to hear that this was resolved :)

**Comment by clayjohn** [comment]
Given that this was fixed after Beta 1, it is likely the same root cause as https://github.com/godotengine/godot/issues/101905 which was fixed by https://github.com/godotengine/godot/pull/101972
