### ISSUE TITLE
[4.4 Beta 2] Lightmaps too dim when using directional toggle

### ISSUE THREAD

**Issue by ricky-daniel13** [godotengine/godot#102300]
### Tested versions

- Reproducible in v4.4.beta2.official [a013481b0]
- Not reproducible in v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.4.beta2 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.6603) - AMD Ryzen 3 2200G with Radeon Vega Graphics (4 threads)

### Issue description

Lightmapping static lights produces way dimmer lights when lightmapping with the "directional" option enabled. Might be a regression of pull request #95888

Before rendering lightmaps
![Image](https://github.com/user-attachments/assets/f963c46f-e34a-4d57-8abc-853c3094ca2a)

After rendering non-directional lightmaps
![Image](https://github.com/user-attachments/assets/897198cd-652f-4659-8392-465f6a29eb4f)

After rendering directional lightmaps
![Image](https://github.com/user-attachments/assets/38d687bd-1df4-49b0-8bbe-c9b8b5ee1380)

Rendering directional lightmaps in stable version 4.3
![Image](https://github.com/user-attachments/assets/f0e573ae-21e7-4e2a-aa98-ebe02290f799)

### Steps to reproduce

- Open the scene "TestScene.tscn"
- Observe the very dim baked lighting.
- Click on the Lightmap3D node
- Under "Data", click to replace the Light Data file, and pick "TestScene.lmbake" (A lightmap baked without the directional option)
- Observe the almost correctly lit lighting.
- Disable the Lightmap3D node.
- Observe the correct lighting.
(Instead of picking lightmaps, the user can disable the directional toggle and render the lightmap again to observe the same results)

Following this steps on the 4.3 MRP with lightmaps rendered on 4.3 lead to lightmaps without such dramatic differences between them or with the realtime lighting.

### Minimal reproduction project (MRP)

4.4 beta 2 MRP:
[lightmap4dot4beta2.zip](https://github.com/user-attachments/files/18630150/lightmap4dot4beta2.zip)
4.3 MRP:
[lightmap4dot3.zip](https://github.com/user-attachments/files/18630152/lightmap4dot3.zip)

**Comment by BlueCube3310** [comment]
See https://github.com/godotengine/godot/pull/96114#discussion_r1745739515

In summary, since 4.0 static lights are baked with a slightly incorrect factor, which makes them appear softer than intended. Before 4.4 the directional lightmaps would be baked with incorrect coefficients that caused the directional data to be too intense, so this issue wasn't noticeable. Since dev-2 the coefficients have been corrected, so this issue has become apparent

**Comment by Calinou** [comment]
I tested https://github.com/godotengine/godot/pull/101141 on the MRP and it doesn't appear to resolve the issue:

### 4.4.beta2

![Image](https://github.com/user-attachments/assets/909ceb6b-757a-4b69-acc2-3d17deea7413)

### PR (before clearing LightmapGIData)

![Image](https://github.com/user-attachments/assets/a03b30c7-904e-4762-b224-57c1c8bf57aa)

#### With EXR imported as Lossless

![Image](https://github.com/user-attachments/assets/f1dba6cf-80bd-4023-9967-8c7e06056371)

**Comment by Rudolph-B** [comment]
There is effectively 2 parts to the problem.

The first is that attenuation based on the angle to the surface normal happen twice. The first time is in `trace_direct_light()` in `lm_compute.glsl` when creating the lightmap and then again when sampling the light map in `scene_forward_clustered.glsl` (Or equivalent for the specific renderer).

Fixing this results in to little attenuation and lights being to bright as can be seen below:
| Dynamic | Double attenuation | Single attenuation | Sqrt attenuation #102723 |
|--------|--------|--------|--------|
| ![Image](https://github.com/user-attachments/assets/53cc3fc3-3aaa-423c-9ac7-2c6f26749a8d) | ![Image](https://github.com/user-attachments/assets/116c30fa-dcc7-45d0-8f1b-952d5f7db25b) | ![Image](https://github.com/user-attachments/assets/49c9f419-8ad4-4fdf-a17d-31eb28bd7fcb) | ![Image](https://github.com/user-attachments/assets/f1cdbdf0-9fa8-4935-898b-a79a2ce38957) |

This is caused by L1 spherical harmonics not really being capable of simulating light3D nodes. This is the second problem. This is mostly do to the L0 constant term and only sampling from the upper hemisphere. Relevant code:
https://github.com/godotengine/godot/blob/f42e612da286b14b3a50eff7935615b3bc132c37/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1706-L1709
 
In 4.3 we got around this problem by having large SH coefficients, this caused other problems that were fixed in #95888. Tampering with the coefficients would run into similar problems.

Currently I think the best solution we have for 4.4 is to add a warning when people are trying to bake light3D nodes with the directional setting. This warning should state something along the lines of that baking light sources using directional settng is unintended. This at least won't risk breaking any other lighting and I believe to be true since the math doesn't really support it. 

Additionally to this we could add square root attenuation (#102723) for when people ignore the warning. This has no basis in  math or literature that I could find, but would just result in a bit more visually pleasing lighting while having little impact on the other scenes:
| Type | Current | Sqrt |
|--------|--------|--------|
| Static | ![Image](https://github.com/user-attachments/assets/09033c35-8724-42ce-99c5-6bcb399a2508) | ![Image](https://github.com/user-attachments/assets/6ec246aa-37d0-44ec-bf0b-2e170cab7aad) |
| Dynamic | ![Image](https://github.com/user-attachments/assets/da297d2a-89b0-41eb-9c64-7929f4469437) | ![Image](https://github.com/user-attachments/assets/a2630df2-c8a8-4686-be07-ce7ba7bdbf6a) | 

Made using: [sh-lightmaps.zip](https://github.com/user-attachments/files/18814046/sh-lightmaps.zip) from #96114

**Comment by Rudolph-B** [comment]
@clayjohn I think you are correct are mixing methods. We would need to hand directly encoding the lights a bit differently.  The method in [StupidSH36](https://www.ppsloan.org/publications/StupidSH36.pdf ) are for lights with an area, where as we us point lights. 

I believe the correct coefficients for direct point lights would be `L0 = 0` and `L1 = 1.0`. The resulting math ends up being indistinguishable from the dot product used in `trace_direct_light()`. This can be seen below:
| Dynamic | Non-Directional | Directional (L1 packing disabled) |
|--------|--------|--------|
|![Image](https://github.com/user-attachments/assets/c1576482-8b09-4277-93d4-960d7dca7304)| ![Image](https://github.com/user-attachments/assets/88b377e3-7ffa-4d43-aa79-dba2e6962e91) | ![Image](https://github.com/user-attachments/assets/47089dff-4b3e-4fac-a444-2f50bded0e0e)|

Using two separate sets of SH coefficients would require us to reassess how we do L1 packing. The current method relies on dividing by the L0 coefficient and L0 in being in a specific ratio to L1. Both of these assumptions would no longer be true. 

I have made two attempts at resolving this. The first just plainly disables L1 packing. The second attempts two use a sigmoid function to pack the L1 coefficients. This kinda works but it lacks the flexibility of the original method that allowed it to scale to the relative brightness and results in significant artifacts. I'm still trying to find a better method to do this.

I have made draft PRs for these methods that contain a bit more detail. They are still in a rough state and methods have only been implemented for the forward+ renderer so far.
 - Without Packing #103204
 - With Packing #103203
