### ISSUE TITLE
Anti aliasing on Polygon2D / Line2D

### ISSUE THREAD

**Issue by rmichaluszek** [godotengine/godot#10241]
Would be really great if that exist. At some points and types of games, Polygon2D fits way better than sprites.

**Comment by reduz** [comment]
thanks!


On Thu, Aug 10, 2017 at 5:40 PM, Rafał Michałuszek <notifications@github.com

**Comment by vunnysher** [comment]
After this update it will be possible just to use old 3.x version project, and import it to the updated one with aa on Polygon2D? Im curious because i want to know if i can start a project already on current 3.0, or do i have to wait for an updated version.

**Comment by toger5** [comment]
Startinga project in3.0 is still at ypur own risk. It can be possible, that there is something broken which u really need. Of course starting never hurts from a learning and testing experience.
I also dont know when aa for poly2d is planned. I implemented it for styleboxes recently and looked at the line 2d code. It would be feasible to implement for lines.
Cant guarantee anythi g though...

**Comment by insomniacUNDERSCORElemon** [comment]
There seems to be a conflict with HDR and AA, if you turn HDR off Polygon2D AA should work (once enabled per-node) should work on most hardware when running on a desktop platform (NOT HTML5).

Line2D and many GDscript functions still need the option to use AA.

More detailed notes on current AA and a test project [here](https://www.reddit.com/r/godot/comments/98m7i4/hdr_conflicts_with_aa_also_geometry_experiments/).

**Comment by insomniacUNDERSCORElemon** [comment]
Update from my previous comment: AA seems to have regressed, at least as of 3.1 Alpha (4 and 5). 

It no longer functions at all, and other options (GLES2 and transparency per-pixel) don't seem to restore it either.

**Comment by lucaslcode** [comment]
I'm using polygons with AA in my project in 3.1. I found that Polygon2D doesn't antialias, but using draw_colored_polygon works when I disable HDR.

**Comment by akien-mga** [comment]
Fixed by #33857.

**Comment by RyanJEC** [comment]
I seem to still be having hard pixel edges with Polygon2D in 3.2 beta 3

**Comment by yetha** [comment]
On 3.2 beta 3, toggling on antialiased for Line2D makes it bigger by one pixel, no anti-aliasing.

**Comment by insomniacUNDERSCORElemon** [comment]
@yetha I've mentioned it elsewhere (and to RyanJEC on the pull request that akien linked to above), make sure that you've tried disabling HDR as AA won't work with it on (*unless* maybe 2D framebuffer is used). Also it doesn't work in HTML5 and some hardware/graphics drivers might not support it either.

Although as I also mentioned on the pull request, it seems to have introduced a rendering issues with AA (resulting in strings)... so it isn't really usable for polygons anyways.

**Comment by lukaskotik** [comment]
It still happens for me on 3.2.1. I have to turn off the HDR to have antialiasing. If this is a "feature" this should be written in the docs.
