### ISSUE TITLE
Tooltips reappear after being closed

### ISSUE THREAD

**Issue by quinnyo** [godotengine/godot#104205]
### Tested versions

Reproduced in v4.5.dev3.official [55fc6e73f], v4.4.stable.official [4c311cbee], v4.3.stable.official [77dcf97d8] and v1.0.stable.custom_build
(it says custom_build but it's the win64 binary I just downloaded)

### System information

Godot v4.4.stable - Windows 11 (build 22631) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 32.0.101.5768) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 threads)

### Issue description

This issue is concerned with the behaviour of tooltips and the rules that govern *when a tooltip should appear*. I've edited this issue in an attempt to clarify this.

When a tooltip is dismissed/closed (hidden in response to user input), *no user input is required to cause it to appear again*.
Specifically, tooltips will reappear without the mouse being moved at all.
The behaviour occurs in running projects as well as the editor and affects all versions of Godot, as far as I can tell.

The expected behaviour, and that of typical desktop software requires the cursor to exit the bounds of the element that triggered the tooltip, before the tooltip *is allowed* to be shown again. I say *"is allowed"* because the other rules still apply -- the rules that governed the initial appearance of the tooltip, i.e. mouse lingers over the element.

In the video, a tooltip for a node in the scene tree appears and I press the Escape key to dismiss it. The mouse/cursor is not moved (other than at the start/end). The tooltip reappears and Escape is pressed again. This is repeated several times.

https://github.com/user-attachments/assets/ffde8d68-5348-4782-ae75-9d1005d4f72c

### Steps to reproduce

1. hover mouse over node in scene tree
2. wait. a tooltip will appear
3. press escape to dismiss the tooltip
4. wait. a tooltip will appear

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
Each video seems to show 3 separate issues, I think. I would heavily recommend reporting each individually.
Regardless, the first two are likely bugs. The last one is absolutely _not_ a problem anymore because the behaviour has changed.

For the first issue, note that by dismissing the tooltip with ESC, the tooltip timer is also reset. If ESC is held and the tooltip timer is waited out, the tooltip does not appear. This hints at the possible oversight.

**Comment by quinnyo** [comment]
I'd be happy to split the issue up, but I'm not seeing the differences that you're seeing. What are the three (or two?) separate issues?

The issue I was trying to report and that is common to all three videos is that the tooltip is shown more than once without the cursor (re)entering the region that triggers the tooltip. The reason I included more than one way to dismiss a tooltip, and different controls/tooltips was to demonstrate that commonality.

The relevant behaviour in the second and third videos appears identical to me. The tooltip is dismissed when the mouse is moved, the mouse lingers, and then the tooltip reappears. I'm not sure what the behaviour is that has changed.

> If ESC is held and the tooltip timer is waited out, the tooltip does not appear.
I just tried this and found that the tooltips do appear. This is on 4.4, with nodes in the scene tree like in the video.

**Comment by Mickeon** [comment]
> The relevant behaviour in the second and third videos appears identical to me. The tooltip is dismissed when the mouse is moved, the mouse lingers, and then the tooltip reappears. I'm not sure what the behaviour is that has changed.

It's worth first noting that there's a difference between the **default** tooltip _(the one with black background and no text formatting)_, and a **custom** tooltip _(like the one used in the Inspector for documentation tooltips)_. The logic that requires them to appear is the same, but dismissing it may be different.

In the first video, the tooltip appears again even after it has been dismissed manually with `ESC`. This is objectively a bug. Probably also means the tooltip timer is reset when it shouldn't be.

In the second video, a nudge of the cursor causes the **custom** tooltip to disappear, even within the bounds of the label. It's _possible_ this is intentional, because as you're scrolling through each property's description, you may not want the tooltip to linger for too long. On the other hand, it makes clicking on the tooltip's links almost impossible. (@dalexeev )

In the third video, a nudge of the cursor causes the **default** tooltip to disappear, even within the bounds of the Button. This behavior is not present in `4.4`. If the cursor is moved to a new position, but the tooltip's string would still be the same, the tooltip is not dismissed.

**Comment by kitbdev** [comment]
Both issues should fixed by 4.5dev2

**Comment by quinnyo** [comment]
@Mickeon thanks for the explanation (over a month ago!). I created #106059 to track the documentation tooltip dismissal issue and edited this one to hopefully clarify the focus.

@kitbdev I just tested and I can still reproduce the behaviour in 4.5dev**3**. Was there a specific change/PR you knew about or did you arrive at that from testing?

**Comment by kitbdev** [comment]
My bad, I was testing on single window mode. This only happens in multi-window mode.
