### ISSUE TITLE
Godot 4.4-stable: Opening menu context items, hints and popup windows cause entire program to freeze for a long time until they close.

### ISSUE THREAD

**Issue by reubenmanning** [godotengine/godot#104484]
### Tested versions

- Reproducible in Godot_v4.4-stable_mono_win64
- Reproducible in Godot_v4.4.1-rc2_mono_win64
- Not reproducible in Godot_v4.5-dev1_mono_win64

### System information

Godot v4.4.stable.mono - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 32.0.13031.3015) - AMD Ryzen 7 7800X3D 8-Core Processor (16 threads)

### Issue description

Doing any of the following will cause the Godot editor to freeze:

- Clicking on a menu item
- Opening hint by hovering
- Triggering a editor popup window

The program unfreezes after these windows disappear.

### Steps to reproduce

- Create a new Godot project in 4.4 stable (.NET) using Forward+ renderer
- Once the project in open in the editor, click on any of the menu items. The program should freeze.
- Attempt to click on empty space in the default empty scene. The program should unfreeze.
- Hover over any UI items which display a hint. The program should freeze again.
- Move the mouse away from the hint item and the program should unfreeze.

### Minimal reproduction project (MRP)

[test-freezing.zip](https://github.com/user-attachments/files/19403335/test-freezing.zip)

**Comment by AThousandShips** [comment]
To confirm, this _only_ happens on the mono version? Not on the non-mono version?

**Comment by reubenmanning** [comment]
> To confirm, this _only_ happens on the mono version? Not on the non-mono version?

I just did a quick test on the non-mono version. It doesn't seem have the same freezing issue.

**Comment by AThousandShips** [comment]
Please test [4.4.1.rc2](https://godotengine.org/article/release-candidate-godot-4-4-1-rc-2/) as well, since this doesn't happen in 4.5.dev1 it is likely something that was fixed and that might have been cherry picked

**Comment by reubenmanning** [comment]
I have noticed if I turn off the display setting "AMD Premium FreeSync Pro" in my driver, the issue seems to disappear.

**Comment by donn-xx** [comment]
v4.4.stable.official [4c311cbee]
Godot v4.4.stable - Ubuntu 24.04.2 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 550.120) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 threads)

Same here. Mostly on tooltips in the gdscript editor. When one opens, and the gods are angry, Godot freezes. I have to hard kill it and restart.

**Comment by RawsharkTang** [comment]
[Same here.](https://github.com/godotengine/godot/issues/104111).

**Comment by raulsntos** [comment]
I'm a bit confused by this issue. It says it's reproducible in 4.4 but not reproducible in 4.5, so does that mean it was fixed and can be closed? In any case, it doesn't look like a .NET issue to me, perhaps it may be a rendering issue.

**Comment by precup** [comment]
@reubenmanning @donn-xx Is this reproducible in any 4.5 version for either of you?

I'm unable to reproduce this on Linux or Windows, but I also have an Nvidia card, and the freesync setting makes this seem like an AMD issue.

> Godot v4.4.stable.mono - Windows 10 (build 19045) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.3713) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

**Comment by reubenmanning** [comment]
@precup I haven't been able to replicate the issue on the latest 4.5 beta versions since the new AMD GPU drivers were released. Turning Freesync on and off doesn't make a difference anymore.

It's possible what I originally experienced was the result of a bad driver.

**Comment by BuzzyBzzz** [comment]
I can confirm that this issue is still present on all versions of Godot 4, and is probably tied to the GPU & GPU Driver. I'm able to fix it by using the 32bit version of the engine, but that did cause another strange issue that I'm going to report separately.

**My Specs**
GPU: Intel Arc 140V (Xe2 architecture, integrated, 128 MB dedicated + 8 GB shared)
CPU: Intel Core Ultra 7 256V (Lunar Lake)
RAM: 16 GB LPDDR5X-8533 (soldered)

A few things that I tried to fix it:
I've tried replicating what @reubenmanning did by turning off Intel's version of gsync/freesync, but I saw no improvement.
<img width="637" height="357" alt="Image" src="https://github.com/user-attachments/assets/fd27c359-be80-4696-98bb-aa22b2817117" />

I also set windows to only use high-performance for Godot. Again; no improvement. I tried the inverse, and also no changes.
<img width="1248" height="585" alt="Image" src="https://github.com/user-attachments/assets/0e1b1b65-16d0-4e9b-8b81-dc41de5c1984" />

I reverted to two older arc drivers to rule out a bad update, but the issue persisted in both.

While it's probably not ideal I have found 2 working solutions for anyone else with the problem.
1. Turn on single window mode.
2. Use the 32-bit build of Godot (Single window can stay disabled.) Doing this prevents the 64-bit editor from opening unless the editor data is manually deleted.

Let me know if I should make a new bug report for this instead of commenting since in my case it happens on both mono and non-mono.

**Comment by BuzzyBzzz** [comment]
I've managed to solve this on my Intel PC (without using 32-bit or single-window mode) by manually locating & installing the generic drivers for my graphics card instead of the OEM-approved ones that Intel distributes through their update tools.
The latest driver provided through their updater was around 4 months older than the generic version so I'm guessing this was an issue that got fixed in a more recent update.
