### ISSUE TITLE
AccessKit Unix version 0.14 causes crash in Godot 4.5Dev3 when viewing Debug>Errors on Linux

### ISSUE THREAD

**Issue by Stealcase** [godotengine/godot#107024]
### Tested versions

- Reproducible in v4.5.dev3
- Not reproducible in v4.4.1.stable

### System information

Godot v4.5.dev3 - Fedora Linux 41 (Workstation Edition) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (nvidia; 570.133.07) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

Godot consistently crashes whenever I open the Debugger Panel then go to the Errors tab (the one labeled "Feil" to the right of "Stack Trace", its in Norwegian).
- This occurs regardless of the project size or number of script errors.

![screenshot showing the menu](https://github.com/user-attachments/assets/da23ad15-a914-485d-a334-9fdc15f5b365)

I ran Godot through the terminal to see if I could get some better error message, and found this:
```
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.14.0/src/context.rs:61:78:
called `Result::unwrap()` on an `Err` value: InterfaceNotFound
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps to reproduce

Launch any Godot project in Godot 4.5dev3 and navigate to the Debug menu and select the "Errors" tab, causing a crash. 

### Minimal reproduction project (MRP)

N/A

reproducible in a fresh new project

**Comment by Stealcase** [comment]
~Might be resolved when https://github.com/godotengine/godot/pull/105595 is in the next dev build, since from my limited understanding I'm guessing it might be trying to use Accessibility features when there is no screenreader.~

Nevermind, seems that PR is already  in v4.5.dev4, and I could reprdouce it there.

**Comment by bruvzg** [comment]
If you are not using screen reader, it should be already fixed by https://github.com/godotengine/godot/pull/106783

**Comment by DataTriny** [comment]
@bruvzg I'm sorry but I think #106783 was a mistake. AccessKit already guarantee that the accessibility tree will only be initialized if an assistive technology is running. Furthermore, why would this crash occur only after an action in the UI? I will take the blame for the unhelpful error messages.

If you can reproduce this yourself, could you please do it with a debug version of the C bindings so we get nicer stack traces? I can see a few places that could generate this error.

I will try to squeeze better error reporting in the next version or so.

**Comment by bruvzg** [comment]
No, I was not able to reproduce it, it likely related to window creation and destruction in a rapid succession (tooltip), which might be removed before pending note tree updates are done.

**Comment by Stealcase** [comment]
Just tested on  Godot 4.5 dev5 and unfortunately can still reproduce crash 100% consistently. 

## New info
- **Crash occurs whether Orca Screenreader is enabled or not.**
- Crash occurs on all Debugger tab menu items (except the first default "stack trace", which it starts on).

![Showing all the godot debug tabs](https://github.com/user-attachments/assets/e2209464-b234-4fea-a40f-8260b956aff9)

I have a vanilla install of Fedora (was Fedora 40 originally, upgraded to 41). Orca was part of the install.

### Orca logs

There seems to be a warning when enabling ORCA that AT-SPI socket doesn't exist. This might just be a temporary issue (its a warning after all, not a crash), but I did make a note of it.
```
(orca:19850): dbind-WARNING **: 18:43:19.878: AT-SPI: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-3VXR72/socket: No such file or file catalog
```

This initial warning is not is not connected to Godot, but the subsequent warnings are after launching Godot.
I'm Including them here just in-case it could be helpful.

```
(orca:19850): dbind-WARNING **: 18:43:22.053: AT-SPI: Error in GetItems, sender=:1.43, error=Unknown object '/org/a11y/atspi/cache'

(orca:19850): dbind-WARNING **: 18:43:28.012: AT-SPI: Error in GetItems, sender=:1.44, error=Unknown object '/org/a11y/atspi/cache'

(orca:19850): dbind-WARNING **: 18:43:45.736: AT-SPI: Error in GetItems, sender=:1.45, error=Unknown object '/org/a11y/atspi/cache'

(orca:19850): dbind-WARNING **: 18:43:59.669: AT-SPI: Error in GetItems, sender=:1.46, error=Unknown object '/org/a11y/atspi/cache'

(orca:19850): dbind-WARNING **: 18:44:31.733: AT-SPI: Error in GetItems, sender=:1.47, error=Unknown object '/org/a11y/atspi/cache'

(orca:19850): dbind-WARNING **: 18:44:34.106: AT-SPI: Error in GetItems, sender=:1.48, error=Unknown object '/org/a11y/atspi/cache'
/usr/lib/python3.13/site-packages/orca/orca.py:257: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  Atspi.event_main()
/usr/lib/python3.13/site-packages/orca/orca.py:257: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  Atspi.event_main()
/usr/lib/python3.13/site-packages/orca/ax_object.py:703: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  role = Atspi.Accessible.get_role(obj)
/usr/lib/python3.13/site-packages/orca/ax_object.py:703: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
```
### Question
Could this be a simple directory path issue?
I have no idea where the "runner" part of this path came from: I have no USER named "runner" and no directory called "runner" in /home either!

I just checked my `/etc/passwd` file and I can't find "runner" at all. 

```
thread '<unnamed>' panicked at 
/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.14.0/src/context.rs:61:78
called `Result::unwrap()` on an `Err` value: InterfaceNotFound
```


Is Godot creating this runner directory in a sandbox? (it might! I don't really know how this works)


Here is what I found when digging around myself in a real user:
```
$ cd /home/benjamin/.cargo/registry/src/index.crates.io-6f17d22bba15001f
$ ls
anstream-0.6.14      anstyle-query-1.1.0  clap-4.5.8          clap_lex-0.7.1     iana-time-zone-0.1.60        proc-macro2-1.0.86  syn-2.0.69
anstyle-1.0.7        autocfg-1.3.0        clap_builder-4.5.8  colorchoice-1.0.1  is_terminal_polyfill-1.70.0  quote-1.0.36        unicode-ident-1.0.12
anstyle-parse-0.2.4  chrono-0.4.38        clap_derive-4.5.8   heck-0.5.0         num-traits-0.2.19            strsim-0.11.1       utf8parse-0.2.2
```

I don't see accesskit_unix-0.14.0 here, but maybe thats expected.

**Comment by bruvzg** [comment]
> I just checked my /etc/passwd file and I can't find "runner" at all.

It's the source code path that was used when compiling AccessKit, it won't be on your system.

**Comment by timothyqiu** [comment]
I can confirm that the editor crashes on v4.5.dev5 and on current master[591e70ff78c665ff11e1f21998d0e52fbc3f23c8].

System information:

> Godot v4.5.dev (591e70ff7) - Arch Linux #‍1 SMP PREEMPT_DYNAMIC Tue, 10 Jun 2025 21:32:33 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 575.57.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

The backtrace is not very useful I think, unexpected `Result::unwrap()` on a separate thread.

<details><summary>Backtrace</summary>

```
#0  0x00007ffff75af74c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7555dc0 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff753d57a in abort () from /usr/lib/libc.so.6
#3  0x000055556d5c1d5a in panic_abort::__rust_start_panic::abort () at library/panic_abort/src/lib.rs:55
#4  0x000055556d5c1d49 in panic_abort::__rust_start_panic () at library/panic_abort/src/lib.rs:49
#5  0x000055556d5cc8c9 in std::panicking::rust_panic () at library/std/src/panicking.rs:894
#6  0x000055556d5cbf51 in std::panicking::rust_panic_with_hook () at library/std/src/panicking.rs:858
#7  0x000055556d5fa408 in std::panicking::begin_panic_handler::{closure#0} () at library/std/src/panicking.rs:706
#8  0x000055556d5fa369 in std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !> () at library/std/src/sys/backtrace.rs:168
#9  0x000055556d5fa9bc in std::panicking::begin_panic_handler () at library/std/src/panicking.rs:697
#10 0x000055556d5b2a8f in core::panicking::panic_fmt () at library/core/src/panicking.rs:75
#11 0x000055556d5b5bf5 in core::result::unwrap_failed () at library/core/src/result.rs:1704
#12 0x000055556d58b108 in core::result::Result<(), zbus::error::Error>::unwrap<(), zbus::error::Error> (self=...) at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/result.rs:1109
#13 accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block#0} () at src/context.rs:61
#14 futures_lite::future::{impl#7}::poll<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}, async_executor::{impl#13}::run::{async_fn#0}::{async_block_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>> (cx=<optimized out>, self=...) at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:454
#15 async_executor::{impl#13}::run::{async_fn#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}> () at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.1/src/lib.rs:748
#16 async_executor::{impl#5}::run::{async_fn#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}> () at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.1/src/lib.rs:344
#17 accesskit_unix::executor::{impl#0}::run::{async_fn#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}> () at src/executor.rs:85
#18 futures_lite::future::block_on::{closure#0}<(), accesskit_unix::executor::{impl#0}::run::{async_fn_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>> (cache=...)
    at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:99
#19 std::thread::local::LocalKey<core::cell::RefCell<(parking::Parker, core::task::wake::Waker)>>::try_with<core::cell::RefCell<(parking::Parker, core::task::wake::Waker)>, futures_lite::future::block_on::{closure_env#0}<(), accesskit_unix::executor::{impl#0}::run::{async_fn_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>>, ()> (self=<optimized out>, f=...) at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/local.rs:311
#20 std::thread::local::LocalKey<core::cell::RefCell<(parking::Parker, core::task::wake::Waker)>>::with<core::cell::RefCell<(parking::Parker, core::task::wake::Waker)>, futures_lite::future::block_on::{closure_env#0}<(), accesskit_unix::executor::{impl#0}::run::{async_fn_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>>, ()> (self=<optimized out>, f=...) at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/local.rs:275
#21 futures_lite::future::block_on<(), accesskit_unix::executor::{impl#0}::run::{async_fn_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>> (future=<error reading variable: Cannot access memory at address 0x2328>)
    at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:78
#22 accesskit_unix::util::block_on<accesskit_unix::executor::{impl#0}::run::{async_fn_env#0}<(), accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0}::{async_block_env#0}>> (future=...) at src/util.rs:13
#23 accesskit_unix::context::get_or_init_messages::{closure#0}::{closure#0} () at src/context.rs:57
#24 std::sys::backtrace::__rust_begin_short_backtrace<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()> (f=...) at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/sys/backtrace.rs:152
#25 0x000055556d58a605 in std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure#0}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/mod.rs:559
#26 core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()>> (self=...)
    at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panic/unwind_safe.rs:272
#27 std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()>>, ()> (
    data=<error reading variable: Cannot access memory at address 0x0>) at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:589
#28 std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()>>> (f=...)
    at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:552
#29 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()>>, ()> (f=...)
    at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panic.rs:359
#30 std::thread::{impl#0}::spawn_unchecked_::{closure#1}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/thread/mod.rs:557
#31 core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<accesskit_unix::context::get_or_init_messages::{closure#0}::{closure_env#0}, ()>, ()> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ops/function.rs:250
#32 0x000055556d5faccb in alloc::boxed::{impl#28}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:1966
#33 alloc::boxed::{impl#28}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:1966
#34 std::sys::pal::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/pal/unix/thread.rs:109
#35 0x00007ffff785e29b in asan_thread_start (arg=0x7bffd43df000) at /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:239
#36 0x00007ffff75ad7eb in ?? () from /usr/lib/libc.so.6
#37 0x00007ffff763118c in ?? () from /usr/lib/libc.so.6
```

</details>

As noted in another issue, running the editor with `--accessibility disabled` won't trigger the crash.

**Comment by timothyqiu** [comment]
Today I tried to run [librerama](https://codeberg.org/Librerama/librerama/) with 4.5.beta1 from the project manager.

The game crashes with the same backtrace after leaving the first scene.

**Comment by HauntedBees** [comment]
I'm facing the same issue in 4.5beta1 on Linux Mint.
