### ISSUE TITLE
Baked NavigationMesh fails with "Navigation region synchronization error"; NavigationAgent3D unable to navigate

### ISSUE THREAD

**Issue by dmlary** [godotengine/godot#108263]
### Tested versions

- Fails on v4.5.beta.custom_build [9b22b4153], v4.5.beta2.official [e1b4101e3]
- Works on v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.5.beta2 - macOS Sonoma (14.7.6) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads) - 64.00 GiB memory

### Issue description

A NavigationMesh that worked on 4.4.1 stopped working on the 4.5 betas, and on master build.  Also fails when I rebake the navmesh in 4.5 beta.  The Navigation agent is able to only navigate to the edge of its navigation region, and no farther.

The only error I get is:
> E 0:00:00:335   _build_step_find_edge_connection_pairs: Navigation region synchronization error. More than 2 edges tried to occupy the same map rasterization space. This is a logical error in the navigation mesh caused by overlap or too densely placed edges.
  <C++ Error>   Condition "pair.size >= 2" is true.
  <C++ Source>  modules/navigation_3d/3d/nav_region_builder_3d.cpp:212 @ _build_step_find_edge_connection_pairs()

Given that this is NavigationMesh is baked by the NavigationRegion3D with default parameters, I expect it to generate a compatible NavigationMesh.

In 4.5.beta2:

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/eaf776be-52ab-41c2-b760-5606743f2082" />

In 4.4.1:

<img width="688" alt="Image" src="https://github.com/user-attachments/assets/1bba752e-4108-4b2f-b390-459512fd6a41" />

In 4.4.1, the following error is generated, but the NavMesh works:
>   ERROR: modules/navigation/3d/nav_map_builder_3d.cpp:151 - Navigation map synchronization error. Attempted to merge a navigation mesh polygon edge with another already-merged edge. This is usually caused by crossing edges, overlapping polygons, or a mismatch of the NavigationMesh / NavigationPolygon baked 'cell_size' and navigation map 'cell_size'. If you're certain none of above is the case, change 'navigation/3d/merge_rasterizer_cell_scale' to 0.001.

The `cell_sizes` for both things are the Godot default in the MRP.

### Steps to reproduce

Open the MRP:
*  (optional) rebake the NavMesh 
* run the default scene
* click the "Start Navigation" button

The player capsule should be able to move to the target marker, but the path received by the NavigationAgent does not extend past the initial NavMesh region.

### Minimal reproduction project (MRP)

Same MRP from #108261; I was trying to test a fix on master.

[navigation-agent-finishes-early-issue.zip](https://github.com/user-attachments/files/21050190/navigation-agent-finishes-early-issue.zip)

**Comment by smix8** [comment]
The only real change in Godot 4.5 regarding the edge merge is that now edges are first merged by region before the leftover edges are merged by the map. The edge rasterization error is all the same and the difference between 4.4 and 4.5 might be simply due to array processing order. In Godot 4.4 it still failed to do the edge merge but it might have failed on a different overlap edge that makes it less obvious but the problem was always there with this navmesh.

Baking navmesh is just one of multiple ways how to create navmesh in Godot, e.g. can be imported, can be procedurally created, can be scaled and transformed to be some entire different geometry layout than the original navmesh resource is. As such the system does not know what and who created a navmesh, it needs to be validated and rasterized on its own with each polygon as if it was handcrafted assuming that at worse it is completely broken geometry.

That is why the server and navigation map needs to rasterize the edges of navmeshes in order to figure out what polygons can be merged and if the navmesh has many very small edges created they may end up falling all into the same rasterization cells which is this error. The result of the baked navmesh depends very much on the input geometry. If it is too detailed it will create very small polygons that can cause this error when rasterized.

That is why the error msgs also has info how to engage with those "errors" as they not always may be valid. In this case they seem very valid because the layout looks like to create broken polygon paths. You can try lowering the error mentioned raster scale setting, if that makes the error go away you only had tiny mini polygon edges somewhere in the layout. If it does not go away even with the smallest possible value there are vertex overlaps somewhere for reasons creating logical errors.

While it is still possible to lower the chances for some error cases (as the region merge already did) with some changes the error will never go fully away as long as Godot allows manual navmesh manipulation and placement on such a low level as it does at the moment. Too many possibilities to cause a mix of layout geometry that just does not work and cant verify everything at very small detail as it would take forever to run at scale. Proposal https://github.com/godotengine/godot-proposals/issues/12707 goes in the direction to do what other engines do that do not need this rasterization step in that they just not allow users access to the navmesh data directly. In such a case that entire problemtic step can be just skipped when you know no one can touch it.

**Comment by dmlary** [comment]
@smix8 I’m still reading through your comment, and the linked proposal, but one thing stood out to me:

> You can try lowering the error mentioned raster scale setting

The new error in 4.5 does not mention the raster scale setting anymore.

**Comment by dmlary** [comment]
The problem is fixed by lowering `navigation/3d/merge_rasterizer_cell_scale`.

To prevent other issues from being opened for this, I can open a PR that expands the error message to direct users to consider changing that value.

**Comment by smix8** [comment]
I think the error mention got lost when working on the async region PR. Originally it was merging by navmesh indices making that error at least for the region obsolete for some time. That got revert back to using raster cell size because there were just too many problems with it but the error mention was not added back in.

**Comment by zomby138** [comment]
I'm experiencing the same problem after moving to 4.5 from 4.4.  The only difference is that for me setting the `navigation/3d/merge_rasterizer_cell_scale` really low makes no difference.  Even at 0.001 I still get the same error.

**Comment by smix8** [comment]
If `merge_rasterizer_cell_scale ` at the lowest possible value does not make the error go away you have created perfect navmesh edge overlap with something in your project.

The most common pitfall in 2D projects is having the TileMap build-in navmesh not disabled while using a baked NavigationRegion2D navmesh on top.

In general it is very unlikely that any geometry will ever fall naturally into the same rasterization cells with a merge rasterize cell scale  set as low as 0.001. That edge that causes that at this scale would need to be microscopic.

If the entire level gets upscale (e.g. set the root node to scale 100.0 for a test) the error will inevitably disappear at some point because the vertices will be spaced out so far that they can not fall into the same cells. Most users with that error when scaling their level navmesh up for a test notice navmesh edges appearing in corners where they did not see them with the default editor camera, and those tiny edges are causing the errors.

**Comment by zomby138** [comment]
I'll elaborate.  It is a 3D project.  In this scene, I have 3 navmeshs for 3 different sizes of monsters.

In 4.4 all 3 navmeshs work perfectly when I press the "Bake NavigationMesh" button at the top.

In 4.5, only ONE of the three navmeshs bakes ok.  The other TWO both give the following error:

<img width="870" height="33" alt="Image" src="https://github.com/user-attachments/assets/ff979d3f-e367-4cf6-a3fc-861817f82804" />

If it was just one with the problem then I could believe something "very unlikely" is happening.  But 2 out of 3 are broken.

And as I said, changing `merge_rasterizer_cell_scale ` to 0.001 made no difference.

**Comment by smix8** [comment]
> And as I said, changing merge_rasterizer_cell_scale to 0.001 made no difference.

> I have 3 navmeshs for 3 different sizes of monsters.

I hope you separated them on different navigation maps using the right cell size. If not that is your error source.

If you can't fix it please provide an MRP with your setup for that error. 

> changing merge_rasterizer_cell_scale to 0.001 made no difference.

You very likely created perfect edge overlap somewhere with your navmeshes. At that value you created a rasterization cell grid of 0.01 (which is the minimum) with that setting. Any normal navmesh that has touching edges causing rasterization errors with default size would be moved miles apart at such a low cell grid. The only way for them to still fall into the same cells giving you that error is by being placed over each other. In that case neither cell size or scale can do anything about such a layout error.

**Comment by zomby138** [comment]
> I hope you separated them on different navigation maps using the right cell size. If not that is your error source.

I hope I have done that too!  Can you please elaborate what you mean by this?  Each navmesh uses a different Navigation Layer ie. 

<img width="143" height="63" alt="Image" src="https://github.com/user-attachments/assets/d0b0eb1c-d8f8-4097-bb8c-a25b1a76659f" />


All of the Cell Size and Cell Heights are set to the same values as the Default Cell Size and Height, ie.

<img width="317" height="98" alt="Image" src="https://github.com/user-attachments/assets/66667fd6-93ec-45a4-bb55-e0750612a5ec" />

<img width="268" height="66" alt="Image" src="https://github.com/user-attachments/assets/4aaee3b3-d6dd-402c-9549-cfca8fa371b0" />

Each one has a unique Navigation Mesh.  I can be sure of this because I can click "Make Unique" in the context menu and the problem persists.

Can you explain what you mean by "separated them on different navigation maps"?

I'll start making a MRP in the mean time.

**Comment by smix8** [comment]
> I hope I have done that too! Can you please elaborate what you mean by this? Each navmesh uses a different Navigation Layer ie.

The `navigation_layers` bitmask does not seperate navmesh geometry, it is a bitmask for the path query to filter out polygon regions. So it can not help you to avoid geometry conflict due to stacking navmesh all over the place.

The separation unit is the navigation map. So when you need different navmeshes for different agent sizes you also need different navigation maps for each size that each hold navmeshes baked for that size.

You can create new navigation maps using the NavigationServer API and after you set them active you can switch the NavigationRegion and NavigationAgent nodes that should be for that agent size to use that map instead of the default.

You can find a script example for this here https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_different_actor_types.html but you can also do this with nodes as each NavigationRegion and NavigationAgent has a set_navigation_map() function. The only thing you need to do with the server API is to create the map and set it active.

**Comment by zomby138** [comment]
@smix8  Ok.  Thank you very much for this information.  I had no idea about any of this.  I am still very confused however.

The script example on the page you linked, is this meant to be a runtime script that you put in a _ready() function, or perhaps an editor script?  How does it relate to scenes?  Do I do it once for the entire project, or will it need to be ran once per scene?  If I run the script more than once will a bunch of Navigation Maps accumulate in my project?

I'm really struggling with how this script and my scenes will relate to one another.

**Comment by smix8** [comment]
That script is for direct server use without nodes involved. Nodes do many of the very same server calls just behind the scene for you.

If you have currently set up all your stuff using NavigationRegion and NavigationAgent nodes all you need to do is in some global class, e.g. an autoload singleton, create the new navigation map at game start, set it active, and then set all the regions and agents that should use that map to that map RID with set_navigation_map().

If you do not set a map RID manually all the region and agent nodes will just use the default navigation map of the Viewport.

**Comment by zomby138** [comment]
Hmm.  But if all this happens at game start, how can it fix my error?  The error happens when I bake the navmeshs, during edit time, long before game start.

**Comment by zomby138** [comment]
Can you explain to me why it all worked fine in 4.4?  I had 3 different sizes of monsters correctly using 3 different navmeshs, having never made a single call to the NavigationServer3D?

**Comment by smix8** [comment]
If you have an autoload singleton, let's name it NavGlobal for the example, you can spawn your maps there at game start.

```gdscript
extends Node
class_name NavGlobal

static var navigation_map_default: RID
static var navigation_map_small: RID
static var navigation_map_huge: RID

func _enter_tree():
	navigation_map_default = get_viewport().find_world_3d().navigation_map # default map that every new nav node uses
	navigation_map_small = NavigationServer3D.map_create()
	navigation_map_huge = NavigationServer3D.map_create()

	# Set the new navigation maps as active.
	#NavigationServer3D.map_set_active(navigation_map_default, true)
	NavigationServer3D.map_set_active(navigation_map_small, true)
	NavigationServer3D.map_set_active(navigation_map_huge, true)

func _exit_tree():
	#if navigation_map_default:
	#	NavigationServer3D.free_rid(navigation_map_default)
	#	navigation_map_default = RID()
	if navigation_map_small:
		NavigationServer3D.free_rid(navigation_map_small)
		navigation_map_small = RID()
	if navigation_map_huge:
		NavigationServer3D.free_rid(navigation_map_huge)
		navigation_map_huge = RID()
```
In case you stick with the default map you dont need to set it active or free it manually, the engine already does that, you only need to clean up manually your extra maps that you created. Hence I out-commented those sections in this script.

And later, for every region or agent that should use a different map than the default you change the map when they join.

```gdscript
extends NavigationRegion3D

enum AgentSizes {
	DEFAULT,
	SMALL,
	HUGE
}
@export var agent_size:AgentSizes = AgentSizes.DEFAULT

func _ready():
	match agent_size:
		AgentSizes.DEFAULT:
			set_navigation_map(NavGlobal.navigation_map_default);
		AgentSizes.SMALL:
			set_navigation_map(NavGlobal.navigation_map_small);
		AgentSizes.HUGE:
			set_navigation_map(NavGlobal.navigation_map_huge);
```

> Hmm. But if all this happens at game start, how can it fix my error? The error happens when I bake the navmeshs, during edit time, long before game start.

When it only happens in the editor but not at runtime you can basically ignore it as you are switching and separating later to avoid the conflict. Else you would need to write a tool script for all your regions to switch maps already while inside the editor but I dont think that is worth it.

> Can you explain to me when it all worked fine in 4.4? I have 3 different sizes of monsters correctly using 3 different navmeshs, having never made a single call to the NavigationServer3D?

It did not work fine when you had stacked navmeshes. Nothing has changed in that regard, only merge ordering has but not what things are merged. You likely had the very same merge errors with edges from the navigation map just in a different place and edge where you did not notice how it affected the pathfinding. Or you had some regions disabled at the start so only caused the error when enabling the regions because Godot 4.4 had no error print for disabled regions.

**Comment by tangx246** [comment]
Could this error message at least show where the overlapping edges are? In a complex map where agents suddenly no longer work, this becomes a blocker to upgrading to 4.5 and we don't even know where to start looking.

In the previous case, even if agents were somehow invisibly unable to navigate somewhere, this had not been apparent enough to bring down the smokes and mirrors that is a game.

**Comment by zomby138** [comment]
[nav-mesh-bug-mre.zip](https://github.com/user-attachments/files/22436098/nav-mesh-bug-mre.zip)

Here is a minimal reproduction example.  In this example, the "normal" navmesh gives the error, the "tall" navmesh is ok, and then the "wide" navmesh gives the error.

While playing the game, the normal and tall monsters behave, but the wide ones do not know how to path find.

The global static calls to NavigationServer3D are being made, however you can turn them off, and it makes no difference to the behavior at all.

I would love to hear your take on this @smix8, is there anything that I have set up incorrectly?

**Comment by smix8** [comment]
See linked PR that tries to amend some of the problems and also explains why all kinds of bad things are happening when errors are present.

@zomby138 I only did a quick look but what I noticed immediately is that both the bake settings and bake input geometry are overly detailed. When you go below the default bake cell sizes you naturally cause more chances for bake artifacts to appear all over the place and those can create rasterization issues later. E.g. those staircases alone turn into 50+ mini polygons due to the small cell sizes an rigid settings. An optimized navmesh would have stairs like that just as a ramp made out of 2-4 polygons total.
