### ISSUE TITLE
Editor freeze on project reimport when "Run physics on separate thread" is enabled (Godot 4.4.1, GT940M laptop)

### ISSUE THREAD

**Issue by MbsElectronics** [godotengine/godot#109982]
### Tested versions

Godot version: 4.4.1 (stable, official build). 

### System information

Godot v4.4.1.stable Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce 940MX (NVIDIA; 32.0.15.8108) - Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 threads) 32G Ram

### Issue description

Issue description

When the project setting Physics > Run On Separate Thread is enabled, the editor freezes during project load (asset reimport). The freeze occurs right after:
Importing assets - 0%
Executing pre-reimport operations...
Preparing scenes for reload - 100%
Preparation done
At this point the editor hangs indefinitely and must be killed via Task Manager.
Disabling the "Run On Separate Thread" option allows the project to import and load normally.
This issue only reproduces on older hardware (GT940M laptop). On a newer PC with GTX1650 the same project works fine.
Seems like a race condition between physics server initialization and asset importer.
when running with verbose enabled, the log file is not created. Apparently the problem occurs before the logging process begins

### Steps to reproduce

Create a new project.
**Go to Project Settings > Physics > Run On Separate Thread and enable it.**
Import  several GLB models
run project and stop
Close the project.
**Delete the .godot/ folder to force reimport.**
Open the project again.
→ The editor freezes during the import phase.

This happens in all my projects on this computer. The attached minimal project uses jolt physics but the problem does not depend on it. The same thing happens when using the godot physics engine. The key point is to enable the checkbox for running physics in a separate thread in the project settings.

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/21985665/new-game-project.zip)

**Comment by jrouwe** [comment]
Could this be fixed by https://github.com/godotengine/godot/pull/108697?

**Comment by Favkis** [comment]
I am having awful time with godot 4.4.1 freezing and crashing on import/reimport of certain files (right now I am having it with .glb AnimationLibrary). However, it's inconsistent at all, so I cant even reproduce it, sometimes it does it 50 times in a row, sometimes it doesn't. Removing .godot folder fixes it once, but next import/reimport might break it. I dont have physics on separate thread enabled, however I did have physics interpolation on, and disabling it, looks like, fixed it, at least for now, but again, its super inconsistent, so I cant tell for sure. 

<img width="960" height="221" alt="Image" src="https://github.com/user-attachments/assets/f9b537d7-f967-49ef-a7ad-5456b13f6b8b" />

this is what I was getting in console. 

More info about how it looks:

<img width="530" height="132" alt="Image" src="https://github.com/user-attachments/assets/35cb89b2-2f8c-42c3-8559-50a5c91146fa" />

it would do this window or (Re)importing window, then freeze and memory would go up and up from 800 mb to around 2 GB RAM used, and then it just silently closes. Most of the times (or even all of them, I honestly couldnt tell), it actually reimports/imports, and looks like just UI bug. 

<img width="531" height="126" alt="Image" src="https://github.com/user-attachments/assets/79995aa3-c707-4fed-b82c-f06ece312bc9" />

Other times, it would show this window forever, but wont go "white" as if its frozen, however, this window would be up and I cant press anything. However, if I press red X on windows to close editor, godot asks me to save scenes, and this window disappears, and I can semi use project again. Semi use because some buttons would break, like for example these instead of toggling windows, would just get pressed and get highlighed and do nothing. 

<img width="364" height="106" alt="Image" src="https://github.com/user-attachments/assets/b1fd3c44-9906-40b7-b8e4-e9b17deb71d2" />

**Comment by clayjohn** [comment]
@Favkis @MbsElectronics could you both test with 4.5 RC2? This issue may have been fixed in 4.5 already

**Comment by greenpixels** [comment]
This has been a big issue for the CI in my project and I just couldn't figure out the reason. Thanks to this post I was finally track it down to the separate physics thread. Thanks @MbsElectronics for finding the root issue.

I migrated to Godot 4.5.1-stable in hopes to fixing it maybe, but the issue still persists and I was only able to fix it by disabling the separate thread for the physics for now ...

Though it has not happened on my local machines (RTX 2070 Super and GeForce RTX 4060 Laptop GPU), only when exporting in the CI pipeline via GitHub Actions does the pipeline freeze about 8 out of 10 times.

**Comment by ratkingsminion** [comment]
A contributor to my project (Godot 4.6.2) gets hit by this too. Import always gets stuck, unless they deactivate the option with the physics thread. So odd.
