### ISSUE TITLE
Problems encountered with WebAssembly export 

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#11197]
**Godot Version:** 3.0 master

Problems encountered with WebAssemply export. Keep getting following error message: 

ERROR: failed to asynchronously prepare wasm: TypeError: Failed to fetch
TypeError: Failed to fetch
ERROR: TypeError: Failed to fetch

Also issues when tried to run file from local repository using the 'run in browser button'. 

Is there a problem with the WebAssembly exporter?

**Comment by raymoo** [comment]
It seems like a lot of people are "accidentally" closing their issues recently.

**Comment by stubbsy345** [comment]
genuine mistake, apologies

**Comment by eska014** [comment]
Your version of Emscripten is probably too old. Emscripten 1.37.9 was released on 2017-3-23 and added the `instantiateWasm` callback we use to manage WebAssembly compilation+instantiation ourselves

You can use `$EMSCRIPTEN_ROOT/emcc -v` on Unix or `%EMSCRIPTEN_ROOT%\emcc -v` on Windows to print your Emscripten version. Of course you need to define `EMSCRIPTEN_ROOT` as you do before building web templates.

If your distributions' Emscripten package is unmaintained or not updated enough, you're better off using Emscripten's `emsdk` to install Emscripten: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#windows-osx-and-linux-installing-the-portable-sdk

**Comment by stubbsy345** [comment]
Great thanks i've sorted that. Is there anything I need to do once downloaded to connect with godot/do i need to build exports though terminal or can they be done directly from godot editor

**Comment by eska014** [comment]
If you didn't build the templates yourself, it'll probably be easier to tell the provider to update the Emscripten version they use for their builds.

If you want to try building yourself, instructions are here: http://docs.godotengine.org/en/latest/development/compiling/compiling_for_web.html
Export templates are built from the terminal using SCons. SCons will interface with the Emscripten installation specified by the `EMSCRIPTEN_ROOT` environment variable.

**Comment by stubbsy345** [comment]
Running into the following error when building own templates:

scons: Reading SConscript files ...
Could not detect MinGW. Ensure its binaries are in your PATH or that MINGW32_PREFIX or MINGW64_PREFIX are properly defined.
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/javascript/os_javascript.cpp
sh: em++: command not found
scons: *** [platform/javascript/os_javascript.javascript.debug.bc] Error 127
scons: building terminated because of errors.

Is it best to build the exports myself. I'm sorry I also don't know what you mean by "it'll probably be easier to tell the provider to update the Emscripten version they use for their builds." When I export using the downloadable templates it exports very quickly as well and I feel like the actual exporter the game into java. Could you tell me where I am going wrong?

**Comment by eska014** [comment]
> em++: command not found

This sounds like you didn't set the `EMSCRIPTEN_ROOT` environment variable

> When I export using the downloadable templates it exports very quickly

There's a difference between:
1. Building export templates, which entails compiling the C++ code of the engine and takes several minutes. Emscripten is used in this process. This usually only done by engine developers or by people offering unofficial Godot builds.
2. Exporting a game, which uses the built (or downloaded) export templates to export your game from within the Godot editor and only takes a few seconds.

The only officially released export templates so far are for [3.0-alpha1](https://downloads.tuxfamily.org/godotengine/3.0/alpha1/). You specified you use the `master` branch, so I assume you're not using 3.0-alpha1.

From where did you download the templates? Whoever built the export templates might have to update their Emscripten version, rebuild and then publish the fixed export templates. Then you can download and use those to export games.

Another possible issue is that the version of your editor and the version of your export templates are not the same.

**Comment by stubbsy345** [comment]
Okay, working with my colleagues but still running into problems. I'm sure the beta release with have some documentation to help as well.

**Comment by stubbsy345** [comment]
Also I had been using the master to try and build the template, but had been using the templates and alpha 1 release from: https://downloads.tuxfamily.org/godotengine/3.0/alpha1/

So I believe these two should have been compatible with one another.

**Comment by stubbsy345** [comment]
Okay so a problem I think we were having was not building emscripten from source. The above page for building your own template only has the syntax for building the asm.js template. Do you know the syntax for webassembly template by any chance?

**Comment by eska014** [comment]
If you tried with `alpha1` templates+editor before, getting new templates or building the templates yourself isn't going to help.
Are you running the game from the local file system (`file://`)? That'll cause issues unless using Firefox, you have to run from a server. You can use

    python -m SimpleHTTPServer

to get a simple server running.

---

If you want still want to build the templates for some reason:

There's no need to build Emscripten from source, `emsdk` (from the very first link I posted) installs up-to-date Emscripten binaries on Windows, Mac OS X and Linux. Emscripten version 1.37.9 already has WebAssembly support.

>Do you know the syntax for webassembly template by any chance?

The page I linked above about building web templates includes a section titled "Compiling to WebAssembly" which explains how to build WebAssembly templates.

**Comment by stubbsy345** [comment]
Thanks for getting back I appreciate it as we need to further test our build on the web and this is holding us back. I have no particular desire to build the templates, I was simply querying if that would fix the issue. I have now ran on firefox and I get output to the java output console, which is better than I have had before. However nothing prints to the game window (although it does change to the appropriate size window) and I get the following error:

 Output:
**ERROR**: pre-main prep time: 8104 ms
let it go dude!
**ERROR**: Calling stub instead of sigaction()
Init OS
Init Audio
Init VS
**ERROR**: At: core/project_settings.cpp:841:set_custom_property_info() - Condition ' !props.has(p_prop) ' is true.
Init Physicsserver
WARNING: not found: physics/2d/thread_model
OpenGL ES 3.0 Renderer: Mozilla
WARNING: not found: rendering/quality/anisotropic_filter_level
WARNING: not found: rendering/quality/anisotropic_filter_level
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: locale/translation_remaps
**ERROR**: exit(0) implicitly called by end of main(), but noExitRuntime, so not exiting the runtime (you can use emscripten_force_exit, if you want to force a true shutdown)
**EXCEPTION**: RuntimeError: index out of bounds
Successfully populated IDB file system

//Below is repeated many times:
close index.pck flags 1
close index.pck flags 1
close index.pck flags 1
close index.pck flags 1
close index.pck flags 1
**ERROR**: enlarged memory arrays from 16777216 to 33554432, took 1 ms (has ArrayBuffer.transfer? false)
close index.pck flags 1
close index.pck flags 1
close index.pck flags 1
close index.pck flags 1
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: At: core/bind/core_bind.cpp:1534:get_as_text() - Condition ' !f ' is true. returned: String()
Null


//Below is my code that is meant to print every second, so I know the game is working, just not printing to the canvas:

(Complete:[]), (Pending:)
(Complete:[]), (Pending:)
(Complete:[]), (Pending:)
(Complete:[]), (Pending:)
(Complete:[]), (Pending:)

**Comment by eska014** [comment]
>     ERROR: At: core/project_settings.cpp:841:set_custom_property_info() - Condition ' !props.has(p_prop) ' is true.
>     EXCEPTION: RuntimeError: index out of bounds

These lines make it look like an instance of #10845, try removing all non-default Input Actions

**Comment by stubbsy345** [comment]
okay so i created a file with one scene only containing a panel this time, so that there is no issues with a conversion of my old game into 3.0 or any custom inputs i created. Still doesn't work. 

> **ERROR**: At: drivers/gles3/shader_gles3.cpp:167:_display_error_with_code() - CubemapFilterShaderGLES3: Fragment Program Compilation Failed:
ERROR: 0:17: '' : No precision specified (sampler) 
**ERROR**: At: drivers/gles3/shader_gles3.cpp:460:get_current_version() - CubemapFilterShaderGLES3: Fragment Program Compilation Failed:
ERROR: 0:17: '' : No precision specified (sampler) 
**ERROR**: At: drivers/gles3/shader_gles3.cpp:468:get_current_version() - Method/Function Failed, returning: 0L
**ERROR**: At: drivers/gles3/shader_gles3.cpp:122:bind() - Condition ' !version ' is true. returned: false
**ERROR**: At: drivers/gles3/shader_gles3.h:376:_get_uniform() - Condition ' !version ' is true. returned: -1
**ERROR**: At: drivers/gles3/shader_gles3.h:376:_get_uniform() - Condition ' !version ' is true. returned: -1
**ERROR**: At: drivers/gles3/shader_gles3.h:376:_get_uniform() - Condition ' !version ' is true. returned: -1
**ERROR**: At: drivers/gles3/shader_gles3.h:376:_get_uniform() - Condition ' !version ' is true. returned: -1
**ERROR**: At: drivers/gles3/shader_gles3.h:376:_get_uniform() - Condition ' !version ' is true. returned: -1

So there is some problem with my shader? Is my graphics card not up to scratch?

**Comment by eska014** [comment]
No, it's an issue with Godot's CubeMap filter shader, precision for `sampler2DArray` isn't specified, I'll make a patch.

**Comment by stubbsy345** [comment]
Thanks!

**Comment by nylnook** [comment]
Hi there,

I'm also tying to compile the Webassembly template with Godot 3 git, but I'm stuck at the first line of the documentation, defining EMSCRIPTEN_ROOT :
`export EMSCRIPTEN_ROOT=~/emsdk/emscripten/master`

I'm using Archlinux and I installed both emscripten (v1.37.21) and emsdk (v 1.35) via my packages but they don't install in the same repository and files are in the /usr/bin/ and /usr/lib/ directories.
I also tried with emsdk-portable, but I can't define a structure where emscripten is inside emsdk ( like ~/emsdk/emscripten/master)  ... 
So when compiling, there is always a binary or another missing... 

Can you bring me some light or clarify the documentation about this line ? 
Thanks in advance !

**Comment by eska014** [comment]
@nylnook
Hello,

there's no point in installing emsdk when you can get a recent Emscripten version per package. 1.37.21 is the most recent Emscripten version, so you can remove both the emsdk package and the portable directory.

To get the proper value for `EMSCRIPTEN_ROOT`, you can call `em-config`, which comes with Emscripten:

    em-config EMSCRIPTEN_ROOT

The directory returned contains the executable files, e.g. `emcc` and `em++`. Should be `/usr/bin/` on your system.

**Comment by nylnook** [comment]
Hello @eska014, and thanks a lot for your answer !

I tried again, and first my system was complaining about missing LLVM_ROOT ...
I uninstalled Emscripten and LLVM, delete the ~/.emscripten file, reinstalled, run 
`em-config EMSCRIPTEN_ROOT`
Emsricpten regenerated and the ~/.emscripten file and the path ot EMSCRIPTEN_ROOT is /usr/lib/emscripten

Then I tried to compile again, and it started to work , but something else fail with GDNative:
```
$ scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> main/main.cpp
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/home/nylnook/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
INFO:root:(Emscripten: Running sanity checks)
[Initial build] Compiling ==> modules/gdnative/gd_native_library_editor.cpp
modules/gdnative/gd_native_library_editor.cpp:4:6: error: use of undeclared
      identifier 'GDNativeLibraryEditor'; did you mean 'GDNativeLibrary'?
void GDNativeLibraryEditor::_find_gdnative_singletons(EditorFileSystemDi...
     ^~~~~~~~~~~~~~~~~~~~~
     GDNativeLibrary
modules/gdnative/gdnative.h:40:7: note: 'GDNativeLibrary' declared here
class GDNativeLibrary : public Resource {
      ^
modules/gdnative/gd_native_library_editor.cpp:4:55: error: unknown type name
      'EditorFileSystemDirectory'
void GDNativeLibraryEditor::_find_gdnative_singletons(EditorFileSystemDi...
                                                      ^
modules/gdnative/gd_native_library_editor.cpp:19:4: error: unknown type name
      'TreeItem'
                        TreeItem *ti = libraries->create_item(libraries-...
                        ^
modules/gdnative/gd_native_library_editor.cpp:19:19: error: use of undeclared
      identifier 'libraries'
                        TreeItem *ti = libraries->create_item(libraries-...
                                       ^
modules/gdnative/gd_native_library_editor.cpp:19:42: error: use of undeclared
      identifier 'libraries'
                        TreeItem *ti = libraries->create_item(libraries-...
                                                              ^
modules/gdnative/gd_native_library_editor.cpp:23:24: error: use of undeclared
      identifier 'TreeItem'
                        ti->set_cell_mode(1,TreeItem::CELL_MODE_RANGE);
                                            ^
modules/gdnative/gd_native_library_editor.cpp:40:6: error: use of undeclared
      identifier 'GDNativeLibraryEditor'; did you mean 'GDNativeLibrary'?
void GDNativeLibraryEditor::_update_libraries() {
     ^~~~~~~~~~~~~~~~~~~~~
     GDNativeLibrary
modules/gdnative/gdnative.h:40:7: note: 'GDNativeLibrary' declared here
class GDNativeLibrary : public Resource {
      ^
modules/gdnative/gd_native_library_editor.cpp:40:29: error: out-of-line
      definition of '_update_libraries' does not match any declaration in
      'GDNativeLibrary'
void GDNativeLibraryEditor::_update_libraries() {
                            ^~~~~~~~~~~~~~~~~
modules/gdnative/gd_native_library_editor.cpp:42:2: error: use of undeclared
      identifier 'updating'
        updating=true;
        ^
modules/gdnative/gd_native_library_editor.cpp:43:2: error: use of undeclared
      identifier 'libraries'
        libraries->clear();
        ^
modules/gdnative/gd_native_library_editor.cpp:44:2: error: use of undeclared
      identifier 'libraries'
        libraries->create_item(); //rppt
        ^
modules/gdnative/gd_native_library_editor.cpp:47:6: error: use of undeclared
      identifier 'ProjectSettings'
        if (ProjectSettings::get_singleton()->has("gdnative/singletons")) {
            ^
modules/gdnative/gd_native_library_editor.cpp:48:17: error: use of undeclared
      identifier 'ProjectSettings'
                enabled_paths=ProjectSettings::get_singleton()->get("gdn...
                              ^
modules/gdnative/gd_native_library_editor.cpp:55:2: error: unknown type name
      'EditorFileSystemDirectory'
        EditorFileSystemDirectory *fs = EditorFileSystem::get_singleton(...
        ^
modules/gdnative/gd_native_library_editor.cpp:55:34: error: use of undeclared
      identifier 'EditorFileSystem'
        EditorFileSystemDirectory *fs = EditorFileSystem::get_singleton(...
                                        ^
modules/gdnative/gd_native_library_editor.cpp:60:2: error: use of undeclared
      identifier 'updating'
        updating=false;
        ^
modules/gdnative/gd_native_library_editor.cpp:64:6: error: use of undeclared
      identifier 'GDNativeLibraryEditor'; did you mean 'GDNativeLibrary'?
void GDNativeLibraryEditor::_item_edited() {
     ^~~~~~~~~~~~~~~~~~~~~
     GDNativeLibrary
modules/gdnative/gdnative.h:40:7: note: 'GDNativeLibrary' declared here
class GDNativeLibrary : public Resource {
      ^
modules/gdnative/gd_native_library_editor.cpp:64:29: error: out-of-line
      definition of '_item_edited' does not match any declaration in
      'GDNativeLibrary'
void GDNativeLibraryEditor::_item_edited() {
                            ^~~~~~~~~~~~
modules/gdnative/gd_native_library_editor.cpp:65:6: error: use of undeclared
      identifier 'updating'
        if (updating)
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
scons: *** [modules/gdnative/gd_native_library_editor.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```
If I can succeed in compiling, I promise I'll try to improve the documentation !
I'm sorry to waste your time, but can you lead me out of this maze ?

Thanks a lot...

**Comment by eska014** [comment]
@nylnook It's a recent bug in builds with `tools=no`, either use the PR (#11326) or the preceding commit 57516a447395223e56e93e05994a5bf69ee3bcac

**Comment by eska014** [comment]
It's merged, so building export templates right off the `master` branch should succeed again

**Comment by stubbsy345** [comment]
Hey bro, is that for the 'Specify sampler precision where missing #11292' or just 'Disable GDNative library editor for no-tools builds to fix build #11326'?

**Comment by eska014** [comment]
@stubbsy345 That's for the build issue (#11326).
The sampler precision PR will probably be merged on Monday

**Comment by stubbsy345** [comment]
Thanks bud!

**Comment by eska014** [comment]
@stubbsy345 Actually, this is already fixed in the `master` branch (not in 3.0-alpha1 though)

**Comment by akien-mga** [comment]
Closing as fixed.

**Comment by nylnook** [comment]
Hi there,

updating to latest git, I confirm I can compile the asm.js export template...  But I'm sorry to say I can't for Webassembly, even after I installed binaryen v37 on my system (which is missing is the doc !):
```
$ scons platform=javascript target=release wasm=yes
scons: Reading SConscript files ...
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 97%] Linking Program        ==> bin/godot.javascript.opt.webassembly.js
WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_37.zip
WARNING:root:unpacking port: binaryen
INFO:root:generating port: binaryen_tag_version_37.txt... (this will be cached in "/home/nylnook/.emscripten_cache/asmjs/binaryen_tag_version_37.txt" for subsequent builds)
INFO:root:building port: binaryen
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/sbin/cc
-- Check for working C compiler: /usr/sbin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/sbin/c++
-- Check for working CXX compiler: /usr/sbin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Building with -std=c++11
-- Building for platform x86-64
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -fPIC
-- Building with -O2
-- Building with -UNDEBUG
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nylnook/.emscripten_ports/binaryen/binaryen-version_37
Scanning dependencies of target ast
Scanning dependencies of target cfg
Scanning dependencies of target asmjs
Scanning dependencies of target support
Scanning dependencies of target wasm
Scanning dependencies of target emscripten-optimizer
Scanning dependencies of target passes
[  1%] Building CXX object src/ast/CMakeFiles/ast.dir/ExpressionManipulator.cpp.o
[  2%] Building CXX object src/ast/CMakeFiles/ast.dir/ExpressionAnalyzer.cpp.o
[  4%] Building CXX object src/cfg/CMakeFiles/cfg.dir/Relooper.cpp.o
[  4%] Building CXX object src/asmjs/CMakeFiles/asmjs.dir/asm_v_wasm.cpp.o
[  5%] Building CXX object src/support/CMakeFiles/support.dir/archive.cpp.o
[  6%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o
[  7%] Building CXX object src/wasm/CMakeFiles/wasm.dir/literal.cpp.o
[  8%] Building CXX object src/passes/CMakeFiles/passes.dir/pass.cpp.o
[  9%] Building CXX object src/support/CMakeFiles/support.dir/bits.cpp.o
[ 10%] Building CXX object src/support/CMakeFiles/support.dir/colors.cpp.o
[ 11%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm.cpp.o
[ 13%] Building CXX object src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o
[ 14%] Building CXX object src/support/CMakeFiles/support.dir/command-line.cpp.o
[ 15%] Building CXX object src/support/CMakeFiles/support.dir/file.cpp.o
[ 16%] Linking CXX static library ../../lib/libasmjs.a
[ 16%] Built target asmjs
[ 17%] Building CXX object src/support/CMakeFiles/support.dir/safe_integer.cpp.o
[ 18%] Linking CXX static library ../../lib/libast.a
[ 19%] Building CXX object src/support/CMakeFiles/support.dir/threads.cpp.o
[ 19%] Built target ast
[ 20%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-binary.cpp.o
[ 21%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-io.cpp.o
[ 22%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-s-parser.cpp.o
[ 23%] Building CXX object src/passes/CMakeFiles/passes.dir/CoalesceLocals.cpp.o
[ 25%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o
[ 26%] Linking CXX static library ../../lib/libsupport.a
[ 26%] Built target support
[ 27%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/simple_ast.cpp.o
[ 28%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-type.cpp.o
[ 29%] Linking CXX static library ../../lib/libcfg.a
[ 30%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-validator.cpp.o
[ 30%] Built target cfg
[ 31%] Building CXX object src/passes/CMakeFiles/passes.dir/CodePushing.cpp.o
[ 32%] Building CXX object src/passes/CMakeFiles/passes.dir/CodeFolding.cpp.o
[ 33%] Linking CXX static library ../../lib/libemscripten-optimizer.a
[ 33%] Built target emscripten-optimizer
[ 34%] Building CXX object src/passes/CMakeFiles/passes.dir/DeadCodeElimination.cpp.o
[ 35%] Building CXX object src/passes/CMakeFiles/passes.dir/DuplicateFunctionElimination.cpp.o
/home/nylnook/.emscripten_ports/binaryen/binaryen-version_37/src/wasm/wasm-s-parser.cpp: Dans la fonction membre « wasm::Expression* wasm::SExpressionWasmBuilder::makeExpression(wasm::Element&) »:
/home/nylnook/.emscripten_ports/binaryen/binaryen-version_37/src/wasm/wasm-s-parser.cpp:871:9: error: cette instruction peut poursuivre son chemin [-Werror=implicit-fallthrough=]
         if (!strncmp(str, "wake", strlen("wake"))) return makeAtomicWake(s);
         ^~
/home/nylnook/.emscripten_ports/binaryen/binaryen-version_37/src/wasm/wasm-s-parser.cpp:873:7: note: ici
       default: abort_on(str);
       ^~~~~~~
[ 36%] Building CXX object src/passes/CMakeFiles/passes.dir/ExtractFunction.cpp.o
[ 38%] Building CXX object src/passes/CMakeFiles/passes.dir/FlattenControlFlow.cpp.o
[ 39%] Building CXX object src/passes/CMakeFiles/passes.dir/Inlining.cpp.o
[ 40%] Building CXX object src/passes/CMakeFiles/passes.dir/LegalizeJSInterface.cpp.o
[ 41%] Building CXX object src/passes/CMakeFiles/passes.dir/LocalCSE.cpp.o
[ 42%] Building CXX object src/passes/CMakeFiles/passes.dir/LogExecution.cpp.o
[ 43%] Building CXX object src/passes/CMakeFiles/passes.dir/InstrumentLocals.cpp.o
cc1plus : tous les avertissements sont traités comme des erreurs
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/build.make:159: src/wasm/CMakeFiles/wasm.dir/wasm-s-parser.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....
[ 44%] Building CXX object src/passes/CMakeFiles/passes.dir/InstrumentMemory.cpp.o
make[1]: *** [CMakeFiles/Makefile2:843: src/wasm/CMakeFiles/wasm.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 45%] Building CXX object src/passes/CMakeFiles/passes.dir/MemoryPacking.cpp.o
[ 46%] Building CXX object src/passes/CMakeFiles/passes.dir/MergeBlocks.cpp.o
[ 47%] Building CXX object src/passes/CMakeFiles/passes.dir/Metrics.cpp.o
[ 48%] Building CXX object src/passes/CMakeFiles/passes.dir/NameList.cpp.o
[ 50%] Building CXX object src/passes/CMakeFiles/passes.dir/OptimizeInstructions.cpp.o
[ 51%] Building CXX object src/passes/CMakeFiles/passes.dir/PickLoadSigns.cpp.o
[ 52%] Building CXX object src/passes/CMakeFiles/passes.dir/PostEmscripten.cpp.o
[ 53%] Building CXX object src/passes/CMakeFiles/passes.dir/Precompute.cpp.o
[ 54%] Building CXX object src/passes/CMakeFiles/passes.dir/Print.cpp.o
[ 55%] Building CXX object src/passes/CMakeFiles/passes.dir/PrintCallGraph.cpp.o
[ 56%] Building CXX object src/passes/CMakeFiles/passes.dir/RelooperJumpThreading.cpp.o
[ 57%] Building CXX object src/passes/CMakeFiles/passes.dir/ReReloop.cpp.o
[ 58%] Building CXX object src/passes/CMakeFiles/passes.dir/RemoveImports.cpp.o
[ 59%] Building CXX object src/passes/CMakeFiles/passes.dir/RemoveMemory.cpp.o
[ 60%] Building CXX object src/passes/CMakeFiles/passes.dir/RemoveUnusedBrs.cpp.o
[ 61%] Building CXX object src/passes/CMakeFiles/passes.dir/RemoveUnusedNames.cpp.o
[ 63%] Building CXX object src/passes/CMakeFiles/passes.dir/RemoveUnusedModuleElements.cpp.o
[ 64%] Building CXX object src/passes/CMakeFiles/passes.dir/ReorderLocals.cpp.o
[ 65%] Building CXX object src/passes/CMakeFiles/passes.dir/ReorderFunctions.cpp.o
[ 66%] Building CXX object src/passes/CMakeFiles/passes.dir/SafeHeap.cpp.o
[ 67%] Building CXX object src/passes/CMakeFiles/passes.dir/SimplifyLocals.cpp.o
[ 68%] Building CXX object src/passes/CMakeFiles/passes.dir/SSAify.cpp.o
[ 69%] Building CXX object src/passes/CMakeFiles/passes.dir/Untee.cpp.o
[ 70%] Building CXX object src/passes/CMakeFiles/passes.dir/Vacuum.cpp.o
[ 71%] Linking CXX static library ../../lib/libpasses.a
[ 71%] Built target passes
make: *** [Makefile:130: all] Error 2
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2606, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 1410, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "/usr/lib/emscripten/tools/system_libs.py", line 701, in get_ports
    ret += filter(lambda f: not f.endswith('.txt'), port.get(Ports, settings, shared))
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "/usr/lib/emscripten/tools/cache.py", line 100, in get
    temp = creator()
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "/usr/lib/emscripten/tools/system_libs.py", line 689, in build_native
    subprocess.check_call(['cmake', '--build', '.'] + make_args)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2
scons: *** [bin/godot.javascript.opt.webassembly.js] Error 1
scons: building terminated because of errors.
```

I tried to run emcc --clear-ports but it doesn't solve the issue.
Is there another way ?
Am I missing another package ?


Additionally, If I export my basic test game to HTML 5 (containing only AnimatedSprites, TextureButtons, signals and a scene change) with asm.js, I get this Error Output: 
```
**ERROR**: pre-main prep time: 4 ms
let it go dude!
**ERROR**: Calling stub instead of sigaction()
Successfully loaded turbo-dispute.pck/project.godot or project.binary
Init OS
Init Audio
Init VS
Init Physicsserver
WARNING: not found: physics/2d/thread_model
OpenGL ES 3.0 Renderer: Mozilla
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
**ERROR**: exit(0) implicitly called by end of main(), but noExitRuntime, so not exiting the runtime (you can use emscripten_force_exit, if you want to force a true shutdown)
Successfully populated IDB file system
close turbo-dispute.pck flags 1
close turbo-dispute.pck flags 1
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
**ERROR**: Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
**ERROR**: warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
```

Can we open this bug again ?

Thanks for your work... !

**Comment by nylnook** [comment]
Sorry for the noob question... but I already installed Binaryen successfully on my system (v37 thought AUR)... Why Godot (or Scons) wants to install it again, in a buggy version ? Can I bypass that ? Should I continue this discussion on IRC ?

**Comment by eska014** [comment]
> Why Godot (or Scons) wants to install it again, in a buggy version ?

Emscripten wants to install it, because it knows which Binaryen version is compatible with the Emscripten version.

You can override it by specifying `BINARYEN_ROOT='/path/to/binaryen_dir'` in the `~/.emscripten` file.

**Comment by stubbsy345** [comment]
Thanks for the fix, is there likely to be an alpha2 soon, or is ti planned just to head for beta? Just weighing up if it's worth downloading the master or waiting for a more stable release.

**Comment by nylnook** [comment]
OK, this is incredibly COMPILING !
Many thanks for your help @eska014 and @akien-mga !
Modify the `~/.emscripten` file with `BINARYEN_ROOT='/usr/bin'`worked.

I will try to update the compilation documentation tomorrow (I have to leave for a meeting now).

And the Webassembly export is working much more than the Asm.js one:
http://nylnook.art/godot-webassembly/turbo-dispute.html
This a basic test (obviously not optimised) for an interactive comic (an arguing with several ends), there are empty TextureButtons on the characters... which start a transition and lead to others scenes, another step of the arguing.

This is working in Godot Editor and with the Linux Binary export template of Alpha1, but... as you can see, the buttons are not reacting on this HTML5 export (at least in Firefox 55 and Chromium 61). I can share the source files if it's useful for debugging. 

Cheers !

**Comment by eska014** [comment]
@stubbsy345
There'll be another alpha snapshot

@nylnook
The mouse issue is a regression from 844c5e12e664e3212feacc9ee3200e116556fbc7, fixed in d1ecc25db4673019d8eff8b90bd94bd60ab2906e

---

Please open a new issue if there's anything else, this thread is already way too long

**Comment by nylnook** [comment]
@eska014 Thanks a lot for the fix, this is now fully working for my test (updated [here](http://nylnook.art/godot-webassembly/turbo-dispute.html)) ;)
I tried to update the documentation with the issues you helped me to solve and submitted a pull request, I hope it will be useful.

**Comment by jonglae** [comment]
**ERROR**: Failed loading file 'tmp_export.wasm'

**Comment by jonglae** [comment]
![_007](https://user-images.githubusercontent.com/12964975/35459101-2ec2e808-0322-11e8-984e-c81edcd5312f.png)

**Comment by vnen** [comment]
@jonglae please open a new issue and fill the template.
