### ISSUE TITLE
Weird lanes of pixels in tilemaps

### ISSUE THREAD

**Issue by Turbito** [godotengine/godot#11417]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux + Windows. Tested in both Nvidia 970M, Intel 520 and R480. Tested alpha1 and a nightly version (build at 15:30 2017/09/27
For some weird reason only renders right on the radeon on linux.
I have tried to do a clean instalation of godot (cleaning all config files)

**Issue description:**
Right: imported png with region activated (16x16 pixels)
Left: 16x16 tilemap with the image of the left imported as tileset
![imagen](https://user-images.githubusercontent.com/11560400/30596207-c10eb7b2-9d53-11e7-8022-154a450c2272.png)

If in the image of the right I check "filter clip" they both looks the same.
I have noticed issue https://github.com/godotengine/godot/issues/9925 but it seems not resolved for me on a nightly build (details of my build at top)

**Steps to reproduce:**
1.- Import a png and cut it.
2.-Create a tileset with these image.
3.- Use these image in a tilemap

**Link to minimal example project:**

[test.zip](https://github.com/godotengine/godot/files/1314497/test.zip)

**Comment by trollworkout** [comment]
This was in 2.1 as well and you had to disable some kind of filter but for 3.0 I don't know what's going on

**Comment by reduz** [comment]
as far as i remember, this was fixed after alpha, please make sure you are
testing an updated build

**Comment by Turbito** [comment]
compiled until commit and happens for me 
https://github.com/godotengine/godot/commit/d1ecc25db4673019d8eff8b90bd94bd60ab2906e

**Comment by kubecz3k** [comment]
Not sure if related but it reminds me how "fix alpha border" is working (image import settings http://docs.godotengine.org/en/latest/learning/workflow/assets/importing_images.html#fix-alpha-border).

**Comment by groud** [comment]
As said #11688, this also happen with AnimatedSprite.

**Comment by zedutchgandalf** [comment]
This still happens in Alpha 2. I did find, however, that this only happens when you're using a non-power-of-two spritesheet

**Comment by reduz** [comment]
Filter clip just enables this piece of code, there may be something wrong on it:
https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl#L382

maybe there is a better way to do this..

**Comment by NathanWarden** [comment]
I'll take a stab at this one. It looks like maybe the math is a little bit off.

**Comment by NathanWarden** [comment]
Actually, it looks like @reduz already fixed this with 19b1ff0fc5f7acce23176ad6c8752604357472f0

**Comment by reduz** [comment]
i didnt completely fix it, if you turn on filter clip it will come back, it
seems to be related to the shader in canvas.glsl when filter clip is
enabled, but i think the code is right..

**Comment by NathanWarden** [comment]
You're talking about the "Clip Uv" setting, right?

**Comment by reduz** [comment]
yeah

**Comment by NathanWarden** [comment]
Okay cool, I think I got it. But, am going to make sure it's the right fix. :)

**Comment by NathanWarden** [comment]
Yep, should be good to go. I also checked it against an even and an odd size (16x16 and 17x17) to make sure it isn't off by half a pixel. It was clamping it one pixel short, causing stretching of the last pixel row/column.

**Comment by reduz** [comment]
closed by #12828
