### ISSUE TITLE
Godot 3.0 Beta 1 Export Templates Issue

### ISSUE THREAD

**Issue by lmbarros** [godotengine/godot#13426]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
ArchLinux

**Issue description:**
I wasn't able to properly export my projects after installing the export templates. The export screen reported that it couldn't find the template files. This used to work in Alpha 2.

I managed to make them work after manually moving the files to `.local/share/godot/templates/3.0-beta.`

For HTML export, I also had to rename the templates files from `javascript_release.zip` to `webassembly_release.zip` (and the same for the debug version).

**Comment by akien-mga** [comment]
I've fixed the issue about the javascript templates in new `.tpz` archives, but I don't understand the part about moving the files. For me they do get installed in `~/.local/share/godot/templates/3.0-beta/` as expected. Where did they get installed for you, and what installation procedure did you use?

**Comment by lmbarros** [comment]
Thanks for looking into this!

As far as I remember, this was the sequence of what I did:

1. Downloaded the Beta `.tpz`.
2. Installed it from the file
3. Noticed that export to HTML wasn't working
4. Clicked on the "remove templates" button.
5. Installed the templates again, this time through the Godot UI (not by
manual download).
6. Still not working
7. Started to look for what could be wrong
8. Found some import templates under `~/.godot/some/other/dir`
9. Noticed some message in the Godot UI saying that it was looking for the
templates in `~/.local/share/...`
10. Looked in `~/.local/share/...`, was empty

I am saying this from memory, cannot check my computer now. But then,
honestly, halfway through this process I was already in hacker mode, just
trying to fix. I might very well have caused the templates location issue
myself. :-/

I can try again from scratch later today, when I am back home.

**Comment by akien-mga** [comment]
Ok, so the templates you had in `~/.godot/templates` come from earlier versions, as that used to be Godot's templates dir. You can delete them.

The ones you got installed with (2) should have been in the right directory, albeit with the wrongly named HTML templates as mentioned.

As to (6) + (10), it might be a bug in the download method, I'll look into it. When I've tried it today it was behaving weirdly.

**Comment by letheed** [comment]
Download from godot froze at 99.smthing % for me, and godot stopped responding. Had to kill it and restart. I downloaded manually and installed from file.

**Comment by lmbarros** [comment]
So, this time I was more careful and took note of what I did.

First, I got rid of all Godot-related settings I could find:

```
rm -rf .godot
rm -rf .local/share/godot
rm -rf .config/godot
```

Then I ran `Godot_v3.0-beta1_x11.64`, and asked it to download the export templates for me, from the "Official Beta 1 HTTPS" mirror.

I wasn't looking at the download screen all the time, but I *think* it finished the download (it certainly was well over 90%). But then the UI stopped to respond. The console was in a loop, just showing this over and over:

```
templates/android_debug.apk
ERROR: add_task: Condition ' tasks.has(p_task) ' is true.
   At: editor/progress_dialog.cpp:168.
templates/android_debug.apk
ERROR: add_task: Condition ' tasks.has(p_task) ' is true.
   At: editor/progress_dialog.cpp:168.
templates/android_debug.apk
```

I took a shower, returned some 20 minutes later and it was still in this loop. (Notice that I am running the same Godot binary as I was yesterday, and yesterday it completed the download and installation of the templates. Maybe this was an intermittent issue. Or maybe it is the same that @letheed reported above.)

So, tired of waiting for Godot, I killed it. My `.local/share/godot/templates/3.0-beta` is still empty.

I downloaded `https://downloads.tuxfamily.org/godotengine/3.0/beta1/Godot_v3.0-beta1_export_templates.tpz` manually.

Ran Godot again to install the templates manually from the file. Hmm, the UI reported that 3.0-beta templates were already installed.

Quit Godot, `rmdir .local/share/godot/templates/3.0-beta`, run Godot again. Great, now it says the templates are missing. I installed them from the downloaded file. Cool, *now* `.local/share/godot/templates/3.0-beta` is populated!

Exported a sample project to win32, win64, linux64, html5 and all of them worked.

**Comment by joshwhitk** [comment]
I'm having similar problems on Windows 10, too. 

I could be doing something stupid, FYI - I'm a junior programmer, coming from Unity, where I was able to export to Android - I'm learning Godot, trying to build my first Android build. I encountered probably related problems. (win 10, Godot 3.0 beta build 1.)

Following the documentation export instructions, I set the JDK, Android's SDK, and the keystorefile.  

![image](https://user-images.githubusercontent.com/3356949/33872993-3ef6caa6-df54-11e7-8365-d46c72797cb2.png)

I downloaded the Export templates using the dialog UI, and the dialog shows them installed.
(Manage Export Templates dialog says "3.0 beta installed")

...but when I go to Export it says 'export templates for this platform are missing' when I add Android preset, alone:

![image](https://user-images.githubusercontent.com/3356949/33872749-200942fa-df53-11e7-85ce-e3f59a6e788f.png)

If I add Windows preset as well as Android, I get another message:
![image](https://user-images.githubusercontent.com/3356949/33872819-6affa24a-df53-11e7-9150-1ab7837f3637.png)

I hope that helps!

**Comment by joshwhitk** [comment]
I forgot to note that Godot crashed after completed the template download.

**Comment by akien-mga** [comment]
> I forgot to note that Godot crashed after completed the template download.

Then they probably didn't get installed properly, but there's enough to full the Export Templates Manager to make it say "installed". The download function seems buggy in beta1, try to download the templates yourself and select to install from a file.

**Comment by akien-mga** [comment]
The issues mentioned here were fixed in 3.0 beta 2.

**Comment by Sseriously** [comment]
lmbarros's solution shows this...

Last login: Wed Jan 10 13:33:03 on ttys000
Seriouslys-MacBook-Pro:~ seriouslyultra$ /Users/seriouslyultra/Desktop/Platformer\ 2D.app/Contents/MacOS/Platformer\ 2D ; exit;
arguments
0: /Users/seriouslyultra/Desktop/Platformer 2D.app/Contents/MacOS/Platformer 2D
Current path: /Users/seriouslyultra/Desktop/Platformer 2D.app/Contents/Resources
OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Graphics 6100
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:791.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:1855.
ERROR: _load: Failed loading resource: res://coin.gd
   At: core/io/resource_loader.cpp:184.
ERROR: poll: res://coin.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://coin.gd
   At: scene/resources/scene_format_text.cpp:182.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:147.
ERROR: _load: Failed loading resource: res://coin.tscn
   At: core/io/resource_loader.cpp:184.
ERROR: poll: res://stage.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://coin.tscn
   At: scene/resources/scene_format_text.cpp:182.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:147.
ERROR: _load: Failed loading resource: res://stage.tscn
   At: core/io/resource_loader.cpp:184.
ERROR: start: Failed loading scene: res://stage.tscn
   At: main/main.cpp:1596.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1988.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]



...when i try to open the .app output build I got from

https://downloads.tuxfamily.org/godotengine/3.0/beta1/Godot_v3.0-beta1_export_templates.tpz
