### ISSUE TITLE
Particles 2D ignore AtlasTexture region

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13923]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

**Issue description:**

Atlas texture region for particles is working in Godot2, but not in 3. 
Atlas texture works in Sprite in both.
The image shows same resource (AtlasTexture) for the two nodes:
I try all options of ParticlesMaterial / CanvasItem/ AtlasTexture etc... etc...

![particles2ddoesntlikeatlas](https://user-images.githubusercontent.com/11712737/33526860-3e387380-d847-11e7-8cdd-03257174b59b.jpg)

**Comment by samdze** [comment]
Still present in 3.0.3 stable.

**Comment by guelinator** [comment]
Still present in 3.1 stable

**Comment by Anyeos** [comment]
Still present in 3.2 stable but at first try it worked and when I opened the Scene the second time it stoped working. It does not work playing game neither. I am using Particles2D not CPU.

**Comment by akien-mga** [comment]
This is fixed by #32496 for 4.0 and 3.2.1.

**Comment by samdze** [comment]
#32496 only fixes the CPUParticles2D bug, this issue is about the Particles2D one, which seems like it has not been fixed yet.

**Comment by Slluxx** [comment]
nope, not fixed

**Comment by bitbrain** [comment]
With 3.2.1 I can confirm that this bug is still a thing:

I configured the AtlasTexture and the preview shows it correctly:

![1](https://user-images.githubusercontent.com/822035/86801374-d709d180-c06b-11ea-8391-015636e18860.PNG)

However, when being rendered it always renders the full texture and ignores the region:

![2](https://user-images.githubusercontent.com/822035/86801371-d6713b00-c06b-11ea-96cf-d55167b65ed6.PNG)

**Comment by raphaklaus** [comment]
JFYI: It happens with me on version 3.2.3

**Comment by boruok** [comment]
same with 3.2.4. rc1

**Comment by Slluxx** [comment]
How is it possible that this is still an issue, 3 years after opening it.

**Comment by Calinou** [comment]
@Siluxx Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by chucklepie** [comment]
In the meantime, how about either disabling region option from particle2D and/or providing a better tooltip, one that explicitly states (like the online documentation) that regions are not supported?

**Comment by Geometror** [comment]
Should be fixed with #64701. Testing is welcome :)
