### ISSUE TITLE
LineEdit and TextEdit do not accept input events entering text, causing them to pass to unhandled.

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#15071]
**Godot version:**
8b0ad17b760b6cc803edc815fe65f8de1d92bf74

**OS/device including version:**
OS X El Capitan 10.11.6

**Issue description:**
`LineEdit` and `TextEdit` don't seem to correctly do `accept_event()` on input events that actually enter text into them (input events like backspace to clear text are fine though!), as such, they pass through to unhandled input which isn't ideal.

I should, the enter key to enter text also has this issue, but that one seems like a really easy fix, because it's doing a `return` before the `accept_event()` call.

I tried to look into this but they're still calling `accept_event()`, so I have absolutely no idea why the events are being passed to unhandled.

**Steps to reproduce:**
1. Type into a `LineEdit`
2. See unhandled input go off everywhere.

**Minimal reproduction project:**
[Unhandled LineEdit Input.zip](https://github.com/godotengine/godot/files/1587638/Unhandled.LineEdit.Input.zip)

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by PJB3005** [comment]
Ok I decided to look into this more. This is because Godot sends key events and unicode input events as separate objects, so the *unicode* ones are handled but the regular press events aren't. That makes sense but I still feel that consuming the regular ones is a good idea for QoL purposes.

**Comment by raymoo** [comment]
Are there use-cases for separate unicode and key event handling? Like maybe if you want to be able to cancel the LineEdit with some key combo, or if you want to be able to do other stuff while typing using a modifier key?

**Comment by brainsick** [comment]
Would one use case be manually implementing Windows-style ALT+NNNN character entry?  #15098 #2689

**Comment by PJB3005** [comment]
Turns out the behavior is actually not consistent between platforms. On Windows the key press events are sent with their unicode key, but on MacOS the unicode keys are sent separately. So that should probably be fixed at least (?)

As for use cases: if I absorb a key press based on Unicode I don't want to have to be chasing a secondary event constantly. I have a key (\`) to toggle the debug console in my game. I had to implement a hack to disable game input entirely if the GUI has a `LineEdit` focused because I knew regular characters would slip through unhandled (though I'm not ruling out that there may be a better way to handle that).

I can't think of any reason why you'd want to separate them, because I can't think of anything you *couldn't* do even when they're the same event.

**Comment by hedin-hiervard** [comment]
Actually, on MacOS all the events (Enter, Backspace and text input) is not consumed and then passed to other nodes' _input() and _unhandled_input() handlers. The logical thing to do is to accept_event() in the TextEdit's handler, but doing so block it completely (it consumes the event before it has the chance to catch it).
This is a severe bug that prevents normal use of those components.
Tried on Godot 3.1 beta 6.

**Comment by dluke** [comment]
After encountering this issue and reading LineEdit.cpp I subclassed LineEdit to "short circuit" and catch desired input. I put it here firstly so that other people finding this issue can get a quick solution and secondly to generate discussion on whether behaviour similar but not identical to this should be implemented in godot by amending `LineEdit._gui_input()` and perhaps implementing `LineEdit._input()` if necessary.
```
extends LineEdit
class_name SafeLineEdit

func _input(event):
	if (has_focus() && is_editable() && event is InputEventKey 
		and event.unicode >= 32 and event.scancode != KEY_DELETE):
		_gui_input(event)
		accept_event()
```

**Comment by TheDuriel** [comment]
I can confirm the _bug_ here.

_unhandled_input will fire on inputevents received by LineEdit.

This makes it incredibly difficult to lets say: Have Enter open a chat interface and focus its LineEdit. Then hide and release focus of said interface when the user presses Enter again to send their message.

Because what will happen is that the message will be sent you hide and release focus, then _unhandled_input fires and you immediately require focus.

**Comment by KawanWeege** [comment]
Can confirm in 3.2.1.
I moved the movement input of my player character into `_unhandled_input `just so I could prevent that the player moves when he's typing in that chat. It didn't work at first, and I had to do a work-around.

Though, when I was doing a "teleport to home base" hotkey, that was written in an _unhandled_input function, I noticed that it didn't teleport the player when I was typing in the key in a LineEdit. It appears that when I type the character in the LineEdit, it would pass the InputEvent to _unhandled_input with pressed set to false.

**Comment by YuriSizov** [comment]
Seems to me this should be fixed in `master` now (though I cannot test). `LineEdit` has been fixed by the aforementioned PR, and `TextEdit` looks complete to me as well. Let me know if we need to reopen (or perhaps, open a new issue against the current Godot 4 version).

**Comment by jrockett6** [comment]
In Godot 4 this is working as intended on Mac OS. 

However, it's not clear to me what the intended workflow is for when you are working with input polling as these are [not handled](https://docs.godotengine.org/en/stable/classes/class_input.html): 
> Note: Input's methods reflect the global input state and are not affected by [Control.accept_event](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-accept-event) or [Viewport.set_input_as_handled](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-method-set-input-as-handled), as those methods only deal with the way input is propagated in the [SceneTree](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree).

which is the commonly [recommended](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/03.player_movement_code.html) workflow for handling movement code, where simultaneous inputs need to be polled.

Is there an appropriate workaround that exists? Either limiting the Input singleton to unhandled events or polling for actions simultaneously in the scene tree input propogation?

**Comment by marcuslimdw** [comment]
This appears not to be fixed for me on an M2 Mac running MacOS Ventura 13.5.2 with Godot 4.1.1 stable.

Minimal reproduction: [example.zip](https://github.com/godotengine/godot/files/12567566/example.zip)

Observations (with the `LineEdit` having focus):

* Tapping any key produces an `InputEvent` with `IsPressed()` returning `false`.
* Holding down certain keys (couldn't ascertain any pattern) continuously produces `InputEvents` with `IsPressed()` returning `true`, and then a single `InputEvent` with `IsPressed()` returning `false` when the key is released.
* Holding down other keys does *not* continuously produce `InputEvents` except for a single `InputEvent` with `IsPressed()` returning `false` when the key is released.

**Comment by jrockett6** [comment]
I figured not consuming key release events was intended behavior, given that a symbol doesn't appear from them. But it seems like it would be useful to consume them, it would make my movement case much simpler.

**Comment by alakoring** [comment]
If I understand the bug, it’s still happening in 4.1.3 stable (on macOS 12.7).

My `LineEdit` enters text when I type when it’s focused. But a parent node receives `_unhandled_key_input` (with the same event).

And another node in my scene graph also gets `__unhandled_key_input` (with that event).

I would expect the `LineEdit` to stop propagation of a key that it handles.

**Comment by jrockett6** [comment]
@alakoring Are you sure these are not `released` events? 

Also the comment prior is clearly the released events not being handled, which I think is expected behavior. It would be a nice to convenience to have, but it makes sense that the default doesn't stop propagation of events that aren't actually being used by the `LineEdit`.

**Comment by marcuslimdw** [comment]
@jrockett6 I would've thought so, except for the second point, which was kind of strange IMO - don't have an MVCE or repro steps though

**Comment by FrasherGray** [comment]
I'm experiencing this problem with `released` events (I need both `pressed` and `released` events for the same key). Is there a fix planned/ongoing?

**Comment by ShenCiao** [comment]
I encounter the same `released` problem in Godot 4.4.1.
