### ISSUE TITLE
Godot crash at start using LLVM as compiler

### ISSUE THREAD

**Issue by robfram** [godotengine/godot#15360]
**Godot version:**
custom-built 8ec06de6681a600bd5a74b4a1bdea85f656b5a88
It also crashed before commit https://github.com/godotengine/godot/pull/15330/commits/76b5f8b0df2a4dc0117684e6e4f503ac378dde65
It worked with https://github.com/godotengine/godot/pull/15326/commits/f2afddbc5201ac7396373beb91f8a8d474013b08

**OS/device including version:**
FreeBSD 11.0-RELEASE-p1 r306420
Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (2195.06-MHz K8-class CPU)

**Issue description:**
After successfully compiled with llvm 4.0.1, it crashed at starting the Project Manager.
```
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 0x806ec778f <pthread_sigmask+0x4ff> at /lib/libthr.so.3 (??:0)
[2] 0x806ec6d6f <pthread_getspecific+0xe9f> at /lib/libthr.so.3 (??:0)
-- END OF BACKTRACE --
Abort trap (core dumped)
```
It works compiling with GCCv7 from pkg.
`$ scons platform=x11 CXX=g++7 CC=gcc7 CCFLAGS="-Wl,-rpath=/usr/local/lib/gcc7" CFLAGS="-Wl,-rpath=/usr/local/lib/gcc7" -j 4 
`

**Steps to reproduce:**
$ scons platform=x11 use_llvm=yes -j 4
$ bin/godot.x11.tools.64.llvm

**Comment by akien-mga** [comment]
This was likely fixed by fab0d53f, can you confirm?

**Comment by akien-mga** [comment]
BTW you stacktrace lacks debug information, do you move/rename your binary?

**Comment by LinuxUserGD** [comment]
Same issue on Ubuntu Linux.

Output (when I execute the application in terminal):
```
No touch devices found
WARNING: initialize: XOpenIM failed
   At: platform/x11/os_x11.cpp:229.
WARNING: initialize: XCreateIC couldn't create xic
   At: platform/x11/os_x11.cpp:408.
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f4ac91cd4b0] (??:0)
[2] OS_X11::initialize(OS::VideoMode const&, int, int) (/media/user/user/git/Godot/godot/platform/x11/os_x11.cpp:519 (discriminator 3))
[3] Main::setup2(unsigned long) (/media/user/user/git/Godot/godot/main/main.cpp:986)
[4] Main::setup(char const*, int, char**, bool) (/media/user/user/git/Godot/godot/main/main.cpp:925)
[5] /media/user/user/git/Godot/godot/bin/godot.x11.tools.64.llvm(main+0xa6) [0x100a0f6] (/media/user/user/git/Godot/godot/platform/x11/godot_x11.cpp:47)
[6] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f4ac91b8830] (??:0)
[7] /media/user/user/git/Godot/godot/bin/godot.x11.tools.64.llvm(_start+0x29) [0x1009f79] (??:?)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment]
> Same issue on Ubuntu Linux.

What commit? I maintain that this issue should be fixed already.

**Comment by LinuxUserGD** [comment]
Sry, it is fixed.

**Comment by robfram** [comment]
I compiled as usual, but explicit target=debug gets this result:

```
$ scons platform=x11 target=debug use_llvm=yes -j 4
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 99%] progress_finish(["progress_finish"], [])
[100%] scons: done building targets.
```

```
$ file godot.x11.tools.64.llvm*
godot.x11.tools.64.llvm:              ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100122), FreeBSD-style, stripped
godot.x11.tools.64.llvm.debugsymbols: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), corrupted program header size, for FreeBSD 11.0 (1100122), FreeBSD-style, not stripped
```

```
$ ./godot.x11.tools.64.llvm
No touch devices found
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 0x806ec778f <pthread_sigmask+0x4ff> at /lib/libthr.so.3 (??:0)
[2] 0x806ec6d6f <pthread_getspecific+0xe9f> at /lib/libthr.so.3 (??:0)
-- END OF BACKTRACE --
Abort trap (core dumped)
```


Any tips to help debugging? I tried gdb and gdb crashed.

**Comment by LinuxUserGD** [comment]
Did you update your Godot folder via git pull? What about 'bits=64' in the Scons command? I tried it with target=debug and it works fine.

**Comment by akien-mga** [comment]
> `godot.x11.tools.64.llvm.debugsymbols: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), corrupted program header size, for FreeBSD 11.0 (1100122), FreeBSD-style, not stripped`

That's interesting, that could explain the bad stacktrace. Maybe the method used to strip the debug symbols is invalid on FreeBSD? Ping @hpvb.

Otherwise you confirm that you still get the crash with fab0d53, right?

**Comment by robfram** [comment]
Solved with fab0d53, sorry for the troubles.
I though doing a "git pull --rebase upstream master" always get the lastest version.
Anyway, if you need more test about the corrupted debugsymbols file, don't hesitate to contact me.

**Comment by akien-mga** [comment]
> Solved with fab0d53, sorry for the troubles.
I though doing a "git pull --rebase upstream master" always get the lastest version.

No worry. In theory it should give you the latest, but I guess you sync before this commit was pushed (it was one hour before your issue).

> Anyway, if you need more test about the corrupted debugsymbols file, don't hesitate to contact me.

It would be nice to have it work on FreeBSD, so maybe open an issue about it so that we can debug further.
