### ISSUE TITLE
Unable to write to file xxxx file in use, locked or lacking permissions (Windows 10)

### ISSUE THREAD

**Issue by nshusa** [godotengine/godot#16274]
Apologize if there's an issue for this already.

**Godot version:**
3.0 stable

**OS/device including version:**
Windows 10, Nvidia GTX 1070

**Issue description:**
I get this extremely annoying popup that says "Unable to write to file xxx file in use." This happens very frequently but not everytime. This issue is very tedious for Windows users.

I am using both Avast and Malwarebytes.

![https://i.imgur.com/X61a9wv.png](https://i.imgur.com/X61a9wv.png)

**Steps to reproduce:**
I get this issue trying to open up or save files.

**Comment by Zylann** [comment]
Duplicate of https://github.com/godotengine/godot/issues/14339

**Comment by nshusa** [comment]
@Zylann I do yes. Avast

**Comment by vnen** [comment]
> none of your files will save when the message pops up.

I'm pretty sure it saves all the files that are not in the message (sometimes they're saved even when they are in the message).

**Comment by nshusa** [comment]
@vnen It will eventually but I think many files get locked at once. The popup only shows you the last ones. I think this because I had issues where I was using gdscript for a player then I removed the script added visual script tried to save and godot thought I was still using gdscript for the player...

I think this is also causing this issue as well.
![https://i.imgur.com/OseFEAx.gif](https://i.imgur.com/OseFEAx.gif)

**Comment by AlmightyScientist** [comment]
Maybe it's related to a bad use of Win API? 

@RayKoopa cc

**Comment by RayKoopa** [comment]
baseless assumption tho, and I have no time to check atm sorry :p

**Comment by AlmightyScientist** [comment]
I thought I had a friend. 🔫 

Noprob bro. But ye, I've checked it before and we argued about the weird Unicode tricks.

**Comment by RayKoopa** [comment]
I recall they turned out correct though

I'm nobodies friend, except akiens maybe, but he doesn't accept me...

**Comment by Calinou** [comment]
I've had this happen on Windows 10 without any antivirus (and Windows Defender disabled). I haven't tested it since December, but I figure it's still the case now.

**Comment by DaDude** [comment]
I'm almost sure Godot is locking the files at least in some cases.
I recently stumbled upon this bug myself when reimporting all of my assets after cloning my repository.
Some of my stex files were broken afterwards so i just deleted everything in the .import folder so i would get a fresh start.

Then i observed something strange:
Sometimes when the "(Re)importing Assets" progressbar appears, it stays at 0% and the UI locks up completely. After a few seconds all files were imported properly.
But when the UI didn't lock up and the progressbar showed it's progress properly there were one or more broken files in the .import directory.

I tried this a few more times on different machines all running Windows 10, no antivirus and no Windows Defender enabled and this was 100% reproduceable.
I don't know if this helps at all, but maybe someone can derive a proper explanation or fix from this.
And if i can try something else to help just say a word ;)

**Comment by akien-mga** [comment]
> Sometimes when the "(Re)importing Assets" progressbar appears, it stays at 0% and the UI locks up completely. After a few seconds all files were imported properly.
But when the UI didn't lock up and the progressbar showed it's progress properly there were one or more broken files in the .import directory.

That's quite interesting. It wouldn't be the first time that the EditorProgress bar causes weird issues.

**Comment by indiemaniac** [comment]
This happens to me when i have a MEGASync running in that folder.
It stops happening if i exit MEGASync, should be the same with most cloud sync applications

**Comment by TomDobbelaere** [comment]
Please fix this, I've tried so many things.
- Running as Administrator
- Removing Godot from %appdata% so it is recreated
- Giving Godot from %appdata% permissions for Everyone and unchecking read-only
- Moving Godot from Documents to Program Files
- Running a newer (3.1 dev LSW) release

It's gotten even worse now for no good reason, with the editor locking up anytime it happens.
Please please focus all your efforts on fixing this, it's a glaring issue.

**Comment by TomDobbelaere** [comment]
I installed Godot on my tower, made a small sample project that imports a texture, has a sprite node with some code that is an instantiated scene.
Haven't had the pop-up once yet. I'll have to check if there's something specific to my laptop's confiugration causing the file locking issue.

**Comment by nshusa** [comment]
@TomDobbelaere I second this. Godot is also unusable for me as well because of this issue. I have tried disabling 3rd party Antiviruses and Window defender and still get this issue.

**Comment by akien-mga** [comment]
As far as I understand, this affects only Windows 10 users? Would need an experienced Windows 10 dev to profile the file accesses and see what Godot can do to workaround Windows' restrictions.

**Comment by vnen** [comment]
I do think it's Godot that's locking the files. I have seen this with the thumbnails if I save the scene twice in a row. Probably the editor is trying to access the file before the last run has released the handle.

**Comment by TomDobbelaere** [comment]
Can confirm, usually happened for me when it said something about generating Thumbnail

**Comment by TomDobbelaere** [comment]
For anyone willing to contribute, the file in question is file_access_windows.cpp, in particular the if (rename_error && close_fail_notify).

The comments mention paranoid antiviruses causing the issue by checking even non-executable files when writing them, though I doubt whether this is true since disabling my antivirus didn't help.

**Comment by TomDobbelaere** [comment]
Okay, I haven't fixed the file renaming issue, but someone was very lazy while writing the 'retry' code. I'll reference a commit in just a moment.

**Comment by akien-mga** [comment]
Fixed by #17869, thanks @TomDobbelaere :tada:

**Comment by drako0812** [comment]
I just wanted to say I'm still occasionally getting this problem in Godot 3.1 Alpha 1 (with and without Mono).  It's possible that I have an underperforming computer that has problems keeping up with the filesystem access. Usually I have no problems if I make sure to save again right after the error window pops up, and this problem is nowhere near as bad as it was a few months ago.

### System Information
OS: Windows 10 Home 64-bit
CPU: AMD A10-5750M
RAM: 8 GiB DDR3 @ 1600 MHz
HDD: 1 TB Seagate 5400 RPM SSHD (Upgraded from original HDD)
Antivirus: Avast Free Antivirus

**Comment by TomDobbelaere** [comment]
Does it still occur when disabling Avast temporarily?

**Comment by Banderi** [comment]
I have no AV running, including any that Windows has out of the box, and I still get this issue (slightly different location than that of the OP's image)

OS: Windows 7 Pro 64-bit
CPU: Intel Core i7 8700K
RAM: 16 GB DDR4
Antivirus: N/A

![output](https://i.imgur.com/3bo4xHq.png)
![output](https://i.imgur.com/yF8SsWR.png)

**Comment by Zylann** [comment]
I am getting this too in Godot 3.1 alpha1, on a computer that has no antivirus installed other than the default Windows one. Interestingly, that's the same computer as mine, but I don't remember getting the problem on mine.

![image](https://user-images.githubusercontent.com/1311555/47362116-9caba580-d6cb-11e8-915a-67b0ce8d171a.png)

**Comment by bmolyneaux** [comment]
I have this issue in v3.1.stable.official trying to save a gdscript. I'm on Windows without antivirus or version control.

**Comment by EpproxZimlon** [comment]
Think I'll try Unity until this issue with Windows 10 is fixed. 

I'm using Godot with Steam installation.

**Comment by Ace-Dragon** [comment]
I just want to place in here that I at least don't get this error anymore (with Win10 64 bit April Update, using AVG as the anti-virus software).

So this bug doesn't affect near as many setups now, but it looks like this is still ongoing with a few people.

**Comment by Toshiwoz** [comment]
Hi, I'm also still experiencing this in version 3.1.1, sporadically, and I believe especially with larger files, or when the computer is already busy reading/writing.

**Comment by mcbits** [comment]
For anyone still encountering this: Make sure your debugger has stopped! I was banging my head on the desk over a mysteriously locked scene until I realized my game had a bug such that closing the game window didn't actually kill the process. Stopping the debugger released the file, and I switched to banging my forehead on my palm.

**Comment by nathanwfranke** [comment]
Getting this with beta 4 on my Windows 10 machine
I get it if I try saving too many times in a second or so and I interrupt the save

**Comment by PMGRNTS** [comment]
Just stop the scene from playing in the window.

**Comment by nathanfranke** [comment]
If this is confirmed then we should re-open the issue :stuck_out_tongue:

**Comment by Calinou** [comment]
@nathanfranke There's already an open issue about this: https://github.com/godotengine/godot/issues/6393

**Comment by mobiusstrip** [comment]
> For anyone still encountering this: Make sure your debugger has stopped! I was banging my head on the desk over a mysteriously locked scene until I realized my game had a bug such that closing the game window didn't actually kill the process. Stopping the debugger released the file, and I switched to banging my forehead on my palm.

that was a bruh moment 🤦

**Comment by JoeBlackSci** [comment]
I'm Still having this issue.

Windows 10, no antivirus running.

**Comment by Koyasha** [comment]
I have this issue in Godot 4.0 on Win 10 when running scenes in one of the 3d projects.

**Comment by robbiesaurus** [comment]
Issue still exists on v4.1.2 on windows 10, please re-open this ticket. No antivirus and running Godot as admin does not fix the issue.

**Comment by Calinou** [comment]
Please open a new issue with a minimal reproduction project attached, as the exact cause is likely different nowadays compared to the original issue.
