### ISSUE TITLE
Line2D UV texture glitch

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16961]
Godot 3.0 master b6bf572e021f59ca9f6e95fca2e1cd08bd3fe0f2
Windows 10 64 bits
nVidia geforce 940M

Line2D looks corrupted when a texture is used on it with the Tile mode.

Here is how UVs are on 3.0 stable:
![image](https://user-images.githubusercontent.com/1311555/36618909-34468a10-18ed-11e8-959b-58848e261317.png)

And this is how they are on 3.0 master debug build:
![image](https://user-images.githubusercontent.com/1311555/36618928-40412352-18ed-11e8-80fe-12cd225277bb.png)

Project:

**Comment by hpvb** [comment]
This doesn't seem to happen in 3.0.1. However there are many log lines like this:
```
SHADER ERROR: (null): Expected 'shader_type' at the beginning of shader.
   At: :1.
ERROR: _update_shader: Condition ' err != OK ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1697.
0 
SHADER ERROR: (null): Expected 'shader_type' at the beginning of shader.
   At: :1.
ERROR: _update_shader: Condition ' err != OK ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1697.
0 
```

**Comment by Zylann** [comment]
What is 3.0.1? Isn't it master?

**Comment by hpvb** [comment]
@Zylann see the 3.0 branch or https://godotengine.org/article/dev-snapshot-godot-3-0-1-rc1 :)

**Comment by Zylann** [comment]
The bug is not present in 133942cfeb0279ca03ab9943459c5140ab1f1725

**Comment by hpvb** [comment]
it doesn't appear to happen when building master with mingw either. So this is a 'fun' one.

**Comment by JFonS** [comment]
@Zylann Do you have the project for that? I can check if it happens on my builds too.

**Comment by Zylann** [comment]
So I decided to verify differently.
Here is what the UVs are when the line gets a glitch:

```
(0, 0)
(0, 1)
(8.087137, 0)
(8.087137, 1)
(-158839966806181746533156862930074992640, -158839966806181746533156862930074992640)
(-158839966806181746533156862930074992640, -158839966806181746533156862930074992640)
(-158839966806181746533156862930074992640, -158839966806181746533156862930074992640)
(17.120441, 0)
(17.120441, 1)
```

For some reason I'm getting garbage for some of them.
So I decided to wrap every `uvs.push_back(uv)` call like this:

```cpp
//#define check_uv(_uv) _uv
Vector2 check_uv(Vector2 uv) {
	if(uv.x < -100.f || uv.x > 100.f)
		print_line("OUT");
	return uv;
}
...
uvs.push_back(check_uv(uv));
```

Aaaand... surprise. No longer glitches. 
INTERESTING.

**Comment by reduz** [comment]
Status of this? @Zylann @hpvb

**Comment by reduz** [comment]
I am not sure who wrote the original Line2D code.

**Comment by Zylann** [comment]
I wrote the original Line2D. We basically found this UV glitch was due to inserting a vector element inside itself (which is normal behavior of the line builder), however doing that had side-effects due to inserting a reference from a vector before it resizes internally, resulting in garbage UVs sometimes being added to that vector. @hpvb saw that too but don't remember if we ever chose an approach to fix this in general. Fixing this locally means never doing stuff like `vector.append(vector[i])`.

**Comment by hpvb** [comment]
@Zylann ah right, I totally forgot about this. I'll assign this to me and fix Vector.

**Comment by akien-mga** [comment]
Bump :)

**Comment by profan** [comment]
Note that any use of insert (or append_array) in Vector is also susceptible to the same problem currently, ala #31609  (i'm currently digging in CowData and the Vector bits so this caught my attention).

**Comment by akien-mga** [comment]
Fixed by #34618.

**Comment by IIGreed** [comment]
I was trying to use a texture on a line2d using the stretch mode when this happened:
![image](https://user-images.githubusercontent.com/72952945/181154422-cd8f68e3-9ef1-42df-89bd-78d3769e78b1.png)

Idk if it is related to this issue but this seemed to be the closest related issue I could find. Should I open a new issue?

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/50076#issuecomment-1194592877.

Please open a new issue with a minimal reproduction project attached.

**Comment by Zylann** [comment]
This artifact is actually normal in the current implementation. It is caused by the way the line is triangulated. It's not designed to support such a precise texturing. Adding some extra geometry around the angles can help, but you will still have the issue in the angles themselves.
