### ISSUE TITLE
MSG (3d) texture options (Flag) problems

### ISSUE THREAD

**Issue by Obaran** [godotengine/godot#1774]
_Bugsquad edit:_ Seen initially in 1.1 rc1.

I make repeat texture in Material Shader Graph editor. For that i must load same texture in Shader param and in edit mode turn on repeat option. In shader graph editor Edit mode dont work? If I click on edit, nothing happen. This is maybe second problem. The more big problem is, options under Flag in texture edit: mipmaps, repeat, filter, anisotropic etc.. are not saved. If I change repeat turn on, and save material and scene, after reload, the repeat option is turned off.

**Comment by reduz** [comment]
i thik this is fixed in github head, please check

**Comment by Obaran** [comment]
Hmm, I am sorry but I dont know what is github head and what does it means.

**Comment by okamstudio** [comment]
no worries, try RC2 fro the godot website, which should have the fix

On Tue, May 5, 2015 at 2:22 PM, Obaran <notifications@github.com> wrote:

> Hmm, I am sorry but I dont know what is github head and what does it means.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1774#issuecomment-99147613>.
>



-- 

*OkamStudio*

**Comment by Obaran** [comment]
In Rc2 still not working, the options under flag are not saving.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in 1.1 stable or in the nightly build of the upcoming 2.0?

**Comment by Griefchief** [comment]
I can confirm (and reproduce) an issue regarding 3d texture settings not being saved.

" options under Flag in texture (3d) edit: mipmaps, repeat, filter, anisotropic etc.. are not saved. If I change repeat turn on, and save material and scene, after reload, the repeat option is turned off."

I can confirm that this is still present in master compiled several days ago, I am guessing it's still in as of today. It's an issue that has been annoying me for a few months...

This is the behaviour that I've noticed:

1) It's intermittent, it happens for some textures, and for others it does not.

(grass after i set it to repeat and saved)
http://imgur.com/64fMYQF

(after saving/closing/reopening godot... no repeat on a ShaderMaterialGraph)
http://imgur.com/GOoTITN

(that grass texture on a FixedMaterial now, but it still won't save it's flag data...).
http://imgur.com/ZwwqemN

(and icon.png on a ShaderMaterialGraph, and it saves it's repeat flag after reopening... it's something with a particular texture, that fails on it but i can't quite pinpoint what after an hour of testing)
http://imgur.com/0mw1dyk

I can supply this project in the images if needed. After thinking it's FixedMaterial vs ShaderMaterialGraph issue at first, then through thorough testing realising it's not, my only other guess is that this texture was saved in a version of godot that master that didn't have propper edditing of multiple scenes still done...but that is nov/dec and this issue is present from Godot 1.1... so, no clue why this happens.

**Comment by quantum-entangler** [comment]
Griefchief: Do you perhaps use Windows as your OS and have relative paths enabled in editor settings?

**Comment by Griefchief** [comment]
@quantum-entangler I use Windows as my OS but i do not have "Save Paths As Relative" checked on in editor settings...

That said, i remmeber i did manually copy this project a few times before i used this current version I am opening and importing it back... If you've seen some code that might be the culprit, maybe it's still thining that it is in the old absolute folders?

I will check this by saving with "Save Paths As Relative" now...

**Comment by Griefchief** [comment]
@quantum-entangler Hm, nope, the scene and editor just seem to have bugged out now due to missing dependencies caused by saving as relative paths... it seems it won't even allow me to repair the dependencies (the screen that appears just won't allow itself to be changed in any way even though it shows a file import dialog for every missing dep..). A new bug report i guess if i can replicate this in a new minimal project.

**Comment by Griefchief** [comment]
Hm, i just noticed your edit regarding the issue you referenced... I will more later today probably and see if I can figure out if it is related.

**Comment by quantum-entangler** [comment]
@Griefchief If you don't have the setting on then I doubt it's related since I have been using Godot without running into issues with the setting off for months now, and through multiple point releases by now. The issue still exists though, should anyone turn it on.

**Comment by bojidar-bg** [comment]
Bump, is this issue still valid on master or 2.1.x?

**Comment by Griefchief** [comment]
I don't know about the shader graph report from above, but about the flags:

@bojidar-bg This issue is probably still valid, because it it was fixed, this code here bellow i linked would have been refactored into it's own common class or something similar to be reused by the jpg saver... Notice how every time when saving the png, it also saves the .flags file here for it... Well, there is copy of this code for JPEGs (and only JPEG's can't have their flags saved because of that)

https://github.com/godotengine/godot/blob/master/drivers/png/resource_saver_png.cpp#L59

What this does is basically save the PNGs on every modification that is done to them, back to the disk... so, every time you save a flag, godot seems to resave the PNG...

In any case, there is a similar "save" function for JPEG images that I can't find now (on short notice), if it does exist at all... resource_saver_jpg or _jpeg does not seem to exist not in drivers/jpeg or jpegd... The thing about JPEG's is that Godot doesn't save them... for obvious reasons... not a good idea to save jpegs over and over...

But because the .flags code i linked to above is .PNG only, godot never saves JPEGS Flags... So, the fix is to refactor the code in this whole "if (err=OK)" block that saves flags into it's own "common" class only for .Flags, and to call it from both jpeg save function, as well as from this png "save" funciton...

I debugged this back in August but could never find time to work on it, or on my own games, or on Godot at all :( Sorry. Hope I helped.

To repeat:

1) Flag saving issue happens only for jpegs, cause the flag saving code exists only inside of drivers/png/resource_saver_png.cpp

2) The fix is probably to refactor it out into it's own class and to apply it both in the current drivers/png/resource_saver_png.cpp as well as in whatever saves the jpeg's currently, if that saver exists, if it's not polymophically replaced with an empty resource saver stub... The save function for jpegs would only call the flags...

That's the simple way of fixing it anyway... I'm not sure if godot should resave the png for every flag change... but... I didn't mess with the internals enough to suggest how to fix that issue... I guess one at a time?

**Comment by Griefchief** [comment]
So please add a label to this bug report  that it's (probably) valid for both the next release, as well as all other releases, and should be checked (whether jpg save their flags when godot is shutdown and turned back on? the flags will persist in memory until godot is shutdown... but will not be read as the .flags file for jpeg is never created on the disc)?

**Comment by Zireael07** [comment]
Is this issue valid for 2.1 and 3.0? @reduz

**Comment by akien-mga** [comment]
The asset import system (include the flags) has been fully rewritten in 3.0, so I assume this might have been fixed/changed along the way.

If you can still reproduce a similar issue in the 3.0 release, I would suggest to open a new issue, as it would have better visibility when focusing on the current state than this older one.
