### ISSUE TITLE
scaling multiple nodes at once doesn't work

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#181]
If you select several nodes at once and then modify the scale property, the change does not apply to all selected nodes, only one of them.

(This was initially reported in the forum by another user, and I can confirm it. http://www.godotengine.org/forum/viewtopic.php?f=9&t=269 )

**Comment by akien-mga** [comment]
Can someone confirm that this issue still exists in the current master branch?

**Comment by akien-mga** [comment]
I checked and the issue is still valid. To be more precise, selecting multiple nodes and scaling them with the scale cursor function does work, but changing the scale parameter in the editor only affects one node as described above.

**Comment by nunodonato** [comment]
Can't replicate this. Might have been fixed before.
What I've notices is that when you multi-select and use the cursor to do changes, it works on all selected objects, even if the multi-edit mode is off. If you use the inspector (thinking that you are affecting all objects) it only changes in the last selected object (its id should be in the inspector title).

It's a bit weird and inconsistent. I would suggest entering multi-edit mode automatically as soon as you select more than one node.

**Comment by adolson** [comment]
Enabling multi-edit automatically makes the most logical sense, really.
It's how I think most people would expect it to behave.

**Comment by neikeq** [comment]
As of f9d615e multi-node edit is automatic. I can't reproduce this issue in the current master branch.

**Comment by MeroVinggen** [comment]
Godot 4.2.2 "scale mode" instrument still doesn't work for multiple chosen nodes
