### ISSUE TITLE
The environment panorama appears too bright sometimes

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18180]
Godot 3.0.2

Windows 10, GTX 1070

When I import a panorama image in .hdr, sometimes the image appears very bright. The bug appears randomly, sometimes the colors are correct and sometimes it appears very bright. I get the bug in a new project (I only have the environment node.
The HDR mode is enabled in the project quality settings, I use every default settings of the engine.

![super bright](https://user-images.githubusercontent.com/30020215/38745751-c8d9f0d0-3f45-11e8-8fef-d7d087152ec2.png)

You can get the HDRI map here if you want to try to reproduce the bug: https://hdrihaven.com/hdri/?c=skies&h=kiara_1_dawn

**Comment by BenjaminNavarro** [comment]
I know this issue is almost 2 years old but I have the impression that the bug is still around in 3.2.

My use case is a bit different (procedural generation of a PanoramaSky texture) but I end up with the same very bright sky and environment. But in my case it's not random at all.

What I find very strange also is that the result is different if you assign the same texture from the editor or when the game is running. 

Here is an example:
![Screenshot from 2020-02-22 11-32-48](https://user-images.githubusercontent.com/14923636/75090835-51c3cb80-5567-11ea-8f67-0684b6a707cd.png)
![Screenshot from 2020-02-22 11-33-01](https://user-images.githubusercontent.com/14923636/75090837-52f4f880-5567-11ea-988e-a08d5244409f.png)

It's clear that the first one (texture assigned from editor) is the correct one. It's very incapacitating for me since I can't implement a proper day/night cycle in my game because of this.

**Comment by Calinou** [comment]
I can reproduce this in Vulkan as well, even in the editor.

As a workaround, I added a MeshInstance with a CubeMesh that darkens what's outside the playable area. It's a hack, but it works surprisingly well :slightly_smiling_face: 

Download this ZIP, extract it instance the scene in your project: [darken_sky.tscn.zip](https://github.com/godotengine/godot/files/4239372/darken_sky.tscn.zip)

**Comment by BenjaminNavarro** [comment]
I reproduced your fix in 3.2 and it indeed darkens the sky, however the environment is still lit using the super bright sky so it's not a perfect fix for me. 

I can try to darken the generated texture though and see if it helps, never though about that

**Comment by Linko-3D** [comment]
For me the problem was fixed by increasing the maximum white value of the scene to avoid clamping:

![Clamp fixed](https://user-images.githubusercontent.com/30020215/75094490-dd4f5380-558b-11ea-8ca7-ab95c5fe0f62.png)

**Comment by BenjaminNavarro** [comment]
My white value is already at 16. 

But even if it made the situation better, there's a clear difference in the rendering between static and dynamic textures so that's probably a bug to fix.

**Comment by BenjaminNavarro** [comment]
I put together a small project showing the issue.

There are two scenes that just differ by the fact that one has a default value for the panorama texture and the other one hasn't.

When a scene is run, there is a button to toggle between two sky textures (day and night).

Two things can be seen:
	1. The scene without the default panorama texture displays a very bright sky while the other one is correct
	2. The illumination is wrong when the scene is started, probably related to #19030
	3. After toggling twice the texture to get back to the day, the scene with the default panorama texture has both a correct sky and illumination while the other one is wrong on both

[PanoramaSkyBug.zip](https://github.com/godotengine/godot/files/4239860/PanoramaSkyBug.zip)

**Comment by BenjaminNavarro** [comment]
I looked at the code and did a bit of debugging but I couldn't find anything...

I let this issue for someone with knowledge of the rendering pipeline to pin point the problem

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
I tried the latest repro, but the sky is black, so not sure what is the issue.

**Comment by KoB-Kirito** [comment]
Uhm, still present in 4.3.dev5?
I can turn the energy multiplier way down, 0.2 looks kinda like intended, but it feels .. wrong?
[minimal_reproduction.zip](https://github.com/godotengine/godot/files/15140248/minimal_reproduction.zip)
