### ISSUE TITLE
iOS build error (Undefined symbols for architecture arm64)

### ISSUE THREAD

**Issue by slmjkdbtl** [godotengine/godot#18359]
**Godot Version**
3.0.2

**OS Version**
macOS High Sierra 10.13.4

**Issue**
produces this error when tries to build on phone
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SKProduct", referenced from:
      l_OBJC_$_CATEGORY_SKProduct_$_LocalizedPrice in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKPayment", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**How to reproduce**
the build works fine in a blank projects with no scenes, produces error when added a scene

sorry i'm not familiar with iOS, xcode and can't get help from Q&A, discord and forums

**Comment by endragor** [comment]
Please provide your Xcode version and output of `xcodebuild -showsdks`. You need Xcode 9+ with iOS SDK 11+.

**Comment by samgreen** [comment]
You need to link against the StoreKit.framework in Xcode.

**Comment by thebartyparty** [comment]
A quick web search shows that you generally get linker errors such as `clang: error: linker command failed with exit code 1 (use -v to see invocation)` due to missing libraries. For me it was the `StoreKit.framework`. This is solved by going to _Build Phases > Link Binary With Libraries_ And pressing the plus button to add a library. In my case I just searched for `StoreKit` and added the library.

**Comment by endragor** [comment]
Notice that frameworks can be added from Godot plugins, so you don't have to mess with the Xcode project in this case. You can add a plugin with the following code:
```gdscript
tool
extends EditorPlugin

class MyExportPlugin:
	extends EditorExportPlugin

	func _export_begin(features, debug, path, flags):
		add_ios_framework("StoreKit.framework")

func _init():
	add_export_plugin(MyExportPlugin.new())
```

**Comment by samgreen** [comment]
@endragor This is incredibly useful, thanks for the tip about the export plugin.

For ease of use for everyone else, I would assume we always want to link against `StoreKit` so perhaps it would be worth modifying the export template.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by naithar** [comment]
Yes, I can reproduce this issue by removing `In-App Purchase` capability which in turn removed `StoreKit.framework` from liked libraries. Adding `StoreKit.framework` manually fixes the issue, but also returns `In-App Purchase` capability, which might not be the expected behavior.

Using `-fmodules` and `-fcxx-modules` for building iOS platform and modules code seems to be fixing all issues connected to missing symbols as it adds required frameworks automatically, but definitely requires some testing.

**Comment by akien-mga** [comment]
Fixed by #39762.
