### ISSUE TITLE
Can't create C# files: csproj.CopyComplete cannot be created

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#19699]
**Godot version:** Mono 3.0.3
**OS/device including version:** Windows 8.1 Enterprise; GPU is AMD Radeon 6700

**Issue description:**
- I installed Godot 3.0.3 with Mono support (64-bit)
- I installed the most recent Mono 5.10 version available
- I created a new Godot project on my E: drive
- I created a new Scene called `Player`
- I added some nodes (kinematic body, color rect, collision)
- I tried to add a new C# script file (`Player.cs' by default)
- I received this error (screenshot attached):
  - Message: `The file "E:\Release\GodotSharp.csproj.CopyComplete" cannot be created. Could not find a part of the path "E:\Release\GodotSharp.csproj.CopyComplete."`
  - Code: `MSB3771`
  - Type: `error`
  - File: `C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets`
  - Line: 4352
  - Column: 5
  - Project: `C:\users\<user name>\AppData\Roaming\Godot\mono\solutions\5516124489248431140_2_3\GodotSharp\GodotSharp.csproj`

![screenshot](https://i.imgur.com/OJccb6i.png)

**Steps to reproduce:**
- Create a Mono Godot project and try to create a script file.

**Minimal reproduction project:** 
[GodotExperiment.zip](https://github.com/godotengine/godot/files/2123159/GodotExperiment.zip)

NB: before this, I tried converting a `.gd` script in a previous project into a C# project, and I received a completely different set of errors.

After doing this, I do see the `.sln`, `.csproj`, and `.cs` files on disk (including `AssemblyInfo.cs`.  I think the root problem is something to do with the hard-coded path `C:\Release` or `E:\Release` (which doesn't exist).

Sorry in advance if this ends up being environmental or a Mono problem and not a Godot issue.

**Comment by CloudAlRio** [comment]
You need to use Mono 5.12 for it to work.
Also, The latest Stable Mono release is: 5.12.0 Stable (5.12.0.226)

**Comment by lethiandev** [comment]
I had the problem too with Mono 5.10, but I figured it by creating the `Release` folder under the mentioned drive as your `E:\Release\`. But overall, the best option is to upgrade the mono as @CloudAlRio said.

FP: Maybe Godot could warn users on misconfigured mono i.e. before solution build?

**Comment by nightblade9** [comment]
I made some progress on this issue, but didn't see your comments until now. I will try upgrading and report back what the results are.

Can someone please update the documentation page [here](http://docs.godotengine.org/en/3.0/getting_started/scripting/c_sharp/c_sharp_basics.html)? I can do it myself if you can let me know what the correct requirements are.

Currently, it says:

> To use C# in Godot you must have Mono installed. Godot 3.0.2 requires Mono 5.4, 3.0.3 requires Mono 5.10 on Linux and Windows, [...]

It should either be changed to `[...] requires the latest version of Mono` or `[...] requires Mono 5.10 [...]`. I purposely installed 5.10, knowing it was not the latest, because I wanted to maximize the chance of Godot integration succeeding.

**Comment by akien-mga** [comment]
> Can someone please update the documentation page here? I can do it myself if you can let me know what the correct requirements are.

It's fixed in the master ("latest") branch, but not the 3.0 branch. CC @mhilbrunner Some cherry-picks missing from 3.0?

**Comment by nightblade9** [comment]
I deleted the `Release` directories, upgraded to Mono 5.12, and I can at least build and run the project.

But I see some other problems:

- With my `KineticBody2D` entity instance, the C# class code doesn't seem to execute
- With a dummy `RigidBody2D` entity instance, I can see exceptions thrown in the C# side showing up in the `Errors` tab of Godot; `GD.Print` statements don't appear.

I guess I can live with this for now. It's technically working. I'll see if the other issues are covered elsewhere and/or open new issues for those.

Thanks! (Feel free to reopen if you're using this to track the required documentation change.)

**Comment by paulens12** [comment]
I'm using the latest version of Mono and the latest version of Godot, both downloaded today from official websites. It still tries to create that file in G:\Release which doesn't exist.

**Comment by JarnoVgr** [comment]
This issue is still present. Downloaded Godot x64 3.0.6 (Mono) with mono-5.12.0.301-x64 and it requires a Release folder to be created in the root folder of my disk. So when I made `H:\Release` it compiled just fine. Without, it doesn't.
 
OS: Windows 10 x64

**Comment by Irrgeist** [comment]
Using Win 10 64 bit with Godot 3.0.6.stable.mono.official.8314054 with Mono JIT compiler version 5.12.0 (Visual Studio built mono) both 32bit versions.

Error: C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3371: Die Datei "D:\Release\GodotSharp.csproj.CopyComplete" kann nicht erstellt werden. Could not find a part of the path "D:\Release\GodotSharp.csproj.CopyComplete". 

Creating the Release folder seems to work, but then crashes Godot. It also crashes when loading the project again. Is there any log file I can post here?

**Comment by Chris3606** [comment]
Same deal -- using Godot 3.0.6 x64 with Mono support, Mono 5.12 installed.  Had to create the release folder manually then it worked fine.

**Comment by TheAkashicTraveller** [comment]
Same for me too. Empty scene but with an icon tried to creat a script and got the same error.

Godot Engine v3.0.6.stable.mono.official.8314054
Mono for Windows (x64) 5.12.0.301

**Comment by colludium** [comment]
This is still a problem for me.

**Comment by neikeq** [comment]
Looks the same as #21834 which was fixed by #25177. What version of Godot are you using? Do you have the same issue with 3.1 beta 4?

**Comment by colludium** [comment]
@neikeq - that's a good call - I hadn't tried the dev versions. This problem is not present with 3.1a3. Keep closed!
