### ISSUE TITLE
Editor bug: Cutting screen content

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#20331]
**Godot version:**
v3.0.5.stable.official.6a88e22

**OS/device including version:**
Mac OS 10.13.4 (17E202)
Macbook Pro 13-inch, Mid 2012
Intel HD Graphics 4000 1536 MB

**Issue description:**
Screen content is being cut

**Steps to reproduce:**
I do not know what triggers this issue. I always have to close project and reopen to get back to normal, but from time to time the problem comes back.

**Minimal reproduction project:**
Any project

![screen shot 2018-07-21 at 12 31 49](https://user-images.githubusercontent.com/3025661/43037700-c383e5ac-8ce6-11e8-9950-64b1b40099ed.png)
![screen shot 2018-07-21 at 13 04 55](https://user-images.githubusercontent.com/3025661/43037701-c3a9ef36-8ce6-11e8-9f1a-2be6f1873cce.png)

**Comment by nunodonato** [comment]
I've experienced this as well, but haven't been able to reproduce it again

**Comment by eon-s** [comment]
Many of the bottom panels cause this (on every OS), I have thought this was solved on the first 3.0 releases.

**Comment by stephanngamedev** [comment]
I discover how to quick fix on MacOs: Double click the titlebar to "shrink", and double click again the titlebar to expand.

**Comment by Joleeee** [comment]
This also happends on my Windows laptop. Not on my desktop though. It often happends after debugging for a while without clicking the editor.

**Comment by Rinma** [comment]
This happens when you go to a subpoint in the inspector like AnimatedSprite -> New SpriteFrames -> Click on generated sources -> The editor jumps to the resources and shows it in the inspector <- Bug happened.
For me, it is reproducible this way and happens all time.

**Comment by Calinou** [comment]
Can anyone still reproduce this on [Godot 3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by eon-s** [comment]
Yes, the central panel seems to have a fixed minimum size that forces the right panels to be cut when the window is smaller than certain size.

**Comment by akien-mga** [comment]
Consolidating all issues regarding to the inspector going out of the window due to too many/long buttons in main screen toolbars in #31133.
