### ISSUE TITLE
Unable to switch to editor with breakpoints or runtime errors in fullscreen

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#21431]
**Godot version:** 3.0.6

**OS/device including version:** Windows 10 64-bit

**Issue description:** Simply as the title.

Switching to editor methods include:
 - Alt + Tab
 - Alt + F4
 - Open Task Manager

**Steps to reproduce:**

1. Run project in fullscreen mode
2. Trigger breakpoint or runtime error
3. Die while painfully stuck

**Minimal reproduction project:**

[FullscreenAltTab.zip](https://github.com/godotengine/godot/files/2321280/FullscreenAltTab.zip)

**Comment by starry-abyss** [comment]
Still the case in v3.1.beta.calinou.4fd579b

The game should minimize and give focus to the editor, but the whole system becomes not usable currently (Windows 7 64 bit), esp. when using one monitor.

Here's another repro just in case (WARNING: better prepare a way to trigger Godot kill with a hotkey in advance...):
[godot-fullscreen-lock.zip](https://github.com/godotengine/godot/files/2848344/godot-fullscreen-lock.zip)

**Comment by reduz** [comment]
Sorry, I just can't reproduce the issue at all... tested on Windows 10 and Ubuntu with Gnome Shell.
Debugger breaks fine. Is this still a problem?

**Comment by starry-abyss** [comment]
Yes, in the latest Calinou build debugger breaks I assume, because shape cursor is changed to a text editing one, but the problem is that the game still occupies the whole monitor on top of the editor (because fullscreen) and has the focus (should give focus to the debugger/editor).
Will try with the PR above shortly.

**Comment by DleanJeans** [comment]
Still experiencing this as of 3.1 beta 5.
@reduz Have you added a breakpoint in the script?
![image](https://user-images.githubusercontent.com/12462089/53135871-7cbfbc00-35af-11e9-9da8-5832f3d4cdba.png)

**Comment by reduz** [comment]
@DleanJeans It works fine for me, it switches back to the editor on the right file and line, tried both projects posted here. I wonder if this may be a driver bug. Can you (and others) add a bit more information about your GPU, OS and hardware?

**Comment by starry-abyss** [comment]
Win 7 64 bit Home Premium SP1 (+ all updates to date), i5-3570 3.40 GHz (GPU driver 10.18.10.4653), 8 GB RAM, NVIDIA GTX 660 (driver 391.35 / 23.21.13.9135). The main monitor 1920x1080 (where I run editor and the project) is connected to NVIDIA, the other one 1440x900 is connected to Intel, positioned above, and they are set up as a seamless desktop.
Switching off the second monitor doesn't help.

**Comment by starry-abyss** [comment]
For some reason I'm not experiencing the issue on breakpoints anymore, but only on assert (like my attached project in the second message here)...

**Comment by reduz** [comment]
It seems the code that allowed the editor window to take over was a bit wonky, so I changed it to immediately allow takeover as soon as the editor starts. I am sure this should fix the issue, but please reopen if you still can reproduce on latest master.

**Comment by starry-abyss** [comment]
9d78274 - didn't help, still breakpoints work in _ready(), but not in _process() behind delay...

**Comment by bruvzg** [comment]
macOS 10.14, with 9d78274 applied, `godot-fullscreen-lock` demo (both as is and with assert replaced with `print("AAA")` and breakpoint) doesn't automatically switch to the editor and become unresponsive (spinning pinwheel).

<kbd>Command</kbd> + <kbd>Tab</kbd> and Mission Control hot corners still allows switching.

**Comment by bruvzg** [comment]
Tested 9d78274 on Windows 10, problem still exists (both with assert and breakpoint).
<kbd>Alt</kbd>+<kbd>Tab</kbd> doesn't work, <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd> -> "Task Manager" brings editor to front.

On macOS issue should be fixed by #26204 (`move_window_to_foreground` was not giving focus to editor).

**Comment by reduz** [comment]
@bruvzg So, if timing was not the cause, then I don't know. I can't really reproduce the issue, so there is not much I can do from my side.

**Comment by reduz** [comment]
@bruvzg The list of restrictions is not very truthful. At some point it worked because the doc said "The process was started by the foreground process." which is our case, but sometime last year it stopped working, so @RandomShaper did a workaround by passing the Process ID to the child so it's manually allowed and this since has worked for me and anywhere else I tried.

**Comment by bruvzg** [comment]
Found some hacks for taking focus on Windows - https://github.com/bruvzg/godot/commit/6ca852008b9896c17888d777119cb03fd2de0b55.
I'll test it a bit later and open PR if it's working.

**Comment by reduz** [comment]
Can you guys describe your setup? Maybe using multiple monitors is somehow related? I never tried with more than one. If this is the case, can you try disconnecting a monitor and trying again?

**Comment by reduz** [comment]
This seems to be common with other games, and some also mention dual monitor setup..

**Comment by reduz** [comment]
There also seems to be a "Fullscreen Windowed" mode on Windows that is supposed to be lighter and not get the whole process priority. Maybe we could use this one when running from the editor? Not sure if it would fix the problem.

**Comment by bruvzg** [comment]
> Can you guys describe your setup? Maybe using multiple monitors is somehow related?

I'm usually using two monitors, but it's not the reason. After unplugging second monitor (and rebooting in case some multi-monitor stuff is still in effect) nothing changes, problem still persists.

**Comment by bruvzg** [comment]
> There also seems to be a "Fullscreen Windowed" mode on Windows that is supposed to be lighter and not get the whole process priority.

Godot already uses only "windowed fullscreen" mode, exclusive fullscreen calls are commented out and `set_window_fullscreen` uses `MoveWindow` to [stretch window to current display size]( https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L1818) .

**Comment by reduz** [comment]
Sorry, I give up then :disappointed: I am clueless as for why this may be happening and why it happens in some configurations and not others.

**Comment by bruvzg** [comment]
> For this fullscreen mode we are supposedly allowed to alt-tab

<kbd>Alt</kbd>+<kbd>Tab</kbd> works fine with a running app, when it's stopped at breakpoint/assert it's not working anymore, same happens if you suspend process by any other means. My only guess would be changing foreground window require some response from the app loosing focus, which it can't give in the suspended state.

**Comment by reduz** [comment]
@bruvzg Can you test the following? Harcode here:
https://github.com/godotengine/godot/blob/master/core/script_debugger_remote.cpp#L132
after sending the debug enter, just exit the function (to let the program continue running) and check whether the editor gets focus. If this is the case, then definitely the problem is that we should be pumping (and ignoring) windows events on background.

**Comment by bruvzg** [comment]
> after sending the debug enter, just exit the function

With `return;` added after `packet_peer_stream->put_var(p_script->debug_get_error());` it is switching to the editor just fine.

**Comment by pbrunet** [comment]
could it be related to queryendsession because of undefined ordering as stated here:  https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler ?

They also say pumping could be a solution if I correctly understand the documentation but what if it is a crash and not a breakpoint?

**Comment by reduz** [comment]
Alright, then it is clear what the problem is, thanks!

**Comment by reduz** [comment]
I made it keep pumping and dropping events while on the debugger loop. Can you test that this works for you?

**Comment by reduz** [comment]
Closing, as reported fixed by @bruvzg. Please reopen if problem persists.
