### ISSUE TITLE
INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#22101]
**Godot version:**
![image](https://user-images.githubusercontent.com/13235119/45585572-7467a480-b8de-11e8-8f1e-3dc66079c7f3.png)

![image](https://user-images.githubusercontent.com/13235119/45585575-8d705580-b8de-11e8-9e63-6fddca762c09.png)

**OS/device including version:**
![image](https://user-images.githubusercontent.com/13235119/45585531-bfcd8300-b8dd-11e8-9b2d-658f497c881a.png)

![image](https://user-images.githubusercontent.com/13235119/45585538-d8d63400-b8dd-11e8-9d8d-f1b41995ea4c.png)

**Issue description:**
I have a project that work/export fine in godot 3.1
Now I updated in 3.1-alpha and I have this error when I try to export and install in same android device:
![image](https://user-images.githubusercontent.com/13235119/45585547-1f2b9300-b8de-11e8-8c83-95b1d9cc3b4d.png)

**Steps to reproduce:**
Export and install in android.

**Minimal reproduction project:**
N/A.

**Comment by akien-mga** [comment]
Did you build Android export templates matching your editor commit?

**Comment by git2013vb** [comment]
> Did you build Android export templates matching your editor commit?

Yes. I did 2 steps: First I update godot to 3.1-alpha, then I update the export tools (download and install with no problems)

**Comment by Zireael07** [comment]
What Android version does your Android device have?

**Comment by git2013vb** [comment]
> What Android version does your Android device have?

4.4.2 
I use also Nox and BlueStacks. I tried in Nox but I have an failure installation error.

**Comment by FeralBytes** [comment]
@git2013vb  akien-mga asked if you built the export templates, not downloaded and installed. There is a difference. See here:  https://godot.readthedocs.io/en/3.0/development/compiling/compiling_for_android.html   or for more clarity here: https://github.com/binogure-studio/godotamazon

**Comment by git2013vb** [comment]
> @git2013vb akien-mga asked if you built the export templates, not downloaded and installed. There is a difference. See here: https://godot.readthedocs.io/en/3.0/development/compiling/compiling_for_android.html or for more clarity here: https://github.com/binogure-studio/godotamazon

I tried but I have an error :
![image](https://user-images.githubusercontent.com/13235119/45598729-8d548080-b9d8-11e8-9296-c944673ffee2.png)

**Comment by avril-gh** [comment]
@git2013vb you should open new issue 'compile error' and attach this image, seems like a new bug

**Comment by akien-mga** [comment]
This error was fixed in the meantime.

**Comment by git2013vb** [comment]
I found another error:
![image](https://user-images.githubusercontent.com/13235119/45628921-16c58a80-ba8d-11e8-9a41-5c2b6884c28f.png)

**Comment by git2013vb** [comment]
> I found another error:
> ![image](https://user-images.githubusercontent.com/13235119/45628921-16c58a80-ba8d-11e8-9a41-5c2b6884c28f.png)

I installed 2.3 gradle but same result. 
any suggestions?
![image](https://user-images.githubusercontent.com/13235119/45632620-a4a57380-ba95-11e8-805d-36d59c29635c.png)

**Comment by git2013vb** [comment]
Hi, even if I close the #23003 and the #22374 - which I don't know if they are related in some way with this one I can confirm that I still have this issue.

Thanks

ps. I feel more comfortable to use screen-shot to show errors.  In m opinion is more fast and I can avoid errors.
