### ISSUE TITLE
Random jerkiness with animating blendshapes

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22361]
**Godot version:**
`master` / ef7b384861

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
I have blendshapes for breathing animation which expands or shrinks the character's chest area. They work perfectly from Blender, and look ok when I manually adjust sliders inside the related mesh instance.

However, when I make a simple animation which animates their values with bezier curve from 0 to 1 and again to 0, it shows random 'hiccups' which make the whole mesh to jerk abruptly with each loops sometimes. This behavior shows both in the editor (when played using the animation view) and in game.

The curve looks like this:
![image](https://user-images.githubusercontent.com/2367032/45922513-88c42680-bf08-11e8-8982-08ae64b4a1ed.png)

And it seems that the jerky behavior occurs when a blendshape first changes its value from 0, because if I add another key point with value 0 near the beginning, the hiccup occurs at that point instead:
![image](https://user-images.githubusercontent.com/2367032/45922536-2586c400-bf09-11e8-9ce3-9cd35a6059ea.png)

**Comment by mysticfall** [comment]
A video shows the symptom (and also that of #19880). The 'hiccup' happens at around 0:17:

* https://www.youtube.com/watch?v=R3zDrk1AiDw

**Comment by pgruenbacher** [comment]
wait so is the black patches showing up at the end of the video a symptom as well yes?
also can you step through the animation manually to see if the jerkiness is occurring between finish and start points (loop)? Cause it could be as simple as end point not continuous with start point.

**Comment by mysticfall** [comment]
@pgruenbacher No, the black patches is for another issue which is mentioned in my other comment. 

I also initially thought it could be just an issue with the animation's start and end position not matching with each other. But as it's just a blendshape animation with bezier curve which has key points at the start and end which are set to zero, and because as I mentioned above, the problem occurs whereever I put additional key frame at which the blendshape starts to change its value from 0 to something positive, I doubt it could be the cause of the problem.

By the way, if I grab the slider and drag it around the problematic frame (the additional `0` value which I added for testing), I can't reproduce the problem. But if I hit the play button, the hiccup happens at that specific point and the same happens in game as well.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by mysticfall** [comment]
Yes, it's still reproducible in the master branch.

**Comment by mysticfall** [comment]
It turned out that this is caused by a mesh resource being shared between `MeshInstance`s each being controlled by a different `AnimationPlayer`.

As noted in the other issue's comments, this is an intended behaviour and probably just needs a warning message in a relevant section on the documentation.

**Comment by Rabocop** [comment]
> It turned out that this is caused by a mesh resource being shared between `MeshInstance`s each being controlled by a different `AnimationPlayer`.
> 
> As noted in the other issue's comments, this is an intended behaviour and probably just needs a warning message in a relevant section on the documentation.

So, what it would be the workaround? I need to instance some scenes and launch a blend shape animation on each. I tried everything for 2 days and I didn't find any solution (It not only happens with AnimationPlayer as I tried to animate those via Timers) . I can understand why it happens but it shouldn't be that difficult to get something that simple. Any insight?
Thanks.

**Comment by mysticfall** [comment]
Select every mesh resource inside `MeshInstance` or other mesh container, and toggle `Local to Scene` to `true`, and it should resolve the issue.

Hope this helps!

**Comment by Rabocop** [comment]
@mysticfall Thank you very much for the tip, didn't tried that, but I'm afraid it doesn't work, as you can see in the gif I have that set up with local to scene, also made unique materials and so, and still happening when spawning. Am I doing something wrong?
PD: Sorry for the crappy GIF haha
![shapes00010642](https://user-images.githubusercontent.com/7796648/56271274-042d3580-60f0-11e9-9b80-cbdbc1648005.gif)

**Comment by mysticfall** [comment]
Sorry, I can't detecte anything wrong with your setup from the gif alone. I don't have much knowledge of the engine internals, but maybe someone may help if you could upload a minimal reproducible case?

**Comment by Rabocop** [comment]
Well, doing the minimal project I realized that making sub resources unique in the MeshInstance 
![image](https://user-images.githubusercontent.com/7796648/56274548-d3043380-60f6-11e9-931a-c36b0571caf4.png) insted of making them unique by hand kinda works and it doesn't make artifacts and weird things. What I don't know if it was a matter of the material or which sub resource was causing that but it's ok.
Thank you very much!

**Comment by urodelagames** [comment]
Want to give a big thank you to folks in in this issue. I kept getting flickering black materials on my 3d objects in Godot. This is the only thread that fixed the issue. I changed my material resources on my mesh instances (just the ones with the issue) with "Local To Scene" checked. And that worked.

This is necessary for me because I'm using AnimationPlayers to change the blend shapes exported from a shape key in blender. When I would play the animation, I'd get all of these flickering black materials... Until today. Thanks!
