### ISSUE TITLE
Window dimensions are limited by wrong monitor

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#22736]
**Godot version:**
3.1-alpha 8068d02

**OS/device including version:**
Linux Mint 19 Cinnamon x64

**Issue description:**
I have two displays: one that is 2560x1440, and one that is 1280x1024. They have this layout:
![image](https://user-images.githubusercontent.com/27100585/46502792-57364e00-c86c-11e8-882f-f5ddcfad1ce2.png)

Note that the larger monitor is set as the "primary" monitor.

The problem is that any Godot window, upon being spawned, will have its size capped to the dimensions of the smaller, secondary monitor. This includes the Godot editor itself, if forced to open windowed. 

For example, I created a project with a window size of 2000x1200:
![image](https://user-images.githubusercontent.com/27100585/46502491-a039d280-c86b-11e8-83d2-9149398d0919.png)

The window should fit on the 2560x1440 monitor. Just to be sure, the editor settings for window placement are configured for Monitor 1 (the primary monitor, being the larger one):
![image](https://user-images.githubusercontent.com/27100585/46502654-06bef080-c86c-11e8-998e-79b11ce4fe51.png)

The project itself just displays the window size:
![image](https://user-images.githubusercontent.com/27100585/46503123-44704900-c86d-11e8-8031-45de010bc10d.png)

When running the project, the window size will always be capped to 1280x1024, the size of the second monitor:
![image](https://user-images.githubusercontent.com/27100585/46503171-6cf84300-c86d-11e8-86d1-b9375a7838cd.png)

cc @Calinou, maybe you're able to help diagnose the problem.

**Minimal reproduction project:**
This is the project I used: [multiple monitor window size bug.zip](https://github.com/godotengine/godot/files/2448151/multiple.monitor.window.size.bug.zip)
It doesn't do much, and you might have to modify the window size to match your monitors, so this might not be too useful...

**Comment by akien-mga** [comment]
AFAIK "Monitor 1" is not the primary monitor, it's the first monitor from the left. See also #21150.

**Comment by akien-mga** [comment]
> AFAIK "Monitor 1" is not the primary monitor, it's the first monitor from the left.

Actually I'm not sure about this. "Monitor 1" is screen `0`, and will query the information of whatever screen `XineramaQueryScreens` identifies as 0 (see `OS_X11::get_screen_size`).

**Comment by homer666** [comment]
@akien-mga "Monitor 2" spawns the window in the smaller monitor as expected, and "Same as Editor" works correctly too. I also tested with the smaller monitor set to "primary" and it also worked as expected ("Monitor 1" being the smaller monitor, etc.)

**Comment by homer666** [comment]
I did some testing, and found out that if the smaller monitor is any more **to the left** of where it is here:
![image](https://user-images.githubusercontent.com/27100585/46526245-10c70a80-c8d1-11e8-9c22-96fc780058c4.png)

or any **higher** than it is here:
![image](https://user-images.githubusercontent.com/27100585/46526488-b9756a00-c8d1-11e8-9bcb-081cf30d5c00.png)

the window dimensions will be capped by the smaller monitor's when spawned in the larger one. Otherwise, it will spawn at the correct size:
![image](https://user-images.githubusercontent.com/27100585/46526053-8a122d80-c8d0-11e8-8682-0f24d5b0c9ea.png)

**Comment by avencherus** [comment]
@homer666 I don't have your screen setup, but I am very curious what the `OS.current_screen ` reports as you move the window from monitor to monitor.  Would you be able to put that in a processing loop and see what kind of ordering is going on?

In my experience so far on Windows, Godot doesn't order the monitors based on the OS arrangement.  I have mine swapped in the OS, and Godot does start on what is the "primary", but it counts with index 1, rather than 0.

Would like to know if you're experiencing something similar.

**Comment by homer666** [comment]
@avencherus Just tried it, it's reading the monitor indexes correctly, respecting what monitor I have set to "primary" and reporting an index of 0 for that.

**Comment by avencherus** [comment]
@homer666 Thanks running that test.  Yeah, it must be referencing the wrong monitor at some point in the startup.  I wonder.  Definitely something I'll be watching for when I go back to doing some display and cursor testing on Linux in the coming weeks.

There was some fix some time ago on the X11 end where certain display queries were lagging behind by a frame or two.  This was fixed using some yielding, https://github.com/godotengine/godot/pull/21914.

@hpvb Might this be related or similar to the timing issues with the window sizes?

**Comment by Calinou** [comment]
Can anyone **on Linux/*BSD** still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
