### ISSUE TITLE
Enum with negative values disables 0 value entry when exported

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#23022]
**Godot version:**

b95f0e61e0e5678eeb9224a012b28479d7f0af58

**OS/device including version:**

Linux

**Issue description:**

Considering the following enum:

```
enum SomeEnum{
    EntryA = -2,
    EntryB, #-1 
    EntryC, #0
    EntryD #1
}
```

When exported, it is not possible to select `EntryC:0`, because the editor will instead default to the first entry, `EntryA:-2`.  This occurs both when trying to select it via the inspector, and when assigning the variable to 0 in code:
`export(SomeEnum) var myEnum := 0`

**Comment by avencherus** [comment]
It definitely is selecting the wrong thing.  In your code you have a space in `Entry D`, but interestingly it still seems to carry on without looking for a comma.

@neikeq I remember your PR and work with the export of enums recently, was wondering if you might also know more about what might be going on here.

**Comment by somnivore** [comment]
> It definitely is selecting the wrong thing. In your code you have a space in `Entry D`, but interestingly it still seems to carry on without looking for a comma.

Ah sorry, thanks for pointing that out, I fixed it.  This was just a test example I wrote for this issue; the real thing looks more like:

```
enum ElementTypes{
	None = -1,
	Fire,
	Light,
	Muscle,
	Water,
	Dark,
	Mind,
	Ice
}
```

**Comment by neikeq** [comment]
Can you check if #22885 fixes this issue?

**Comment by avencherus** [comment]
Sure, I'll cherry-pick it again and rebuild.

**Comment by avencherus** [comment]
Still appears there as well.  Using the above example with #22885 on a Windows 10 64-bit 3.1 build.

```
enum ElementTypes{
	None = -1,
	Fire,
	Light,
	Muscle,
	Water,
	Dark,
	Mind,
	Ice
}

export (ElementTypes) var choices = 0
```
The **None (-1)** option is not reachable from inspector selections, it will drop down into Fire.

**Comment by neikeq** [comment]
Oh, wait this actually sounds like an editor issue instead of GDScript. I will have a look, maybe I can find the cause.

**Comment by neikeq** [comment]
#22885 actually fixes the issue. There was a bug preventing negative values which I just fixed. Should work now.

Note: The bug described in this issue is a visual bug. The value is selected correctly, but the Inspector displays the wrong one as selected. You can check this by printing the value of the exported variable in your code.

**Comment by avencherus** [comment]
Thanks so much for looking into this.

Interesting, I did notice once in the TSCN file the value was negative, but when trying again it was 0, so I thought maybe what I was seeing was left over from a test of initializing the value to -1.

I wasn't too sure about it though.
