### ISSUE TITLE
Bitrate-like artifact when playing low frequency sounds

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23544]
Godot 2.1.5
Godot 3.0.6
Godot 3.1 alpha 2
Windows 10 64 bits

I noticed when I play a specific low-frequency sound with Godot, it always comes with a small high-frequency artifact noise.
This happens for both WAV and OGG formats.
This does not happen when I play the sounds in Audacity or VLC.

Example project:
[LowFrequencySound.zip](https://github.com/godotengine/godot/files/2551329/LowFrequencySound.zip)

Video:
https://zylannprods.fr/dl/godot/GodotLowFrequencySound.mp4

**Comment by marcelofg55** [comment]
You're testing this on Windows using the WASAPI driver, right? What's the sampling rate of your device? I suspect that those artifacts may be a resampling issue.

**Comment by Zylann** [comment]
I don't even know which driver Godot uses, how do I check this?

**Comment by marcelofg55** [comment]
If you start godot with `--verbose` you'll see what driver it's using.

**Comment by Zylann** [comment]
Testing on another computer, I don't get the artifact. The log says:
```
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 970 calculated latency: 21ms
```
I'll test on my own machine once I'm back home.

**Comment by Zylann** [comment]
My home computer prints the same thing:
```
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms
```
But it has the artifact.

**Comment by marcelofg55** [comment]
I've tested this on OS X using different sample rates and there is no artifact.
After that I've tested this on Windows 10 using WASAPI, with 44100 Hz there is no artifact but when I set my device with 48000 Hz there is an artifact.

Can you check the sample rate of your device? Let me know if you can confirm that with 44100 Hz there is no artifact and with higher sampling rates there is an artifact.

**Comment by Zylann** [comment]
Where can I check that sample rate?

**Comment by marcelofg55** [comment]
On the properties of the device. https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/how-to-change-sound-control-panel-settings-in/5a70718b-7ecf-4547-a64a-22efda8da0c2?auth=1

**Comment by Zylann** [comment]
I am indeed set to 24 bit 48000Hz.

**Comment by sleepcircle** [comment]
I'm running into the same issue. Also "slowing things down a lot" seems to lead to roughly the same problem.

**Comment by norton-corbett** [comment]
On Windows I hear this aliasing regardless of my audio device's sample rate.

**Comment by norton-corbett** [comment]
After some investigation I don't think this is actually a Godot issue. In summary, I can reproduce this in other applications using WASAPI or otherwise non-ASIO audio driver.

Anyone hoping to utilize Godot for any serious professional audio application will probably want to set their project's audio driver to "Dummy" and write their own audio backend as I'm doing now.

Which is a bit of a shame, since Godot's audio effects library and mixer/bus system might lead some to believe it's ideal for an audio app, but without ASIO support on Windows I think it's a no-go.

**Comment by starry-abyss** [comment]
Why set driver to dummy though? If you add your own audio driver in Godot, there shouldn't be a need for rewriting other audio functionality as well.

**Comment by norton-corbett** [comment]
Because it's easier to just use portaudio instead.

**Comment by Calinou** [comment]
Godot has an XAudio2 driver, but it's not enabled by default and probably not working anymore. It also used RtAudio on Windows in the past, but that driver was removed entirely.

**Comment by norton-corbett** [comment]
Well it would be cool to get ASIO support back in, which RtAudio apparently provided, but I'm also aware that professional audio is outside the scope of a game engine which is why I'm not pushing the issue.

Disabling Godot's audio and going the portaudio route also allows me to switch driver at runtime (common in audio applications). As far as I can tell Godot's AudioServer currently has no interface for doing that.

**Comment by RockyMadio** [comment]
i also confirm this issue. In our fighting game (similar to street fighter V ) where punching, wooshing and shouting sounds are played/ resetted frequently, you can easily spot the "clicking" noise everytime a new sound is launched. The issue occurs with different export settings for .WAV  from Audacity.

Or when you just make a simple scene with a timer that loops between play and stop  just one sound in an AudioStreamPlayer3D, you can hear the noise as well.

**Comment by Zylann** [comment]
@RockyMadio note that this issue is not about "clicking", but high-frequency artifacts that persist when low-frequency sounds are played

**Comment by Calinou** [comment]
@RockyMadio The audio clicking issue is being tracked in #22016.

**Comment by griffinjennings** [comment]
Something of note here: this effect seems to be slightly reduced (but not entirely gone) when run through the HTML5 exporter (see video attachment). Maybe something to do with how the browser handles audio devices?


https://user-images.githubusercontent.com/2602756/102688420-b1077080-424a-11eb-9c5c-81bcc5b01ff8.mp4

This is on 3.2.3. I'm hoping this at least gets another look before 4.0, as this is a fairly critical issue for me.

**Comment by Calinou** [comment]
> Something of note here: this effect seems to be slightly reduced (but not entirely gone) when run through the HTML5 exporter (see video attachment). Maybe something to do with how the browser handles audio devices?

The HTML5 uses a different audio driver than native platforms (Web Audio API), that's probably why. Also, the default output latency is higher on HTML5 compared to other platforms.

**Comment by ellenhp** [comment]
In the case of an ogg/mp3 stream, this might be related to the resampling that's done. For wav streams, I think resampling is only done if the sample rate of the wav doesn't match the sample rate of the audio device, however resampling for wav streams seems to be linear so I bet it's fairly noticeable when it does happen. I implemented the "4 point, 4th order optimal" resampling algorithm from [this paper](http://yehar.com/blog/wp-content/uploads/2009/08/deip.pdf) for oggs and mp3s and I'm curious if it improves things for anyone (will not help with wavs). My ears are really terrible at picking out details but I think I hear an improvement in some cases.

https://github.com/ellenhp/godot/tree/new_resampling

**Comment by wingedadventurer** [comment]
@ellenhp I have tested this in 3.2.4 RC3 and it doesn't solve the issue. There's no noticeable "ringing" reduction between 3.2.3 stable and 3.2.4 RC3.

Below I've recorded playing all 3 supported audio formats in VLC (where they sound normal), and then in 3.2.4 RC3. I recommend headphones to be able to hear low-end frequencies better, since kicks are used in the video, as ringing is most noticeable in low-end of the spectrum.

https://user-images.githubusercontent.com/26509794/109627785-43c56500-7b42-11eb-8eef-0114a1d277aa.mp4

**Comment by akien-mga** [comment]
Can you provide these files for testing?

**Comment by wingedadventurer** [comment]
Sure, here: [kicks.zip](https://github.com/godotengine/godot/files/6067716/kicks.zip).

**Comment by akien-mga** [comment]
Interesting, I can't reproduce the issue with those sounds on 3.2.3-stable nor 3.2.4-rc2 or 3.2.4-rc3. The sounds play fine in all version, the same as with `ffplay` (and similar to the VLC output in your video, though they do sound significantly different with my headphones or PC speakers).

I'm on Mageia 8 using PulseAudio 14.2.

**Comment by wingedadventurer** [comment]
(Should've written before, I'm on Windows 10)

Ok, so I just checked the sample rate of the 2 devices I used for testing and they were set to 48000 Hz by default. Changing them to 44100 Hz that Godot uses makes ringing gone **even on 3.2.3-stable**.

I had a somewhat related issue 2 years ago where setting the sample rate for devices to 44100 Hz fixed large audio latencies.

So there's now no ringing on my end even in 3.2.3-stable, for any file format.

However, if device sample rate being different from Godot's mix rate in project settings creates these issues, how should this be handled? I haven't seen any video game offer the "sample rate" setting. All audio played just fine.

Godot's tooltip for mix rate setting says `In general, it's better to not touch this and leave it to the host operating system.`

**Comment by Zylann** [comment]
I confirm that sample rate of the device is what caused it for me originally, and I have the same questionning as to how every other software is able to cope with that just fine, while Godot does not.

**Comment by akien-mga** [comment]
This might be worth tracking in a new issue then as it's likely a different issue specific to the WASAPI Windows audio driver.

**Comment by wingedadventurer** [comment]
I will do more testing, then open a new issue for this.

@ellenhp Sorry for another ping, but I compared 3.2.3-stable and 3.2.4-rc3 with matching sample rates now, and slight ringing can be heard in OGG in 3.2.3-stable but it's gone in 3.2.4-rc3. WAV and MP3 play without any ringing.

So I can confirm that #46086 fixes this issue (when sample rates are matching). 😃

**Comment by ellenhp** [comment]
@Zylann The PR that originally fixed this issue will be reverted by #51082 because of some regressions it caused, FYI. I was wondering if you'd be willing to help test that new PR to make sure it doesn't introduce any more regressions? I'm tired of introducing regressions, would be nice to get it right this time. :)

**Comment by Zylann** [comment]
I tested with your PR applied to my fork of Godot 3.x (I have no setup for Godot 4 yet), but the problem still happens. Is there something else I have to pull from Godot 4 in order for this to work?

**Comment by ellenhp** [comment]
I reverted #46086 (because it caused #49131) in the first commit of #51082, and the second commit changes the resampling algorithm coefficients to actually sound okay. Would you mind pushing the code that you tested with or is there stuff in there you can't share? I just double-checked my change works on the master branch, and I can't imagine why it wouldn't work on 3.x.

If you're on Windows, you could be running into [this bug](https://github.com/godotengine/godot/issues/46595), which I might try and tackle next.

**Comment by Zylann** [comment]
There is no particular code to share, the project is really just empty with a sound file in it (as in the first post), the problem can be heard by double-clicking and playing the sound in the inspector.

**Comment by ellenhp** [comment]
I'm more interested in the 3.x fork that you rebased my changes onto. I'll rebase myself and see what happens though, but I can't imagine this being dependent on anything in 4.0, because the original change was cherrypicked for 3.3 with no issues.

**Comment by Zylann** [comment]
About the fork, it's really just latest 3.x with #51082 applied on top in here https://github.com/godotengine/godot/blob/20d46c5b9ede7bfb9001d341ac20d8a30f49cba5/servers/audio/audio_stream.cpp#L49

**Comment by ellenhp** [comment]
Oh you know what, I just noticed that you're on windows and noticing this with wav and ogg files. I strongly suspect this is same issue as #46595. Sorry for bugging you! I'll go fix that when I get a chance. I'll need to install windows in a VM or something to test it though which is why I haven't fixed it in one of my previous audio bug bash sessions 😄

**Comment by wareya** [comment]
Apologies in advance if this is the wrong issue to post this on, but it looks like the same issue from what I can tell. Why does cubic resampling not apply to .wav files like it applies to .ogg? I'm getting a loud low frequency bitcrushy artifact when playing bell/chime sound effects because of linear resampling. Is there an open issue for wav resampling that I can comment on that I missed?

The base .wav and .ogg files in this zip are 48khz, the resampled .wavs are 44.1khz (to demonstrate what the two resampling algorithms sound like). The base .wav exhibits the ringing when played back in a 44.1khz godot project, but the .ogg does not. This happens regardless of what I have my audio card's sample rate set to in Windows (44.1khz or 48khz) as long as the project is set to 44.1khz. I'm using Godot 3.4.2.

[entrance_bell_edit_original_and_resampled.zip](https://github.com/godotengine/godot/files/8064241/entrance_bell_edit_original_and_resampled.zip)

https://user-images.githubusercontent.com/585488/153953174-16301031-53cb-4463-a7a8-064f51119aaf.mp4

**Comment by ellenhp** [comment]
I played the video back on my studio monitors and can't tell the difference between the ogg and the wav. I also don't think linear resampling should be introducing low frequency components but I could be wrong there because I'm not a DSP person really. I know it causes a low pass kind of effect but introducing a loud low frequency artifact doesn't sound right to me. Can you hear an obvious difference in the video? I hear some bass on both, especially when I EQ it to make it more obvious. I'll take a look at the sample later to see what's going on.

**Comment by wareya** [comment]
Yes, I can hear an obvious difference. There is a distinct distorted tone around 650hz on the .wav that is much quieter on the .ogg. I am using studio monitor headphones. The video's audio looks like this under a spectrogram:

![image](https://user-images.githubusercontent.com/585488/153959262-d992a223-4207-4569-b89b-977a7d71fddb.png)

The tone at 650hz is distinctly louder and longer-lasting in the linear-resampled .wav than the .ogg. (Both tones near 600hz are coming from resampling, but the hermite resampling that the .ogg goes through produces much quieter tones that are easier to ignore.)

> I also don't think linear resampling should be introducing low frequency components but I could be wrong there because I'm not a DSP person really.

This is *mostly* true when upsampling, but not when downsampling. Downsampling can introduce new information anywhere depending on the particular combination of signal and resampling ratio.

**Comment by ellenhp** [comment]
Good enough for me, my ears aren't great but spectrograms don't lie. Just be glad the cubic resampler's coefficients are fixed though because oggs and mp3s used to sound wayyyy worse than wavs, hah. If anything it's kind of a relief that things are sounding the way one would expect now. Would you mind opening a new issue with all this information? This is a different bug than what this issue originally tracked.

Wavs currently use linear resampling for performance reasons but I think computers have gotten fast enough that we can change that. Godot was originally written for very resource constrained machines. We don't have to be nearly as frugal now. Will have to discuss with reduz though. Thanks for bringing this up!

**Comment by wareya** [comment]
> Wavs currently use linear resampling for performance reasons but I think computers have gotten fast enough that we can change that.  

Yeah; imo, hermite sampling will *probably* be fast enough to not make a difference. It's not like sinc where you have to call a trig function a dozen times per sample, it's basically just a handful of extra multiplications and additions.

> Would you mind opening a new issue with all this information? This is a different bug than what this issue originally tracked.

Will do! (when I have a spare hour)

**Comment by ellenhp** [comment]
Agreed, it's cache and pipeline friendly so I can't imagine it really being detectable in most situations. It'll be a bit tricky to lift the cubic resampler into AudioStreamSample though and I'm also not entirely sure that there will be much of a difference between wav code and ogg/mp3 code at that point so I'd be reluctant to do it without a bit of a refactor.
