### ISSUE TITLE
Strange, seemingly random crash with repeating "det == 0" error

### ISSUE THREAD

**Issue by Nathan173AB** [godotengine/godot#24997]
**Godot version:**
3.0.6 standard

**OS/device including version:**
Ubuntu 18.04 64-bit
Nvidia GeForce GTX 1060 (415.25 drivers)

**Issue description:**
```
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/math_2d.cpp:336.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fce57c1af20] (??:0)
[2] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1524f64] (<artificial>:?)
[3] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x15ad898] (<artificial>:?)
[4] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1b4ffc3] (??:?)
[5] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1b491b2] (??:?)
[6] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x7b3728] (??:?)
[7] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x808618] (<artificial>:?)
[8] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1b4feff] (??:?)
[9] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1b3c9a9] (??:?)
[10] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1b3d6c9] (??:?)
[11] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1221336] (<artificial>:?)
[12] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1ac6c34] (??:?)
[13] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x11d5993] (<artificial>:?)
[14] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x1225d37] (??:?)
[15] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x770fef] (??:?)
[16] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x6e97dd] (??:?)
[17] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fce57bfdb97] (??:0)
[18] /home/nathan173ab/Gamedev/Godot/Godot_v3.0.6-stable_x11.64() [0x6f61ce] (??:?)
```

**Steps to reproduce:**
Simply playing the game through various levels. Sometimes it will crash and display the aforementioned output in the terminal (editor debugger didn't show anything). It doesn't always crash. Sometimes it will crash pretty quickly, sometimes not at all. It seems to happen when there are many RigidBody2Ds in the scene bouncing around. There could be anywhere from dozens to hundreds when it happens. Beyond that, I can't discern any pattern to the crash. It seems random.

**Minimal reproduction project:**
I had to shrink down the project size by removing a lot of assets, so keep that in mind if you try to run it. If needed, I'll try to provide a more complete project file.
[project file](https://github.com/godotengine/godot/files/2757665/Abstract.Hell.zip)

**Comment by eon-s** [comment]
Too many broken dependencies in the sample project.

`det == 0` error was usually related to transform matrices with scale = 0 on any axis or when bodies had no shape, but I think those situations were solved on 3.0... 
In any case, check if you use scales that can do that on any node with a transform, if shapes are being added correctly.

Also look for other issues (opened and closed) with `det == 0` error to see if help to find the origin of the crash, otherwise will be too hard to fix.

**Comment by Xrayez** [comment]
Godot 3.1 beta.

I have the same error with no crash (in editor, not release). This seems to happen with `RigidBody2D` sporadically which represents missile in my project. Strangely, the error occurs with some delay following missile's explosion. This happens more frequently if lots of those gets exploded at short range. This might be somehow triggered by detection areas via `Area2D` which I use to disable/enable collisions for missile.

**Comment by Nathan173AB** [comment]
> det == 0 error was usually related to transform matrices with scale = 0 on any axis or when bodies had no shape, but I think those situations were solved on 3.0...
> In any case, check if you use scales that can do that on any node with a transform, if shapes are being added correctly.
> 
> Also look for other issues (opened and closed) with det == 0 error to see if help to find the origin of the crash, otherwise will be too hard to fix.

Well there are a number of other issues I found which seem somewhat related.

https://github.com/godotengine/godot/issues/17067
This one also says it occurs in math_2d.cpp, but 10 lines previous. I don't use ViewportTextures in any Light2Ds, but I do use several for most of my Sprites. Could this be the same issue, but it simply affects Sprites as well?

https://github.com/godotengine/godot/issues/6296
Seems to be what you mentioned, but I don't have any situation where a node's scale is set to 0.

https://github.com/godotengine/godot/issues/20966
Seems tangentially related.

> I have the same error with no crash (in editor, not release). This seems to happen with RigidBody2D sporadically which represents missile in my project. Strangely, the error occurs with some delay following missile's explosion. This happens more frequently if lots of those gets exploded at short range. This might be somehow triggered by detection areas via Area2D which I use to disable/enable collisions for missile.

As it so happens, I also have a "missile" RigidBody2D in my game. How does yours function and what does it do? I'm wondering if there is some specific behavior underlying both of ours that might be causing this.

**Comment by Xrayez** [comment]
@Nathan173AB the first issue you linked does seem to be caused by `Light2D` nodes in my case. I have both missile and explosion nodes with with lights added as child. The delay I was describing was amusingly caused by explosion's tween node that animates `texture_scale` property to simulate spreading light:
```gdscript
$tween.interpolate_property($light, 'texture_scale', $light.texture_scale, 0.0, 1.0, Tween.TRANS_QUINT, Tween.EASE_IN_OUT)
$tween.start()
```
But as soon as the explosion times out and fades away (using `Timer`) it's freed. It seems like the tween object tries to animate non-existing transform property just before the explosion node is actually freed but which was removed from a scene.

Setting tween's `playback_process_mode` to `physics` seems to fix this in my case. 

Attempting to use `tween_completed` signal (as explosion faded away) instead of timer's `timeout` signal causes to spit those errors each frame.

**Comment by Xrayez** [comment]
Still reproducible despite #17067 being fixed. Created minimal project:
[light-2d-texture-scale.zip](https://github.com/godotengine/godot/files/2800483/light-2d-texture-scale.zip)

Run the main scene. Upon ready, the explosion will occur, no error yet. Click anywhere on the screen to create explosion, and wait for it to fade out. Now it should spam errors each frame.
