### ISSUE TITLE
Recent commits broke updating modified resources in the viewport

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#25243]
**Godot version:**

4f4e46edd539b0c26a6b086aa19c303b10de66b1

**OS/device including version:**
Linux, Ubuntu 18.04

**Issue description:**
I looked at the patch for an older issue #24286 and found that the Viewport update is currently
not working at all.

**Steps to reproduce:**

* modify and re-export a model instanced in the scene (tested with dae and gltf)
* the viewport ignores any material or mesh changes and displays the old cached object

Works in a 'played' project or after restarting the Godot user interface.
Changing options or clicking on the `Import tab -> "Import` also does not help.

```
Blender -> File -> Export -> glTF2.0 - > assets/cube.gltf

...
glTF: Creating mesh for: Cube
ERROR: iteration: Condition ' iterating ' is true. returned: false
   At: main/main.cpp:1803.
ERROR: iteration: Condition ' iterating ' is true. returned: false
   At: main/main.cpp:1803.
Saving scene to: res://.import/cube.gltf-d13e4fdf61e9c9812503e38d119762af.scn
ERROR: iteration: Condition ' iterating ' is true. returned: false
   At: main/main.cpp:1803.
Loading resource: res://Cube.tscn (cached)
Loading resource: res://assets/cube.gltf (cached)
ERROR: iteration: Condition ' iterating ' is true. returned: false
   At: main/main.cpp:1803.
Loading resource: res://Cube.tscn (cached)
Loading resource: res://assets/cube.gltf (cached)
Loading resource: res://Cube.tscn (cached)
Loading resource: res://assets/cube.gltf (cached)
```

Changing `Import tab -> Material -> Storage` gives me a bonus error:
```
ERROR: _call_function: Error calling deferred method: 'EditorInspector::_property_changed_update_all': Method expected 2 arguments, but called with 4.
   At: core/message_queue.cpp:259.
```

**Comment by capnm** [comment]
Only the error message is gone, the real problem remains:

* modify and re-export a model instanced in the scene (tested with dae and gltf)
* the viewport ignores any material or mesh changes and displays the old cached object

![image](https://user-images.githubusercontent.com/4047289/51731843-80c5f000-207c-11e9-8a6e-cbd8bafa6ba5.png)

Test project 
[i25243-model-export.zip](https://github.com/godotengine/godot/files/2795083/i25243-model-export.zip)

**Comment by akien-mga** [comment]
Reopening, 32fa136 referenced the wrong issue.

**Comment by reduz** [comment]
sorry mistake :\

**Comment by akien-mga** [comment]
```
ERROR: _call_function: Error calling deferred method: 'EditorInspector::_property_changed_update_all': Method expected 2 arguments, but called with 4.
   At: core/message_queue.cpp:259.
```

This error is fixed by #25383, but I don't know if it was related to this bug and would fix it too.

**Comment by reduz** [comment]
This seems to be working fine, just tested it. Materials won't be updated if you set them as external (which is the default) and this is intended. The rest seems to be working without issues. Maybe this was fixed in recent commits, so please feel free to reopen with more specific information if it still fails.

**Comment by Busata** [comment]
I seem to have the same issue, when trying to come up with a way to just link an meshinstance node, I export .dae files with import settings set to "multiple scenes", then use the meshinstance scn file in another scene. 

when updating the model in blender & exporting it, it'll display the new data only in playmode, viewport will still show the old model & this only seems to update when restarting the editor.

**Comment by vt5491** [comment]
Same problem here.  

I discovered that if you click on the "scene clapper" icon (to the left of the eyeball) on the "Scene Root" of the opened subscene, and then select "Open Anyway" on the "Please Confirm" dialog, then the changes are reflected in the new tab, and then on the original tab as well.  Thus, you can just close the newly opened tab, and then your original tab will have the new material.  Just a hack to cause a proper refresh.

**Comment by cybereality** [comment]
I'm having this issue as well on Godot 3.1.2-stable (Steam version). Ubuntu 19.10 and models exported as glTF from Blender.
