### ISSUE TITLE
Unexpected InputEvent delivery order in 2D scene with ViewportContainer

### ISSUE THREAD

**Issue by logicor-cn** [godotengine/godot#25525]
**Godot version:**

3.0.6-stable

**OS/device including version:**

Windows 10 1803
Python 3.6.4
pywin32 224
scons 3.0.1
Visual Studio 2015 14.0.25431.01 Update 3

**Issue description:**

Here is the scene hierarchy:

Main Scene
```
Node_Root
|-CanvasLayer_HUD
|  |-Scene_HUD
|-ViewportContainer_GameMap
   |-Viewport_GameMap
      |-Scene_GameMap
```

GameMap Scene
```
Node_GameMap
|-TextureRect_GameMap
|-Camera2D_GameMap
```

- Window size 1600x900
- `ViewportContainer_GameMap` and `Viewport_GameMap` are 1470x800
- `TextureRect_GameMap` is originally 800x600 but is zoomed by `Camera2D_GameMap`.  Its equivalent size on screen, including those parts cut off by `Viewport_GameMap`, can cover the whole window and event extend beyond.
- Both `Scene_HUD` and `Scene_GameMap` has `_gui_input` implemented in script of its root Node.
- No custom `_input` is implemented in the whole project.

**Now, any mouse events on HUD, even the parts outside the `ViewportContainer_GameMap`, is actually sent to `Scene_GameMap` instead of `Scene_HUD`.**  And because `TextureRect_GameMap` is zoomed in and have a larger onscreen size, it actually processes and consumes the event in `_gui_input` when it is delivered to it.

I traced down the C++ call stack and found here is what happened:

1. Root Viewport captures the event and try process it through `_input` of its children
2. `ViewportContainer` has a default `_input` and captures it.
3. `ViewportContainer` pass the event to its child `Viewport`
4. `Viewport::input` is called on the child `Viewport`
5. `Viewport::input` first try to process the event in `_input` of its children, no valid candidate found.
6. `Viewport::input` **immediately tries to process the event in `_gui_input` of its children.
7. `Scene_GameMap` receives the event and consumes it.
8. HUD never gets the event.

IMHO the behavior of `Viewport::input` is exactly the issue here:

https://github.com/godotengine/godot/blob/0c030d6e0850e8ee185ec57b7e24e3552678c9d2/scene/main/viewport.cpp#L2323-L2333

It implements the logic of the Root `Viewport` of the game, but is ill formed when used as `_input` of a contained `Viewport` because through the `_input` of `ViewportContainer`, it escalates the execution order of its children `_gui_input` methods to be before any other `_gui_input` outside the `ViewportContainer`, including those are supposed to receive the event.

**Steps to reproduce:**

* Extract attached project.
* Run with 3.0.6-stable and see events on HUD gets consumed by GameMap

**Minimal reproduction project:**

[project.tar.gz](https://github.com/godotengine/godot/files/2818996/project.tar.gz)

**Comment by hilfazer** [comment]
As i understand it input event should not reach subviewports until all other options are tried and event still wasn't accepted.

https://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html?highlight=input
From docs:
"But SceneTree does not know what to do with the event, so it will give it to the viewports, starting by the “root” Viewport"

A Viewport will try following options:
_input()
_gui_input()
_unhandled_input()
ray into the physics world
and:
"Finally, if the event was unhandled, it will be passed to the next Viewport in the tree, otherwise it will be ignored."

**Comment by logicor-cn** [comment]
@hilfazer In that case, simply renaming `_input` of `ViewportContainer` to `_gui_input` should fix the behavior.

**Comment by hilfazer** [comment]
What do you mean by "manually handled with capturing and other techniques"?

ViewportContainer capturing _gui_input() is fine. What i meant is it shouldn't forward events to its Viewport child.

**Comment by xiay-lcw** [comment]
By "manually" I mean `Viewport` that is not contained in a `ViewportContainer`, but rather used as a Viewport Texture.  Those `Viewport` usually need written script to explicitly pass due input event from the surface Viewport is actually rendered on.

I am not sure if `ViewportContainer` is originally designed to handle input also.  With the current code base it seem to be.  I would also argue it should because otherwise this container has no value.  You can replace it with a `TextureRect` and set the texture to capture from the `Viewport` and get the exact same result.

IMHO, the true value of `ViewportContainer` lies in that it handles input events implicitly and reduce the redundant script work.  Thus it should proxy `_gui_input()` event to `Control` components within its child `Viewport`

**Comment by logicor-cn** [comment]
By "manually" I mean `Viewport` that is not contained in a `ViewportContainer`, but rather used as a Viewport Texture.  Those `Viewport` usually need written script to explicitly pass due input event from the surface `Viewport` is actually rendered on.

I am not sure if `ViewportContainer` is originally designed to handle input also.  With the current code base it seem to be.  I would also argue it should because otherwise this container has no value.  You can replace it with a `TextureRect` and set the texture to capture from the `Viewport` and get the exact same result.

IMHO, the true value of `ViewportContainer` lies in that it handles input events implicitly and reduce the redundant script work.  Thus it should proxy `_gui_input()` event to `Control` components within its child `Viewport`

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by Calinou** [comment]
Closing due to lack of response (see the above comment). Please comment if you can still reproduce this issue on Godot 3.2.2 or a later release.

**Comment by SuperSuit12** [comment]
Wait, this is now marked "closed" with no "X closed this issue" visible to me. Was this closed, or is "archived" a state? I thought it was archived. Did I accidentally close this?

**Comment by SuperSuit12** [comment]
I think this MAYBE should be reopened? The dual-highlighting thing is an issue, at least.

**Comment by SuperSuit12** [comment]
Okay, yeah, probably needs reopened because ViewportContainer seems to be intentionally shutting off "handle input locally," implying this isn't two sets of intended behavior to choose between but rather an unintended behavior and something you're not supposed to be able to do. I have no idea what "handle input locally" means, or why you shouldn't do it when the Viewport is in a ViewportContainer, but... something feels really wrong here, and I can't think of any reason you'd want the Viewport to propagate input in this way.

**Comment by Calinou** [comment]
> Okay, yeah, probably needs reopened because ViewportContainer seems to be intentionally shutting off "handle input locally," implying this isn't two sets of intended behavior to choose between but rather an unintended behavior and something you're not supposed to be able to do. I have no idea what "handle input locally" means, or why you shouldn't do it when the Viewport is in a ViewportContainer, but... something feels really wrong here, and I can't think of any reason you'd want the Viewport to propagate input in this way.

This is now tracked in https://github.com/godotengine/godot/issues/56502.

**Comment by rpahut** [comment]
@Calinou this issue is still present as of 3.5 . Letting know as requested above.
The [#56502](https://github.com/godotengine/godot/issues/56502) appears to be a sidetrack with no actual fixes coming out of it.

The effect is actually more severe than initially described, as controls inside Viewport appear to consume input even when there are gui receivers _in front_ of the viewport. Found no real workarounds, other than to disable the mouse on each control in the viewport or the viewport itself.
