### ISSUE TITLE
Too many polygons in NavigationPolygon breaks navigation debugging

### ISSUE THREAD

**Issue by bretzl** [godotengine/godot#25578]
**Godot version:**
3.1 beta 3 official

**OS/device including version:**
Linux / Debian9 
GTX 1080 / NVIDIA Driver Version: 410.78 

**Issue description:**
Too many polygons in NavigatinoPolygon throws an error when debugging/navigation is enabled. Also no debug navigation is added to screen:

ERROR: _draw_polygon: Condition ' buffer_ofs > data.polygon_buffer_size ' is true.
   At: drivers/gles3/rasterizer_canvas_gles3.cpp:352.

**Steps to reproduce:**
Generate more than 1365 polygons which all have 4 vertices (e.g. squares). Enable 'Navigation' in debugging. See attached sample project. Size of polygons makes no difference. Not tested with more then four vertices per polygon. Error thrown with GLES3. When GLES2 is used there is no error output but same behavior.

**Minimal reproduction project:**
[DebuggingNavError.zip](https://github.com/godotengine/godot/files/2825401/DebuggingNavError.zip)

**Comment by Xrayez** [comment]
I have a similar problem as well when trying to draw very large polygon in a single draw call, with that many vertices as described in the issue. Solved by splitting the polygon into chunks per node, so that it has many smaller polygons that rasterizer can manage to draw I suppose.

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
master needs updated MRP to test.

**Comment by KoBeWi** [comment]
Bump.
Can anyone still reproduce this in 4.0 alpha7? If yes, attach an updated MRP.

**Comment by smix8** [comment]
@KoBeWi 
In Godot 3.5 this is no bug anymore as the error msg is "poly has too many indices to draw, increase batch buffer size" which means ... surprise ... increase the batch buffer size in ProjectSettings "rendering/batching/parameters/batch_buffer_size" and with this limit increased it draws the poly without error in 3.5.
