### ISSUE TITLE
Adding animation to AnimatedSprite doesn't update inspector immediately

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26381]
**Godot version:**
3.1 beta8

**Issue description:**
When you add a new animation in AnimatedSprite
![image](https://user-images.githubusercontent.com/2223172/53526481-9e0b3580-3ae4-11e9-853c-8cbd93370425.png)
the inspector isn't updated
![image](https://user-images.githubusercontent.com/2223172/53526510-b3805f80-3ae4-11e9-94d6-cb900be84a4c.png)
and you need to reselect the sprite to have it refreshed. Surprisingly, renaming animation updates correctly.

**Steps to reproduce:**
1. Create AnimatedSprite node
2. Add SpriteFrames
3. Add a new animation
4. Check animation list in inspector

**Comment by ChakradharGanta** [comment]
Hi
I am able to reproduce this issue on Ubuntu.
I would like to work on it.

**Comment by veryprofessionaldodo** [comment]
I would like to give it a shot too, see if I can fix this :) 

I haven't looked at this part of the code base, but I'm curious to see it!

**Comment by veryprofessionaldodo** [comment]
It appears that removing a Animation also doesn't update, but renaming animations does seem to do the trick... Interesting... I'll look into this more today, I got some classes now :)

**Comment by KoBeWi** [comment]
This issue is weird. I investigated it and nowhere in code the animation list is updated explicitly. I noticed that it's refreshed upon calling `_validate_property`, but it's only called magically when doing rename ("magically" ie. not anywhere near AnimatedSprite). Trying to force any validation sadly fails.

I also noticed that it happens with other nodes too. E.g. when changing a Polygon2D from the editor, inspector's vertex list doesn't update. I noticed that AnimationPlayer does this correctly, but ugh .-. I failed to determine how. It seems to require some deep digging. Or someone who knows how it works.

**Comment by veryprofessionaldodo** [comment]
Yeah, that's what I originally thought. Maybe a function that someone forgot to call to update the inspector, but it seems it's deeper than that. 

I'll keep looking into it today!

**Comment by piyushdagar** [comment]
https://github.com/godotengine/godot/blob/a53645e726097e9020d12df886b62431cb1740b9/editor/plugins/sprite_frames_editor_plugin.cpp#L385-L386
Removing these two lines give the expected behaviour, but it also changes selected animation in inspector as the new animation. 
![Peek 2019-03-19 16-27](https://user-images.githubusercontent.com/30121673/54601037-17eb6a80-4a64-11e9-8cbf-315c6e44fe26.gif)


I am also trying!

**Comment by veryprofessionaldodo** [comment]
Yeah, I was looking at that file too, nice catch tho! We might be getting closer :)

**Comment by piyushdagar** [comment]
@veryprofessionaldodo What's the behaviour required? Just removing these lines seems to fix this particular issue and it does not seems to break anything(or does it?).

**Comment by veryprofessionaldodo** [comment]
Oh, actually it seems like the problem is fixed! 

KoBeWo did mention that it also appears in Polygon2D. Is that problem affected, or is it another problem entirely?

**Comment by piyushdagar** [comment]
Which part in Polygon2D? It works fine for me..

**Comment by veryprofessionaldodo** [comment]
I don't know, I never actually noticed it. 

But that seems like another issue, maybe this looks like it's ready for a pull request

**Comment by KoBeWi** [comment]
The array isn't updated if it's expanded in the inspector. You either need to re-select node or shrink/expand the array.

**Comment by piyushdagar** [comment]
It still does not work properly on removing animation(deleting). I was conforming whether maybe issue is something else, but can not yet figure it out.
