### ISSUE TITLE
Pasted nodes place on the same position instead of mouse position

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#26719]
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script
when copy a node in visual script area and paste, Godot place it on the same place instead of mouse position.
in big visual scripts this is problem, because user will drag the nodes and pan the view many times to place the nodes correctly.

**Comment by fire** [comment]
This should be resolved by https://github.com/godotengine/godot/pull/28162

**Comment by fire** [comment]
This is a related problem, but not resolved.

**Comment by KoBeWi** [comment]
In 3.2.3 rc3 the duplicates get stacked:
![image](https://user-images.githubusercontent.com/2223172/89744022-154e4280-daa9-11ea-9007-f1b7dbe1f75e.png)
I can't use shortcuts though for some reason.

**Comment by kreaninw** [comment]
This is still happening in 3.2.4 beta 4.

The pasted node(s) will not be at the user's mouse position or the current viewing area, making it useless to copy and paste nodes in a big and complex Visual Script.

This could also cause a serious problem in usability since a lot of nodes that the user intended to use elsewhere will be stacked at the same position which had so many nodes already, thus the reason why they were copied in the first place.

I am not sure if this issue could fit into the _discussion_ tag since the current behavior definitely doesn't align well with the expected behavior of the copy and paste feature where the user expected to be able to control the pasted position/destination of the copied item. If they just want to copy and paste at the same place, that would be the duplication (ctrl+d).

However, with all that said. I don't think that to copy and paste a group of complex nodes to use at many places in the script is a good way to work in Visual Script. Especially, when we don't have the ability to search for a function call and a variable in Visual Script yet (proposal [#1780](https://github.com/godotengine/godot-proposals/issues/1780)). I think it would be more manageable if that kind of a node group is converted to a function by which the differential in logics is controlled through the function's aruments.

**Comment by Gallilus** [comment]
Possibly solved with merged PR  https://github.com/godotengine/godot/pull/54564
