### ISSUE TITLE
Godot doesn't run on 32-bit Linux with GeForce 9200M and nouveau

### ISSUE THREAD

**Issue by fgictfgfokpf** [godotengine/godot#26986]
**Godot version:**
[Godot 3.1 RC3 ](https://downloads.tuxfamily.org/godotengine/3.1/rc3/)

**OS/device including version:**

```
~$ neofetch --backend off
lubuntu@lubuntu
---------------
OS: lubuntu 17.04 32bit i686
Host: HP Pavilion dv5 Notebook PC Rev 1
Kernel: 4.13.0-16-generic
Shell: bash 4.4.12
Resolution: 1280x800
DE: LXDE
WM: Openbox
CPU: Intel 2 Duo P8400 (2) @ 2.267GHz
GPU: NVIDIA GeForce 9200M GS
Memory: 1203MiB / 4007MiB
```

```
~$ glxinfo | grep "OpenGL"
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.2.2
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 17.2.2
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

```
**Issue description:**
Nothing happens when trying to run Godot 3.1 RC3. The terminal output is just this: 

```
~$ ./Godot_v3.1-rc3_x11.32
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbcd04] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbcd04] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbcd04] (??:0)
-- END OF BACKTRACE --
Aborted
```

**Comment by qarmin** [comment]
Can you tun it with this parameters and show result? : ./Godot_v3.1-rc3_x11.32 --video-driver GLES2 --verbose

**Comment by akien-mga** [comment]
I'm surprised that your GPU is NVIDIA GeForce 9200M GS but your driver is Mesa? Do you have an integrated GPU, maybe Intel?

I'm surprised that `glxinfo | grep OpenGL` doesn't name any vendor, mine has:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 670MX/PCIe/SSE2
```

**Comment by fgictfgfokpf** [comment]
@qarmin, oops, there is my vendor:

```
OpenGL vendor string: nouveau
OpenGL renderer string: NV98
```

```
~$ ./Godot_v3.1-rc3_x11.32 --video-driver GLES2 --verbose

XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.

handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbbd04] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbbd04] (??:0)
-- END OF BACKTRACE --
Only one GPU found, using default.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7fbbd04] (??:0)
-- END OF BACKTRACE --
Aborted

```

**Comment by akien-mga** [comment]
> Should I update my drivers?

That might help, but you'd likely have to update your complete OS, as Lubuntu 17.04 is no longer supported. Might be worth upgrading to 18.04 which is a LTS release.

It would be interesting to check if the crash happens in Godot or in the driver though, so if you can compile a debug binary from source and try it, it should give us more information. There are instructions on http://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html and for the debug binary it would be `scons p=x11` (it's debug by default).

**Comment by fgictfgfokpf** [comment]
Ok, i'll try to compile the debug binary.

**Comment by fgictfgfokpf** [comment]
```
~$ ./godot.x11.tools.32
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  17
  Current serial number in output stream:  18
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  17
  Current serial number in output stream:  18
ERROR: initialize: Condition ' ctxErrorOccurred || !p->glx_context ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:188.
ERROR: initialize: Condition ' !p->glx_context ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:175.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:167.

** (zenity:21940): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

```

**Comment by akien-mga** [comment]
Is it still fixed after a reboot? If so, it might have a been a Mesa misconfiguration issue that your install + uninstall of nvidia-340 fixed.

**Comment by fgictfgfokpf** [comment]
@akien-mga, Godot just ran on a live cd where the mesa driver is the same as on my installed os and I didn't do the install-uninstall nvidia-340 procedure.

**Comment by akien-mga** [comment]
Thanks, so this was indeed a system specific configuration issue.

**Comment by fgictfgfokpf** [comment]
@akien-mga, really? Because only the debug build works - RC3, RC2, RC1 releases don't.

**Comment by akien-mga** [comment]
Well you tell me :) You mentioned above that the debug build didn't work initially, and then after a system config change it did work. So the fault doesn't seem to lie in Godot itself, but was in the system.

RC3 should now work on that fixed configuration.

**Comment by fgictfgfokpf** [comment]
Actually, I didn't run the debug build before I installed-uninstalled nvidia-340 - I first run the debug build after i installed nvidia-340. I initially ran RC3 and even after the system config change it still doesn't work. The debug build would've run even before I messed with the drivers, and it does: I reinstalled my lubuntu 17.04 so It would revert all changes made to the system and the debug build still runs, but RC3 doesn't.

**Comment by akien-mga** [comment]
Can you try with 3.1-stable?

**Comment by fgictfgfokpf** [comment]
@akien-mga, that's weird: 

```
$ ./Godot_v3.1-stable_x11.32 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7eecd04] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7eecd04] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] [0xb7eecd04] (??:0)
-- END OF BACKTRACE --
Aborted
```

but the debug build that I've compiled yesterday runs fine:

```
$ ./godot.x11.tools.32
OpenGL ES 3.0 Renderer: NV98
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:944.
```

**Comment by akien-mga** [comment]
There must be a problem with how we build official binaries, I'll let @hpvb have a look. In the meantime, you can build from source yourself to have a working version :)
