### ISSUE TITLE
RayShape2D Collides with the bottom of one way collision tiles

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#27431]
**Godot version:**

v3.1.stable.official (Steam)

**OS/device including version:**

macOS Mojave 10.14.3 

**Issue description:**

If you use RayShape2D with one way collision tiles, it collides with the bottom them.

**Steps to reproduce:**

Create a KinematicBody2D with a RayShape2D:
![Godot 3.1 doc](https://godotengine.org/storage/app/uploads/public/5b4/de1/39c/5b4de139c8635728849121.png)

Create a tilemap with one way collision tiles:
![Tilemap](https://user-images.githubusercontent.com/423381/54973590-4dfe8200-4f6f-11e9-9728-cecad2495b30.png)
![Screen Shot 2019-03-26 at 02 30 57](https://user-images.githubusercontent.com/423381/54973625-6c647d80-4f6f-11e9-8b98-7324e48e72d6.png)

Create a basic jump logic, and then when you jump you will collide with the bottom of the tiles:
![Screen Shot 2019-03-26 at 02 31 11](https://user-images.githubusercontent.com/423381/54973670-9ddd4900-4f6f-11e9-93b4-50759a26e0d1.png)

**Minimal reproduction project:**

[rayshape2d_bug.zip](https://github.com/godotengine/godot/files/3006660/rayshape2d_bug.zip)

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by pouleyKetchoupp** [comment]
Fixed in #42574

**Comment by madmiraal** [comment]
Reopening, because this was not fixed with #42574.

**Comment by ThrdPrsnLmtd** [comment]
I investigated this in 64bit Linux, Godot 4.7.1
The process of creating TileMaps is a bit different in 4.x, so I had to redo the physics. I created tiles with a one-way collision and a collider the size of the tile, and some tiles without collision.

<img width="1689" height="1006" alt="Image" src="https://github.com/user-attachments/assets/4f7eaf5c-8ae9-4854-b7e6-c4ef13bf0527" />
(I used the bottom tiles for the collider so I could see if the player landed on the midline of the platform)

The player successfully passes through the one-way collider:
<img width="1201" height="600" alt="Image" src="https://github.com/user-attachments/assets/513c220d-e032-4461-97a0-00d800ec13f6" />
I did also recreate the bug in Godot 3.6.2 as described.
So I think we can take this off the 4.x milestone and add it to 3.x.

### Godot 4 MRP:
[rayshape2d_bug_godot_4_7_1.zip](https://github.com/user-attachments/files/31088929/rayshape2d_bug_godot_4_7_1.zip)

**Comment by KoBeWi** [comment]
Still reproducible in 4.8 dev, and like most physics issues, it's not even specific to TileMaps.

Here's a better reproduction project. All shapes are one-way.

[Raybugger.zip](https://github.com/user-attachments/files/31089117/Raybugger.zip)
