### ISSUE TITLE
Godot launcher fails to open in most recent builds from Calinou

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#27750]
**Godot version:**
3.2 Dev, April 5 and April 6 from Calinou's site. I can't get the hash because the launcher fails.

**OS/device including version:**
Win10 64 bit, April Update. Ryzen 2700X CPU, GTX 1060 6GB GPU.

**Issue description:**
New Godot builds over the last two days fail to launch. The console appears then disappears, the launcher fails to run. I have a build from April 3 and that runs just fine.

**Steps to reproduce:**
Download the daily build from here.
https://hugo.pro/projects/godot-builds/

Just double-click the icon and see if anything shows up.

EDIT: Accidentally typed the wrong Win10 revision.

**Comment by Calinou** [comment]
> I can't get the hash because the launcher fails.

You should be able to run the executable with `--help` from a command-prompt to see the build hash.

**Comment by Ace-Dragon** [comment]
Well, the day's commits usually stop early in the evening in my Timezone, and the newest build's date was around 8:30 PM, so I assume this was the latest commit it had.
https://github.com/godotengine/godot/commit/de825df1210089b4f8427618bb758101d5ad379b

The only real big commit I can recall over the past couple of days is the inclusion of the assimp library (as my newest working build has the fake 3D effect from Juan).

**Comment by Ace-Dragon** [comment]
I will also add, the console closes before anything is even printed. It stays blank and no errors are given.

**Comment by plucian** [comment]
I can confirm it is not working on windows 10.

**Comment by Norrox** [comment]
The x64 not working, the x32 does work.

**Comment by Norrox** [comment]
@Ace-Dragon sorry for the late reply, i was compiling from source myself, I will check later if  calinous build still fails

**Comment by Norrox** [comment]
i just compiled https://github.com/godotengine/godot/commit/07b76c0376eef34fcbf52ecc21074c5084f980f5
and it works.

i downloaded @Calinou latest win x64 and same error. the "godot.exe --help" does not even show a sign of life. usually information would appear but nothing.

**Comment by Ace-Dragon** [comment]
The last Calinou build was from the 8th of April (I can tell because the modified date of the Godot.exe reflects the time it was built rather than the time I downloaded and unzipped it).

Sometimes his buildbot fails for a day or so, it could be more likely right now since big changes are coming in.

**Comment by Calinou** [comment]
@Ace-Dragon I ran a new build this evening, try downloading it again.

**Comment by Norrox** [comment]
> @Ace-Dragon I ran a new build this evening (as yesterday's build failed indeed), try downloading it again.

Sorry but still won't work for me :P

**Comment by Ace-Dragon** [comment]
> @Ace-Dragon I ran a new build this evening (as yesterday's build failed indeed), try downloading it again.

Still nothing for the 64 bit build, the console still opens and closes with no errors or prints.

**Comment by takhimi** [comment]
Same problem with me. It wont open.

**Comment by akien-mga** [comment]
You all have issue with @Calinou's builds IIUC? Do you get the same issue with @fire's nightly builds? https://ifiregames.itch.io/stern-flowers-chibifire-com-godot-engine

**Comment by Ace-Dragon** [comment]
> You all have issue with @Calinou's builds IIUC? Do you get the same issue with @fire's nightly builds? https://ifiregames.itch.io/stern-flowers-chibifire-com-godot-engine

Good find, the build works perfectly, even though it might take more than one try to actually get the launcher. It really does seem now it's due to Calinou's build process.

I didn't pay for the access, but I will make sure not to download every day to help him save bandwidth. :-)

**Comment by akien-mga** [comment]
@Calinou @fire Can you share your respective build options for Windows (toolchain, use of LTO, etc.)?

**Comment by fire** [comment]
@Ace-Dragon Bandwidth is not the issue, the system to build the setup is the expensive part.

@akien-mga Here's the windows editor build:

```bash
scons platform=windows target=release_debug use_static_cpp=yes -j`nproc` use_lto=no use_llvm=yes gdnative_wrapper=yes deprecated=no
```

I can also send you the entire file by message.

**Comment by akien-mga** [comment]
@fire So you're using LLVM for Windows build? Or is this just a stray argument from your Linux build?

**Comment by Calinou** [comment]
These are the flags used for my 64-bit editor build:

```bash
# Build Windows editor
scons platform=windows bits=64 tools=yes target=release_debug use_lto=yes debug_symbols=no progress=no
```

Maybe link-time optimization is causing the issue (since it's not used on 32-bit)?

**Comment by Calinou** [comment]
I just pushed a new commit that disables LTO for my Windows builds, check back in a few hours when the build is finished.

**Comment by akien-mga** [comment]
@Calinou @fire It would still be good to know the exact toolchain that you're using (I assume MinGW, but what GCC version?). The binutils version would also be useful as it impacts LTO.

**Comment by fire** [comment]
I am also using fedora 29, but I don't have the exact versions. Currently busy with work.

**Comment by Ace-Dragon** [comment]
@Calinou ; I noticed your new build works as expected, now I can use things like the VSE additions :-)

**Comment by plucian** [comment]
I just tried the windows 64 bit ZIP version and still not working. Starts and quits without a message.

**Comment by Norrox** [comment]
Works for me now. :)

**Comment by plucian** [comment]
still no luck for me.... 32 bit version works though.. So I'm on Windows 10 and trying the 64 bit version coming from the Zip archive .

**Comment by Ace-Dragon** [comment]
Anyone who still has trouble with Calinou's builds should give Fire's builds a shot. If they still don't work, then it would help to know system information such as the Windows 10 version.

**Comment by plucian** [comment]
Fire's build, works for me.

**Comment by bojidar-bg** [comment]
What is the status of this issue?

**Comment by Calinou** [comment]
@Ace-Dragon Can you still reproduce this with the latest builds?

**Comment by Ace-Dragon** [comment]
Your builds have worked like a charm for a couple of months now.

**Comment by Calinou** [comment]
I haven't got a response from @plucian, so I'll close this. Thanks for reporting it :slightly_smiling_face:
