### ISSUE TITLE
Can't open quotation in editor or any title for node

### ISSUE THREAD

**Issue by eduardonunesp** [godotengine/godot#292]
I'm running godot in a Mac OSX Mavericks latest version 10.9.2, and can't create a simple string "simple string" or 'simple string', because pressing ' or " causes nothing. My keyboard is configured with international english, and i'm using dead keys. The godot version is v1.0.4147-beta1.

And thank you very much for the nice project, i'm will try more and wanna help more in future :+1:

**Comment by akien-mga** [comment]
Can someone reproduce this bug in the current master branch?

**Comment by akien-mga** [comment]
I haven't seen any recent report of this issue, so assuming it has been fixed or is a hardware-specific issue.

**Comment by emanuelcds** [comment]
Same issue here, using v2.0.2.stable downloaded from website.

**Comment by emanuelcds** [comment]
@eduardonunesp how did you solved the problem?

**Comment by eduardonunesp** [comment]
No, the problem persists even on the latest version `Godot_v2.0.2_stable_osx32`. I can't use any quotation. I'm using `OSX 10.11.4`

**Comment by emanuelcds** [comment]
Why the hell is this issue closed then? I will checkout the project and try to identify the issue.

**Comment by akien-mga** [comment]
> Why the hell is this issue closed then?

Calm down and read the comments. *I* closed the issue because there had been no activity in almost two years, even though I had asked in October 2015 if someone could still reproduce the issue. A closed issue can always be reopened if need be (though I see you've opened a new one already), so just ask for it when you can reproduce an old issue that has been closed due to inactivity.

If we were to keep all such issues open, we wouldn't be at around 1000 open issues today, but more like 2000. And that's not something we can work with.

**Comment by akien-mga** [comment]
See #4403 which now supersedes this issue.

**Comment by emanuelcds** [comment]
Fair enough. Sorry about the "why the hell", just expression that does not represent my mood that time. I am a nice guy :)

About the issue, just moved back to Vim and its working great once godot autoload the files before compiling.

As soon as I have a clue on this issue I will make a pull request.
