### ISSUE TITLE
Depth Draw Order issue with meshInstance alpha and CPUParticles

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#29354]
**Godot version:**
3.1.1 stable / GLES2

**OS/device including version:**
Windows 10, Surface Book 2
Android Samsung Galaxy S7, Oukitel K6000 Pro

**Issue description:**
In my project I have a meshObject and a CPUParticle effect in front of that. It works fine, until I set an alpha value in the shader of meshObject. Than the depth order drawing gets confused and my mesh is drawn in front of my particle effect:

https://youtu.be/SoHEjtwOgus
If you can't see what I'm doing, I'm commenting out the line "alpha = 1.0;" in the shader script and commenting it in again. You can see the effect in the 3d window, the effect in the running game is the same.

**Steps to reproduce:**
- Create a meshInstance with a custom shader where any alpha value is set (easiest to see is 1.0)
- Create a CPUParticle Node which emmits something that has a partially transparent texture
 

**Minimal reproduction project:**

[DepthDrawOrderIssue.zip](https://github.com/godotengine/godot/files/3242613/DepthDrawOrderIssue.zip)

**Comment by clayjohn** [comment]
This is already fixed in master by https://github.com/godotengine/godot/pull/28520

**Comment by Tobi-La** [comment]
Thank you very much, great to hear that!
Is there a way to test the current master without building it myself?
I tested the daily build from https://hugo.pro/projects/godot-builds/, but the issue still occurs.

**Comment by clayjohn** [comment]
You have the ``render_priority`` property of the SpatialMaterial attached to your particles set to ``-100``. Having a ``render_priority`` that low means that you want it drawn behind all other objects. Just reset ``render_priority`` to ``0`` and everything will work fine.

**Comment by Tobi-La** [comment]
Oh I feel like an idiot now, I'm so sorry!
I played around with that value to see if I can work around the issue in 3.1.1 stable and somehow forgot to set it back before testing with the daily build. 
Thanks again, it works fine now.
