### ISSUE TITLE
Skeleton2D doesnt influence polygons correctly - buggy behavior

### ISSUE THREAD

**Issue by fogine** [godotengine/godot#29353]
**Godot version:**

`v3.1.1`

**OS/device including version:**

> Linux 5.0.11-arch1-1-ARCH x86_64 GNU/Linux

**Issue description:**

I believe I have setup skeleton2D with correctly synced bones to polygons. However I'm experiencing bugs causing bones to influence polygons they are not supposed to influence.  

In the posted project example when rotating characters right arm (`ArmR`), it behaves as expected, however when you try to rotate left arm (`ArmL`) it also influences polygons of characters torso. There are multiple issues like that. Try rotating for example forearms or lower legs

**Steps to reproduce:**

[SkeletonBugExample.zip](https://github.com/godotengine/godot/files/3242325/SkeletonBugExample.zip)

**Minimal reproduction project:**

**Comment by andrewstrauch** [comment]
Commented on the related issue but also posting here:

I can reproduce something similar in our project.

![flier_mesh_bug_g](https://user-images.githubusercontent.com/732367/66004363-a52d6400-e476-11e9-9271-6014804c8780.gif)

We also have multiple Skeleton2Ds and multiple Polygon2Ds in the instanced scene of those flying enemies.

**Comment by KoBeWi** [comment]
I checked the project in 3.2.3 and here's how it looks
![Sw5x0i3CN5](https://user-images.githubusercontent.com/2223172/98412568-75d52780-2078-11eb-8e5b-14ad082363f6.gif)
Not sure if it's a valid bug or just a wrongly setup model. The related issue mentioned in above comment was fixed in 3.2..

**Comment by Calinou** [comment]
@fogine @andrewstrauch @KoBeWi Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
