### ISSUE TITLE
TileMap throws error when trying to draw/place a tile

### ISSUE THREAD

**Issue by kis3lori** [godotengine/godot#29715]
**Godot version:** v3.1.1
OS/device including version: Windows 10

**Issue description**
After playing a while with the TileMap I got the following error:
ERROR: tile_get_tile_mode: Condition ' !tile_map.has(p_id) ' is true. returned: SINGLE_TILE
   At: scene/resources/tile_set.cpp:449

This happens both when I try to run the project and when attempting to put/draw some tiles in the editor.

After re-creating the TileMap the error disappeared.

**Steps to reproduce** 
Sadly I'm not sure how I got to this error.
I mainly played with the position of the TileMap and the cell options (like Half Offset and Tile Origin)

**Comment by Ranoller** [comment]
This error can be related with autotile, not with the other options. And it should be tested in master, i think that some work was done about that.

**Comment by ZingBlue** [comment]
I am still getting this issue in Godot 3.2.1.stable.

**Comment by shash-nerurkar** [comment]
I too am still getting this.

**Comment by Devlin556** [comment]
+1

**Comment by NelsonSMG** [comment]
Me too when clicking my tile map node, not sure if you'll need a proyect

**Comment by Devlin556** [comment]
I'm faced with this error when I was trying to place a tile (with autotile) with the method in a script (`set_tile(pos)`), I get this error for every method call and tile isn't placed.
I'm using autotile with tileset - 128x128 by each block and some configured collisions.

**Comment by ZingBlue** [comment]
I get this error when I try to place an autotile at runtime.

**Comment by ZingBlue** [comment]
@Devlin556, you are setting these tiles at runtime? After `_ready()` has ran?

**Comment by Devlin556** [comment]
@ZingBlue Yes, and I guess I fixed this by using `set_tile(pos, 1)` (when the required tile is first) instead of `set_tile(pos, 0)`. Try this.

**Comment by ZingBlue** [comment]
In my case that won't work. It also occurs for me just by clicking the node, even when the game isn't running.

**Comment by ZingBlue** [comment]
Correction, when I first click one TileMap, then select another.

**Comment by fershopls** [comment]
Im also getting this error when I update a bunch of tile cells and call update_bitmask_region or update_bitmask_area..

Godot v3.2.1.stable.official

**Comment by keipaglows** [comment]
I don't know if this is still relative, but reimporting tileset in `Tile Set` property of `TileMap` fixed this issue for me.

**Comment by ZingBlue** [comment]
That also removes all tiles though.

**Comment by ZingBlue** [comment]
Is there a way to reimport without removing all the tiles from the scene?

**Comment by LukasOfLockless** [comment]
I encountered this error too in 3.2.2 stable. was doing tilemap editing using set_cellv. I found that this only occurs when calling update_bitmask_region

**Comment by fershopls** [comment]
@LukasOfLockless same here, I only get this error when I'm trying to update the bitmask on a tile that does not exists on my tileset.

**Comment by swordofbling** [comment]
I fixed this problem by reseting my tiles as my tile for some reason had an id of 2 so when i remade it and I made sure it was 0 and then it started to work

**Comment by chucklepie** [comment]
On 3.2.2 I'm getting a similar error

scene/resources/tile_set.cpp:480 - Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE

From calling one of the following two lines of code it fails, but not all the time, and it's always for the same tile not any other tile. I don't know if this helps but it seems consistent the above errors where this is just failing for a lot of people regarding something gone wrong in the tileset that cannot be easily fixed, and seems linked to the tileset getting mixed up with its IDs.

'''
var shapes=tileset.tile_get_shape_count(id)
one_way=tileset.tile_get_shape_one_way(id,0)
'''

For me, it only seems to do it with one specific tile. I've tried deleting the collision polygon for this id to no effect and the tile id is correct and everything is just normal, there is nothing wrong. I cannot reimport everything because I have over 200 tiles and you can't easily create this many tiles.

**Comment by ThaYoost** [comment]
Same error simple use case:
- Setup tileset with a single texture. Made 2 'single tiles'.
- painted in the 2nd tile
- remove the 2nd tile from the tileset
- now i get the error whenever I paint the 1st tile

**Comment by aorcaz** [comment]
This happens because there is a missing reference in the .tscn file, with the while updating the array containing the tiles.

Concider the following defining the Tiles:
```[sub_resource type="TileSet" id=1]
0/name = "ground_sand.png 0"
0/texture = ExtResource( 7 )
0/normal_map = ExtResource( 2 )
0/tex_offset = Vector2( 0, 0 )
0/modulate = Color( 1, 1, 1, 1 )
0/region = Rect2( 0, 0, 256, 513 )
0/tile_mode = 0
0/occluder_offset = Vector2( 0, 0 )
0/navigation_offset = Vector2( 0, 0 )
0/shape_offset = Vector2( 0, 0 )
0/shape_transform = Transform2D( 1, 0, 0, 1, 0, 0 )
0/shape_one_way = false
0/shape_one_way_margin = 0.0
0/shapes = [  ]
0/z_index = 0
2/name = "ground_tile_01.png 5"
2/texture = ExtResource( 6 )
2/tex_offset = Vector2( 0, 0 )
2/modulate = Color( 1, 1, 1, 1 )
2/region = Rect2( 0, 0, 256, 512 )
2/tile_mode = 0
2/occluder_offset = Vector2( 0, 0 )
2/navigation_offset = Vector2( 0, 0 )
2/shape_offset = Vector2( 0, 0 )
2/shape_transform = Transform2D( 1, 0, 0, 1, 0, 0 )
2/shape_one_way = false
2/shape_one_way_margin = 0.0
2/shapes = [  ]
2/z_index = 0
```

And the array contains a reference to Tile with the ID 1 as:
```
[node name="Map1" type="TileMap"]
mode = 1
tile_set = SubResource( 1 )
cell_size = Vector2( 256, 128 )
cell_y_sort = true
format = 1
tile_data = PoolIntArray( -589830, 1, 0, -589829, 1, 0, -589828, 1, 0,
```


Re-adding the correct information for Tile1 will correct the issue.

**Comment by DRKSLV** [comment]
hm, that makes sense, i deleted some textures from my tileset that are still hanging in the tilemap
(v3.3.stable.official)

is there a way to find and remove these "dead" cells?
i'm rapidly changing cells in the tilemap once i hit these cells,
the large spike in errors freezes my game for several seconds, just because of the logs

**Comment by DRKSLV** [comment]
(i figured it out)
yes there is! you can use the fill tool and see where the preview has these peculiar gaps, then replace them with another tile
just, uhh, make sure you don't misclick and fill the entire map, it fries the editor

**Comment by akien-mga** [comment]
Fixed by #51327.
