### ISSUE TITLE
Reflection probe does not work when arvr mode is turned on

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#30676]
**Godot version:**
Tested with commit 708092f0373019256845f486435f92a99437843f
But also reproduced with the official 3.1 release, probably been a problem for some time

**OS/device including version:**
Windows 10
GTX 1060ti

**Issue description:**
Reflection probes don't seem to work when the viewport is changed to an arvr viewport. Notice the difference in the ball between runtime and the editor in the background:
![image](https://user-images.githubusercontent.com/1945449/61455397-beaa2e00-a9a6-11e9-9cd8-1d7909fe0f37.png)

Turning the ARVR mode off but still tracking the headset I can see the reflection probe working properly so there is something missing in setting up rendering for stereo scopic.

**Steps to reproduce:**
Grab something with an environment.
Put a sphere inside with a reflective surface.
Add a reflection probe
Add a VR setup

**Minimal reproduction project:**
I'm working on one based off of https://github.com/wburton95/Godot-FPS-Demo

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by BastiaanOlij** [comment]
Just tested this in the latest 3.2.4 beta and seems to work fine so pretty sure this was fixed at some point in time.

**Comment by rhodochrone** [comment]
I'm still getting this problem in godot 3.3.

**Comment by Calinou** [comment]
@rhodochrone Please open a new issue with a minimal reproduction project attached.

**Comment by TheConceptBoy** [comment]
Still an issue in 3.3.4. Although the reflections are sort of there, just not as prominent as in 3D preview.
![image](https://user-images.githubusercontent.com/52581279/136086622-b0ff2168-083e-4191-847a-bd0f8fdf51bb.png)

**Comment by Calinou** [comment]
@TheConceptBoy  Please open a new issue with a minimal reproduction project attached.
