### ISSUE TITLE
VariantParser issue: layout and snap/grid settings not loaded on startup.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3197]
Currently happening in  be1f2a0 , but the error started a couple days ago. The position of the inspector (which I usually move to the same space as filesystem to form two tabs and free space to the right) is reset every time the project is opened, where it will return to its default position at the right of the 2D/3D/Script editor components.

While only a minor near-cosmetic issue, it used to remember the setting before, so I assume something went wrong with the recent config file changes?

EDIT: It seems some other settings like snap/grid settings aren't getting saved either. Should this be renamed to a general config file thing?

**Comment by neikeq** [comment]
The docks issue is a duplicate of #3186. It seems to be a bug with the new VariantParser, so renaming it to specify the general problem makes sense.

**Comment by hetdegon** [comment]
Hm, seems the other issue doesn't mention snap/grid settings, so I'll put some emphasis on that. If it's preferred, I can comment on that issue about the snap/grid settings and close this one.

**Comment by reduz** [comment]
i think this is fixed now, please test

**Comment by neikeq** [comment]
I just tested it, it is fixed!

**Comment by hetdegon** [comment]
Doesn't work for me. At least, not entirely. One of my scenes will start with grid and snap but no pixel snapping, while the main scene will always start without grid, snap or pixel snapping. Setting them and restarting has no effect.
I double checked in case my build was wrong, since I still get a couple of supposedly fixed bugs, but it's apparently current with no git or build errors.

**Comment by akien-mga** [comment]
>  I double checked in case my build was wrong, since I still get a couple of supposedly fixed bugs, but it's apparently current with no git or build errors.

Maybe check that you run the binary in bin/ that corresponds to the target you build? I often found myself running an older release_debug or debug binary when trying to test a new commit.

**Comment by hetdegon** [comment]
Yeah, made sure to run "scons platform=x11 bits=64 target=release_debug -j4 -c" first, and the binary's modified date is from minutes ago. The process is automated in my system, but since neikeq says it's fixed, that made me question it, and that's why I double-checked.
Actually, where are these settings saved? I don't seem to find them in editor_settings.xml or engine.cfg, are they scene settings? That might explain why, even if the setting is not currently remembered, a few scenes have grid+snap while others don't. Although none seems to be remembering pixel snap regardless.

**Comment by akien-mga** [comment]
Reopening while we investigate.

**Comment by hetdegon** [comment]
Thank you. Let me know if there's something I can/must do for debugging.

**Comment by neikeq** [comment]
Just checked again and it remembers the options fine for me. However, it doesn't remember options in the Transform menu of the 3D view (could be a separated issue though).

These settings seems to be saved in (unix) ~/.godot/config/_ProjectName_-_md5path_/_scene_file_-editstate-_md5path_.cfg

Example with the Platformer 2d demo:

~/.godot/config/platformer-_md5path_/stage.xml-editstate-_md5path_.cfg

``` ini
[editor_states]

2D={ "ofs":Vector2( -1159.71, 491.491 ), "snap_grid":true, "snap_offset":Vector2( 0, 0 ), "snap_pixel":true, "snap_relative":false, "snap_rotation":false, "snap_rotation_offset":0, "snap_rotation_step":0.261799, "snap_show_grid":true, "snap_step":Vector2( 64, 64 ), "zoom":0.397214 }
3D={ "ambient_light_color":Color( 0.15, 0.15, 0.15, 1 ), "default_light":true, "default_srgb":false, "deflight_rot_x":0.942478, "deflight_rot_y":0.628319, "fov":45, "show_grid":true, "show_origin":false, "viewport_mode":1, "viewports":[ { "distance":18.6438, "listener":true, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0.575, "y_rot":-0.3625 }, { "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 }, { "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 }, { "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 } ], "zfar":500, "znear":0.1 }
Anim={ "visible":false }
```

**Comment by hetdegon** [comment]
Interesting. My default scene is named debug.xscn, and there's no config for it with the rest, and ...
Wait, I lie. Settings seem to be created when *saving* the scene, despite being marked as unchanged, meaning you can touch those settings and close the scene without it being considered a "change", therefore it doesn't get saved. After forcing a save of the scene it does seem to be properly applied.

Has this changed since before? It feels those used to be more global settings (like, once you enabled pixel snap once, you didn't need to set it again for other scenes), but my memory is spectacularly bad. Since my default scene didn't have a config until now, I assume those were globally applied...? It did have grid+snap+pixel snap until the original bug happened.

Anyway, I digress. Seems the bug is actually fixed, just with that odd caveat of requiring a save to create config files. Perhaps they should count as a change in the scene?

**Comment by akien-mga** [comment]
IMO it's fine to have to save the scene for such changes to be taken into account. You rarely open a scene just to change its snapping behaviour and then close it :) And it's important to be able to have different settings for all scenes, as you might have a scene with a 10x10 grid and another one with 64x32 for example.

**Comment by hetdegon** [comment]
Yeah, can't argue against that. Although I think it might be a good idea to consider it a change in the scene so it's always clear that it needs to be saved for it to stick. Other than that, the issue is fixed indeed.
Thanks for your help, everyone.
