### ISSUE TITLE
"Show a list of all objects at the position clicked" does not work

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#32177]
**Godot version:**

```
3.1.1.stable.custom_build
```

**OS/device including version:**

```
Linux 5.2.13-arch1-1-ARCH #1 SMP PREEMPT Fri Sep 6 17:52:33 UTC 2019 x86_64 GNU/Linux
```

**Issue description:**

The "Show a list of all objects at the position clicked" editor tool does not show a list at all.

**Steps to reproduce:**

1. Create a scene with a box mesh
2. Generate a static body/trimesh collision shape
3. Place the mouse anywhere over the cube
4a. Choose the "Show a list of all objects at the position clicked" tool and left click, OR
4b. Choose the "Select" tool and alt+RMB
5. Nothing happens

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/3620774/example.zip)

**Comment by codecustard** [comment]
For the StaticBody, the reason is because it has no physical body to check collision with.  So the only way to select it would be in the SceneTree. I'm not sure if this should be changed or not.

This patch should resolve the issue regarding the Concave Collision Shape: https://github.com/codecustard/godot/commit/db4d5709d358ddef857167fc5438639a7b180f67

**Comment by rcorre** [comment]
@codecustard what do you mean that a StaticBody has no "physical body"? What types of nodes is this feature supposed to work with?

**Comment by codecustard** [comment]
It has no 3d representation. It should probably get a gizmo like empty 2d nodes that you can click on.

**Comment by rcorre** [comment]
What _does_ have a "3d representation"? A MeshInstance? It has one of those (see step 1) and still isn't selectable.

**Comment by codecustard** [comment]
The mesh instance gets selected for me. The context menu isnt going to show because it only detects one object, the mesh instance... the concave collision shape is fixed so in 3.2 your example should show a menu with the mesh instance and the collisionshape.

**Comment by Calinou** [comment]
Make sure your window manager does not intercept the <kbd>Alt</kbd> + click action. This is commonly done by Linux window managers to move/resize windows. To fix this, go to your window manager's settings and change the modifier key to something else such as <kbd>Super</kbd>.

**Comment by rcorre** [comment]
Alright, so I confirmed that a convex collision shape does work, but only with the "show list" selection mode, not alt+rmb. So I think this is partially the issue @codecustard fixed, and maybe partially @Calinou's comment? I'm using the [DWM](http://dwm.suckless.org/) window manager, and it uses meta (windows) + lmb to resize windows, so I'm not sure why it isn't getting through. Anyways, I'll close this, thanks for the help!
