### ISSUE TITLE
Glitchy dropdown in animation tree

### ISSUE THREAD

**Issue by Drakenroft** [godotengine/godot#33909]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 10 Pro - 1903 - Build: 18362.476
CPU: i7 9700k
GPU: RTX 2070
MOBO: Asus ROG STRIX Z390-E GAMING
32gb ram ddr4 2666mhz
Monitor 1920x1080 - 144hz

**Issue description:**
Glitchy dropdown in the animation tree

**Steps to reproduce:**
Just go in the player node then in AnimationTreePlayer and check the animation tree

**Minimal reproduction project:**
The 3D platformer demo.

![screen2](https://user-images.githubusercontent.com/35116091/69621564-a4144f80-103f-11ea-9116-352b6595db91.PNG)
![screen4](https://user-images.githubusercontent.com/35116091/69621565-a4144f80-103f-11ea-9d90-e0802a664493.PNG)
![screen3](https://user-images.githubusercontent.com/35116091/69621566-a4ace600-103f-11ea-836b-d9914c612b6e.PNG)
![screen1](https://user-images.githubusercontent.com/35116091/69621568-a4ace600-103f-11ea-9734-377db6c5d7bf.PNG)

Update: I did try to see if the problem is also in the 3.0.6 version and there isn't so it comes with the new 3.1

**Comment by KoBeWi** [comment]
Fixed in 3.2

**Comment by Drakenroft** [comment]
![image](https://user-images.githubusercontent.com/35116091/105868725-c3698c80-5ff6-11eb-9f18-33f35dccb84d.png)

![image](https://user-images.githubusercontent.com/35116091/105868739-c6647d00-5ff6-11eb-9e61-6c3982b31d1c.png)

Godot 3.2.3, the problem is still here

**Comment by KoBeWi** [comment]
@Drakenroft Can you attach a GIF and minimal reproduction project? I can't reproduce it.
Also try 3.2.4 beta6

**Comment by Drakenroft** [comment]
Yeah sure.
The GIF is on Godot 3.2.4 RC1
![Godot_bug](https://user-images.githubusercontent.com/35116091/106153839-43226300-617f-11eb-8fd6-5367452596a7.gif)

**Comment by KoBeWi** [comment]
I see something completely different here.
![image](https://user-images.githubusercontent.com/2223172/106176930-2f372b00-6198-11eb-91fc-7207aa70c752.png)
Are you maybe using custom editor theme or something? This is weird.

**Comment by Drakenroft** [comment]
Nope, it's just Godot out of the box, zero plugin installed

**Comment by KoBeWi** [comment]
Is it the latest version of this demo? I see AnimationTreePlayer in your GIF, which is a deprecated node.
