### ISSUE TITLE
Vulkan: Incorrect GPU is utilized in multi-GPU setups

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#35397]
**Godot version:**
a9e7dcba4d91b8e3f1089b57897317ce119bc8e5

**OS/device including version:**
Windows 10 1909
Radeon VII - Adrenalin 20.1.1
GeForce GTX 750 Ti

**Issue description:**
GPU 0 is the one connected to a monitor, but Godot is instead using GPU 1.
Perhaps it has something to do with the card being on an earlier PCI bus (8 < 68)?
Does not occur in mainstream versions of Godot.

![image](https://user-images.githubusercontent.com/5272529/72787477-9f11ed80-3bf5-11ea-8fe0-b8d4475301a5.png)
![image](https://user-images.githubusercontent.com/5272529/72787481-a2a57480-3bf5-11ea-82bf-50ae39c3bc1d.png)

**Comment by hoontee** [comment]
@reduz

**Comment by disks86** [comment]
This specific behavior could probably be corrected by selecting the first discreet GPU with the most VRAM. However, it would still be an issue if you had two identical cards.

**Comment by akien-mga** [comment]
Fixed by #136585.

**Comment by akien-mga** [comment]
PR #36585 was reverted as advised there (f70b5fa30c), so reopening.

**Comment by plasticbomb1986** [comment]
There is vulkan layer for manually choosing the desired gpu, [LINK](https://github.com/aejsmith/vkdevicechooser)

But, its sometimes tricky, and in some rare cases isnt working, havent checked why. Sadly, the device index sometimes get "remixed", and in those moments the pre defined ID will be the wrong, thus have to change it.

So sometimes its not helping if you want to determine which is the primary GPu in the system, if you base it on memory ammount and first. Rather would be ideal to use pcie bus id, since thats never change, and its very rare you not using the first x16 pcie slot with lower bus id then the rest.

AMD 2700x
32GB 3200MHz RAM
2x VEGA64

**Comment by hoontee** [comment]
Still a problem. I really don't want to disconnect the secondary GPU since I'm actively using it for performance testing.
Any chance this could be fixed soon?

**Comment by clayjohn** [comment]
Godot 4.0 is in active development. It is not intended to be used in production. We have not even released an alpha. If you need a production-ready build, please use 3.2.2.

Please be patient. But don't expect a stable release until 2021.

**Comment by hoontee** [comment]
No worries, just testing!

For anyone looking for a temporary fix: disable the secondary GPU in Device Manager. I don't know why it took me this long to remember that I can do that.

**Comment by strank** [comment]
Just adding a note here that this problem also applies to laptops with both intel and nvidia gpus ("optimus"). Intel is the first device and godot crashes on swapchain initialization with `ERROR: Could not find both graphics and present queues`.
Manual gpu selection would be great, but I think there needs to be at least some automatic pre-selection that weeds out gpus that cannot even run godot because of missing capabilities.

Temporary workaround on linux is to uninstall the vulkan-intel package.

**Comment by NoFr1ends** [comment]
My idea on automatically selecting a physical device (there should be a parameter to overwrite this too) would be the following:
1. Prefer dedicated gpu
2. Filter out physical device without graphics or present queue
3. Filter out devices with geometry shader (?)
4. Maybe at a score for max texture size or similar parameters

Thats what I used in different Vulkan applications which worked fine on my tested devices (Windows, Linux, macOS).
If that would be okay for the time being I could create a new PR for that.

**Comment by hoontee** [comment]
Disabling the second card in Device Manager no longer works, and instead produces an infinite error loop within Godot:
![image](https://user-images.githubusercontent.com/5272529/120838760-cdb01000-c52d-11eb-9f25-d9a6ac799480.png)

Here's a sample of some of the errors produced, each unique:
```
ERROR: Error (-3) creating shader module for stage: Compute
   at: (drivers\vulkan\rendering_device_vulkan.cpp:4567)
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::compute_pipeline_create (drivers\vulkan\rendering_device_vulkan.cpp:5751)
ERROR: Error (-3) creating shader module for stage: Vertex
   at: (drivers\vulkan\rendering_device_vulkan.cpp:4567)
ERROR: Condition "p_shader.is_null()" is true.
   at: PipelineCacheRD::setup (servers\rendering\renderer_rd\pipeline_cache_rd.cpp:67)
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::uniform_set_create (drivers\vulkan\rendering_device_vulkan.cpp:4799)
ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:6454)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (C:\Godot\godot-master\servers/rendering/renderer_rd/pipeline_cache_rd.h:71)
ERROR: Condition "!pipeline" is true.
   at: RenderingDeviceVulkan::draw_list_bind_render_pipeline (drivers\vulkan\rendering_device_vulkan.cpp:6379)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (128)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6562)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6579)
```

**Comment by hoontee** [comment]
Disabling the second card in Device Manager works again but the main issue still hasn't been fixed.

**Comment by hoontee** [comment]
Fixed.

**Comment by Calinou** [comment]
> Fixed.

Did you do anything specific to resolve the issue? If so, please document this here :slightly_smiling_face:

**Comment by hoontee** [comment]
Not by me. The issue no longer occurs on the latest pre-alpha builld.
