### ISSUE TITLE
Polygon2D/Skeleton2D rendering bug when the polygon's rest pose is outside the viewport

### ISSUE THREAD

**Issue by nesja** [godotengine/godot#35726]
**Godot version:**
3.2.stable

**OS/device including version:**
Windows10 x64 1809

**Issue description:**
Polygon2D texture is not rendered with Skeleton2D if the rest pose of the polygon is outside the viewport but when animated polygon should be inside the viewport. Same results in the editor and when scene is playing. GLES2/GLES3 both.

**Steps to reproduce:**
Play example scene or pan in the editor so that the transparent icon moves outside the viewport
![capture](https://user-images.githubusercontent.com/22263042/73412829-7946c000-433c-11ea-9387-8dcfa32d538d.gif)

**Minimal reproduction project:**
[skeleton_bug.zip](https://github.com/godotengine/godot/files/4131684/skeleton_bug.zip)

**Comment by Regnaris** [comment]
I can confirm. Faced the same problem in my project.

**Comment by SaffronStreams** [comment]
Is there a workaround for this problem? I'm trying to animate a snake-like creature, but since it's a long straight line down in its Rest Pose (because setting up the Skeleton), and then more horizontal for its animation, if it's too low on screen, half its segments disappear.

https://www.youtube.com/watch?v=0P_ctbHoTvs

**Comment by Calinou** [comment]
You could change the CanvasItem's culling rect to be large enough to cover the whole pose, so it never fully leaves the screen. I don't remember how to do it exactly though.

**Comment by SaffronStreams** [comment]
I've gone down a little rabbit hole looking for how to override or change the culling rectangle or force the canvasitem to be drawn, but although I've found some possible hints, those properties/methods have no documentation on them or discussion online.

**Comment by SaffronStreams** [comment]
Coming back to this problem as I have a wide spider model that suffers greatly from this problem.

I've found there's a get_viewport().get_visible_rect() method, but the rectangle passes a constant, so you cannot change it. Can't find it in Project Settings. 

There are also nodes called VisibilityNotifier2D/VisibilityEnabler2D, but those don't seem to work/override what Skeleton2D does to visibility.

I'm somewhat surprised that this issue hasn't been added to a milestone yet. It is pretty breaking for the 2D experience. How can we get dev attention for this? Or is this an edge case I just keep bumping into?

**Comment by Calinou** [comment]
> I'm somewhat surprised that this issue hasn't been added to a milestone yet. It is pretty breaking for the 2D experience. How can we get dev attention for this? Or is this an edge case I just keep bumping into?

I can't guarantee this will be fixed for 4.0, as reduz may be too busy handling other issues right now.

**Comment by SaffronStreams** [comment]
Yeah, I read reduz has to work on specific Vulkan stuff because of the sponsorships that have been granted. I guess all other attention is dependent on interest by contributors. Then again, perhaps there's room for an extra hire in the budget who can devote some time back to 2D? I understand wanting to improve 3D to draw in more people, that's where the big budget is, but some of the earlier people came in especially because of the 2D capabilities, so I would hope that keeps getting attention as well.

I'm going to spend some more time looking for a workaround, but have been considering looking into C++ (even though the idea is daunting) so I could contribute to a solution. Then again, that solution might simply be to make visible_rect of viewport not a constant but changeable, perhaps with a warning in code or something?

**Comment by jtaart** [comment]
This seems to fix it for me. 
```
extends Polygon2D

func _ready():
	var custom_rect:Rect2 = Rect2(Vector2.ZERO,Vector2(1000,1000))
	VisualServer.canvas_item_set_custom_rect(get_canvas_item(), true, custom_rect)
```

**Comment by SaffronStreams** [comment]
I had been looking at VisualServer, wondering if it was something I needed to do there, but couldn't really figure out what does what. This code (slightly adapted*) certainly does something. It helps for certain nodes, doesn't for others. Is there some more documentation available on how this method works? (the docs are pretty sparse :-)  "Defines a custom drawing rectangle for the CanvasItem.")

*func correct_all():
	var custom_rect = Rect2(Vector2.ZERO, Vector2(3000,3000))
	for polygon in $polygon.get_children():
		print("check: " + polygon.name)
		VisualServer.canvas_item_set_custom_rect(polygon.get_canvas_item(), true, custom_rect)

(I set it at 3000 because my base models are pretty big (for if I ever need to zoom in for cut_scene))


Without this code (look when Drider (spider-like) character enters and leaves screen):

![without_code](https://user-images.githubusercontent.com/50481103/86918797-7213b180-c127-11ea-8bbb-cf16412be9bf.gif)

With code:
![with_code](https://user-images.githubusercontent.com/50481103/86919259-3decc080-c128-11ea-8ccc-d53362dac5cf.gif)

**Comment by SaffronStreams** [comment]
(Thanks for the help btw, seems like this is a promising path)

**Comment by jtaart** [comment]
Yeah I've used the physics server stuff before, which uses a function called get_rid() on the nodes that use it. It was pretty confusing to find it for the canvas nodes. I think get_canvas_item() should be renamed to get_canvas_rid().

Also you might be able to use a Control node to copy its rect to use, so you can visually see it in the editor. 

```
extends Control
func _ready():
	var custom_rect = Rect2(rect_position, rect_size)
```

**Comment by SaffronStreams** [comment]
I figured it out. I took over the Vector2.ZERO from your example code, but that determines the position of the rect within the base node of my character. I've now put it at Rect2(Vector2(-2000, -2300), Vector2(6000,2500)); which seems to do the trick! 

(Remember, the Drider you see on screen is scaled down ( to .17 to be exact), I make them so big because I like to have the possibility to zoom in. If I ever need to look for performance gain, it's probably there that I'll find it.)

**Comment by clayjohn** [comment]
We should be able to add the custom rect as a property of Canvas items and then expose it to the editor. That should make this way easier to solve. 

Eventually I guess we need to recompute bounding rect from the animation, but I don't know how slow that would be.

**Comment by akien-mga** [comment]
Fixed in 3.2.3 with #40869, but still relevant to fix for `master`.

**Comment by h0lley** [comment]
In Godot 4 alpha 3, the Polygon2D's texture disappears the moment I assign it a Skeleton2D node - seemingly regardless of any UV or rest position setup, or whether it's within the viewport or not - and the console is spammed with this (even without running the game):
```
E 0:00:00:0965   vertex_array_create: Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:4044 @ vertex_array_create()
E 0:00:00:0967   draw_list_bind_vertex_array: Condition "!vertex_array" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7272 @ draw_list_bind_vertex_array()
E 0:00:00:0967   draw_list_draw: No vertex array was bound, and render pipeline expects vertices.
  <C++ Error>    Condition "dl->validation.vertex_format == INVALID_ID" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7352 @ draw_list_draw()
```
The moment I add at least one item to the `polygons` array of Polygon2D, the error stops from being logged, but the texture remains invisible.

I'm not sure if that is this is pretty much this issue (or perhaps #57650) or should get its own?

**Comment by Bropocalypse** [comment]
[buggy skeleton.webm](https://user-images.githubusercontent.com/58696984/197318187-735c3876-1f53-4c10-b30e-7effe125ab6b.webm)
Can confirm something is off with Polygon2D in 4.0b3.
Kubuntu 20.04

**Comment by jonSP12** [comment]
The image is UpsideDown, maybe thats why it crashes once the sekelton2D gets in
![poly2D](https://user-images.githubusercontent.com/77213594/202154016-62443694-5f8e-4d1a-b2b9-b35aa4a9e6f0.png)

**Comment by clayjohn** [comment]
The above 3 comments were all duplicates of #59451 so I have hidden them to keep this thread tidy

**Comment by GeekzGamingz** [comment]
This looks like it was closed, but I am having a similar issue. Any ideas?
https://github.com/godotengine/godot/assets/42735252/c0c99009-ecf3-4d63-86d1-e0dbe1422b75

**Comment by lawnjelly** [comment]
It's closed as it is fixed for Godot 3 (this issue relates to Godot 3), the 2D skeleton culling still needs fixing in Godot 4. @clayjohn had a go but no joy, I'd said I'll see if I can have a go as I did the Godot 3 fix (but master is different so no guarantees). There may already be an issue for master in fact, if you search.

**Comment by akien-mga** [comment]
@lawnjelly This issue was closed for 4.0 with #68863.

**Comment by lawnjelly** [comment]
Skinned 2D culling is still broken in master afaik, see #76184 .

**Comment by SaffronStreams** [comment]
Oh no. I was planning to switch to 4 this summer, but might be too soon still then.

**Comment by SaffronStreams** [comment]
Can confirm that this issue still persists. Am switching my project to 4.1 at this moment, and this is one of the issues that I'm encountering.

**Comment by lawnjelly** [comment]
Rather than reopen this, it would probably be best to create a new issue for master (with MRP). Godot 3.x and 4.x are significantly different in this area, hence why it is taking a while to be addressed in Godot 4.

**Comment by SaffronStreams** [comment]
Oh, had forgotten it was closed. I'll try to make an MRP tonight if I can, otherwise Friday.

**Comment by SaffronStreams** [comment]
Trying to make a minimum project, I notice that the whole way you assign IK to Skeleton Bones has been changed. Will need to see how it works now (it looks more complicated at first sight), and possibly the problem has to do with my system being wholly set up in the old way of working. The switch for my current project to 4 is looking like more and more work. 😅
