### ISSUE TITLE
[Bullet] KinematicBody jitters up and down when walking along a flat gridmap.

### ISSUE THREAD

**Issue by evsey9** [godotengine/godot#35780]
___

***Note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.2 stable
**OS/device including version:** 
Windows 10
**Issue description:**
KinematicBody jitters up and down a lot on edges of tiles of a gridmap.
**Steps to reproduce:**
1. Get a kinematicbody that you can control with gravity
2. Get a gridmap with some tiles
3. Walk around, you'll notice it pretty quickly

**Minimal reproduction project:**
Kinematic Character 3D Demo from the templates has this bug easily noticeable.
![ViVBBp0UAH](https://user-images.githubusercontent.com/7791364/73540616-34ad4880-4452-11ea-8d66-ac50aafc381e.gif)
https://github.com/godotengine/godot/issues/35713 is possibly related.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/6fcb58f40dae8228074591e3262d5db97db3e2d7.

**Comment by rzuf79** [comment]
It's the same on alpha0.

**Comment by Calinou** [comment]
I'm trying to bisect the regression as we speak.

**Comment by jamie-pate** [comment]
Confirmed to still be a problem on bullet engine for me. Seems fine if the floor is **exactly** level, but I think my gridmap floors might be on a _very_ slight incline. The y component is not removed when I call `move_and_slide(velocity, Vector3(0, 1 ,0), true)` even if the kinematic body is on the floor

**Comment by Two-Tone** [comment]
In the Kinematic Character 3D Demo I only have the jittering when the player cube is between two or more floor cubes.  On a flat mesh there is no jitter for me.

What GPU is everyone running on?  Win7 with an Nvidia 1080ti here.

**Comment by Calinou** [comment]
@Two-Tone I'm using a GeForce GTX 1080 on Fedora 31.

**Comment by Two-Tone** [comment]
So that rules out it being an AMD issue then.

**Comment by Janders1800** [comment]
Maybe related? #34436

**Comment by DenisBelmondo** [comment]
This looks a great deal like [issue 34596](https://github.com/godotengine/godot/issues/34596) where user @madmiraal listed a number of duplicate issues which hopefully can lend even further insight. `move_and_slide_with_snap()` does indeed stop jittering on the floor, but any continuous movement in any direction up against a gap between two walls causes the same kind of jitter.

**Comment by akien-mga** [comment]
#40377 fixes it for GodotPhysics (but not for Bullet).

**Comment by thar0x29a** [comment]
> Another suggested workaround: change the vector in move_and_slide() or whatever you have from (X, 0, Z) to (X, -0.1, Z).
This worked on me. Godot 2.32 - capsule/sphere vs cube collision edges. Im not sure WHY and how. But it solved it. Thanks

**Comment by NathanLovato** [comment]
I can confirm the issue in Godot 3.3.3, but also 3.4, and it happens not only with Bullet physics but also when setting the physics engine to GodotPhysics.

Happens in our latest project. I can make a minimal reproduction demo if you'd like.

**Comment by akien-mga** [comment]
> I can confirm the issue in Godot 3.3.3, but also 3.4, and it happens not only with Bullet physics but also when setting the physics engine to GodotPhysics. Ping @akien-mga as you said it was fixed for the latter. This may be a regression?

I tested your project, I can reproduce the issue with Bullet, but not with GodotPhysics. I see no bumps with GodotPhysics in Godot 3.3.3-stable, 3.4-beta1 through 3.4-beta4 and latest `3.x` (25bd0c3f7).

The bumps in Bullet are subtle but noticeable, but in GodotPhysics I really don't see any. To be sure, I only go forward/backward in the initial position and make sure that the intersection between the left or right edge of the floor and the bottom of the window does not move.

It seems like you changed the **2D** engine from "DEFAULT" to "GodotPhysics", not the **3D** one. Maybe that's the issue?

**Comment by NathanLovato** [comment]
Ah! I didn't know there were separate settings for 2D and 3D. Indeed it's only bullet physics then!

**Comment by cybereality** [comment]
I have also encountered this issue. I can confirm that it only happens on Bullet physics and GodotPhysics solves it. I made a test project which shows the issue with using Bullet and GridMap collision, and the effect is quite extreme jitter, very noticeable. Maybe that will help debug the problem.
[GridMap.zip](https://github.com/godotengine/godot/files/7272232/GridMap.zip)
.

**Comment by Calinou** [comment]
> Will there be a fix for Bullet in 3.x?

It depends on whether a contributor finds a fix for it. I think @pouleyKetchoupp investigated this a while ago, but he didn't find a solution to this bug.

**Comment by Calinou** [comment]
As mentioned in [Shifty's Godot Character Movement Manifesto](https://markdownpastebin.com/?id=d9d61e67f9d64db2bd215f165b931449), the `is_on_floor()` part can be worked around by using a filter on the `is_on_floor()` check:

> - Unstable floor results make my 'is grounded' flag jitter
>   - This seems to be down to the collision margin system
>   - Use a rolling window (2-3 frames should be sufficient) that folds down to a single bool using OR to de-noise the floor check

In other words, create a function that wraps `is_on_floor()` and returns `true` if `is_on_floor()` returned `true` at least once in the last 3 physics frames (or 2, but it may not always suffice).

**Comment by NathanLovato** [comment]
That's great news, thanks much for the fix!

**Comment by akien-mga** [comment]
Fixed by #56801.

**Comment by elvisish** [comment]
Bullet still bumps on gaps in gridmaps in 3.5 RC1, doesn't do it with Godot Physics.

**Comment by akien-mga** [comment]
That's normal, #56801 was merged *after* 3.5 RC 1. It will be in 3.5 RC 2.

**Comment by elvisish** [comment]
Still having issues in RC2 with this, if the KB is moving slow enough, it'll jitter on the gridmap seams. It does not do this with Godot Physics.

**Comment by akien-mga** [comment]
I would suggest opening a new issue for cases which are not solved yet.

**Comment by elvisish** [comment]
> I would suggest opening a new issue for cases which are not solved yet.

I can do, but I didn’t want to fill issues up since this issue isn’t resolved properly.
