### ISSUE TITLE
Making the window resizable causes visible static image tear when the window is made fullscreen

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#35899]
**Godot version:**
3.2 Stable

**OS/device including version:**
macOS Catalina 10.15.3 / MacBookPro11,1

**Issue description:**
When Project -> Settings -> Window -> Resizable is enabled and the window goes into full screen, some image tearing appears. This is especially visible with symmetric tiles.

**Steps to reproduce:**
Run the project with Window Resizable ON and OFF.

**Minimal reproduction project:**
[Image_Tear.zip](https://github.com/godotengine/godot/files/4152179/Image_Tear.zip)

---

With Window Resize turned OFF:

![Screenshot 2020-02-04 at 10 36 21](https://user-images.githubusercontent.com/13488692/73727780-cfe83b80-473a-11ea-8588-26e4800fa9e1.png)

With Window Resize turned ON:

![Screenshot 2020-02-04 at 10 37 08](https://user-images.githubusercontent.com/13488692/73727805-db3b6700-473a-11ea-8f8d-eb74fa844021.png)

**Comment by Torguen** [comment]
In 3.2 stable mono win10 it happens in both cases.

resizable off:
![resizableOff](https://user-images.githubusercontent.com/19652075/73737736-7f291080-4743-11ea-97b1-28d1b4348915.png)

resizable on:
![resizableOn](https://user-images.githubusercontent.com/19652075/73737746-84865b00-4743-11ea-92d4-61d5e3f64b27.png)

**Comment by sumit0190** [comment]
Not reproducible for me on both 3.2 and `master`. I even tried turning V-Sync off, but I still couldn't reproduce it.

**Comment by Gerarama** [comment]
I confirm this bug , I have tried to recored it and take screenshots for it , but all of my recording and screenshots trun out to look fine , but while playing it does tear the screen at (differnet position moving from top to bottom as time pass, also it spawn randomly in V location after you move the window and then go full screen)

by alot of debug , for some reason there is some objects that doesn't get tearing , like the main character , but when enable smoothing in camera setting , the tearing just doesn't happen, 

i moved my project into a new project and the tearing followed , but trying to make the same bug with completly new project won't do it , in my way i find that my project is lagging alot , even tho the fps is very high.

i hope this help address this problem.

**Comment by Gerarama** [comment]
Update : adding phyical process cost this bug to be visible.
replacing it with process will get rid of this bug.
replacing it with input will make the tearing move from bottom to the top faster.
Speeding phyical process to over 60fps doesn't have an effect.

**Comment by Gerarama** [comment]
Update 2 :
I manage to recreate this bug , you can open this project and move around to see the tearing.
It doesn't only happen when resizing but simply going full screen

[Flicker.zip](https://github.com/godotengine/godot/files/4854724/Flicker.zip)

**Comment by Gerarama** [comment]
UPDATE 3 ! :
Changing the phyical fps value in project settings changes how the tearing look like , values like 64 makes the hole screen overlap in very bad way , kinda like these old TVs , changing to 60 or 30 makes a line of tearing visible in a V position.
--------------------------------------------------------------------------------------------
I have tested this bug in the latest build in godot 4.0 , the bug has been fixed !
Note : Well i have heard that vsync is not disabled in godot 4.0 there for this buy may not be really fixed. we will see that when the stable godot 4.0 came.
----------------------------------------------------------------------------------------------------

**Comment by Gerarama** [comment]
UPDATE 4 :
I have rebuilded the movement system using C++
The tearing become so visible even when moving virtualy.

**Comment by drmar** [comment]
Confirming that the problem still exists in Godot 3.2.3.beta.1.official.

**Comment by Gerarama** [comment]
UPDATE 5:
I have find a workaround, The key is to not use _physices_process
As for my theory, the physices frame and the render frame are not aligned.
try to transform your script into _process

**Comment by drmar** [comment]
> UPDATE 5:
I have find a workaround, The key is to not use _physices_process
As for my theory, the physices frame and the render frame are not aligned.
try to transform your script into _process

It has nothing to do with the physics process.
In fact, the problem occurs even if there are **no scripts** and **no camera** in the project at all.
Run the attached project (Godot 3.2.3 beta 1) **with** and **without** display/window/size/resizable **on** and **off**.

**display/window/size/resizable** - **OFF**

![Screenshot 2020-07-23 at 08 29 29](https://user-images.githubusercontent.com/13488692/88254683-b9b94200-ccbe-11ea-8b9c-a3621f26e738.png)

**display/window/size/resizable** - **ON**

![Screenshot 2020-07-23 at 08 29 40](https://user-images.githubusercontent.com/13488692/88254753-e1a8a580-ccbe-11ea-8992-b2e3effcaa5d.png)

Minimal reproduction project - no scripts:

[Image Tear.zip](https://github.com/godotengine/godot/files/4963988/Image.Tear.zip)

**Comment by Gerarama** [comment]
Looks like we are addressing differnet problems,
While moving you can see visiable tearing, doing it on process removed this problem
UPDATE 6:
The tearing come back if you force fps to 60. even when using process

**Comment by Calinou** [comment]
I can't reproduce this on 3.5.stable (Linux):

## Resizable window

![2022-08-07_21 44 32](https://user-images.githubusercontent.com/180032/183308499-ab3fc96d-dde2-494c-8912-f3917cf21b14.png)

## Non-resizable window

![2022-08-07_21 44 43](https://user-images.githubusercontent.com/180032/183308500-8f3978c6-8ad2-42c4-9a39-22a9020ede6d.png)

I haven't tested fullscreen in 1920×1080, but I did test fullscreen in 2560×1440 with the `2d` stretch mode. However, while changing the project to use the `2d` stretch mode, I did notice that filtering is disabled on the texture used in the MRP. I recommend enabling filtering for this kind of texture to avoid scaling artifacts, especially if you don't enforce [integer scaling](https://github.com/Yukitty/godot-addon-integer_resolution_handler) in the project.

**Comment by yikescloud** [comment]
@Calinou 
I can reproduce this issue in the newest 3.5, if you use  the "Viewport" stretch mode. Please consider reopen it or submit a new one.
Viewport stretch mode
![image](https://user-images.githubusercontent.com/9168814/226454024-5e30a8d1-d13f-42ce-8b7f-6685696c2599.png)
2D stretch mode:
![image](https://user-images.githubusercontent.com/9168814/226454121-af754008-a957-468f-b50d-a9cb15060cce.png)
