### ISSUE TITLE
 <built-in>:14 - Invalid set index 'text' (on base: 'Nil') with value of type 'String

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35967]
**Godot version:**
3.2.0

**OS/device including version:**
Windows 10 pro education 64 bit

**Issue description:**
onready vars doesn't guarantee a the tree will be ready for getting a nodepath

**Steps to reproduce:**
- make 2x2 square of buttons
- add tool script to root
- use onready to store references to the buttons
- use export string property to set and get text from all buttons.
- try to edit property in editor.
- see error.

**Expected result**
- onready should only trigger when all child controls are ready
- onready and _ready should retrigger on script edit.

**Minimal reproduction project:**
[OnReadyBug.zip](https://github.com/godotengine/godot/files/4168292/OnReadyBug.zip)

**Comment by DmDerbin** [comment]
onready var Control1A = $Control1/Control1A
onready var Control1B = $Control1/Control1B
onready var Control2A = $Control1/Control2A # - Control1 -> Control2
onready var Control2B = $Control1/Control2B #- Control1 -> Control2

**Comment by luckyuk** [comment]
I probably didn't understand something, but if you fix the code:
```
onready var Control2A = $Control1/Control2A;
onready var Control2B = $Control1/Control2B;
```
to:
```
onready var Control2A = $Control2/Control2A;
onready var Control2B = $Control2/Control2B;
```
You see no errors.

**Comment by Shadowblitz16** [comment]
@akien-mga  reopen this please it was a typo but the bug still exists
[OnReadyBug.zip](https://github.com/godotengine/godot/files/4178486/OnReadyBug.zip)

@DmDerbin next time try fixing the error before you report back that it wasn't a bug

**Comment by KoBeWi** [comment]
This is weird. Setting the `all_text` variable will correctly set the button texts, but saving the scene always throws the mentioned error. Also the `all_text` variable is lost upon reload.

From my experience, it's better to use `get_node()` directly in the tool scripts instead of relying on `onready` variables. They don't work well with tool scripts.

**Comment by Shadowblitz16** [comment]
this should be fixed then because we should be able to declare our nodes at the top of the script instead of having to retype them out every time we want to use them

**Comment by bojidar-bg** [comment]
Setters of exported variables (tool or not) can get called while the node is being instanced and before its children have been instanced. This means that it can happen before `get_node()` is even able to find the buttons.

Changing the script to check for `is_inside_tree` before trying to use the `onready` variables and using `_ready` to call the setter:

```gdscript
func _ready():
	_set_all_text(_all_text)

func _set_all_text(value):
	if is_inside_tree():
		Control1A.text = value;
		# …
	_all_text = value;
```

**Comment by Shadowblitz16** [comment]
this is bad it though on ready should only be triggered when it "ready" this includes its children.
its compleatly defies what its suppost to be for. 

no one is going to want to do something before its ready that doesn't even make sense

**Comment by Anutrix** [comment]
Tried reproducing in v4.3-dev6. It wasn't reproducible.

@Shadowblitz16 or someone else can confirm maybe.

4.3 auto-converted project: [OnReadyBug.v4.3-dev6.zip](https://github.com/godotengine/godot/files/15281503/OnReadyBug.v4.3-dev6.zip)

**Comment by KoBeWi** [comment]
The error still appears when you reload the scene.
Though that's expected, because setters run before onready: https://github.com/godotengine/godot-proposals/issues/325
