### ISSUE TITLE
CanvasLayer soaks up my mouse events

### ISSUE THREAD

**Issue by dev-cyprium** [godotengine/godot#36891]
**Godot version:**
v3.2.stable
**OS/device including version:**
Windows 10 Home
**Issue description:**
I'm developing a resource management game. There are planets that `_on_KinematicBody2D_input_event` event. Once I add a `CanvasLayer` as documentation states to handle UI on games.

**Steps to reproduce:**
- Download the project 
- Run the project 
- Try clicking on the orbiting planets
- It doesn't work

Setting the filter to `ignore` makes it work... However, it also stops processing the `input` events on my HUD. Is there a way I can solve this by having both events enabled on the HUD and propogating them to nodes below the HUD.

**Minimal reproduction project:**
https://github.com/dev-cyprium/EndOfTheUniverse/tree/godot/bug-report

**Comment by luislodosm** [comment]
I have also encountered this problem. My solution has been to set up an interface with control type nodes that do not cover the area where the draggable objects are.

**Comment by orelb** [comment]
Any update on what to do in this situation? I'm experiencing the same issue.

**Comment by Sauermann** [comment]
In your MRP, when you change in GUI.tscn for the root `Control` the property `mouse_filter` from `Pass` to `Ignore`, the other GUI-elements still do receive mouse-events in Godot v3.5.1.stable.official [6fed1ffa3]. So I can't reproduce your described problem with your MRP in the latest version of Godot 3.
It may be, that this issue has been solved since v3.2.

The current behavior is, that Control nodes process events before events are used for physics-processing (e.g. `KinematicBody2D`).

@orelb without a Minimal reproduction project for your problem, it is difficult to tell, if you are experiencing the same issue.

**Comment by Novark** [comment]
I can confirm that this is still an issue in the latest v4.4.stable.official [4c311cbee] release.

MRP attached.

[canvas-mouse-input-mrp.zip](https://github.com/user-attachments/files/19562047/canvas-mouse-input-mrp.zip)

**Comment by YeldhamDev** [comment]
The thing about the `pass` mode is that it passes up the input until it stops finding `Control` nodes. Since `CanvasLayer` is not one, it halts right before it.

But even if the `CanvasLayer` would be replaced with a `Control` in @Novark's MRP, the covered button would still not receive inputs, since it isn't in the parent trajectory when passing up.

**Comment by KoBeWi** [comment]
So it's basically #55432 with added CanvasLayer.

**Comment by YeldhamDev** [comment]
Considering that the behavior is documented, and there is already a discussion about it, I say this can be closed.
