### ISSUE TITLE
Awaiting GDScriptFunctionState instances are not freed (and no way to free them manually)

### ISSUE THREAD

**Issue by mudbile** [godotengine/godot#37188]
**Godot version:**

Godot 3.2.1

**OS/device including version:**

Windows 10, 64-bit

**Issue description:**

If a function is being waited for when the application closes, the GDScriptFunctionState instances are not freed, preventing the main scene from being freed and causing a crash:

```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2071
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476
```

I don't know if the instances are also leaked silently when the scene is changed from.

To my mind, the instances should just delete themselves once the number of variables referencing them go to 0, but the big problem is I haven't been able to find a way to even manually delete them. 

I've tried:

- call `free() `on any that aren't null when exiting, but apparently you can't manually free references.

- `unreference()`ing them hoping that the counter would hit 0 and they'd be freed, but no luck- still not freed.

I've also tried:

```
var f = weakref(await_func())
if f.get_ref():
    yield(f.get_ref(), 'completed')
```

I've also tried storing them somewhere and going through them in _exit_tree():

```
for f in _fs:
    while f and f.is_valid():
        f = f.resume()
```

but nothing works.

**Steps to reproduce:**

1. Call a function that yields for whatever reason and store the returned GDScriptFunctionState instance in a variable.

2. Yield until that function is completed.

3. Quit the game before the function actually completes.

**Minimal reproduction project:**
[Demo.zip](https://github.com/godotengine/godot/files/4360101/Demo.zip)

**Comment by avencherus** [comment]
I've also had issues in the past with having to do careful management of these.  Nowadays, a yield for me has to be wrapped in several other lines of code so it can be safely cleaned up.

Games with yields have to free objects and shutdown with care, which can be quite burdensome in bigger projects, as it should probably be self managed far more than it is.

It's a bit limited how you can interact with GDScriptFunctionStates, but the following code should solve the issue given in the demo.

```
extends Control

var f

var shutting_down = false

func _ready():
	
	f = await_secs(5)
	quit_after_secs(2)
	yield(f, 'completed')
	
	if(shutting_down):
		return
		
	print("other code") # shouldn't execute
	

func quit_after_secs(secs):
	
	
	yield(get_tree().create_timer(secs), 'timeout')
	
	shutting_down = true
	
	if(f.is_valid()):
		f.resume()
	
	get_tree().quit()


func await_secs(secs):
	yield(get_tree().create_timer(secs), 'timeout')
```

**Comment by mudbile** [comment]
Your approach is similar to the last thing I tried. It does work, but as you say it is a quite limiting and begins to fall apart as your project grows, with functions yielding for other functions etc. 

I'm currently rewriting everything to yield on nodes themselves, as nodes correctly free themselves even if something's yielded on them. It's been easier than I thought to change it all. I've found the pattern reflected in the following example useful:

```
# Node A

func _ready():
	countdown_secs(10)
	quit_after_secs(2)

func countdown_secs(secs):
	for i in range(10,-1,-1):
		print(i)
		var key = $NodeB.await_secs(1)
		while $NodeB.ongoing_function_keys.has(key):
			yield($NodeB, 'func_finished')

func quit_after_secs(secs):
	yield(get_tree().create_timer(secs), 'timeout')
	print('~quit~')
	get_tree().quit()


#Node B

signal func_finished()#emitted whenever a yielding function is done
var ongoing_function_keys = []

func await_secs(secs):
	var key = generate_unique_key()#code omitted
	ongoing_function_keys.push_back(key)
	_await_secs(key, secs)
	return key

func _await_secs(key, secs):
	yield(get_tree().create_timer(secs), 'timeout')
	ongoing_function_keys.erase(key)
	emit_signal('func_finished')
```
Sometimes I have more than one signal- it's a balance between having too many signals and the performance of any waiting Node checking it's their function that just ended each time a general signal fires. It's a bit of a pain, and it's easy to make errors, but it actually scales fairly well and it's easy enough to translate from using to function states to this pattern. The slight advantage of this pattern is it works even if there's no yield in `_await_secs` .

**Comment by avencherus** [comment]
I do something similar inside one of my singletons for the general game things.  I have a registry where I register and unregister them where it matters.  Then during shutdown there is a shutdown function that handles cleanup, and it contains a yield section with a bunch of special case control over how this gets handled before doing a quit().

**Comment by RandomShaper** [comment]
I'm reopening this, since #38322 doesn't fix all the leaks, just some of them.

In the first reproduction code, the fix goes from this
```
Leaked instance: GDScript:1165 - Resource name:  Path: res://MainScene.gd
Leaked instance: GDScriptFunctionState:1175
Leaked instance: GDScriptNativeClass:897
Leaked instance: SceneTreeTimer:1171
Leaked instance: GDScriptFunctionState:1172
```
to this
```
Leaked instance: GDScriptFunctionState:1175
Leaked instance: SceneTreeTimer:1171
Leaked instance: GDScriptFunctionState:1172
```

So there's already some improvement, but this needs to be investigated and fixed further.
