### ISSUE TITLE
Godot WebGL export doesn't work on Safari

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#37931]
**Godot version:**
3.2.1.stable

**OS/device including version:**
macOS Catalina 10.15.4 / MacBookPro11,1
Safari version: 13.1 (15609.1.20.111.8)
Although this problem happens on the latest version of Safari, I remember that it happened on earlier versions of Safari too.

**Issue description:**
I quickly exported this project to WebGL and uploaded it to itch.io:
https://stone-age-jazz.itch.io/godot-weggl-test
PASSWORD: godot

The project is barebones, standard configuration, nothing has been changed.
The game does not work when running the game from Safari.
The game works when running on Firefox.

The particular error message that I get when trying to run the project in Safari is:
call_indirect to a null table entry (evaluating 'Module["asm"]["Gi"].apply(null,arguments)') 

On Safari - desktop:

<img width="1280" alt="Screenshot 2020-04-16 at 16 57 58" src="https://user-images.githubusercontent.com/13488692/79465129-a03f9480-8003-11ea-95ce-e07593fce095.png">

On Firefox - desktop:

<img width="1280" alt="Screenshot 2020-04-16 at 16 58 32" src="https://user-images.githubusercontent.com/13488692/79465215-b4839180-8003-11ea-9f65-428049264ae7.png">

On Chrome - desktop:

<img width="1280" alt="Screenshot 2020-04-16 at 17 33 09" src="https://user-images.githubusercontent.com/13488692/79469155-7b99eb80-8008-11ea-871a-5a982f22b335.png">

On Edge - desktop:

<img width="1280" alt="Screenshot 2020-04-16 at 17 35 27" src="https://user-images.githubusercontent.com/13488692/79469383-c3b90e00-8008-11ea-8539-662eec969a08.png">

On Opera - desktop:

<img width="1280" alt="Screenshot 2020-04-16 at 17 37 10" src="https://user-images.githubusercontent.com/13488692/79469541-fb27ba80-8008-11ea-88f1-11e18efec42a.png">

**Steps to reproduce:**
On macOS, run the game in Safari. It will NOT work.
On macOS, run the game in Firefox. It will work.
On macOS, run the game in Chrome. It will work.
On macOS, run the game in Edge. It will work.
On macOS, run the game in Opera. It will work.

**Minimal reproduction project:**
[Apocalypse Now.zip](https://github.com/godotengine/godot/files/4486467/Apocalypse.Now.zip)

**Comment by akien-mga** [comment]
Device, version...? Is this Safari 2.0 on an iPod Touch?

**Comment by drmar** [comment]
@akien-mga 

I have updated the issue with all the required information, according to the template.

**Comment by Calinou** [comment]
I think this is a duplicate of #26554.

**Comment by drmar** [comment]
@Calinou 

According to the author of this issue https://github.com/godotengine/godot/issues/26554 his problem is with iOS Safari:
"I noticed with GLES2 that html5 exporting is working with Desktop Safari and probably Edge. But I haven't been able to get a project to work with iOS Safari."

The problem that I described is happening on laptop/desktop - macOS.
I will post screenshots for more clarity.

**Comment by Calinou** [comment]
@drmar Nevermind, I read the issue wrong.

**Comment by drmar** [comment]
I made tests will all major browsers: Safari, Firefox, Chrome, Edge and Opera and posted screenshots as proof.
The only browser that doesn't work is Safari.
I hope this helps with the debug.

**Comment by bruvzg** [comment]
Project uploaded it to itch.io fails in Safari with following error, but the same project exported with 3.2.1.stable locally works:

```
exception thrown: Error: call_indirect to a null table entry (evaluating 'Module["asm"]["Gi"].apply(null,arguments)'),<?>.wasm-function[810]@[wasm code]
	<?>.wasm-function[803]@[wasm code]
	<?>.wasm-function[55416]@[wasm code]
	wasm-stub@[wasm code]
	Gi@[native code]
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:308575
	ccall@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:5556
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:19199
	doCallback@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:59201
	done@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:59287
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:43855
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:45401
	getDB@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:44131
	getRemoteSet@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:45344
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:43805
	getLocalSet@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:45241
	syncfs@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:43732
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:59438
	forEach@[native code]
	syncfs@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:59363
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:19174
	_emscripten_asm_const_iii@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:30447
	wasm-stub@[wasm code]
	<?>.wasm-function[55240]@[wasm code]
	wasm-stub@[wasm code]
	Hi@[native code]
	https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:308662
	callMain@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:7:316629
	synchronousStart@https://v6p9d9t4.ssl.hwcdn.net/html/2129873/Godot_HTML_Test/Apocalypse%20Now.js:211:23
	apply@[native code]
	promiseReactionJob@[native code]
```

**Comment by drmar** [comment]
@bruvzg 

How did you check locally? I want to try it myself too.

**Comment by bruvzg** [comment]
<img width="310" alt="Screenshot 2020-04-16 at 22 35 36" src="https://user-images.githubusercontent.com/7645683/79498908-c3ce0380-8032-11ea-952e-6cd15196f289.png">

There's "Run in browser" button in the editor (HTML5 export should be configured). It will export project and start local web server and open in default browser (you can copy URL and open it in any browser too, server will be active until stopped by the same button).

**Comment by drmar** [comment]
@bruvzg 

I found out in the meantime how to use Python for a quick local server: python -m http.server (http://localhost:8000)

I can also confirm that locally the exported project has no problem in Safari.

Also, if it helps with the debug, a while back I released my first game ever and it was made with Godot 3.1.2.stable
I posted the game on kongregate.com, among other places.
Here is the link:
https://www.kongregate.com/games/Stone_Age_Jazz/arza-adrenaline-rush-zombie-assault?acomplete=arza

Again, in Firefox, Edge, Chrome and Opera is works perfectly.
In Safari, it doesn't work at all. The error message is: abort(114). Build with -s ASSERTIONS=1 for more info.

**Comment by herrnett** [comment]
I just encountered the same problem with my project (https://shanzhai.itch.io/lonely-year). 

I tracked the source down, however: It's an issue on itch.io's side. I hosted the exact same project on github pages (herrnett.github.io/Lonely-Year) and it runs without any problems.

**Comment by drmar** [comment]
@herrnett 

> It's an issue on itch.io's side.

Are you sure it is itch.io's problem? On other browsers beside Safari the games seem to work just fine.

**Comment by herrnett** [comment]
I can only assume since it works when you "run in browser" using godot and it works when hosted on a github page, so the problem must be caused by how itch (and kongregate) handle the files. You are right, though: Of course this could probably be fixed by making the export more "readable" to them.

**Comment by herrnett** [comment]
True. I just wanted to point it out to narrow down what might be causing it. Also its like the first result when one looks up the error on google and I thought it might help people knowing that there is a kind of workaround for this.

Btw: I just put it up on my own place at http://www.herrnett.de/test/ and it works just fine.
So to sum it up, using Safari 13.0.5: 
- Itch.io wont work ("call_indirect to a null table entry [...]")
- Github Pages works
- "Regular hosting" works

**Comment by Calinou** [comment]
I wonder if this is due to MIME types used to serve the files (or compression, though itch.io doesn't use gzip compression for WASM files).

**Comment by nice-shot** [comment]
Someone wrote about this issue in reddit:
https://www.reddit.com/r/godot/comments/g49alx/issues_when_uploading_on_itchio_html5/

It looks like it's caused by the use of iframe in itch that prevents third-party cookies. Don't know why it causes godot to crash but it can be fixed for a specific iPhone by going to `Settings > Safari` and disabling `Prevent Cross-site Tracking`.
This makes it work in Safari on iOS but not in other browsers like Chrome.

**Comment by dijs** [comment]
I got further with 3.2.2, but still having issues in safari.

![image](https://user-images.githubusercontent.com/1774430/91012396-b3d0bc80-e5ee-11ea-9f21-12e163e59329.png)
