### ISSUE TITLE
GDScript: can't use constants in inner classes

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40857]
**Godot version:** v4.0.dev.custom_build 5ba46ddf8

**OS/device including version:** windows 10

**Issue description:**
**EDIT**
currently the const are behave like vars it could be defined in a local scope, can't use it in an inner classes is this intended ?
the error message : `ERROR: Parse Error: Identifier "C" not declared in the current scope`
```gdscript
const C = 0
class A:
	var c = C ## <--- this line is invalid
```

**Comment by lyuma** [comment]
I believe also the same as issues #40856 and #40825 and fixed in #40824

**Comment by ThakeeNathees** [comment]
@lyuma thanks, the crash fixed and I've completely changed this issue now

**Comment by JestemStefan** [comment]
I added type to const and this code is valid. Maybe it will help fix this issue
![obraz](https://user-images.githubusercontent.com/37214990/129100546-06352d60-94c2-44a9-a55b-4392cedfb3fc.png)

**Comment by lyuma** [comment]
Related issue with enums: #52035

**Comment by briansemrau** [comment]
This same issue seems to be relevant for classes and functions.
Class example:
```gdscript
class A:
	var x = 1

class B:
	var y = A.new()
```
```
Error at (5,13): Identifier "A" not declared in the current scope.
```

Function example:
```gdscript
static func do_thing():  # same issue for static and non-static
	return 1

class A:
	var x = do_thing()
```
```
Error at (5,13): Function "do_thing()" not found in base self.
```

The analyzer does not report issues if you include `self`, (i.e. `self.A.new()`, `self.do_thing()`), but they still fail at runtime.
