### ISSUE TITLE
MultiMesh2D + Line2D or Polygon2D changes color of MultiMesh

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#40901]
**Godot version:**
<img width="586" alt="Screenshot 2020-07-31 at 13 22 09" src="https://user-images.githubusercontent.com/100964/89011840-d7c31a00-d330-11ea-9496-e10e781ede03.png">

**OS/device including version:**
<img width="332" alt="Screenshot 2020-07-31 at 13 22 21" src="https://user-images.githubusercontent.com/100964/89011860-e01b5500-d330-11ea-94b0-bd9e4b69a36a.png">

**Issue description:**
When adding a `MultiMeshInstance2D` after a `Line2D` or `Polygon2D` node, the color of the MultiMesh changes (becoming more faded).

An example repository [can be found here](https://github.com/tavurth/godot-multimesh-bug)

**Actual result**:
<img width="1136" alt="Screenshot 2020-07-31 at 13 24 20" src="https://user-images.githubusercontent.com/100964/89012042-2ec8ef00-d331-11ea-961e-af4b72e015bc.png">

**Expected result**
<img width="1136" alt="Screenshot 2020-07-31 at 13 24 25" src="https://user-images.githubusercontent.com/100964/89012065-3b4d4780-d331-11ea-9547-e998e6061ca3.png">

Expected result can be achieved by changing the order of the nodes (i.e. put the MultiMesh instance before the Line2D)

Expected result can also be achieved by setting "Show Behind Parent" to true, but this does not work in all cases.

Expected result can also be achieved by setting the color to `Color(3, 0, 0, 1)`, although `Color(2, 0, 0, 1)` still leaves the MultiMesh looking dimmed.

Note that the Line2D and Multimesh can be anywhere in the tree (any depth), as long as the MultiMesh is rendered later than the Line2D this effect occurs, causing this to be particularly difficult bug to track down.

**Comment by tavurth** [comment]
After some experimentation it seems like the color of the `Line2D` seems to directly modulate the `MultiMeshInstance2D`. 

To reproduce this drag the color picker for the `Line2D` around. When white, the `MultiMesh` will be coloured normally, but in other cases, such as a bright blue, the `MultiMesh` will be modulated accordingly.

**Comment by tavurth** [comment]
After doing some more testing digging through the Godot sources, it appears that this issue is not present with other kinds of 2D nodes such as Sprites or Meshes, just the multi-mesh.

I was looking [here](https://github.com/godotengine/godot/blob/006bb33b79fe110406a539a919d59e558fea5e1c/drivers/gles2/rasterizer_storage_gles2.cpp#L3041), and [here](https://github.com/godotengine/godot/blob/a5fb4451210625702474a8fac1dd880e78a409e9/servers/rendering/rasterizer_rd/rasterizer_storage_rd.cpp)

However, the likelyhood of this area being the problem is reduced as If `multimesh.set_instance_color` is called during setup, and then another line is moved in behind it afterwards, the problem persists. (The code there is also simple enough that I don't see a bug if there is one)

I would suggest that there's some place we draw the Multimesh, and we forget to reset the modulation at the beginning of the draw loop. However I've not found it yet as I'm unfamiliar with Godot's source.

Probably we could just put a `VisualServer.canvas_set_modulate(get_canvas_item(), Color(1,1,1))` there to fix this issue.

**Comment by clayjohn** [comment]
Great work! It looks like many draw commands start with a line like this (from regular mesh drawing):
https://github.com/godotengine/godot/blob/241e709462cd90d3daade3c6a05ff130fe85b4c0/drivers/gles2/rasterizer_canvas_gles2.cpp#L598-L599

Copying this into the multimesh command should solve this

```
glVertexAttrib4f(RS::ARRAY_COLOR, 1, 1, 1, 1);
glDisableVertexAttribArray(RS::ARRAY_COLOR);
```

**Comment by tavurth** [comment]
> glVertexAttrib4f(RS::ARRAY_COLOR, 1, 1, 1, 1);
> glDisableVertexAttribArray(RS::ARRAY_COLOR);

Thanks for the hint! :) I'll try build it on Godot 3.x (as my sample repo doesn't work yet on 4.x) and get back to you!

**Comment by tavurth** [comment]
Sadly adding the above lines to the start of the render process in the Multimesh switch did not fix the issue:

[commit](https://github.com/tavurth/godot/commit/91f57c47fde28dc85707177a71997d110699da6c?branch=91f57c47fde28dc85707177a71997d110699da6c&diff=unified)

I think it's because a [few lines lower](https://github.com/tavurth/godot/blob/fix/multimesh-color-issue/drivers/gles2/rasterizer_canvas_gles2.cpp#L1467) we specifically enable color vertex attributes based on the users node configuration?

If so, bypassing this would break (I assume) the modulation ability of the Node2D. Any thoughts?

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/47582
