### ISSUE TITLE
Godot 3.2.4 does not actually use separate textures for GLTF files exported with separate textures enabled (they're instead embedded in the materials).

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#44309]
**Godot version:** v3.2.4.beta4.official, affects master as well.

**OS/device including version:** Linux Mint 20 x86_64

**Issue description:**
![image](https://user-images.githubusercontent.com/781121/101961496-21d6d900-3c0a-11eb-82f6-997b0de2be81.png)
When exporting a blender scene to GLTF for use in Godot 3.2.4.beta4, with the export settings shown in the screenshot above, with textures exported into a folder instead of packed into the GLTF itself, Godot is supposed to use those textures in the resulting SpatialMaterial resources after importing.

beta4 currently fails to do this, even with separate textures enabled, it always ends up packing the textures directly into the SpatialMaterial, leaving the textures in the exported folder unused.

This does not happen in 3.2.3, so I'm guessing some regression may have happened at some point.

**Steps to reproduce:**
1. Setup a blender scene in a recent version of blender, 2.8 or 2.9.
2. Make sure textures are used in it. (ofcourse)
3. When exporting to GLTF, make sure to set it so it exports textures separately. (as shown above)
4. After exporting to Godot, right click the resulting SpatialMaterial(s), and click "Edit Dependencies".
5. Notice that there are no dependencies.

**Comment by Calinou** [comment]
cc @fire

**Comment by EzraT** [comment]
I hope this one can get fixed before 3.2.4.stable releases, my workflow relies heavily on this working correctly, since GLTF currently works the best out of all the export options available right now for me.

**Comment by fire** [comment]
Are you able to do a bisect to find the commit that change the behaviour? I have some suspects.

**Comment by EzraT** [comment]
@fire
For what its worth, all of the 3.2.4 betas suffer from this issue, so it has to be a commit from sometime before beta 1.

**Comment by fire** [comment]
https://github.com/godotengine/godot/commit/9529ce41eb4c58a395962ea3cdd61f090717fd54#diff-391b8dac176705a7434fd9ca93ac540183658308fcb6a91cc40f6f2ecd4439baR1384 is suspicious, but I'm currently busy and in the middle of something.

**Comment by EzraT** [comment]
On an extra note, this issue affects the 4.0 master branch as well currently, but I'm guessing this will probably be resolved with the upcoming 3D asset import rework for 4.0.

**Comment by akien-mga** [comment]
Might indeed be related to #42504, I'll have a look. It would help me out if there was a minimal reproduction project that I can use right away to debug the issue.

**Comment by EzraT** [comment]
@akien-mga 
[mrp.zip](https://github.com/godotengine/godot/files/5770620/mrp.zip)

This includes a blender file that you can use for exporting, open it in blender, export it to GLTF using the export settings shown in OP, export it to the import folder in the MRP to reproduce.

**Comment by akien-mga** [comment]
Thanks! I exported as described with Blender 2.91.0, and it seems to work fine for me in Godot 3.2.4 beta 4 and latest `3.2` branch:
![Screenshot_20210105_152232](https://user-images.githubusercontent.com/4701338/103657193-e231b180-4f69-11eb-8e3e-fe22749367ce.png)

Can you still reproduce it, and which Blender version do you use?

**Comment by EzraT** [comment]
Please read the OP carefully, I'm not talking about the material dependencies, this issue concerns the textures that are copied over, they do not get linked to the materials, instead they packed inside of them.

**Comment by akien-mga** [comment]
Thanks, I can confirm that. The `.material` files are indeed 3 MB of embedded data.

**Comment by akien-mga** [comment]
Indeed this change is wrong: https://github.com/godotengine/godot/pull/42504/files#diff-391b8dac176705a7434fd9ca93ac540183658308fcb6a91cc40f6f2ecd4439baR1322-R1338

This causes loading the external images as a byte array instead of a resource if it has a proper `mimeType`, which is wrong.  I'll fix it.

**Comment by EzraT** [comment]
@akien-mga Thanks a bunch!
