### ISSUE TITLE
GDScript 2.0: "Parser bug (please report): Trying to check compatibility of unset value type" error

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#44375]
**Godot version:**
current master 4.0 a511a26ad

**OS/device including version:**
Windows 10

**Issue description:**
E 0:00:00:0827   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:3157 @ is_type_compatible()

**Steps to reproduce:**
I don't know because debugger don't show me where it is in my code.
Empty project don't do that

**Minimal reproduction project:**
n/a

**Comment by Calinou** [comment]
@TotCac Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

We absolutely *need* a minimal reproduction project here. Also, please specify the commit hash of your 4.0 build ("latest `master`" is a moving target).

**Comment by TotCac** [comment]
build a511a26ad

I can't upload my whole project. How can I get more information on the context?

**Comment by Calinou** [comment]
> How can I get more information on the context?

I'm not sure if you can do much more. Maybe setting a breakpoint in the C++ source could help, but I'm not sure.

cc @vnen

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Comment by TotCac** [comment]
I really don't understand why you close it while in code, where the error pop, there is comment like this:
`// TODO: Add safe/unsafe return variable (for variant cases)`

and

`// These return "true" so it doesn't affect users negatively.
	ERR_FAIL_COND_V_MSG(!p_target.is_set(), true, "Parser bug (please report): Trying to check compatibility of unset target type");
	ERR_FAIL_COND_V_MSG(!p_source.is_set(), true, "Parser bug (please report): Trying to check compatibility of unset value type");`

**Comment by Calinou** [comment]
> I really don't understand why you close it while in code, where the error pop, there is comment like this:

We need a minimal reproduction project to be able to diagnose this, unless @vnen is already aware of a solution to this issue somehow.

**Comment by TotCac** [comment]
After days (weeks) of investigating, I find where does error come from.

On 3.2 i use to define a method like this
> func set_object(_object: Object = null) -> void:
> 	if _object:
> 		selected_object = _object
> 		selected_object.map_status = "FLYING"`
> 		(...)

On 4.0 i have the error shown in title
If I remove null assignation as default value for parameter obect, the error is gone

> func set_object(_object: Object) -> void:
> 	if _object:
> 		selected_object = _object
> 		selected_object.map_status = "FLYING"`
> 		(...)

I have no idea if the issus should be close of not.

**Comment by TotCac** [comment]
If I declare
>func get_oxygenflow_direction() -> int:
	var tot = 0
	for dir in oxygen_flow_direction.values():
		tot += dir
	return tot

The error pop too

When I use
>func get_oxygenflow_direction() -> int:
	var tot: int = 0
	for dir in oxygen_flow_direction.values():
		tot += dir
	return tot

Maybe it has something to do with static typing and initialization

**Comment by Gastronok** [comment]
Here's a reasonably minimal project that gets this error on Godot v4.0.dev.calinou.de83ee57e

I'm not really sure what's causing it so I'm just following up with a Please Report. If you run the project and click on it in the error line, it'll point to the line in my project which claims is the source of the problem.

[ParserBug.zip](https://github.com/godotengine/godot/files/6872937/ParserBug.zip)

**Comment by Hannyson** [comment]
I got the same error when I try to create a Thread, it crash when I launch a start()
In the long list of errors in teh debug, I also get this:
E 0:00:01:0543   _ready: Cannot get class 'Thread'.
  <Erreur C++>   Condition "!ti" is true. Returning: nullptr
  <Source C++>   core/object/class_db.cpp:529 @ instantiate()
  <Pile des appels>Camera.gd:140 @ _ready()
E 0:00:01:0543   _ready: Class type: 'Thread' is not instantiable.
  <Erreur C++>   Condition "!o" is true. Returning: Variant()
  <Source C++>   modules/gdscript/gdscript.cpp:76 @ _new()
  <Pile des appels>Camera.gd:140 @ _ready()

**Comment by akien-mga** [comment]
@Calinou I think @Hannyson's bug was a duplicate of #50831 and not this bug, isn't it?

**Comment by Calinou** [comment]
> @Calinou I think @Hannyson's bug was a duplicate of #50831 and not this bug, isn't it? And if so it's fixed already.

Maybe, I don't know for certain.

**Comment by lyuma** [comment]
This issue report is a bit messy, but @Gastronok's repro project works and I can reproduce the parser bug on 85186bc
```
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
```
(even if I add a `0` argument to get_used_cells to fix the script error)

Note that another bug exists with this error: #50313 - I also see this error all the time in my own projects, so it's not super hard to reproduce given complex GDScript.

**Comment by Chaosus** [comment]
The error caused by `var event_string : String = player_identifier + suffix` line of `Player.gd` of the @Gastronok project.

**Comment by Chaosus** [comment]
The simple reproduction script will be:

```
extends Node3D

var a : String = "a"
var b : String = "b"

func _ready():
	var p : PackedStringArray = ["_test"]
	for b in p:
		var t : String = a + b
```

**Comment by Chaosus** [comment]
I don't see it either, I suppose it was fixed by one of the recent @vnen commits. I think it's fine to close it for now (and see if this happens again to re-open).

**Comment by tavurth** [comment]
I just saw this while attempting to convert a 3.x project to 4.x.

The function which caused the error was this:

```gdscript
func add_instance(var some_bool: bool = true):
	var instance = self.create_instance()
	return self.environment_pool.append(instance)
```

Removing the `bool = true` removes the error.

Can we re-open this again?

**Comment by tavurth** [comment]
Unfortunately I've already worked past this point amidst the sea of errors.

**Comment by akien-mga** [comment]
Well if you cannot reproduce the issue, then GDScript contributors wouldn't be able to fix it either.

**Comment by tavurth** [comment]
If I come across it again (which seems likely) I will try to narrow down exactly what's causing it and we can move to a new issue with a reproductive sample. 👍

**Comment by tavurth** [comment]
I finally managed to figure out what was causing this.

SomeSingleton.gd
```gdscript
extends Node

var a = 5;

var my_sub_item = preload("res://something.gd").new()
```

res://something.gd
```gdscript
extends Node

func _ready():
    print(SomeSingleton.a)
```

**Comment by cassandrus** [comment]
Hello! I'm not 100% sure that source of this issue is the same, but here it is:
![image](https://user-images.githubusercontent.com/97176349/180253775-aaad4c01-46e3-4e58-bda0-c2ae34bd2554.png)
I've made mini-project for you:
[game-client_test.zip](https://github.com/godotengine/godot/files/9160621/game-client_test.zip)
Error is in file PlayerAttrs.gd.
If you omit type hint, it works.

Hope this helps!

**Comment by flotos** [comment]
For me this issue is partly resolved by renaming the unparsable class as mentionned in this (duplicate?) ticket : https://github.com/godotengine/godot/issues/63439

But only partly because I then get the error on other classes

**Comment by rblopes** [comment]
Just discovered that issue recently, porting one of my old projects to Godot 4 (beta 1).

Doing my own tests, I've found that the following code:

```gdscript
extends Node2D

var some_var: int = some_func()

func some_func() -> int:
	return 42
```

Reports the following on the console:

```
  modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
```

However, if I declare the variable after the function, no errors are reported.

I've tried a few combinations, declaring the function as `static`, annotating the variable as `@onready` or `@export`, with the same result: errors reported only if the variable appears first in the code.

I hope that helps a little.

**Comment by ShinyDeagle** [comment]
Discovered this issue when porting a new Godot 3.5 project to Godot 4 (beta1)

These were the errors that were being brought up at the time.
`Could not parse global class "GameUnit" from`
`Parse Error: Trying to check compatibility of unset value type`

Deleting .cfg files and filesystem_cache7 files you get when you first port the project worked for me.

This might be an unrelated case, though, as we have different parse errors.

**Comment by BrianMWest** [comment]
I see this issues exactly as described by @rblopes in 4.0-beta2

```
@onready var loaded_save: Dictionary = __default_save()

func __default_save() -> Dictionary:
    return {}
```

causes the problem. Related, it gives me an error if I attempt type inference on the var as `@onready var loaded_save := __default_save()` although the function in question is explicitly annotated with the return type.

```
Parse Error: Cannot infer the type of "loaded_save" variable because the initial value doesn't have a set type.
```

In the meantime, my workaround is to set manually in `_ready()`

```
var loaded_save := {}

func _ready():
    loaded_save = __default_save()

func __default_save() -> Dictionary:
    return {}
```

**Comment by takaturre** [comment]
Here is one very simple minimal reproduction code - the effects are immediate (don't even need to save, just comment/uncomment the lines). 
    
![image](https://user-images.githubusercontent.com/16601926/200760264-1660f3f9-aea3-4701-b931-ddf9cc6107b8.png)

So in words, one way to make trigger the error is by _declaring a class member after declaring a function that uses the member as a default value for an argument_. It's okay to use it inside the function (but not for the arguments). Note also that you'll get the error for any scripts open in the script editor. Accordingly, when you open Godot and you had a script like that open, you'll get errors on start up.

**Comment by dalexeev** [comment]
Please check if this is reproducible in master. Maybe #67714 fixed that too.

**Comment by takaturre** [comment]
Tested that at least the issue reported in the above screenshot still exists in Godot 4.0.beta5. (The error seems to be triggered just like in beta4.)

**Comment by lufog** [comment]
I believe this is fixed in the master. 
Test project: [parser-bug-test.zip](https://github.com/godotengine/godot/files/10046646/parser-bug-test.zip)

In v4.0.beta5.official [89a33d28f]:
`SCRIPT ERROR: Parse Error: Could not preload resource file "res://something.gd".`

In v4.0.beta.custom_build [c2f03533d]:
No errors

**Comment by lostminds** [comment]
I think this might be related to cyclic class references. Before beta6 this didn't compile at all, but after the improvement/fix in 4.0.beta6 ( #67714 ) you can now have these references. Or, at least the game compiles and runs, but I still get this error (same as above) if I set up a simple cyclic class reference. 
```
E 0:00:00:0697   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4141 @ is_type_compatible()
```

The cyclic class reference I tested was a simple one: One node of the class GameBoard has a number of child nodes of the class BoardObject, both classes inherit from Node3D. If I in the script for BoardObject reference the class GameBoard I get the error above when I run the game. If I remove the reference to GameBoard in BoardObject the error goes away.

**Comment by cassandrus** [comment]
Guys, I'm afraid my issue variant was never resolved and still valid even in RC5. I mean this [comment](https://github.com/godotengine/godot/issues/44375#issuecomment-1191637706).

Similar issue with "match" syntax was fixed in #63535, but this one still fails (despite same set of singletons in both my MRP).

**Comment by akien-mga** [comment]
@cassandrus I tested your project, you need to make the script `GameSettings.gd` the autoload, not the PackedScene `GameSettings.tscn`.

**Comment by cassandrus** [comment]
> @cassandrus I tested your project, you need to make the script `GameSettings.gd` the singleton, not the PackedScene `GameSettings.tscn`.

But why? Docs state "You can create an AutoLoad to load **a scene or a script** that inherits from Node". Is it incorrect? No more correct?

**Comment by akien-mga** [comment]
I think it's correct, but maybe not in the context of accessing an enum from that script as type hint. This would warrant a dedicated issue.

**Comment by vnen** [comment]
You can use a scene or script for autoload but GDScript will not look into an autoloaded scene to check its contents, so for GDScript it is only a regular `Node`. Not to say this can't be improved, but it is a different problem.
