### ISSUE TITLE
Vector2 and Vector3 .sign() method does not output zero for components equal to zero

### ISSUE THREAD

**Issue by Onusai** [godotengine/godot#44841]
**Godot version:**
3.2.3

**OS/device including version:**
Windows

**Issue description:**
Using the sign() method on vectors whos components are zero does not output the correct sign.

**Steps to reproduce:**
`print(Vector2.ZERO.sign())`
outputs (1, 1) instead of (0, 0)
The same thing is true for Vector3.
However, the normal GDScript sign() function on floats works properly.

**Comment by 31** [comment]
It looks like the `SGN` macro was recently fixed in `master`: https://github.com/godotengine/godot/pull/43903, which is what `.sign()` uses:

https://github.com/godotengine/godot/blob/adfc646f8cb497d520ea2238482ab674fe90d43a/core/math/vector2.cpp#L101-L104

In `3.2`:

https://github.com/godotengine/godot/blob/adfc646f8cb497d520ea2238482ab674fe90d43a/core/typedefs.h#L120-L122

**Comment by KoBeWi** [comment]
Sounds like 3.2-specific issue. #43903 should be cherry-picked (although it slightly breaks compatibility).

**Comment by aaronfranke** [comment]
#43903 breaks compatibility, so it shouldn't be cherry-picked.

**Comment by KoBeWi** [comment]
Well, fixing this issue would break compatibility, so either we fix it or close it.

**Comment by Lucrecious** [comment]
lol this bug is really small but also very annoying and completely caught me off guard.

#43903 goes in and fixes the `SGN` marco but why not just fix the `Vector2.sign` method itself?
```cpp
 Vector2 Vector2::sign() const { 
 	return Vector2(x > 0 ? 1 : (x < 0 ? -1 : 0), y > 0 ? 1 : (y < 0 ? -1 : 0)); 
 } 
```
Basically this but with nicer code...

Would this break compatibility?

**Comment by aaronfranke** [comment]
@Lucrecious That's identical to the existing behavior in the master branch, and yes it would break compatibility.

I forgot about this, it should be closed, so I'll do so now. It's already fixed in master, but changing this in 3.2 breaks compatibility.

**Comment by Lucrecious** [comment]
@aaronfranke So maybe I misunderstood, but how does `Vector2::sign` returning the correct result break compatibility? Does the engine in 3.2 expect `Vector2.ZERO.sign()` to return `Vector2(1, 1)`?

**Comment by aaronfranke** [comment]
@Lucrecious It breaks compatibility because if a *project* expects that result, it would fail.

**Comment by Lucrecious** [comment]
I still don't get it.

When you say "project" do you mean "user" that expects an incorrect result from `Vector2.sign`? How is fixing a bug "breaking compatibility"? Wouldn't all bugs then be breaking compatibility if users expect the incorrect result?

Just seeking clarity. Thanks

**Comment by aaronfranke** [comment]
@Lucrecious The behavior of this method for the number zero is arbitrary, it can either be treated as positive or no sign, both make sense. The initial implementation treated the sign of zero as positive, so clearly the person who implemented it desired that behavior. It's not a bug or unexpected behavior because the behavior is arbitrary and it makes sense either way, there is no single correct result. In cases where one behavior is obviously wrong and was never intended then yes it's a bug fix because we can't support people who relied on invalid behavior. However, changing a method's behavior from one valid behavior to another valid behavior breaks compatibility so it should not be done in a stable branch.

**Comment by Lucrecious** [comment]
I see that makes sense; I can see why in this case the "math" is arbitrary. I guess this mostly a documentation issue since the behaviour doesn't agree with the documentation and also is not consistent with `sign(value: float)`.
<img width="838" alt="image" src="https://user-images.githubusercontent.com/4584511/110251820-62679980-7f50-11eb-885a-0310554f6e7d.png">

Thanks Aaron!

**Comment by aaronfranke** [comment]
@Lucrecious Thanks for pointing that out! This is actually [my fault](https://github.com/godotengine/godot/pull/40581/files#diff-62c42313c2bd1de216bf7a9aab362b557e3a7e06af35a2ea2690221bcb28a062R277), I accidentally backported documentation that doesn't apply to 3.2.

**Comment by sereyn** [comment]
I noticed the documentation contains "and 0.0 if it's zero" in Godot v4.4

**Comment by KoBeWi** [comment]
That's because it returns 0 if it's 0, which is we the issue was closed.
