### ISSUE TITLE
'The following files are newer on disk' dialog everytime project run

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#45958]
**Godot version:**
Godot_v3.2.4-rc2_mono_win64

**OS/device including version:**
Windows10 x64 Nvidia 1650

**Issue description:**
When running project a dialog appears saying:

please confirm.

The following files are newer on disk. Which action should be taken?

project.godot

Resave Reload Cancel

Here is an image link: https://pasteboard.co/JOb0ik2.png
Project.godot is the file listed (dosen't appear on screenshot for some reason)

This hasn't happened before. It only happens on one mono project. Even RC1 works as expected.

**Steps to reproduce:**
Load project, run

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by rick551a** [comment]
No, i cannot reproduce it on a newly created project. Also,It only appears on one mono project, not others I've tested. :/

**Comment by Calinou** [comment]
This may be a duplicate of https://github.com/godotengine/godot/issues/45965 (fixed by https://github.com/godotengine/godot/pull/45968).

**Comment by rick551a** [comment]
This issue is still present in Godot_v3.2.4-rc3_mono_win64.
Every other project is okay. 

So I decided to delete each part of the project one by one until the error disappeared.
When every file was deleted from the project, I made a new blank main scene and ran it.
A message dialog popped up 

"Alert error while saving".

On the panel below it says:
"Failed to get modified time for: C:/Users/p/Downloads/Godot BetaTesting/BETAPROJECTS3/copiedtestprojRC3/source/Rooms/UI/rmTitle.tscn."

Which is weird as there is no rmTitle.tscn (I deleted everything).

I tried to save & close the project but it said:
"Alert error while saving"
So I closed without saving.

Upon opening, the project worked fine then (no errors).
That is all.

**Comment by rick551a** [comment]
Hmm, found its triggered by calling ProjectSettings.Save();

**Comment by Calinou** [comment]
> Hmm, found its triggered by calling ProjectSettings.Save();

See https://github.com/godotengine/godot/issues/46358.

**Comment by KoBeWi** [comment]
Where are you using `ProjectSettings.Save()`? It should be called only from plugins/editor scripts, otherwise it might be detected as external change.

**Comment by Calinou** [comment]
cc @naithar

**Comment by HEAVYPOLY** [comment]
was able to fix Failed to get modified time for: res://ios/plugins/inappstore/inappstore.release.a.

The problem is that file does not exist in the project, not sure why godot is looking for it.  After copying the inappstore.release.a. file to that location, the error stopped.

I copied from xcframework folder to the location specified in the error. @naithar 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/24432677/114637770-fe3aa280-9c7e-11eb-9639-177d90e444f1.png">

Although I'm not getting the errors anymore, I'm still getting the "project files newer than on disk" project.godot error each time focus leaves godot :(

**Comment by akien-mga** [comment]
> was able to fix Failed to get modified time for: res://ios/plugins/inappstore/inappstore.release.a.
>
> The problem is that file does not exist in the project, not sure why godot is looking for it. After copying the inappstore.release.a. file to that location, the error stopped.

This was fixed by #47853.

---

That was a separate issue to the one in the OP though, so it should really have been tracked in a dedicated issue. (Now it's fixed so no need to.)

As for the original issue, it's hard to debug without knowing more precisely how to reproduce it. @rick551a had it happen only in a specific project calling `ProjectSettings.Save()`, but we don't know more. Is there anything specific about yours? Do you get the same issue in a different project, or only that one?

**Comment by naithar** [comment]
> was able to fix Failed to get modified time for: res://ios/plugins/inappstore/inappstore.release.a.
> 
> The problem is that file does not exist in the project, not sure why godot is looking for it. After copying the inappstore.release.a. file to that location, the error stopped.
> 
> I copied from xcframework folder to the location specified in the error. @naithar
> 

Yeah, it was a bug on my part when I've enabled `xcframework` support for plugins. It should now be fixed, so you wouldn't need this workaround when next RC comes or if you can build editor by yourself.

**Comment by HEAVYPOLY** [comment]
@naithar  Thanks, glad to hear it's fixed!
@akien-mga I am using config.cfg.save() and config.cfg.load(), maybe that's it?

**Comment by akien-mga** [comment]
@HEAVYPOLY Do you still have this issue in 3.3.2?

> Found something!
Exporting the project from command line triggers "the following files are newer on disk"
Exporting from project export menu does not trigger "the following files are newer on disk"

Can you clarify how you export the project from command line exactly, and how the error is displayed?

@rick551a We haven't heard back from you on what usage of `ProjectSettings.Save()` you are making exactly. Can you still reproduce the issue in 3.3.2, and if so, can you provide more information about what you do to trigger the issue (or ideally a reproduction project)?

**Comment by HEAVYPOLY** [comment]
@akien-mga Yes, still happening in 3.x

here is my build script:
```bash
    godot --path $SRC --export "Windows Desktop" $build_path_windows
    cp $build_path_windows $WINDOWS/$HP-unsigned.exe
    rm $build_path_windows
    cp -r $README $WINDOWS/INSTALL_INSTRUCTIONS.txt
    rcedit $WINDOWS/$HP-unsigned.exe --set-file-version ${version} --set-version-string "FileDescription" "HEAVYPAINT" --set-version-string "ProductName" "HEAVYPAINT" --set-version-string "ProductVersion" ${version} --set-version-string "LegalCopyright" "Copyright (c) 2019-2021 Vaughan Ling"

    osslsigncode -sign ...

    # cp $build_path_windows $DROPBOX_BUILDS/HEAVYPAINT.exe
    # cp $pck_path_windows $DROPBOX_BUILDS/HEAVYPAINT.pck

    godot --path $SRC --export "Mac OSX" $build_path_mac
    godot --path $SRC --export "Linux/X11" $build_path_linux
    
    cp -r $README $DESKTOP/INSTALL_INSTRUCTIONS.txt
    zip -j -X $zip_path_windows $build_path_windows $pck_path_windows
    zip -j -X $zip_path_linux $build_path_linux
```

**Comment by KoBeWi** [comment]
Sounds like something that could be caused by #47385
Exporting from command line still opens the editor, so it triggers saving 🤔

**Comment by HEAVYPOLY** [comment]
on this note, is there a way to export from command line without opening the editor?

**Comment by Calinou** [comment]
> On this note, is there a way to export from command line without opening the editor?

You can use a headless binary or pass the `--no-window` command line argument (since Godot 3.3).

**Comment by HEAVYPOLY** [comment]
Awesome, thanks Calinou, added to my build script.  Oddly, even though editor doesn't open, still getting the project.godot newer on disk popup.

**Comment by HEAVYPOLY** [comment]
The other strange thing is after export, the popup continues to show when focus is lost/regained every time until editor is restarted fresh.

**Comment by Calinou** [comment]
> Oddly, even though editor doesn't open on export, still getting the project.godot newer on disk popup.

The headless editor will still attempt to write to `project.godot`, and there's no way to disable this.

**Comment by KoBeWi** [comment]
So the solution would be to disable saving on startup when the editor is headless.

**Comment by Calinou** [comment]
> Or add a new flag, like --no-save.

I don't think this needs a flag, but the editor in general should not attempt to save `project.godot` when nothing has changed.

**Comment by KoBeWi** [comment]
This is already the case. But then users complained that opening a project doesn't make it last modified, so now it's saved once on startup.

I think disabling that autosave in headless editor would be the best solution for this issue.

**Comment by rick551a** [comment]
Sorry about not replying, the issue is non existent for me now. I removed ProjectSettings.Save(), as in my infinite stupidity I assumed it was saving config file stuff for the game (like user settings).
Had no issue since.

**Comment by nathanfranke** [comment]
See https://github.com/godotengine/godot/issues/60997 for a similar issue in Godot 4

**Comment by Chaosus** [comment]
It is still happened even after https://github.com/godotengine/godot/pull/50767 was merged

**Comment by paul-mcnamee** [comment]
In case anyone is searching for this and is new to godot, I had this happen when I was using vscode and the script in the godot editor as well, I didn't realize that I never closed the script in the built in editor 👍

**Comment by Linshiqi** [comment]
I run into this same issue in godot 4.5 and godot 4.6_dev, but I'm only open godot editor for script, it struggles me for about one month, still no luck.

**Comment by Calinou** [comment]
> I run into this same issue in godot 4.5 and godot 4.6_dev, but I'm only open godot editor for script, it struggles me for about one month, still no luck.

Please open a new issue with a minimal reproduction project attached.
