### ISSUE TITLE
Resource values do not update in inspector with remote scene dock

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#47237]
**Godot version:**
3.2.3

**Issue description:**
When values in a resource are changed at runtime, the changes are not reflected in the inspector. This issue is specific to debugging the running project using the inspector.

It appears that the inspector reads and writes the resource file, while the running project uses an in-memory copy.

**Steps to reproduce:**

1. Modify a variable within a resource in the running scene
2. Change the scene dock to Remote
3. Check the value of said variable in the inspector and note that it does not reflect the runtime value

**Minimal reproduction project:**
In this example, player HP is shared between nodes as a resource. The initial value is 10. After the scene loads, the value is set to 9. The issue is that the inspector still shows a value of 10, despite any changes to the value.

![image](https://user-images.githubusercontent.com/1959973/111916067-73c3a200-8a36-11eb-9f6c-e600824b61c3.png)
[ResourceValueDebug.zip](https://github.com/godotengine/godot/files/6178085/ResourceValueDebug.zip)

**Comment by rudidev08** [comment]
Confirmed also an issue in v4.0.beta3.mono.official [01ae26d31]

**Comment by Nikola526** [comment]
Is this being worked on? Resources don't update in the remote inspector unless they are inside a collection of some sort. This is still the case in Godot 4.1.1.

**Comment by Nikola526** [comment]
Is there a reason this issue is so low-priority? I understand most Godot users primarily use it for game jams and simpler projects, but this issue makes it difficult to work on more complex data-oriented games. I constantly find myself making "debug" arrays in order to view and edit resources when the game is running (mentioned in #41442 ). This, combined with the overall unresponsiveness of clicking on runtime resources makes resource-centric workflows quite problematic to work with.

**Comment by Nikola526** [comment]
It seems that a large part of this issue was fixed in 4.3. Fields containing resources now show runtime resources in the remote inspector if created through code. They are only unresponsive if referencing a resource that was dragged in from the file manager. Putting them in arrays does show their runtime counterpart.

**Comment by AThousandShips** [comment]
This isn't low priority, it's just not critical priority, if someone can find a solution to this it would be greatly appreciated

**Comment by Ewall198** [comment]
I'm seeing this same issue in `4.3.stable` where a value in a resource inside a resource will not display the latest value in the inspector.

[dictionary_bug.zip](https://github.com/user-attachments/files/17985056/dictionary_bug.zip)

**Comment by MikeLundahl** [comment]
I just discovered this is still an issue in Godot 4.2.2, is this something that's fixed in a newer version? I would say this is critical for debugging purposes, as it can be very misleading having different values when inspecting a remote instance and printing values.

**Comment by AThousandShips** [comment]
I'd test a newer version, it's at least in 4.3

**Comment by B-B-2** [comment]
Can confirm it's still a bug in the newest 4.5 beta. I posted an issue report before I found this one

[https://github.com/godotengine/godot/issues/110001](https://github.com/godotengine/godot/issues/110001)

**Comment by KoBeWi** [comment]
So I investigated it and it's a bug in remote inspector. When you unfold the Resource, it shows the local copy of Resource in the editor, not in the running project. It's possible to inspect the remote resource via debugger.

**Comment by radioactivejackal1414** [comment]
I'm still reproducing it in 4.7.2 stable.

<img width="1984" height="758" alt="Image" src="https://github.com/user-attachments/assets/51180d27-ff40-4fea-a749-1fce087b8ea4" />
