### ISSUE TITLE
Autocompleted variables are immediately deleted when using the Language Server via CoC on Vim.

### ISSUE THREAD

**Issue by AlbeyAmakiir** [godotengine/godot#47930]
**Godot version:**
v3.2.3.stable.openSUSE

**OS/device including version:**
openSUSE Leap 15.2 (linux)

**Issue description:**
Using the Language Server with Vim and CoC, when using autocompletion, if I select a function name, it works fine, but if I select a variable, the autocomplete enters the selection, then immediately deletes the whole word. If I press `.`, it re-enters the text without deleting it.

**Steps to reproduce:**
vim version: VIM - Vi IMproved 8.0
https://github.com/habamax/vim-godot plugin
coc.nvim version: 0.0.80-2cece2600a
coc-settings.json:
```json
{
  "languageserver": {
    "godot": {
      "host": "127.0.0.1",
      "filetypes": ["gdscript"],
      "port": 6008
    }
  }
}
```
Godot setting for External Editor flags: `gvim --remote "+call cursor({line}, {col})" {file}`
Open the example project attached.
In Godot, open the `.gd` file in the project. It should open in gVim.
In `_ready():` type the start of `test_var` and use autocomplete to finish it. It very briefly appears, and then immediately vanishes.
If you do the same with `test_func()` it works as expected.

**Minimal reproduction project:**
[LSUncomplete.zip](https://github.com/godotengine/godot/files/6320040/LSUncomplete.zip)

**Comment by ventolin** [comment]
I've been running into this, as well. I'm using neovim and have tried `CoC` as well as neovim's built in lsp support with `nvim-compe` (using neovim nightly). I've tried both Godot 3.2.3 and 3.3rc9. I've tried the most minimal configuration, loading only the lsp/completion plugins with no special mappings (due to seeing several reported issues where the suggestion is to remap `<cr>`, none of which worked for me) and it still happens with default settings.

**Comment by ventolin** [comment]
Something else I have noticed is that it doesn't always happen. I just tried auto-completing `CollisionPolygon2D` in an empty file in a brand new Godot project. I tried it about 6 times, and sometimes it worked, while most of the time it deleted the whole thing after completion.

**Comment by julkip** [comment]
I have done some testing with this. It would seem that this goes further than just variables. The autocompletion only works for functions. Neither variables, nor class names, nor keywords like `while` or `onready`, nor literals like `$Sprite` stay after beeing completed.

At first I was a bit unsure if this is really a bug of the language server in Godot. I have looked at the verbose output of coc using `:CocCommand workspace.showOutput` (remember that you have to add `"trace.server": "verbose"` to your coc-config for the godot language server to see everything). I am far from an expert on language servers and the language server protocol is extremely verbose, but I have found the following part, that occurs just as I am trying to complete a class name, `Sprite` in this instance. This is a completely new project and a new, empty .gd-file.

```
[Trace - 15:57:18] Received response 'completionItem/resolve - (2)' in 10ms.
Result: {
    "command": {
        "command": "",
        "title": ""
    },
    "data": {
        "context": null,
        "position": {
            "character": 1,
            "line": 0
        },
        "textDocument": {
            "uri": "file:///home/julkip/temp/lsptests/lsptests.gd"
        }
    },
    "deprecated": false,
    "detail": "",
    "documentation": {
        "kind": "markdown",
        "value": "\t<Native> class Sprite extends Node2D\n\nGeneral-purpose sprite node.\n\n\n\n\n\nA node that displays a 2D texture. The texture displayed can be a region from a larger atlas texture, or a frame from a sprite sheet animation.\n\n"
    },
    "filterText": "",
    "insertText": "",
    "kind": 7,
    "label": "Sprite",
    "preselect": false,
    "sortText": ""
}

[Trace - 15:57:21] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/julkip/temp/lsptests/lsptests.gd",
        "version": 5
    },
    "contentChanges": [
        {
            "text": "Sprite\n"
        }
    ]
}


[Trace - 15:57:21] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "code": -1,
            "message": "Unexpected token: Identifier:Sprite",
            "range": {
                "end": {
                    "character": 6,
                    "line": 0
                },
                "start": {
                    "character": 0,
                    "line": 0
                }
            },
            "severity": 1,
            "source": "gdscript"
        }
    ],
    "uri": "file:///home/julkip/temp/lsptests/lsptests.gd"
}

[Trace - 15:57:21] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/julkip/temp/lsptests/lsptests.gd",
        "version": 6
    },
    "contentChanges": [
        {
            "text": "\n"
        }
    ]
}
```

I read this as:
1. godot ls says: "Please complete with the following parameters: ..."
2. coc says: "The source file changed and now it looks like this: Sprite\n"
3. godot ls says: "Please display the following diagnostic message: ..."
4. coc says: "The source file changed and now it looks like this: \n"

So it looks like coc is deleting the completed text itself.

When I type the word `Sprite` myself the trace looks exactly the same, just the first and last messages are absent. Plus, the diagnostic message is shown as soon as I leave insert-mode.

When I complete a function name, `print` in this instance, the trace looks like this:

```
[Trace - 16:13:54] Received response 'completionItem/resolve - (11)' in 23ms.
Result: {
    "command": {
        "command": "",
        "title": ""
    },
    "data": {
        "context": null,
        "position": {
            "character": 1,
            "line": 0
        },
        "textDocument": {
            "uri": "file:///home/julkip/temp/lsptests/lsptests.gd"
        }
    },
    "deprecated": false,
    "detail": "",
    "documentation": {
        "kind": "markdown",
        "value": ""
    },
    "filterText": "",
    "insertText": "print(",
    "kind": 2,
    "label": "print",
    "preselect": false,
    "sortText": ""
}


[Trace - 16:13:55] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/julkip/temp/lsptests/lsptests.gd",
        "version": 43
    },
    "contentChanges": [
        {
            "text": "print\n"
        }
    ]
}

[Trace - 16:13:55] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "code": -1,
            "message": "Unexpected token: Built-In Func:",
            "range": {
                "end": {
                    "character": 5,
                    "line": 0
                },
                "start": {
                    "character": 0,
                    "line": 0
                }
            },
            "severity": 1,
            "source": "gdscript"
        }
    ],
    "uri": "file:///home/julkip/temp/lsptests/lsptests.gd"
}


[Trace - 16:13:56] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/julkip/temp/lsptests/lsptests.gd",
        "version": 44
    },
    "contentChanges": [
        {
            "text": "print(\n"
        }
    ]
}

[Trace - 16:13:56] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "code": -1,
            "message": "Unexpected token: Built-In Func:",
            "range": {
                "end": {
                    "character": 6,
                    "line": 0
                },
                "start": {
                    "character": 0,
                    "line": 0
                }
            },
            "severity": 1,
            "source": "gdscript"
        }
    ],
    "uri": "file:///home/julkip/temp/lsptests/lsptests.gd"
}
```

The interesting difference here is the first message. In the case of the class name the field `insertText` is empty, but in the case of the function name `insertText` contains `print(`. It would seem that the bug is located somewhere around here.

Just to be sure, I have tried using the old Websocket-based language server from Godot 3.2-stable in combination with the (as of Godot 3.2.2-stable) deprecated coc-godot module (https://github.com/j3d42/coc-godot). This shows exactly the same behaviour, functions work, keywords and so on don't (but this module lacks a verbose logging mode). Additionally I have tried using coc with another TCP based language server, solargraph for ruby. I have tried using the coc-solargraph module as well as the generic socket based language server module that is also used for godot. Here every completion works just fine so that I can conclude that it is not a problem of coc's implementation of TCP based language servers.

**Comment by TobiasDev** [comment]
Is this an issue on Godot's side or on COC's side? If anyone here actually happens to know. Just wondering since right now the bug is on the Godot repo, but if it would be a COC bug, it should probably be moved there. :)

**Comment by AlbeyAmakiir** [comment]
I've since switched to YCM and the problem is not present, so it would seem to be a COC bug, but since the large comment above says COC works on other language servers, it seems more complex that that. Perhaps the way Godot is handling this is running into a subtle difference between YCM and COC? I'm inclined to believe it's on Godot's end, but that it will be hard to spot.

**Comment by julkip** [comment]
I have switched from COC to nvim-lsp a few months ago and there the problem is also not present. I would suspect that this is probably a bug in the way the language server is implemented. Maybe somewhere the specification leaves some leeway and COC interprets the leeway Godot is taking differently from YCM or nvim-lsp, however this is 100% unfounded speculation.

**Comment by TobiasDev** [comment]
> I have switched from COC to nvim-lspconfig a few months ago and there the problem is also not present. I would suspect that this is probably a bug in the way the language server is implemented. Maybe somewhere the specification leaves some leeway and COC interprets the leeway Godot is taking differently from YCM or nvim-lsp, however this is 100% unfounded speculation.

How did you get Godot to work with NVIM-lsp? I tried that over and over again but without any luck. :( If you don't mind me asking.

**Comment by jacekjarosz55** [comment]
> > I have switched from COC to nvim-lspconfig a few months ago and there the problem is also not present. I would suspect that this is probably a bug in the way the language server is implemented. Maybe somewhere the specification leaves some leeway and COC interprets the leeway Godot is taking differently from YCM or nvim-lsp, however this is 100% unfounded speculation.
> 
> How did you get Godot to work with NVIM-lsp? I tried that over and over again but without any luck. :( If you don't mind me asking.
with nvim-lspconfig
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#gdscript

**Comment by lygamac** [comment]
It seems that it is fixed in the [latest master branch of coc](https://github.com/neoclide/coc.nvim/issues/3548#issuecomment-1010432777).

> It has `InsertText` as empty string.

**Comment by theRemix** [comment]
Autocompletion gets deleted when using lsp and nvim-cmp too.

```vim
'neovim/nvim-lspconfig'
'hrsh7th/nvim-cmp'
'hrsh7th/cmp-nvim-lsp'
'hrsh7th/cmp-vsnip'
'hrsh7th/vim-vsnip'
```

It looks like the popup dialog is what is causing the word to get deleted.

https://user-images.githubusercontent.com/132562/152545002-4e47fbf1-6c73-45ec-80c3-c8ca32354906.mp4

When pressing `<cr>` to select the first suggestion, autocomplete works because there was no popup.

When pressing `<tab>` to cycle which suggestion to select, pressing `<cr>` quickly works because there was no popup.

When pressing `<tab>` to choose a suggestion, the popup appears, and pressing `<cr>` **deletes** the completed word.

Completion does work even if the popup is shown only when the completion comes after a `.` property/method.

**Comment by Cris-lml007** [comment]
> Autocompletion gets deleted when using lsp and nvim-cmp too.
> 
> ```viml
> 'neovim/nvim-lspconfig'
> 'hrsh7th/nvim-cmp'
> 'hrsh7th/cmp-nvim-lsp'
> 'hrsh7th/cmp-vsnip'
> 'hrsh7th/vim-vsnip'
> ```
> 
> It looks like the popup dialog is what is causing the word to get deleted.
> 
>  lsp.nvim-cmp.2022-02-04.at.6.10.20.AM.mp4 
> When pressing `<cr>` to select the first suggestion, autocomplete works because there was no popup.
> 
> When pressing `<tab>` to cycle which suggestion to select, pressing `<cr>` quickly works because there was no popup.
> 
> When pressing `<tab>` to choose a suggestion, the popup appears, and pressing `<cr>` **deletes** the completed word.
> 
> Completion does work even if the popup is shown only when the completion comes after a `.` property/method.

how can I disable floating documentation in coc?

**Comment by mphe** [comment]
This issue is still present in current versions of Coc and Godot.
I'm using a custom Godot build with c07d1d0de8594130bdc2feac846c01c84c1b368a reverted, as it fixes the issue, but it would be nice to have an upstream fix.
I'm not sure if this is a Godot or CoC bug.

**Comment by HolonProduction** [comment]
@mphe is it occurring in 4.x or 3.x?

**Comment by melewald** [comment]
Both

**Comment by mphe** [comment]
Both

**Comment by HolonProduction** [comment]
I'm asking because I'm pretty sure we always set the insert text nowadays. So either the original trace is outdated, or something in our LSP server is discarding it for some reason.

**Comment by mphe** [comment]
Last time I checked was 4.2 and the issue was still present there.
I just checked 4.3 and I can't reproduce it anymore. So maybe there has been a fix in the meanwhile or the bug only triggers in certain situations.
I'll keep using the default Godot build and report back when I start encountering it again.

**Comment by HolonProduction** [comment]
If you are able to reproduce please open a new issue with up to date information on versions used, and maybe also a new LSP trace. The original issue with the empty insertText shouldn't happen on our side (haven't checked) and even if it is, it was also fixed on the coc side. So something else has to be going wrong.

**Comment by HolonProduction** [comment]
So based on the current version of the spec sending empty strings is now a problem (it wasn't in the previous version) so the fix on coc side might have been removed by now.

We still send an empty insert text when completion options from the "smart resolve" LSP feature are used (it can be disabled in the editor settings). 

Could you check whether it occurs in one of the cases mentioned in https://github.com/godotengine/godot/issues/69912 (those cases would trigger smart resolve right now). 

#96684 removes "smart" resolve for completion
#96725 prevents empty strings from being sent to the client

I hope that either combination of those PR's fixes this so a consistent way to reproduce would be great.

**Comment by mphe** [comment]
I checked the methods suggested in #69912 and indeed this reproduces the bug.
Then I tested the mentioned PRs independently and they both seem to fix the issue.

Thanks for looking into this! Much appreciated!
