### ISSUE TITLE
SkeletonIK works incorrectly in Godot 3.3

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#48078]
**Godot version:**
3.3

**OS/device including version:**
Win10, PC, GLES3, Nvidia Geforce RTX2070

**Issue description:**
I opened my 3.2.3 project in 3.3 and noticed that the SkeletonIK node behaves erratically.
I had its target set to copy the camera's rotation so that the player's torso moves with the camera, which works perfectly fine in 3.2.3, but in 3.3 the SkeletonIK seems to be ignoring its target and instead looking in erratic directions (it's impossible to find the pattern here).

**Steps to reproduce:**
Open attached tscn in Godot 3.3. Play IK on spine_ik (the SkeletonIK node under camera root). Move the target node on z axis (positive z) and watch the root bone twist around.

**Minimal reproduction project:**
[Player.zip](https://github.com/godotengine/godot/files/6366186/Player.zip)

**Comment by yaelatletl** [comment]
Can confirm, the previously working IK setup is now twisted

**Comment by macryc** [comment]
Yes, something got messed up around RC5. Suggest returning to the RC4 commit for SkeletonIK - I believe it worked fine until RC5. Heard it also works OK in 4.0 which apparently is using the previous code for SkeletonIK (haven't tried 4.0).

**Comment by smix8** [comment]
Can't reproduce your issue with my test Skeletons as all bones rotate as expected for me in Godot 3.3.

This issue needs a reproduction project with your Skeleton setup.

From your description I expect the bug fixes in #47738 for root bone rotation and solver update to be the issue for your skeleton setup no longer working as before.

**Comment by akien-mga** [comment]
CC @TwistedTwigleg @AndreaCatania

**Comment by macryc** [comment]
> Can't reproduce your issue with my test Skeletons as all bones rotate as expected for me in Godot 3.3.
> 
> This issue needs a reproduction project with your Skeleton setup.
> 
> From your description I expect the bug fixes in #47738 for root bone rotation and solver update to be the issue for your skeleton setup no longer working as before.

The project is huge and messy - it would be difficult to extract just the minimum reproduction component. But I've recorded this bug, take a look (maybe that gives you a hint?):
https://www.youtube.com/watch?v=titXIneUxIc

**Comment by brakhane** [comment]
> The project is huge and messy - it would be difficult to extract just the minimum reproduction component. But I've recorded this bug, take a look (maybe that gives you a hint?):
> https://www.youtube.com/watch?v=titXIneUxIc

If you cannot create a minimal working example, could you make your project downloadable, at least for devs who want to try to debug this?

While a video is good, nothing beats a (non-)working example, because using that a develop can find the exact commit that broke it (instead of say "it broke between RC4 and RC5" you can see that commit abcdef broke it) and it can also confirm that the fix actually works.

**Comment by smix8** [comment]
@macryc
I don't need your entire project. Just your skeleton resource (any maybe skinned mesh for visuals) and your SkeletonIK setup saved in a packedscene should be enough to debug this.

**Comment by TwistedTwigleg** [comment]
Out of curiosity, is it only the bone twist that is the issue? Prior to #47738 the root/first bone wouldn’t rotate itself correctly. If all the rotation, not just the twist, is incorrect then #47738 may have not fixed the issue in this case.

**Comment by macryc** [comment]
It looks like the bone is twisting. Overall the posture seems correct - it works the same way it did in 3.2.3. It's the root bode (the 1st spine bone, in this case) that is rotating incorrectly. The tip and the bone in the middle seem to be working fine, otherwise the character wouldn't be looking at the target mark (I'm referring to the video).

**Comment by macryc** [comment]
> @macryc
> I don't need your entire project. Just your skeleton resource (maybe character skinned base mesh for visuals) and your SkeletonIK setup saved in a packedscene should be enough to debug this.
> 
> The visuals in the video only tells me that one or more of your bones in the bone chain are oriented in opposite directions of your target node. Since the tip bone is copying the transform rotation of your target node it gets flipped and twists invert.
> 
> You could test this by placing a rotated child Spatial under your camera node and use it as the IK chain target node.



> @macryc
> I don't need your entire project. Just your skeleton resource (maybe character skinned base mesh for visuals) and your SkeletonIK setup saved in a packedscene should be enough to debug this.
> 
> The visuals in the video only tells me that one or more of your bones in the bone chain are oriented in opposite directions of your target node. Since the tip bone is copying the transform rotation of your target node it gets flipped and twists invert.
> 
> You could test this by placing a rotated child Spatial under your camera node and use it as the IK chain target node.

Here is the player scene with the rig and SkeletonIK (and a bunch of other mess). Spine_IK_looker is the target for SkeletonIK. It it has a child of spine_IK_target - I used that to see if I can rotate it and maybe fix the issue that way but it didn't work...
[Player.zip](https://github.com/godotengine/godot/files/6360618/Player.zip)

**Comment by smix8** [comment]
I managed to get your Player.zip working (was broken on load) and removed dependencies and everything that is unnecessary for this issue.

here is a new MRP for debug
[Player.zip](https://github.com/godotengine/godot/files/6368244/Player.zip)


Your skeleton has an inverted spine bone rest pose but this alone is not the problem. Your inverted bone gets twisted when SkeletonIK kicks in and rotates the bone to -180 degree. I think the problem is that parts of the SkeletonIK source are made with Euler rotations while in a sane world we could use Quat's to prevent such rotation errors.

**Comment by TwistedTwigleg** [comment]
> ... I think the problem is that parts of the SkeletonIK source are made with Euler rotations while in a sane world we could use Quat's to prevent such rotation errors.

I’m not sure Euler angle use is the direct problem. Whether you are using Euler or Quat, the rotation of a bone to a target position has infinite possibilities, so you’d have to resolve using some method. *How* you resolve that rotation is where it makes a bit of a difference, but more from an implementation perspective than an end result.
(Unless you are interpolating, then yeah, Quat rotation is MUCH better 🙂)

My hunch is that the issue is caused by using look_at to generate the Basis for rotation, and the calculation there is leading to -180 degrees of twist rotation rather than reaching the same point using swing rotation. I wrote the code to use look_at for the root bone because otherwise the BoneAttachment3D node wouldn’t work when assigned to the root bone.

That said, I have a hunch on how to revert the code so the root bone is rotated like the other bones while also having BoneAttachment3D nodes working, I just haven’t had the time to try it. I think that executing the IK code after `_process` will fix the issue with BoneAttachment3D nodes while still using the old code, but the code in SkeletonIK will need some minor adjusting to get there. I plan to look at it soon, probably this weekend assuming nothing unexpected happens with my schedule.

**Comment by macryc** [comment]
> I managed to get your Player.zip working (was broken on load) and removed dependencies and everything that is unnecessary for this issue.
> 
> here is a new MRP for debug
> [Player.zip](https://github.com/godotengine/godot/files/6368244/Player.zip)
> 
> Your skeleton has an inverted spine bone rest pose but this alone is not the problem. Your inverted bone gets twisted when SkeletonIK kicks in and rotates the bone to -180 degree. I think the problem is that parts of the SkeletonIK source are made with Euler rotations while in a sane world we could use Quat's to prevent such rotation errors.

Thanks mate. Yea, I just posted the player resource on its own - should have mentioned there's bound to be tons of dependencies to ignore/remove. This is a Mixamo skeleton. I did think that there may be some issues with the original rest pose of the spine bone but it looked fine in Blender (perhaps something to do with the importer). Anyway, like you said, that isn't the issue. I'm curious to see what you find. Thanks for looking at it.

**Comment by Naurk** [comment]
Hi everyone, I have the same issue with a Mixamo skeleton. Here is the minimal project: https://github.com/Naurk/TP-Minimal-Controller

Just apply a SkeletonIK and you will see the twisted root bone, this didn't happen in 3.2.3 and previous. Sorry if I'm redundant, probably it depends on orientation issues, but do you know how can be solved (preferably directly in Godot)?

**Comment by macryc** [comment]
> Hi everyone, I have the same issue with a Mixamo skeleton. Here is the minimal project: https://github.com/Naurk/TP-Minimal-Controller
> 
> Just apply a SkeletonIK and you will see the twisted root bone, this didn't happen in 3.2.3 and previous. Sorry if I'm redundant, probably it depends on orientation issues, but do you know how can be solved (preferably directly in Godot)?

TwistedTwigleg has already fixed it. There is a request to pull the fix into the next release (3.3.1., I believe). Just need to wait a bit.

**Comment by Zireael07** [comment]
The PR @macryc mentioned is this one: https://github.com/godotengine/godot/pull/48166

**Comment by okay300** [comment]
**Apart from turning, there's a problem with scaling the bone.**   **Godot version: v3.2.3 / 3.3**

It was the №2 problem in my report, but the topic was closed.
https://github.com/godotengine/godot/issues/48358
![Scale________1](https://user-images.githubusercontent.com/75214342/116814716-ba4b0700-ab73-11eb-8a33-10e1214f3373.png)

**Godot and blender file.**
[Ik_test.zip](https://github.com/godotengine/godot/files/6411438/Ik_test.zip)

**Comment by TwistedTwigleg** [comment]
@okay300 - are you scaling the bone, the Skeleton, or the SkeletonIK node? Also, was this issue occurring prior to Godot 3.2.3?

**Comment by okay300** [comment]
The defect appears if you use SkeletonIK along with zoom animation.   I zoom in through the animation of Bone 1. 

![Scale__](https://user-images.githubusercontent.com/75214342/116821676-40774580-ab94-11eb-80c8-4ccd8666bad7.png)

**Godot and blender file:** [Ik_test.zip](https://github.com/godotengine/godot/files/6411932/Ik_test.zip)

**Comment by okay300** [comment]
Can I recreate a theme that touches bone scaling?

**Comment by TwistedTwigleg** [comment]
@okay300 - thank you for the clarification on the issue and additional pictures! Sorry I didn't get back sooner, things have been busy on my end. 

Can you test the artifact Godot editor builds [here](https://github.com/godotengine/godot/runs/2486991399) (Windows link) to see if they fix the scaling issue? The PR still has an issue with interpolation that I need to fix (planning to try and tackle it this weekend). You can find the build by clicking the "Artifacts" button in the top right corner of the screen and then downloading the editor.
In my testing the issue was fixed in that build, but if you can still reproduce it, then it is probably a separate issue, in which case we can reopen the issue you made previously and/or make a new issue.

**Comment by okay300** [comment]
Now animation does not zoom bone 1 heirs.
Testing in **fixed version -** [Fixes the SkeletonIK](https://github.com/godotengine/godot/runs/2486991399) 
![Scale__2_1](https://user-images.githubusercontent.com/75214342/117383658-b237f200-aefa-11eb-84a7-14c8e9e730d6.png)
**if you scale in a godo, scaling works.**

[godo and blender project.zip](https://github.com/godotengine/godot/files/6438387/godo.and.blender.project.zip)

**Comment by akien-mga** [comment]
I tested the above project in the latest version of #48251 (updated yesterday) and I can confirm that there still appears to be an issue with the scaling animation when IK is playing.

**Comment by TwistedTwigleg** [comment]
Sounds like the scaling problem is a separate issue then. I'd suggest we reopen #48358 and close this issue since #48251 fixes the OP problem.
