### ISSUE TITLE
Error when Playing .ogv Video

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4878]
**Operating system or device - Godot version:**
Godot_v2.0.3_stable_win64.exe

**Issue description** (what happened, and what was expected):
When importing a `ogv` video file, and then previewing, an unexpected error returns and freezes the app, with this error:

![image](https://cloud.githubusercontent.com/assets/10387670/15634662/54fc1194-257e-11e6-9c83-741948c60666.png)

**Steps to reproduce:**
 - Add Video Player Node
 - Load attached video file to Video Player Node
 - Play Scene

**Link to minimal example project** (optional but very welcome):
[ogv bug.zip](https://github.com/godotengine/godot/files/288424/ogv.bug.zip)

**Edit:** Just tested it with an .ogm file too, same result

**Comment by vnen** [comment]
@Dillybob92 is this error the same as #5133? Specifically: does it only gives error when the video has no sound?

**Comment by Dillybob92** [comment]
@Vnen, Wow, it does work with sound, weird. I added a simple fake audio track to the video

**Comment by vnen** [comment]
I'm closing this in favor of the other then.

**Comment by Dillybob92** [comment]
That's not fair though, I made my issue first

**Comment by vnen** [comment]
The new issue had more specific information on how to reproduce the bug. Also, newer issues tend to get more attention because of GitHub's interface. This is not a competition of who found the bug first and it does not matter if the fix come from that issue or from this one, as long as it's fixed.

**Comment by Dillybob92** [comment]
> This is not a competition of who found the bug first and it does not matter if the fix come from that issue or from this one

Ofcourse it's not a competition I agree with you. But there's a fine line of respect towards someone who is willing to spend time to report bugs, and even supply an example code (as an attachment). It's not fair to just close someones bug report issue because someone else reported the same issue, it's a duplicate issue.

**Comment by akien-mga** [comment]
That's for you to decide, but we have more than 1000 issues to manage and we can't keep duplicates around just to satisfy the ego of bug reporters. Reporting bugs is a harsh and unrewarding job, but fixing them is even worse. We need to go for the most efficient way to ensure that each bug gets the proper attention from the people who can fix it.

I don't think there's a kind of intellectual property on bug reports that would imply that it's necessary to always go back to the first time the bug was reported. The other bug report was better diagnosed and is thus better to keep as the main bug report to ensure the issue is fixed in a timely manner.

I'm sorry that you find it all disrespectful, but the way we work will not change, bug triage is done this way all over the world. The most helpful bug report gets kept, the others get closed as duplicates of the former.

**Comment by Dillybob92** [comment]
There is no ego here... I am reporting the bug issues to help the engine, not for myself. I just found it hypocritical that @vnen says it's not a "competition", but when it is. You just said it was. (If a bug report is better reported -- it's kept) -- That implies some type of competition. Whoever "reports" the bug report the best, gets their issue kept.

That's not okay. And  that's what bothered me. It shouldn't be like that. Because I have seen countless bug report issues being marked "duplicated #xxx" and closed. But why wasn't mine? I supplied the same amount of information as the other report did.  Even more, since I supplied example code.

**Comment by SuperUserNameMan** [comment]
You say there is no "ego here", but who is feeling hurt by what you describe as an injustice ?

anyway, your issue is still referenced into the other one, and you're still welcome to go there to add complementary information or to say that a "better" or "alternate" example is available into the issue you opened.

**Comment by akien-mga** [comment]
Alright, let's play the "competition" game:
- Your issue is titled "Error when Playing .ogv Video", the other one is titled "VideoPlayer throws error when it loads video without sound". The other issue is much more descriptive: it mentions the node that exhibits the error, and already has a diagnostic of the issue regarding the fact that it's sound-related. This is capital information. It's not required of a bug reporter to find that by themselves/know about it, but when this information is available, it's a huge plus for developers that can locate the relevant code directly.
- You provide an example project, and the other issue doesn't. That's a big plus for your issue, so I'll link your example project there as we chose to keep the other one.
- All in all, I might have kept your issue personally, closed the other one as duplicate and edited the title of your issue to be more specific, but at the end of the day, it's a personal choice of the bug triager and **it doesn't matter**. What matters is that the bug (regardless of its reporter or the way it was described) gets enough attention from developers and gets fixed. reduz has already commented on the other bug, so it looks like @vnen's triage worked.

So, both issues had good elements, two issues are not useful, one of them was closed. We usualyl keep the oldest one, unless a more recent one has more precise information or more extensive discussion, which @vnen considered the case here. And I fully backup this choice :)

**Comment by Dillybob92** [comment]
Alright that's fair enough... I just felt thrown under the bus that's all.   I am more "attached" to the bug reports as most people that's all. I take an opposite approach when bug reporting. I do feel "rewarded" when my bug reports are fixed or assigned.  Some people don't, and that's fine, but personally, that's just how I am. Appreciate the post akien and I have no hard feelings towards you or anyone else. Lets just move on and sorry for this.

**Comment by akien-mga** [comment]
I understand. I do report bugs in many projects and I know that it might be harsh when your bug is closed as a duplicate, especially when you spent time filing the report following the guidelines, with a screenshot and an example project.

You should just not feel that your report being closed as a duplicate means that it's "discarded", we see it more as a way to merge two similar issues into one, to be able to focus on one ticket for each development task. When closing a report as a duplicate, I usually try to ensure that all the relevant information from the bug report being closed is also present in the kept one, to maximise efficiency.
