### ISSUE TITLE
Vulkan: Clip Children has wrong blend mode and a rendering issue

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godotengine/godot#49198]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:** Master branch, b63f9b5

**OS/device including version:** Linux, 1050Ti (w/proprietary drivers). I also had someone who said they have an RX 580 confirm. Vulkan.

**Issue description:** I *expect* this feature to work like the clip content option that nodes in the Control family have, where visuals outside of the parent disappear. And that is all that should happen (at least by default).

Clip children causes blending that shouldn't happen (pure white is rendered as *seemingly* transparent, other colors mix with the parent). 

The opaque parts of the parent that aren't covered by children are darkened (except for pure white, which it turned into transparent due to the blending). 

There is also a rendering error where already-rendered stuff (the buffer?) is repeated. This will cause the seemingly-transparent parts to actually render the background (or any other details) over other content (rather than simply showing what is behind it).

**Steps to reproduce:** Have a visual node (label, sprite, polygon) with another visual child node, enable clip children in the inspector (canvas item>visibility>clip children). For the rendering issue, see notes at the bottom (but in general, you need other visual things to see it).

**Minimal reproduction project:** [clip_children_rendering_issues.zip](https://github.com/godotengine/godot/files/6565404/clip_children_rendering_issues.zip)

**Demonstration of project**: 
Left is unclipped.
The icon.png in the label, the 2nd icon.png on the right (and the matching triangle) are the rendering issue.
![clip_children_rendering_issues](https://user-images.githubusercontent.com/4397725/120086479-556cc900-c0ad-11eb-9356-93de2853904f.png)

--------------------------

Other notes:

- the rendering issue depends on the draw-order of the scene tree
- it also depends on the view itself, even editor pan and zoom
- a parent with clipped children enabled but no children will have incredibly odd rendering
- the clipped pieces can in certain instances show on other parents that clip. For instance when zooming in close: 
![clipped_showing](https://user-images.githubusercontent.com/4397725/120086630-74b82600-c0ae-11eb-9799-354fd3893c90.png)

------------------

A checklist with more technical/shortened descriptions:

- [ ] Backbuffer ghosting and seemingly related dark overlay on parent (note: either 1 line fix OR issue pointed out? see my comment that mentions line 1382 EDIT: I've tested with an FXAA screen shader and it seems to screw up the backbuffer with the line edit, so it's likely not the proper fix...)
- [ ] Parent node, in areas not covered by clipped child, renders white as transparent (same note as above)
- [ ] Child nodes have ugly color blend and have brightness turn to alpha (full white, fully transparent) rather than keeping their unclipped appearance (seems to be caused by multiply mode)
- [ ] Enabling clipping for nodes that have no visible children causes rendering issues, seemingly an unhandled condition.
- [ ] In some cases (like the item above), areas erased from clipping can render onto other nodes that have clipping enabled
- [ ] Recursive clipping renders in the wrong order (grandchild renders behind its parent, properly clipped by grandparent but not parent. Changing z-index only breaks clipping further)
- [ ]  Clipping does not work with the Vulkan Mobile renderer (instead it glitches, likely because it's an unhandled status)

**Comment by HaSa1002** [comment]
Confirmed with AMD RX 580. (We had a discussion on the dev chat).
Here is a [MRP](https://github.com/godotengine/godot/files/6565434/49198.Clip.Children.zip)

<details>
<summary>Research details</summary>

Conversion started [here](https://chat.godotengine.org/channel/devel?msg=xujf3pA2zrTdKR8uh).
Thread is [here](https://chat.godotengine.org/channel/devel/thread/sQiwuimkrNnFsyhr5)

Some more evidence:
![grafik](https://user-images.githubusercontent.com/14185889/120086924-ae575400-c0e3-11eb-8557-c988324f5575.png)


</details>

**Comment by insomniacUNDERSCORElemon** [comment]
Just some extra pictures to show stuff more.

No extra visuals to cause the rendering error, just showing how colors blend, 4 colors (same nodes, screenshots combined):
![clip_just_4colors](https://user-images.githubusercontent.com/4397725/120123797-fbd4cf00-c17e-11eb-9c44-809bd992e3cd.png)




All visuals from my MRP scene, but a gray polygon with no children. The top red triangle is a clipped child from the label (like shown in the issue itself, but at any zoom), the rest is similar to the buffer seen with normal clipping but with added rendering artifacts that changes as you pan/zoom:
![nochildren](https://user-images.githubusercontent.com/4397725/120123256-cd092980-c17b-11eb-80bd-8616562cdd70.png)

------------------------

As a side-note: if the problems shown here were fixed this could be a useful tool for polygonal art. Specifically because it sidesteps some of the issues encountered when working with internal vertices/polygons, vertex colors, and the lack of hard-edge colors (without faking it with additional vertices to create a buffer zone).

Although adding more options might make this even more useful. Possibly even changing this feature to clip_mode with the options of options none (default), clip_children, clipped_by_parent (allowing individual clipped nodes w/o it used by parent), and unclippable (allowing individual unclipped nodes w/a parent that clips). Assuming that it makes sense to structure it that way.

**Comment by insomniacUNDERSCORElemon** [comment]
Small update: I've discovered a fix for the ghosting by changing [line 1366](https://github.com/godotengine/godot/blob/8ab9b397070174aab7b20cdcd97506db25fb919d/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp#L1366) here to:
 `storage->render_target_clear_back_buffer(p_to_render_target, group_rect, Color(1, 1, 1, 1));`. This also fixes the parent having its brightness/saturation controlling opacity. I'm not sure if that's the proper fix or not, their might be an issue with the default-used method (unless I'm missing something w/how it's used).

There is still the issue of clipped elements using brightness/saturation (see left icon unclipped vs middle icon clipped) that way (/other blending). My previous screenshots did not make it clear how bad blending on differing colors can look (red will render blue as black).
![fixed_with_blend_issues](https://user-images.githubusercontent.com/4397725/120572684-63db1d80-c3ea-11eb-9993-42b43da4aa1b.png)

If blending can be fixed, there are still a few technical issues. One is related to nested clipping rendering in the wrong order that can be fixed by the user via changing the z index of said child.

**Comment by golddotasksquestions** [comment]
Still present in the latest dev build: v4.0.dev.20211210.official [21b8199]

**Comment by SilencedPerson** [comment]
Still present in alpha 1.

**Comment by golddotasksquestions** [comment]
Still present in alpha3:
![clip_children_alpha3](https://user-images.githubusercontent.com/47016402/155632511-68665d90-c7f1-42d8-b82e-cd1f8f134073.gif)

**Comment by insomniacUNDERSCORElemon** [comment]
I just made the connection that clipping in its current implementation (with improper fix, as explained above) seems to use multiply blend mode. That's the ugly color mixing and brightness turns to alpha, though it does not carry the transparency-changing nature of multiply (though you can add that back via another multiply material).

Though I don't know if it's caused by my improper edit or just how clipping works, if/how it can be fixed etc.

**Comment by golddotasksquestions** [comment]
Issue still present in Alpha7:
![image](https://user-images.githubusercontent.com/47016402/165784317-aa8edb3d-f195-456f-bacb-5971f338ac30.png)

**Comment by 2877242250** [comment]
Tested and still present in Alpha8:
![image](https://user-images.githubusercontent.com/22912744/170814805-3b2ae9c7-3e1f-4251-83c2-fc9175274547.png)

**Comment by dmaz** [comment]
is this fixed or is there just a misunderstanding on how "clip children" should work?   there is no real documentation for the feature but it works as I would expect if you think of the parent as a mask.
![image](https://user-images.githubusercontent.com/203130/175928429-67ae2264-cc5d-4c28-ad54-9b72639e5354.png)
![image](https://user-images.githubusercontent.com/203130/175928491-6f312d7c-6949-43bd-aaf1-6be6290d756e.png)
![image](https://user-images.githubusercontent.com/203130/175928532-e8f2ca7d-e726-4a5c-a6e0-d70fea39bce1.png)

**Comment by golddotasksquestions** [comment]
@dmaz No it does still not work both Alpha9 and Alpha10 still have the same issue. The issue is the blend mode. It is multiplying when it should be mixing. You tested with a white gradient, which will look like it's working because multiply white == 1.0. If you multiply with 1.0 you get the same result. 

Try a texture with pixels which are not white. The icon.png is suitable.

**Comment by golddotasksquestions** [comment]
Since the property is name "clip children", I would expect it to work like Control node "clip children and the the VisualServer canvas_item_set_clip()

**Comment by TackerTacker** [comment]
@dmaz you can also see how it is suppose to work in [this blog post](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40 )
Scroll down until you see CanvasGroup and 2D Masking / Clipping

**Comment by insomniacUNDERSCORElemon** [comment]
@dmaz I can't give insight to implementation but you do see the backbuffer ghosting right? It is easy to miss if you don't have a populated scene (I even made that mistake once).

As for intention, personally I think that the current method of changing how the original parent node displays is suited for a very niche situation (and clunky for more general use), and would be better accomplished some other way (particularly that gives choice to what color, if any, is re-interpreted). I would assume that in its current state people will end up needing to duplicate their parent node (maybe even 2 textures if using them) to ensure the colors work as expected. Also multiply (while also clunky) when added to the clipped tree gives at least the negative areas of the same niche effect.

On the other hand, clipping in a way that is true to the name (original parent node is not changed, child nodes have the intended color) allows for so much general use without duplication. Fully in-engine art/composition, including dynamic stuff (be it rigged elements of characters, animated details, generated additions, alternatives/user-tweaked) and incredibly easy at that. Particularly for prototyping, jam-type stuff, or just indie/minimalist in general.

![2_examples](https://user-images.githubusercontent.com/4397725/180174292-054b574e-c7d9-4adc-9324-4ba3cd3a1edb.png)

--------------------------

Also, just posting this again (originally commented on golddotasksquestions' masking proposal that's mentioned above) about a potential for more advanced clipping options:

> If it could possibly work, here are some re-thought options:
> 
> Clip type: off (default), normal, invisible, inverted (AKA subtract/cut)
> Clip target: children (default), parent, children&parent, siblings start, sibling end
> Clippable bit option, allowing multiple choices: by all (default), by parent, by siblings, by children, force clipped by parent. Could use icons (infinity for all, up-arrow for parent, right-arrow for siblings etc).
> 
> `siblings start` would clip all siblings later in the tree (not rendering order!) until the node that has `sibling end` (last clipped node). If no sibling has `siblings end`, it ends with the tree itself.
> 
> clip type `invisible` works the same as normal clipping except the original canvasitem is not rendered (similar to inverted or multiply). In concept, its most basic usage is similar to `clip content` of node2d (except you can use any shape via polygon or sprite). This would allow for more advanced clipping of children, as well as better use of the trick I said (clip parent that clips children). So that's the 3rd way (inverted clip on child/siblings are the other 2) for cutting multiple nodes as Lielay9 first suggested. A very common usage of this would be using this as bounds, such as for a poster/card art/a TV etc or for a room (roof/wall fade/tear away). Also this is a mask (as other programs use the term) in the most literal sense (well, except for colors), especially if the target is set to parent
> 
> Some sort of mask bit option (user-defined like light mask or item cull mask) would be better than *just* having a clippable bit as I've defined it (though they could be part of the same option). This would make sibling clipping more useful (though I don't think it makes sense to group parent/child like that) and thus more complexity.

Although that's trying to think of everything.

**Comment by clayjohn** [comment]
I took a deep look into this issue today. ``clip_children`` is definitely working in an unintuitive way. I struggle to call it totally broken as it appears to be working the way it was originally designed. That being said, as the screenshots in this thread show the way it is currently working is not ideal. 

However, on a review of the comments here and elsewhere, there is no agreed upon expected behaviour. I can see at least 4 unique positions as to how ``clip_control`` should work:
1. The same as ``Control.clip_contents`` (i.e. Children only draw within bounding rect of parent, but they still draw on top using selected blend mode)
2. Clip based on parent alpha (parent not drawn, children drawn, but masked by parent alpha value)
3. As a mask (similar to Light2D "mask" mode from 3.x, parent not drawn, children drawn, but masked by parent alpha and multiplied by parent color)
4. Clip children but keep parent

## The current approach

The current approach essentially turns the CanvasItem into a CanvasGroup with an opaque background. 

**First let's look at how the CanvasGroup works:**

When the first of the CanvasGroup children is about to be rendered, we clear the back buffer to transparent black and begin rendering the CanvasGroup's children to the backbuffer (they keep their alpha). Then, when we render the CanvasGroup we use a shader that multiplies the CanvasGroup's color (always white) by the color of the backbuffer (using premultiplied alpha):
```
void fragment() {
	vec4 c = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);

	if (c.a > 0.0001) {
		c.rgb /= c.a;
	}

	COLOR *= c;
}
```

This works great because the CanvasGroup is always white. 

**Now let's look at clip_children**

For clip_children, we don't clear the backbuffer to transparent black, instead we copy the entire front buffer to the backbuffer and continue rendering there. Then we use the same shader as above to blend the parent CanvasItem with the backbuffer. This includes all of its children rendered as normal, but also includes the background color or any other nodes underneath. This is how it looks in practice:

![Screenshot from 2022-10-06 14-09-33](https://user-images.githubusercontent.com/16521339/194419109-e00c164e-1b9a-40c2-ac53-e66a8d4f19cf.png)

The children do not render outside of the parent and they are modulated by the parent's alpha. However, the parent is still drawn and their color is modulated by their children and by the background. If the parent was opaque white, it would appear invisible where the background shows through and would appear to be a mask for the children's contents. This is what we see in [Juan's original example](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40).

However, this appears to break when the parent is not plain white, the parent then essentially is forced to multiply blend with the background in the shader, then mix blends with the background (or whatever blend mode the parent is using).

Now I will look at the various options discussed

## ``Control.clip_contents``

One option is to clip children the same way as ``Control.clip_contents``. What this does is define a clipping rect based on the bounding rect of the parent Control node. Any part of the child outside of the rect is clipped away.

This works great for GUI as it saves the GPU from having to render those areas outside of the parent. However, since clipping is based on the bounding rect, children can be drawn where their parent is transparent as you can see in the picture below which contains a similar scene to the one above.

![Screenshot from 2022-10-06 14-05-54](https://user-images.githubusercontent.com/16521339/194419113-dde5d25f-bf1e-4f4d-91d0-a02759559fbb.png)

Children draw on top of their parents, but also draw where their parent was transparent. 

I don't think this is the approach we want for ``clip_children``

## Clip based on parent alpha only

One option that appears similar to [Juan's original example](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40) is to use a different shader for ``clip_children`` instead of the one above, we could use:
```
void fragment() {
	vec4 c = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);
	COLOR.rgb = c.rgb;
	COLOR.a *= c.a;
}
```

This shader sets the parent's color to the color of the backbuffer essentially only rendering anything where the children overlap with the parent. And in that case it just renders the children.

This turns the parent into a pure mask that cuts out any part of the child rendered outside the parent. 

![Screenshot from 2022-10-06 13-28-31](https://user-images.githubusercontent.com/16521339/194419118-72e2d721-72cd-4f7c-adcb-43bd9abfec97.png)

This appears to be the closest to what Juan originally had in mind. It matches the behaviour of the current implementation when the parent CanvasItem is pure white.

## Mask

Finally, we have the mask mode. This is closest to the way that Light2Ds using Mask mode in 3.x worked. In this case, the alpha of the parent modulates the children and the children modulate the parent resulting in the only drawing occurring where the two overlap. When they overlap their colors are multiplied together

![Screenshot from 2022-10-06 13-30-46](https://user-images.githubusercontent.com/16521339/194419117-0169cc01-17ab-4454-bde1-d238f7423596.png)

This can be implemented by changing the canvas group mode when using clip_children from ``CANVAS_GROUP_MODE_OPAQUE`` to ``CANVAS_GROUP_MODE_TRANSPARENT``

## Clip children but keep parent

Lastly, we could clip the children based on the parent's alpha, but still have the parent draw underneath. This would work like ``Control.clip_contents`` but would respect the alpha of the parent. 

I'm not sure exactly how we could implement this, but I'm sure it can be done.

**Comment by markdibarry** [comment]
I like "Clip based on parent alpha only" and "Clip children but keep parent". I can see use-cases for both, but if I had to only pick one, I'd go with "Clip based on parent alpha only". That seems the most intuitive, and probably most used.

Great work! With this, fixing the `CanvasGroup` node is the only rendering blocker I personally still have!

**Comment by golddotasksquestions** [comment]
Thanks for looking into this and writing up your conclusions @clayjohn !

**Clip children but keep parent** seems to be how I would have expected this feature to work.
