### ISSUE TITLE
slerp between two normalized colinear vectors return not normalized error

### ISSUE THREAD

**Issue by JestemStefan** [godotengine/godot#53928]
### Godot version

3.3.4

### System information

Pop!_OS, Xbox Series Gamepad

### Issue description

I was trying to gamepad input for my game and I'm stuck on this weird error.

Slerp method complain that vectors are not normalized, but when I use `.is_normalized()` method I get `True` for both vectors.

Also error only show up when I use vertical axis at the beginning and disappear after after moving joystick to the side.

Here is the code:

```gdscript
extends KinematicBody

var l_joystick_input: Vector3 = Vector3.FORWARD
var dir: Vector3 = Vector3.FORWARD

func _physics_process(delta):
	
	l_joystick_input.x = Input.get_action_strength("P1_L_joystick_right") - Input.get_action_strength("P1_L_joystick_left")
	l_joystick_input.z = Input.get_action_strength("P1_L_joystick_down") - Input.get_action_strength("P1_L_joystick_up")
	
	l_joystick_input = l_joystick_input.normalized()
	
	if l_joystick_input.length() > 0.8:
		print("is dir vector normalized?: " + str(dir.is_normalized()))
		print("is l_joystick_input vector normalized?: " + str(l_joystick_input.is_normalized()))
		
		dir = dir.normalized().slerp(l_joystick_input.normalized(), 0.1)
	
	$TankTurret.look_at(global_transform.origin + dir * 10, Vector3.UP)
 ```
And here is an error.
![image](https://user-images.githubusercontent.com/37214990/137639475-f353f94c-5bdd-4f52-bab2-9784bcca628f.png)

### Steps to reproduce

1. Download the project
2. move left joystick on your xbox gamepad

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/7360591/MRP.zip)

**Comment by Calinou** [comment]
I can't reproduce this on `3.x` fddbbf445 on Linux.

**Comment by kleonc** [comment]
I confirm `Vector3::slerp()` isn't implemented properly:
https://github.com/godotengine/godot/blob/468b987aa38b21b55c1cd8a8d4c03b8e1b2a1373/core/math/vector3.h#L217-L220

This issue specifically seems to be caused by not handling collinear vectors properly (in such cases their cross product is a zero vector (which can't be normalized)):
```
# Both would throw errors:
Vector3.FORWARD.slerp(Vector3.FORWARD, 0.5)
Vector3.FORWARD.slerp(-Vector3.FORWARD, 0.5)
```

**Comment by Hakunamawatta** [comment]
Is anyone working on this?

**Comment by kleonc** [comment]
> Is anyone working on this?

AFAIK, no.

**Comment by akien-mga** [comment]
Fixed by #55877.

**Comment by lawnjelly** [comment]
@akien-mga BTW I'm not sure this is fixed (it isn't in a fairly recent 4.0 build). This bug is about colinear vectors, and the PR is about lengths of vectors.

Not to say strictly that this issue is a bug, we ended up partly coming to the conclusion that the user should be responsible for fixing this.

**Comment by akien-mga** [comment]
I didn't read the full history but the title of this issue does sound like what #55877 fixed. If there's a specific case to discuss regarding colinear vectors maybe this should be retitled, or opened with a dedicated issue? Or just documented via a PR.

**Comment by kleonc** [comment]
@akien-mga Yeah, the title isn't precise.

Before #55877 the issue was that for any normalized `Vector3` `v` both `v.slerp(v, weight)` and `v.slerp(-v, weight)` would result in internally deducing the axis of the rotation to be a zero vector and such axis would be passed to `Vector3::rotated()` which would error out about the axis being not normalized.

#55877 doesn't fix this whatsoever, the difference is that now vectors of any length "can" be slerped, meaning the same error will occur for any two collinear vectors e.g. `(2 * v).slerp(3 * v, weight)` or `v.slerp(-4.5 * v, weight)` (assuming `v` being non-zero `Vector3`).

**Comment by lawnjelly** [comment]
On the other hand, while there is a bug, the more I think about the more I suspect that maybe we should not attempt to correct for this engine side.

The reality is that the bug is in the user code - slerping two vectors at 180 degrees in nonsense mathematically, because there is no single solution, there is a circle of solutions, because the rotation around this axis is undefined.

If we _do_ bodge this engine side, it is likely to lead to further errors of popping between the undefined state (near 180 degrees) and defined. So on balance the lesser of two evils in my mind is to get the user to fix these type of bugs (even if it means forcing them to understand why this is a problem in the first place).

**Comment by akien-mga** [comment]
I would just add something like this in all relevant methods:
```diff
diff --git a/doc/classes/Vector3.xml b/doc/classes/Vector3.xml
index ead08d86df..2ec496fde0 100644
--- a/doc/classes/Vector3.xml
+++ b/doc/classes/Vector3.xml
@@ -289,7 +289,7 @@
 			<argument index="0" name="to" type="Vector3" />
 			<argument index="1" name="weight" type="float" />
 			<description>
-				Returns the result of spherical linear interpolation between this vector and [code]to[/code], by amount [code]weight[/code]. [code]weight[/code] is on the range of 0.0 to 1.0, representing the amount of interpolation.
+				Returns the result of spherical linear interpolation between this vector and [code]to[/code], by amount [code]weight[/code]. [code]weight[/code] is on the range of 0.0 to 1.0, representing the amount of interpolation. If this vector and [code]to[/code] are colinear, the interpolation is undefined and the method returns an empty vector.
 				This method also handles interpolating the lengths if the input vectors have different lengths. For the special case of one or both input vectors having zero length, this method behaves like [method lerp].
 			</description>
 		</method>
```

**Comment by kleonc** [comment]
Currently errors are shown for collinear vectors but slerping vectors with the same direction is fine, simply no rotation needs to be done.

Meaning the 0 degrees case (collinear vectors with the same direction) currently errors out but according to the behavior introduced in #55877 it should just lerp the vectors.

And yeah, not supporting the 180 degrees case (collinear vectors with the opposite direction) is fine. But besides documenting it maybe it should also result in a meaningful error, not like the current one? :thinking:

**Comment by aaronfranke** [comment]
For vectors pointing in the same direction, I tried adding these test cases and it passes:

```cpp
	CHECK_MESSAGE(
			Vector2(1, 1).slerp(Vector2(2, 2), 0.5).is_equal_approx(Vector2(1.5, 1.5)),
			"Vector2 slerp with colinear inputs should behave like a regular lerp.");

	CHECK_MESSAGE(
			Vector3(1, 1, 1).slerp(Vector3(2, 2, 2), 0.5).is_equal_approx(Vector3(1.5, 1.5, 1.5)),
			"Vector3 slerp with colinear inputs should behave like a regular lerp.");
```

For vectors pointing in opposite directions, I don't know what you expect to happen. If we interpolate over the surface of a sphere, there is no preferred direction if the vectors are pointing in exactly opposite directions. I guess the best we can do is add a meaningful error message for debug builds?

**Comment by Helpsypoo** [comment]
I was having issues with Slerp, and the merged test seems to be failing in v4.2.stable.mono.official [46dc27791].

This line causes the "argument is not normalized" error.

`var myVector = new Vector3(1, 1, 0).Slerp(new Vector3(2, 2, 0), 0.5f);`

Looking at the Slerp method, I don't see why it would handle parallel or anti-parallel vectors gracefully, since Cross will produce a zero vector (not normalized), and normalizing a zero vector leads to a zero vector, which is then fed to Rotated, causing the error. A solution could be to just check whether the normalized cross product is still zero, and in that case, simply lerp. This would be strange for antiparallel vectors but still probably better than an error. And the documentation could describe the behavior for parallel and anti-parallel vectors. Currently the documentation (and the merged solution above) only describes what happens with zero vectors, not parallel vectors.
