### ISSUE TITLE
Duplicated files or resources retains the same UID

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#54774]
### Godot version

4.0.dev (56cfebbe9)

### System information

Windows 10

### Issue description

When duplicating a file through the FileSystem dock, the duplicated file has the same UID as the original file. This leads to the wrong file being used later on, if something references the original and duplicated files.

### Steps to reproduce

Duplicate a file through the FileSystem dock.
Open the original file in a text editor (or it's .import file if it has one)
Open the duplicated file the same way.
Notice that both file's UIDs are identical.

To see the issue with duplicated UIDs:
Duplicate a file through the FileSystem dock.
Add both the original and duplicated files to a scene.
Run the scene.
Notice that, instead of loading the original file, the duplicated file was loaded twice.

### Minimal reproduction project

[DuplicateTest.zip](https://github.com/godotengine/godot/files/7499188/DuplicateTest.zip)

*Bugsquad edit (keywords for easier searching): ID*

**Comment by cameronsteele** [comment]
Until this is fixed, one can create a new scene (without using duplication) and copy paste the nodes, instead.

I think this is quite a high-priority bug in terms of how confusing it is for users. Thanks!

**Comment by lufog** [comment]
I think this is fixed, I can't reproduce it on v4.0.alpha.custom_build [272b35595].

https://user-images.githubusercontent.com/10379487/156926916-50dd2773-2ad1-4129-a558-5fbdbf822c4c.mp4

**Comment by akien-mga** [comment]
It was worked around in https://github.com/godotengine/godot/pull/55584, but we're not convinced that it's the proper fix for it.

**Comment by ywaby** [comment]
I can reproduce it with AtlasTexture.
Duplicate *.atlastex would gen a same uid and *.tres is work fine.

![image](https://user-images.githubusercontent.com/12198203/163146388-8503a8cb-45ec-4f2e-a411-5894c16552c1.png)

scene src
```
[gd_scene load_steps=3 format=3 uid="uid://o5k1cbo6e8vs"]

[ext_resource type="Texture2D" uid="uid://7mjm28afm5cy" path="res://new_atlas_texture.atlastex" id="1_l0am1"]
[ext_resource type="Texture2D" uid="uid://7mjm28afm5cy" path="res://2.atlastex" id="2_x7lof"]

```

project here [uid same bug.zip](https://github.com/godotengine/godot/files/8480084/uid.same.bug.zip)

**Comment by floere** [comment]
I can still reproduce this for scene UIDs on 4.0 alpha 6 by duplicating a folder with a scene inside. The scene keeps the UID, even after changing the scene.

**Comment by Rinocrosser** [comment]
Will this be fixed before BETA? It looks like a very annoying bug that affects my workflow every single day.

**Comment by Calinou** [comment]
> Will this be fixed before BETA? It looks like a very annoying bug that affects my workflow every single day.

While this will be fixed before stable release, contributors work on a best-effort basis. Therefore, we can't make guarantees on whether this will be fixed before beta1 is released.

**Comment by YuriSizov** [comment]
I'm lowering the priority of this issue and marking it to be fixed in beta rather than alpha. We've implemented a temporary fix before alpha 2 which covers all the text resources (https://github.com/godotengine/godot/pull/55584). Binary resources may not be handled well yet, but it should be okay for now.

**Comment by mickeyordog** [comment]
I just ran into this bug again on v4.1.1.stable.mono.official [bd6af8e0e]. Duplicated a scene a couple times, but they each have the same UID 
<img width="754" alt="image" src="https://github.com/godotengine/godot/assets/36612632/ed3de3d7-09f3-4776-823a-8d8fe633a373">

**Comment by debris** [comment]
> I just ran into this bug again on v4.1.1.stable.mono.official [[bd6af8e]

just experienced it as well, same version :/

**Comment by ArdaE** [comment]
For those who are still experiencing this issue: Make sure that you duplicate resource/scene files using Godot's FileSystem dock and not your operating systems file manager (File Explorer, Finder, shell, etc.). The former will create new UIDs as needed, whereas the latter obviously will not.

It'd be nice if Godot displayed a warning when it detects multiple resource/scene files with the same UID, which can prevent a lot of headache*.

* I spent 15 minutes scratching my head why different fbx files that I configured to use different external material files all kept using the same material file (I kept reimporting them, thinking I must have misconfigured their import settings). While I did guess a UID issue in the end and checked, many junior developers may give up if they don't know about UIDs.

**Comment by ForkandBeard** [comment]
Just to add to @ArdaE's comment. Not a junior dev but new to Godot and lost a lot of time troubleshooting this issue with copied textures used in multiple materials. Didn't know about the UIDs until I did a diff against a working, simple project, vs my main project.

A warning for duplicate UIDs would be great.

**Comment by ArdaE** [comment]
I've added a discussion for a warning, https://github.com/godotengine/godot-proposals/discussions/8949, which someone may hopefully implement. It should be fairly easy to implement it.

**Comment by SweatyTryhardx10** [comment]
I am experiencing this as well in my first project. I just found the cause of the issue which is this: duplicate UIDs.

**Comment by AThousandShips** [comment]
> I am experiencing this as well in my first project. I just found the cause of the issue which is this: duplicate UIDs.

Specifically from duplicating a file inside the editor? Or from copying the file manually?

**Comment by SweatyTryhardx10** [comment]
> Specifically from duplicating a file inside the editor? Or from copying the file manually?
I can't comment on that since I'm not the individual that actually copied the file (it was a 2-man hobby project). I just noticed that the UID for the resources were identical which was causing materials to differ between editor and runtime.

**Comment by tgiddings** [comment]
I experienced this issue today v4.3.stable.official [77dcf97d8], and I used the in-editor "FileSystem" Dock. Issue is still present.

**Comment by akien-mga** [comment]
Please test with 4.4.beta3 or later, and open a new bug report with a reproduction project and detailed steps to reproduce. This old issue was fixed years ago. It doesn't mean that all instances of duplicated UIDs are solved, but the case outlined in this issue was.
