### ISSUE TITLE
Parser assumes types when it shouldn't

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#56171]
### Godot version

4.0.dev (0f6a6ca5b)

### System information

5.15.2-2-MANJARO

### Issue description

The following causes a parser error:
```gd
var a = "a"
func _process():
	a + 1 # Invalid operands "String" and "int" for "+" operator.
```
But `a` is not typed, and it could change to an `int` before `_process()` is called.

For example, this should be fine:
```gd
var a = "a"
func _process():
	a + 1
func _ready():
	a = 1
```
But the parser still produces the same error.

Interestingly, the parser doesn't complain if we change the function definition order:
```gd
var a = "a"
func _ready():
	a = 1
func _process():
	a + 1
```

### Steps to reproduce

```gd
var a = "a"
func _process():
	a + 1 # Invalid operands "String" and "int" for "+" operator.
```

**Comment by pycbouh** [comment]
That same code fails in `3.x` with the same exact error. There is no regression.

![image](https://user-images.githubusercontent.com/11782833/147243137-5bda73a1-d263-4bb5-b80b-14b2b0852ff2.png)

I think you have some misconception about how typing works in GDScript. It is dynamically typed, but it's strongly typed. Or whatever you want to call it, because definitions get murky here. But the point is, the variable can be untyped at its declaration, but as soon as it is defined, it receives a type from the value and it cannot change that type. We don't even allow coercion in places where some users of dynamically typed languages expect (see the int & float division discussion across multiple issues and proposals).

Look at [this example](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_advanced.html#as-function-arguments) from the docs that explains dynamic typing.

```
func print_value(value):
    print(value)

...

print_value(55) # Valid.
print_value("Hello") # Valid.
```

`value` here can be any type upon function call, but it will remain the same type throughout the function execution.

**Comment by cdemirer** [comment]
The main problem in this issue is fixed by #56194, however the root cause of the aforementioned inconsistency that depends on the function definition order hasn't been analyzed. Maybe another issue could be opened for it, but I'm not sure how to reproduce that inconsistency on current master, since neither definition order will produce a parser error now.

To understand it better, I printed the analyzer's type inference results alongside `--test gdscript-parser`, for the following:
```gdscript
extends Node

var x = "abc"

func fun1():
	x
func fun2():
	x = 1
func fun3():
	x
```
```
Class <unnamed> Extends Node :
|   Variable x
|   |   = "abc":String

|   Function fun1(  ) :
|   |   x:String?

|   Function fun2(  ) :
|   |   x:String? = 1:int

|   Function fun3(  ) :
|   |   x
```
(no inferred type for the last one)

So it looks like assignments to members affect their inferred (non-static) type, in sequential order of function definition.

Since the fix in #56194, inference for non-static types shouldn't be a problem even if they're wrong, so the potential harm is probably minimal, and doesn't justify keeping this issue open. It doesn't even break Script Editor's type guessing, as I believe it has other logic in it. So I believe this issue can be closed.

**Comment by dalexeev** [comment]
Your example does not cause a compile time error in RC 1 (now there is a bug that it is marked as a type-safe line).

![](https://user-images.githubusercontent.com/47700418/217907459-16e5badc-d443-49c0-bec8-cc7717d7e578.png)

If in some cases you still encounter this, you can suppress this by explicitly specifying `Variant` type (`var a: Variant`). But, in general, this is intentional. GDScript tries to infer types whenever possible, even with dynamic typing. This allows for example to offer better autocomplete suggestions.

https://github.com/godotengine/godot/blob/5c1295dc20323ee1596369b5bcf91ba6a9383336/modules/gdscript/gdscript_parser.h#L116-L121
