### ISSUE TITLE
Invert Mouse option for editor 3d UI

### ISSUE THREAD

**Issue by liquidape** [godotengine/godot#571]
Request:  Invert Mouse option for editor 3d UI.

I would like there to be an option to invert the mouse when using ctrl+drag so that ctrl+mouseup = zoom out, ctrl+mousedown = zoom in.

**Comment by neikeq** [comment]
I think this could be rather fixed by allowing to customize the _Zoom In_ and _Zoom Out_ hotkeys. The hotkeys seem to be the same for all navigation schemes (Godot, Maya and Modo) so there shouldn't be any problem with that.
Ping @djrm who recently added editor shortcuts to the spatial editor.

**Comment by djrm** [comment]
@neikeq those shortcuts (zoom in, and out) are already available to customize, but this issue is asking about the ability to invert the mouse gesture to zoom in and out

**Comment by bojidar-bg** [comment]
Hm, is this still an issue or no?

**Comment by akien-mga** [comment]
I guess one can rebind the hotkeys nowadays to configure this.

**Comment by X32Lapis** [comment]
Sorry to comment on such a old post. But could we still get a option to invert the direction for zooming using the mouse? I tried to see if I could change the hotkeys but I only could find with keyboard inputs. 

I would like to be able to press Ctrl + Mouse Down to zoom in. Currently by default Ctrl + Mouse Down zooms out. Unless there is a option for it that I'm missing. Currently using Godot 4.3. It's how I use it in Blender and unfortunately got use to it.

Thank you
