### ISSUE TITLE
[Godot 4.0 Alpha 2] - Jittering and Non Screen Tearing even when disabling V-Sync

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#57914]
### Godot version

Godot 4 Alpha 2

### System information

Windows 10 - GTX 980

### Issue description

After disabling V-Sync the screen tearing is gone, it should appear, also the game Start jittering and stuttering, also when enabling V-Sync the game still jittering/stuttering
In Alpha 1 after disabling V-Sync, the screen tearing will appear, but there is no Jitter, and the game runs very smooth no matter what compared to Alpha 2
All of this happen when in Full screen

### Steps to reproduce

in any 3D project do you have that contain a moving camera, open it in Alpha 1 and Alpha 2, and see the difference

**Comment by owstetra** [comment]
> Jitter and stutter will always happen to an extent when you have V-Sync disabled, because the physics step does not match the rendered frame rate. [Physics interpolation](https://github.com/godotengine/godot/pull/52846) fixes this by ensuring every rendered frame "sees" a different physics state, but it's not implemented yet.
> 
> If you need physics interpolation right now, you could try porting https://github.com/lawnjelly/smoothing-addon to `master`.

The problem is not with physics interpolation, no... it will never Jitter/Stutter at all if V-Sync is disabled in any game or engine, you maybe mean Screen tearing ?
Because in Alpha 1 there is no Jitter/Stutter at all when moving the camera in 3D when the V-Sync is disabled and there is Screen Tearing
But in Alpha 2 There is Jitter/Stutter but there is no Screen tearing when V-Sync is disabled, and even if V-Sync is Enabled the Stutter is still there

**Comment by Calinou** [comment]
@owstetra If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by AttackButton** [comment]
Ok. I know this will depend on each circumstance, but I was finally able to solve the jittering problem of my 2D project on the old laptop that I use as a base. I haven't tested the parallax yet, but so far it's as smooth as ever.

godot version: v4.0.alpha.custom_build [f425d403f]

To fix this, I did the following:

1) I let windows/nvidia do the automatic cap (60 fps). The godot force 60 fps option was not able to bring the same quality, I don't know why.
2) I enabled vsync in godot + vsync in the nvidia settings.
3) I unchecked in the project settings: `snap_2d_transforms_to_pixel` + `snap_2d_vertices_to_pixel` + `snap_controls_to_pixels`.
4) I left the force fps at 0.

Just a note, the item 3/ is the most important, only `snap_controls_to_pixels` doesn't seem to bring any jittering, whereas the other two snaps options always bring a little bit.

Maybe the problem is not in godot itself, but in this OS/nvidia/godot relationship.

Anyway, the 2D is Smooth as hell now. :)

**Comment by bruvzg** [comment]
`snap_controls_to_pixels` was broken and restored in #57481, and it probably reintroduced #28804 issue (this was fixed and reverted multiple times in 3.x).

**Comment by owstetra** [comment]
![Untitled](https://user-images.githubusercontent.com/51128638/153619297-4213e85f-8bf2-48dd-acd3-9a124fb5c527.png)


Here's something, You can download this Advanced movement system template and test it, Before you test it add this line of code in _ready()
DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)


now open it in Alpha 1, You will see the game runs very smooth, but in Alpha 2 the game stuttering, it's hard to see at first but you will feel it and start seeing it

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by dreamsComeTrue** [comment]
yes, I can confirm that - I still get jiter movement when VSync is enabled. When I disable it, it's also there but less noticeable.
I have the simplest scene: CharacterBody3D with _physics_process adjusting it's Velocity and then move_and_collide()
I am using latest 4.1 version of Godot

**Comment by akien-mga** [comment]
Might be the same issue as #84137 - presumably a Windows DWM bug.
