### ISSUE TITLE
Dialogs don't appear in Godot alpha 4 on macOS 12.2.1 (DisplayServer regression)

### ISSUE THREAD

**Issue by bryanrieger** [godotengine/godot#58996]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

macOS 12.2.1 (Monterey), Apple M1 Pro

### Issue description

Upon opening Godot I am unable to open the Godot preferences, Project preferences or any of the menu items by interacting with the menus using a mouse. I can however still use keyboard shortcuts where available.

https://user-images.githubusercontent.com/60825/157737137-97f1980d-4bf7-4301-bef9-84a52787a122.mp4

### Steps to reproduce

1. Launch Godot on macOS.
2. Try to interact with the menus using a mouse.

**Comment by Calinou** [comment]
Is single-window mode enabled in the editor settings? It's disabled by default, but you may have enabled it in a prior 4.0alpha version. If you can't open the Editor Settings dialog, check the editor settings file (`~/Library/Application Support/Godot/editor_settings-4.tres`).

**Comment by bryanrieger** [comment]
> * Can you reproduce this on earlier 4.0 alphas? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.0/).

No, I only experienced this issue with latest Godot 4 alpha 4.

> * Is single-window mode enabled in the editor settings? It's disabled by default, but you may have enabled it in a prior 4.0alpha version. If you can't open the Editor Settings dialog, open the editor settings file with a text editor (`~/Library/Application Support/Godot/editor_settings-4.tres`).

I actually removed everything Godot related in my library thinking it may have been a bad prior setting, but it still happens with a fresh install (ie: no ~/Library/Application Support/Godot/ folder or existing preferences).

**Comment by bruvzg** [comment]
I can't reproduce it with `alpha 4` or current `master`.

**Comment by fabriceci** [comment]
same for me, macOS Big Sur MacBook Pro Readon Pro

**Comment by bryanrieger** [comment]
Using Command ⌘ + , to access the editor settings, and enabling 'Single Window Mode' seems to have fixed it.

**Comment by bruvzg** [comment]
Are any other dialogs ("New Project" in the Project Manager) and popups (e.g., language selection dropdown in the Project Manager) working? Also, what's your external display config?

**Comment by bryanrieger** [comment]
If 'Single Window Mode' isn't enabled and you open the editor settings using the keyboard shortcut, the other dialogs, popups, dropdowns, etc all do seem to work using the mouse.

I am also running an external display. If I remove the external display, with 'Single Window Mode' disabled (default) everything works fine. Adding the second display Godot then exhibits the original behaviour with 'Single Window Mode' disabled.

**Comment by slasktotten** [comment]
I also ran into this. Tried enabling 'Single Window Mode'. However that made things worse. Instead of nothing happening when I try to trigger a dialogue it seems to lock the entire ui and I have to kill Godot through the activity monitor.

**Comment by Jack-Trent** [comment]
Can reproduce in Godot 4 `4.0.alpha4` & `4.0.alpha5` if an external monitor is connected.

Cannot reproduce in Godot 4 `4.0.alpha3`.

**Machine Specification**
    Model: MacBook Pro (14-inch, 2021)
    Chip: Apple M1 Pro
    OS: macOS Monterey (12.2)

**Reproduction Steps**
    1. Connect an external monitor (I am using the built-in HDMI port)
    2. Open a new project in Godot 4
    3. Attempt to open a dialog such as Editor->Editor Settings

**Comment by AnnisVeryGoodCode** [comment]
Just happened to me in a new project on Windows 10, alpha7, single monitor setup. I was first able to open menu items, then it stopped working. I could also still open menus via shortcuts or command palette. Issue fixed by closing and re-opening Godot.

A difference to the reporter's video was that the menu items weren't even highlighted for me on mouse-over. When I clicked on a menu item, Godot registered clicks as if the menu wasn't there, so anything "underneath" got selected or clicked.

**Comment by AnnisVeryGoodCode** [comment]
It's now happened without changing a shortcut beforehand. I can't pinpoint a specific trigger so far.

**Comment by akien-mga** [comment]
I believe this was fixed a long time ago, or we'd see a lot more reports about this against recent betas. Please comment if you can still reproduce it.

**Comment by zhengxiaoyao0716** [comment]
I found the problem still exist on macOS 26.3.1 (Apple M4) when using `DisplayServer.dialog_show` or `DisplayServer.file_dialog_show`:

<img width="1282" height="1134" alt="Image" src="https://github.com/user-attachments/assets/36b71489-2846-4d0b-8c50-6ae3898845a5" />

Here is a minimal reproducible example:

[test-dialog.zip](https://github.com/user-attachments/files/26996640/test-dialog.zip)
