### ISSUE TITLE
`get_world_3d().get_navigation_map()` returns invalid RID

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#60462]
### Godot version

Godot_v4.0-alpha5_win64

### System information

Windows 10

### Issue description

I'm trying to get the RID of the navigation map of the current world (if I understood this correctly, there can only be one World in the entire Root, someone please correct me if I'm wrong, in the debugger both nodes return the same exact ID. It shouldn't matter if I add or delete 100 sub-scenes with their own navmeshes because all point to the same World3D) because I need to call functions such as NavigationServer3D.map_get_path() that require that RID.

### Steps to reproduce

Just run the project and add a breakpoint, the agent moves so it is detecting the navmesh but the RID is always Invalid
![screenshot](https://user-images.githubusercontent.com/98270528/164893134-db45d950-f79e-4cbc-9ec9-ef54b9ef2355.PNG)
.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/8546851/bug.zip)

@AndreaCatania

**Comment by AndreaCatania** [comment]
Hello, thx for the issue report.
I didn't debug this but I've checked the source code.

Here the nav map is created: https://github.com/godotengine/godot/blob/master/scene/resources/world_3d.cpp#L151
Here the nav map is returned: https://github.com/godotengine/godot/blob/master/scene/resources/world_3d.cpp#L57

Navigation map is private https://github.com/godotengine/godot/blob/master/scene/resources/world_3d.h#L49 and inside `World3D` it's not assigned to `RID()` until the very end when everything is freed. So everything seems fine.

I wonder if the issue is the debugger wrongly reporting `Invalid RID`, I remember I saw something like this already. Can you please try to use that variable to see if the function fails?

**Comment by venilark** [comment]
Just tried this under the other code

`	var destination_node_transform = get_node("../Destination").global_transform.origin
	var agent_transform = global_transform.origin
	var path : PackedVector3Array = NavigationServer3D.map_get_path(navigation_map_rid, agent_transform, destination_node_transform, true)
`
and I get an empty PackedVector3Array

**Comment by venilark** [comment]
Alpha 6, same result

**Comment by smix8** [comment]
@venilark 
Can't recreate any of the issues with the MRP on recent Godot 4.0 commit 4c2a614ad41564ab33eb6515b48e0e5b52ea8b81

Returned World3D Navigation Map RID is valid and correct.
The returned Navigation Path as PackedVector3Array is also not empty and correct.
Moving the agent around also updates the path correctly.
Your last code snippet works as well.

Maybe meanwhile something changed / was fixed?

**Comment by venilark** [comment]
> 

I opened the same project in Alpha 7 and still invalid RID :S

**Comment by smix8** [comment]
Tested with newest version again and both RID's are valid.
With your code snippet I also receive a PackedVector3Array with the full path as expected.

That said, if your issue is that the path is empty in the agent _ready() function that is expected and should be added as part of the documentation that does not exist rightnow.

The reason is that both NavigationRegion Nodes and your NavigationAgent need to register with the NavigationServer first and the NavigationServer has its own syncphase on a thread for updates that runs each frame. If you query the path in _process() it is not empty cause the NavigationServer has been updated / received its first update tick but if you query in any _ready() it still has not updated cause the SceneTree is still updating childnodes. The virtual navigation map is empty at that point so the path returns empty. Please test / confirm if this is the source of this issue.

**Comment by venilark** [comment]
> Tested with newest version again and both RID's are valid. With your code snippet I also receive a PackedVector3Array with the full path as expected.
> 
> That said, if your issue is that the path is empty in the agent _ready() function that is expected and should be added as part of the documentation that does not exist rightnow.
> 
> The reason is that both NavigationRegion Nodes and your NavigationAgent need to register with the NavigationServer first and the NavigationServer has its own syncphase on a thread for updates that runs each frame. If you query the path in _process() it is not empty cause the NavigationServer has been updated / received its first update tick but if you query in any _ready() it still has not updated cause the SceneTree is still updating childnodes. The virtual navigation map is empty at that point so the path returns empty. Please test / confirm if this is the source of this issue.

thank you, I added the code in _process() and now I am getting the path, although I still get INVALID RID for some reason, I'm really confused about it, maybe a debugger error? the RID has to be right otherwise map_get_path() wouldn't work

sorry but what do you mean by "query the path in _process()"? for what I have in mind, I need to call several map_get_to() to different nodes and do it as soon as possible, a I expected it to work in _ready() but if that's not possible how do you make sure when you call it, the server has already set everything up as you said?

**Comment by smix8** [comment]
@venilark 

If you mean the remote debugger displays in the Editor with 'INVALID RID' that is "normal". Try printing your RID variables with rid.get_id() and you will see that everything works fine and it is just a display issue. When you test your game from the editor Godot starts a new instance of Godot to playtest your game. Since the RID is only valid in this instance it is displayed as 'INVALID RID' in the editor instance.

When the SceneTree is build from nodes it takes some time to register all Navmesh regions and Agents to the Navigation Map since the NavigationServer runs on a different thread. One way to deal with this is to use a bool toggle in _process() so as soon as a path is available it runs once.

``` gdscript
var waiting_for_navigationserver_sync : bool = true
func _process(delta):
    # Arrays will always return empty in _ready() and on first frame(s)
    # NavigationRegions and NavigationAgents queue up to register with threaded NavigationServer in _ready()
    # Afterwards NavigationServer needs a physics tick to sync regions and agents and flush queue
    var map : RID = get_world_3d().get_navigation_map()
    var path : PackedVector3Array = NavigationServer3D.map_get_path(map, start_pos, target_pos)
    if waiting_for_navigationserver_sync  and not path.is_empty():
        waiting_for_navigationserver_sync = false
        # do your _ready() navigation stuff
```

**Comment by venilark** [comment]
> @venilark
> 
> If you mean the remote debugger displays in the Editor with 'INVALID RID' that is "normal". Try printing your RID variables with rid.get_id() and you will see that everything works fine and it is just a display issue. When you test your game from the editor Godot starts a new instance of Godot to playtest your game. Since the RID is only valid in this instance it is displayed as 'INVALID RID' in the editor instance.
> 
> When the SceneTree is build from nodes it takes some time to register all Navmesh regions and Agents to the Navigation Map since the NavigationServer runs on a different thread. One way to deal with this is to use a bool toggle in _process() so as soon as a path is available it runs once.
> 
> ```gdscript
> var waiting_for_navigationserver_sync : bool = true
> func _process(delta):
>     # Arrays will always return empty in _ready() and on first frame(s)
>     # NavigationRegions and NavigationAgents queue up to register with threaded NavigationServer in _ready()
>     # Afterwards NavigationServer needs a physics tick to sync regions and agents and flush queue
>     var map : RID = get_world_3d().get_navigation_map()
>     var path : PackedVector3Array = NavigationServer3D.map_get_path(map, start_pos, target_pos)
>     if waiting_for_navigationserver_sync  and not path.is_empty():
>         waiting_for_navigationserver_sync = false
>         # do your _ready() navigation stuff
> ```

thank you, I thought it would be some kind of signal but it's just a simple bool check and it just works
