### ISSUE TITLE
Using viewport

### ISSUE THREAD

**Issue by abochar** [godotengine/godot#60475]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Windows 11, Vulkan, Nvidia 3080Ti (511.79)

### Issue description

Using main Viewport as Sprite2D texture causing artefacts and arror:

E 0:00:02:0993   draw_list_bind_uniform_set: Attempted to use the same texture in framebuffer attachment and a uniform (set: 3, binding: 0), this is not allowed.
  <C++ Error>    Condition "attachable_ptr[i].texture == bound_ptr[j]" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7419 @ draw_list_bind_uniform_set()

![image](https://user-images.githubusercontent.com/35319858/164916044-36a9d3b8-6623-41d6-9011-f6c5a34f7fb3.png)

![image](https://user-images.githubusercontent.com/35319858/164915694-257b2980-69cb-48d9-b3e1-c497fc05b2ec.png)

### Steps to reproduce

Create sprite 2d, assign main viewport texture to it.

### Minimal reproduction project

[Viewport.zip](https://github.com/godotengine/godot/files/8547668/Viewport.zip)

**Comment by gerrywastaken** [comment]
This same error was mentioned in a few places so I want to create a link to them so that people eventually find this issue as it doesn't yet come up on Google:
1. https://github.com/godotengine/godot/issues/44473#issuecomment-748490674
2. https://github.com/godotengine/godot/issues/66483#issue-1387025952
3. https://godotengine.org/qa/132245/trying-shader-based-game-using-same-texture-uniform-allowed
4. https://youtu.be/VSwVwIYEypY?t=377 (clearly shows the error spam - watched by 66K times, not sure how many encountered the same error and also encountered 512x512 error fixed by #69256 )

**Comment by c-schembri** [comment]
This issue is still occurring in 4.0.3.

**Comment by wilkie** [comment]
Still occurring in 4.1.1 stable. More or less any viewport texture to itself, in order to reference a prior frame. This all works in spite of the message suggesting that it is not allowed. The error spam ends up making the debugger quite useless that I will likely build Godot myself to silence it, which isn't the worst workaround.

**Comment by nan0m** [comment]
I found a workaround that eliminates the warning.


try this:
```gdscript
var viewport_texture = get_viewport().get_texture()
node.texture = ImageTexture.create_from_image( viewport_texture.get_image() )
```

the docs mention that you might want to do
```gdscript
await RenderingServer.frame_post_draw
```
before creating the image texture. Which wasn't necessary for my usecase. But I thought I would still mention it here.

**Comment by clayjohn** [comment]
Just jumping in here to add some context. Using the root Viewport as a texture to draw a Sprite in the root Viewport is not supported and cannot be supported. The error is correct, but not very helpful for end-users. 

What we probably need to do is detect if the user is trying to use the ViewportTexture of the root Viewport and then provide a proper error that this is not supported. 

This will of course be tricky as we need to do the same for SubViewports (SubViewports cannot be used as a texture to draw an item that is a child of that SubViewport)

**Comment by Arecher** [comment]
I think most of the confusion with this issue, at least for me, came from the fact that **I expected `get_viewport().get_texture()` to return a static image/texture** (aka an ImageTexture) of the current frame in the viewport, rather than a dynamically updating texture.

While a useful feature, I doubt it's what every user expects when they see the function `get_texture()` autocompleted in their script editor (or when they find it in the docs), and there is little to hint that you're essentially getting a video projection texture. **If it weren't compatibility breaking, I would suggest renaming `get_texture()` to `get_dynamic_texture()`** or `get_dynamic_viewport_view()` or `get_viewport_texture()` or something that indicates that this texture can change over time, and this is not the standard `ImageTexture` that get_texture() typically returns elsewhere.

**Adding a single, non-dynamic texture getting function, such as `get_static_texture()`** or `get_viewport_snapshot()` or `get_image_texture()` to `Viewport`, which would return an ImageTexture akin to nan0m's implementation, **would at least hint that there are different usecases**, and might inspire further investigation from users.

**Either way, the Documentation should really be updated** to help users avoid this, presumably common, misconception. Because even if I would have investigated more thoroughly, [`get_texture()`](https://docs.godotengine.org/en/4.7/classes/class_viewport.html#class-viewport-method-get-texture) does not mention the dynamic nature, nor that this means it cannot be used inside its origin viewport directly. That limitation should really be mentioned inside the documentation here, since it's an easy mistake to make.

<img width="1150" height="299" alt="Image" src="https://github.com/user-attachments/assets/6eb555f2-fa1b-454c-b5af-c4dc1209895e" />

[Viewport Texture's documentation ](https://docs.godotengine.org/en/4.7/classes/class_viewporttexture.html)feels similarly lacking. It does not mention this limitation, and the only reference to this not being a simple, static Texture is the sentence

> Provides the content of a Viewport as a dynamic texture.

without any further explanation on what this means. An additional sentence that mentions that changes to the viewport scene will automatically be displayed on the viewport texture in real-time wouldn't go amiss.
