### ISSUE TITLE
Major framerate drop on Windows when moving mouse in very simple project, unless profiling

### ISSUE THREAD

**Issue by Thoughtquake** [godotengine/godot#60646]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, GLES 3, Geforce GTX 970, Core i7-4790, 32GB RAM

### Issue description

The combination of the following observations leads me to believe there's a bug in the engine causing an unreasonable performance drop when handling rapid mouse movement:

- With Vsync off, my game runs at over 1000FPS, regardless of mouse movement.
- With Vsync on, my game runs at 60FPS until I start rapidly moving the mouse - then FPS drops significantly, sometimes below 30FPS.
- When I enable profiling in the editor, the framerate drop no-longer occurs.

That last point is the most puzzling; I would expect profiling to slow things down, not speed them up.

I have stripped down my game project to a bare minimum repro; a Sprite node that follows mouse movement, and a label that reports the current FPS. I'm not sure what other details of my repro project may be relevant, as starting from a blank slate I was not immediately able to reproduce the problem.

I am not normally using Vsync via Compositor, but turning that option on makes the problem worse.

Note that I only see this issue on Windows; it does not happen on Mac or Linux.

### Steps to reproduce

Unzip the attached project, open it in the Godot editor, and run. Then, rapidly move the mouse around inside the window.

Observed result: The label shows "60 FPS" when the mouse is still, and drops to lower numbers while the mouse is moving, at least as low as 31 FPS.

### Minimal reproduction project

[InputRepro.zip](https://github.com/godotengine/godot/files/8595456/InputRepro.zip)

**Comment by Thoughtquake** [comment]
Apologies for not checking this from the beginning, but I just confirmed this also happens on v3.4.4.stable.official [419e713a2].

**Comment by Calinou** [comment]
Are you using a variable refresh rate monitor?

**Comment by Thoughtquake** [comment]
> Are you using a variable refresh rate monitor (G-Sync/FreeSync)?

Nope. Unfortunately I don't have a variable refresh rate monitor to test this on.

**Comment by Thoughtquake** [comment]
Update: I can reproduce this with an even simpler project, attached. This time I started from a new project and didn't change any project settings, and I removed the Sprite node that was following the pointer. At this point there are no _input methods anywhere, and the only script is to display the current FPS in a label. There are only two nodes in the scene.

The framerate drop when moving the mouse isn't as bad as before, but it gets as low as 43FPS if I continue rapid movements

[InputRepro3.zip](https://github.com/godotengine/godot/files/8665764/InputRepro3.zip)
.

**Comment by Thoughtquake** [comment]
I have now tried this on another PC which does not reproduce the issue. However, I can't imagine it's related to the performance of the hardware - both PCs can handle games like GTA 5 well. Also, that wouldn't explain the problem going away when I enable profiling in Godot

**Comment by Calinou** [comment]
This hints at the performance bottleneck being linked to higher mouse USB polling rates (500 Hz or 1000 Hz).

**Comment by Thoughtquake** [comment]
I can confirm I'm using a mouse with a 1,000Hz polling rate, on both machines. Not seeing this on the second machine might be a fluke; the framerate drops do mysteriously stop happening sometimes, but they always come back eventually. It seems I'm unable to reproduce it within a short time of booting.

FYI, I can reproduce this at least as far back as Godot 3.1.

**Comment by Thoughtquake** [comment]
I might be onto something - I couldn't reproduce large framerate drops until I put my PC to sleep and woke it back up. I do that often enough that a sleep/wake may have happened before every other occurrence.

Based on one of the related issues I tried calling this in _ready: Input.set_use_accumulated_input(true)

It didn't help.

**Comment by Thoughtquake** [comment]
This is a pretty serious problem for my game - on another machine the frame drops as low as 1FPS when moving a mouse with a high polling rate. Lowering the polling rate fixes the problem, but I don't expect most players to know how to do this.

Again, using accumulated input doesn't help (even on Godot 3.5 RC6), but starting profiling in the editor does. How is that possible? Does the profiler somehow separate the input handling from the rendering thread?

I've been hoping to spot the cause myself using profiling tools, but the CPU usage is negligible even during the extreme framerate drops.

**Comment by Calinou** [comment]
> Does the profiler somehow separate the input handling from the rendering thread?

No.

**Comment by keenfoong** [comment]
I just want to add my 2c, I'm also getting this issue. I'm using a G203 Lightsync mouse with 3200 DPI at 1000hz. Setting it to 500hz makes it a bit better, but it still spikes alot when moving the mouse.

Tested with the various V-Sync settings (Off, On, Mailbox, Adaptive), it still spikes.
Tested with Release build, still spikes.

The spikes happen only in Windowed mode for me. (Which happen to be what I game in 99% of the time)

Godot v4.0.2.stable.mono.official [7a0977ce2]
Windows 10 Home 64-Bit
Operating system: Windows-10-10.0.19045-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 531.68
AMD Ryzen 9 3900x 12-Core Processor ~3.8GHz
32714MB RAM

I'm using a pretty beefy machine, so cpu shouldn't be an issue. Also tested on other game engines and mouse movement doesn't lag. (Unity Release build, Love2D)

**Comment by rune-scape** [comment]
Godot v4.0.2.stable.mono.official [https://github.com/godotengine/godot/commit/7a0977ce2c558fe6219f0a14f8bd4d05aea8f019]
Microsoft Windows 10 Pro
NVIDIA GeForce GTX 1080 Ti
AMD Ryzen 5 3600X 6-Core Processor, 3793 Mhz, 6 Core(s), 12 Logical Processor(s)
also getting this issue, i tested with g-sync on and off, and it didn't seem to make a difference in fps drop

using an empty project with just a control node on Forward+ renderer:
with my mouse at 1000Hz polling rate, my fps dropped to exactly 1 when wiggling
![image](https://github.com/godotengine/godot/assets/55224592/b9e28c44-2da9-46ad-b810-8ed87762d9fe)

changing my polling rate from 1000Hz to 500Hz instantly made the problem mostly go away, but it still dropped from ~2000fps to ~500fps
![image](https://github.com/godotengine/godot/assets/55224592/acaa43ed-9f35-4ff6-8e25-d48214c9b377)

**Comment by Swarkin** [comment]
Is there some "I have the same issue" button to avoid creating new comments? 🤔
Confirming this on Godot 4.1 (Built from source a couple weeks ago.) Weirdly enough it doesn't happen in all of my projects, only noticed this in one I created last week.. Maybe some setting's default state was changed, causing the issue? When I'm back home at my PC, I'll compare both of those projects.

**Comment by univeous** [comment]
I'm having a similar issue, but I suspect that in my case it's a Windows bug.
After the computer woke from sleep, all windowed games, not only Godot but Unity or GameMaker games, experience extreme frame rate drops (8~20fps) when shaking the mouse quickly.
A reboot can fix this but I'm still wondering why🤔

**Comment by Swarkin** [comment]
This happens for me on every new project I create.
Strangely, this issue completely disappeared once I capture the mouse like this:
```
func _ready():
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
```

**Comment by Calinou** [comment]
I'd suggest updating to the latest Windows 11 version currently available, as noticed in [this article](https://www.pcgamer.com/julys-windows-11-update-could-be-the-solution-to-your-game-stuttering-woes/).

**Comment by Swarkin** [comment]
@Calinou What about people using Windows 10 tho? I'm not sure if this update will appear there..

**Comment by Calinou** [comment]
> @Calinou What about people using Windows 10 tho? I'm not sure if this update will appear there..

It's unlikely to be backported, as Windows 10 mainly gets security fixes nowadays. In general, if you're running a system for gaming and other high-end use cases, I'd recommend upgrading to Windows 11 or switching to Linux. Windows 10 is not going to be supported forever :slightly_smiling_face:

**Comment by Thoughtquake** [comment]
> I'd recommend upgrading to Windows 11 or switching to Linux.

That's fine advice for end users, but as a developer I want my game to work well on all supported operating systems. Also, many very capable gaming PCs are not supported by Windows 11 due to TPM requirements, so I think there will be more hold-outs than usual for upgrading.

**Comment by Calinou** [comment]
> Also, many very capable gaming PCs are not supported by Windows 11 due to TPM requirements, so I think there will be more hold-outs than usual for upgrading.

It is possible to bypass the TPM/CPU requirements when installing Windows 11. For example, [Rufus](https://rufus.akeo.ie/) can do it for you.

**Comment by Harris170** [comment]
Happend on latest Godot Engine v4.1.1.stable.official.bd6af8e0e on windows 10, and the framerate drop was fixed when i rebooted my PC.

**Comment by okbuss** [comment]
Hi, from my findings, this bug is related to windows MouseDataQueueSize - aswell as mice with high polling rates. If your MouseDataQueueSize is high, then windows tries to optimize mouse inputs my accumulating small movements and outputting them as one. If you have a low MouseDataQueueSize, windows is forced to output every little mouse movement without optimizing them, great for hardcore vidya gamers, but this is too much for unoptimized godot xDD

In my case at least, setting MouseDataQueueSize to 105 fixed a lot of the fps drops, now i only get around -5% fps when moving the mouse in an empty project, and i'd probably get more if i set the MouseDataQueueSize higher (But rip mouse accuracy lol)

Either way, from the way people reacted on my reddit post about this issue (/r/godot/comments/18cemvb), and from the time that this post has been up, i seriously doubt any godot developers will fix this let alone even mention that there engine buckles it's knees when faced with lots of mouse input. The only way seems to be to just keep complaining and maybe in some years they'll do something about how their engine handles massive amounts of mouse input, because even in unity or unreal, i can happily have an absurdly low MouseDataQueueSize and use my 1000hz mouse without any problems.
I literally just wanted to make a game, but this bug has basically stalled my project and burnt my head, and it makes me scared to get too invested into godot in fear that i might find more issues that won't be fixed, and then i would've wasted my time.

**Comment by Calinou** [comment]
Thanks for the findings!

> Either way, from the way people reacted on my reddit post about this issue (/r/godot/comments/18cemvb), and from the time that this post has been up, i seriously doubt any godot developers will fix this let alone even mention that there engine buckles it's knees when faced with lots of mouse input. The only way seems to be to just keep complaining and maybe in some years they'll do something about how their engine handles massive amounts of mouse input, because even in unity or unreal, i can happily have an absurdly low MouseDataQueueSize and use my 1000hz mouse without any problems.

I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by wmboeckman** [comment]
Thought I would add a little bit to this. Not only do I experience this very issue with high polling rate mice (I use a Razer Viper 8k, so I can cause the entire project to hang completely if i circle the mouse fast enough lol)

In my (limited) testing, it seems like the way Godot handles mouse input (in Windows) seems to cause a pretty big difference in FPS in an empty project.

With V-Sync off, with the game window not in focus (and therefore not processing things like mouse input) I get somewhere between 1k-220 fps, with very strange fluctuation. However, when the window is brought into focus, I drop down to only 100-112 fps.

I'm on Godot v4.2, running Windows 11 Version 22H2, Updated to KB5034765.

On older hardware, but still enough to get more frames than shown:
Intel Core i7 6700k, 2x8GB RAM@2500, GTX 1080 w/ 8GB vRAM

Here is a quick clip I recorded of this behavior, including the project file:

https://github.com/godotengine/godot/assets/47402550/63f342ac-6f44-437c-a91f-b8769ea71f8c

[Godot Mouse Polling Bug.zip](https://github.com/godotengine/godot/files/14413476/Godot.Mouse.Polling.Bug.zip)

Running on relatively older hardware, but I should be experiencing higher frames than this, no?

Also, the same effect can be seen on the actual editor window. For example, if you have the profiler open for a running project and move the editor window with a high polling mouse, the profiler will hang!

Really hope this gets prioritized, sure I can use a lower polling rate and be just fine, but anyone else who plays a game I make will have to do the same :/

**Comment by wmboeckman** [comment]
> Thought I would add a little bit to this. Not only do I experience this very issue with high polling rate mice (I use a Razer Viper 8k, so I can cause the entire project to hang completely if i circle the mouse fast enough lol)
> 
> In my (limited) testing, it seems like the way Godot handles mouse input (in Windows) seems to cause a pretty big difference in FPS in an empty project.
> 
> With V-Sync off, with the game window not in focus (and therefore not processing things like mouse input) I get somewhere between 1k-220 fps, with very strange fluctuation. However, when the window is brought into focus, I drop down to only 100-112 fps.
> 
> I'm on Godot v4.2, running Windows 11 Version 22H2, Updated to KB5034765.
> 
> On older hardware, but still enough to get more frames than shown: Intel Core i7 6700k, 2x8GB RAM@2500, GTX 1080 w/ 8GB vRAM
> 
> Here is a quick clip I recorded of this behavior, including the project file:
> 2024-02-26.19-04-39.mp4
> 
> [Godot Mouse Polling Bug.zip](https://github.com/godotengine/godot/files/14413476/Godot.Mouse.Polling.Bug.zip)
> 
> Running on relatively older hardware, but I should be experiencing higher frames than this, no?
> 
> Also, the same effect can be seen on the actual editor window. For example, if you have the profiler open for a running project and move the editor window with a high polling mouse, the profiler will hang!
> 
> Really hope this gets prioritized, sure I can use a lower polling rate and be just fine, but anyone else who plays a game I make will have to do the same :/

Quick update, the weird frame limiting I was experiencing was due to a graphics driver issue, needed a clean install that must have overwritten a bad setting on my end.

Still experience the mouse polling issue, unfortunately.

**Comment by Swarkin** [comment]
The severity that you show in your video at 8000hz happens for me at 1000hz already. I'm running pretty good hardware; overclocked intel i5-9600k and a rx 6700 xt if that matters.

**Comment by jitspoe** [comment]
Just wanted to note that I'm also seeing this issue in Godot 4.3.  I had a test project that was getting over 1000 fps, and when moving the mouse over the window, the framerate halved into the 500's.  If I move the mouse around outside of the window, over the Godot editor, the framerate stays over 900.  However, if I have a different window in the background, such as a web browser, the framerate drops more.

I thought maybe it was some issue with windows drawing the cursor over the window, so I changed the mouse_mode to Input.MOUSE_MODE_CONFINED_HIDDEN and still had the issue.

Also, it seems it's still causing like a 10% framerate hit on lower framerate projects.  I've got one where I'm getting about 75-80, and when moving the mouse outside the window, it doesn't seem to impact the framerate much, but inside the window, I get 68-73 FPS.

I was using this project to test: https://github.com/godotengine/godot/files/14203338/test_omnilight_fade.zip

Note that you can enable/disable the omni lights to change the perf.

**Comment by Calinou** [comment]
Possibly relevant article: https://ph3at.github.io/posts/Windows-Input/

**Comment by okbuss** [comment]
> Just wanted to note that I'm also seeing this issue in Godot 4.3. I had a test project that was getting over 1000 fps, and when moving the mouse over the window, the framerate halved into the 500's. If I move the mouse around outside of the window, over the Godot editor, the framerate stays over 900. However, if I have a different window in the background, such as a web browser, the framerate drops more.
> 
> I thought maybe it was some issue with windows drawing the cursor over the window, so I changed the mouse_mode to Input.MOUSE_MODE_CONFINED_HIDDEN and still had the issue.
> 
> Also, it seems it's still causing like a 10% framerate hit on lower framerate projects. I've got one where I'm getting about 75-80, and when moving the mouse outside the window, it doesn't seem to impact the framerate much, but inside the window, I get 68-73 FPS.
> 
> I was using this project to test: https://github.com/godotengine/godot/files/14203338/test_omnilight_fade.zip
> 
> Note that you can enable/disable the omni lights to change the perf.
> 
> Also note that I'm not doing ANY input handling in the script. Just displaying the FPS.

Hi Jitspoe, i remember watching your tutorials way back in the day and to me it's crazy that this issue has gotten this big and they've STILL not fixed it. it's been a YEAR LMAO
Even running the latest windows on my 128 core nasa computer, a little mouse movement crunches any project right down. We're talking -70% of FPS gone in my case. Frametimes get demolished and stutters make projects more unplayable than any actual FPS drop. And it's not just in own projects, big games like Buckshot Roulette have the exact same problem - almost any game in Godot 4.0+. To test the issue i recommend Rivatuner because it gives you a lot more detail on what's actually happening in godot while it's choking on mouse input. 

I actually managed to get myself away from this engine because of this issue and honestly, there are way more optimized and obscure options out there that don't have an aneurysm when mouse is moved xD, it's why i wasn't active in thread after my post. Thanks

**Comment by mightymochi** [comment]
This pretty much makes the engine a deal breaker for games on Windows. I hope they fix it. Gamers use high resolution mice. It's hard to imagine a game engine that can't support them.

**Comment by Swarkin** [comment]
I havent had issues since I updated to windows 11, but even while i was on 10 the problem is randomly appearing and disappearing for no apparent reason.

**Comment by bunniewormy** [comment]
> This pretty much makes the engine a deal breaker for games on Windows. I hope they fix it. Gamers use high resolution mice. It's hard to imagine a game engine that can't support them.

I think the issue is that majority of people do not even have this problem, else I'm pretty sure it would have been fixed. Personally the issue only really exists for me if I keep my pc running for more than ~12 hours at a time, although I'm not sure why that is. I have noticed that killing some meaningless background processes reduces the amount of stutters as well (although the most reliable method is literally just going down from 1000hz to 125hz polling rate)

Moreover, this issue exists with a lot of games. Personally I've had it in Apex Legends, and a quick google shows that there were players pretty much in every competitive game that had to reduce their mice polling rate from 1k+ hz to lower to deal with the FPS drops

https://ph3at.github.io/posts/Windows-Input/

This post linked before seems to be pretty much exactly what is happening here, with Windows spamming legacy input messages. Godot's input handling seems to be done in `display_server_windows.cpp` if anyone wants to give fixing it a try in the engine, although I am not sure what would be the best approach to take here

**Comment by bunniewormy** [comment]
I've done some testing with the input stuff and my findings are as follows:
- The majority of the FPS drops come from the WM_MOUSEMOVE legacy messages. Doing an early `return 0;` if the `uMsg` in `WndProc` is `WM_MOUSEMOVE` (basically ignoring all WM_MOUSEMOVE messages) significantly reduces the problem, although in my case the FPS drops still persist, just not as strong as before.
- WM_INPUT (raw input) ALSO contributes to the issue, because it doesn't seem like Godot actually uses buffered raw input (mentioned in the article)? I would assume that would be what `Input.use_accumulated_input` is supposed to do, but I don't think it does. 

Disabling both `WM_INPUT` AND `WM_MOUSEMOVE` messages seems to almost completely solve the issue for me; 1000hz mouse goes from being completely unplayable to having stable 144fps (although there's still the possibility that some other Windows legacy input messages might cause stutters from time to time). The blog article I've linked however mentions that raw input is the most precise form for mouse movement, so I suppose if you're making a shooter game you probably don't want to disable it.

Note: disabling WM_MOUSEMOVE makes Godot's GUI on-hover signals unresponsive. For example, Button will no longer emit mouse_entered. However, you can still click those buttons.

On another note, I have no idea why mouse movement even works with both WM_INPUT and WM_MOUSEMOVE disabled, but in my case it continues to work.

I'm not really competent at C++ and I don't really understand majority of the code, but I feel like the best fix for this issue would involve:
1) Adding buffered reading for raw input
2) Giving some kind of control script-side over what legacy messages to filter out and when (and probably filtering out WM_MOUSEMOVE by default)

I don't really understand how to do 1). The windows docs mention it https://learn.microsoft.com/en-us/windows/win32/inputdev/using-raw-input , but I don't exactly understand how to implement that in the context of `display_server_windows.cpp`.

Personally, for my game I'm probably satisfied with a dirty hack which will let me enable and disable WM_INPUT and WM_MOUSEMOVE script-side, so that I can just ignore those messages during actual gameplay and re-enable them when the player wants to interact with the UI. I feel like I'll eventually run into some other issues, but I suppose I would recommend to do the same to people who are willing to compile Godot on their own and don't want to wait or develop any more sophisticated solution

**Comment by Calinou** [comment]
> @Calinou what are your thoughts?

Solution 1. sounds better to me, as 2. sounds like a lot of added complexity for what is essentially a Windows-only issue as far as I can tell.

**Comment by jitspoe** [comment]
> * The majority of the FPS drops come from the WM_MOUSEMOVE legacy messages. Doing an early `return 0;` if the `uMsg` in `WndProc` is `WM_MOUSEMOVE` (basically ignoring all WM_MOUSEMOVE messages) significantly reduces the problem, although in my case the FPS drops still persist, just not as strong as before.

Ah, that explains why if we set `Input.mouse_mode = Input.MOUSE_MODE_CAPTURED`, the issue is reduced:

```C++
		case WM_MOUSEMOVE: {
			if (windows[window_id].block_mm) {
				break;
			}

			if (mouse_mode == MOUSE_MODE_CAPTURED && use_raw_input) {
				break;
			}
```

I guess making sure you're using the captured mouse mode is a workaround for now.

**Comment by Spartan322** [comment]
> I don't really understand how to do 1). The windows docs mention it https://learn.microsoft.com/en-us/windows/win32/inputdev/using-raw-input , but I don't exactly understand how to implement that in the context of `display_server_windows.cpp`.

SDL's implementation may be a contribution to figuring it out: https://github.com/libsdl-org/SDL/blob/d53241a29911011f4846af9be19d497d4c5046fa/src/video/windows/SDL_windowsevents.c#L743

**Comment by dmaz** [comment]
So I'm seeing this too and it's very very noticeable without vsync. In reading this thread, it seems to me (and I may be wrong here) that the key information from the blogpost (and comments) is being missed?

My understanding is that Windows doesn't queue mouse messages when hardware events arrive. Instead, it just sets a flag. The actual messages are generated when GetMessage/PeekMessage are actually called... hence why our hardware can even "process" that number of events in the first place.  So Windows only generates as many messages as we are willing to actually process... if we ask for all of them, then Windows will create all of them... so we don't want to even buffer that many message in the first place right?

**Comment by RPicster** [comment]
I encountered this problem for the first time. I think it is impressive that this issue manages to still be around 3 years after the initial issue opened.

As a developer it is beyond frustrating to know that there are players out there that experience the problem and I am not able to stop it beforehand. These are the type of problems that results in a refund or even worse - a bad review.

It's very hard to spot for a player and can just be interpreted as "game sucks, bad performance".
And even if a player reaches out and explains it, asking them to install a different operating system or changing hardware settings is not a great solution.

**Comment by LlamaSE** [comment]
Want to add my own data to this. I am not running on Linux but I am experiencing similar issues. Depending on how many objects are being managed in the engine the framerate can drop anywhere from 20 to 80 percent below the current average. I am using a mouse with a high polling rate but I have not configured it all since installing Linux so I do not. Exporting to a non-debug build does not seem to have any effect on the issue. I am using Forward+ rendering mode.

**Comment by nanto2016** [comment]
@LlamaSE given how different things fix the problem on different devices I’m not sure there is a single cause to this…

**Comment by LlamaSE** [comment]
> [@LlamaSE](https://github.com/LlamaSE) given how different things fix the problem on different devices I’m not sure there is a single cause to this…

For sure.

Ended up doing more testing later and it seems the root cause (at least for me) is running windowed. I did not have any issues with frame dropping when running in full screen.

**Comment by AlexAnder1946** [comment]
same issue godot 4.4.1 stable, in Windows 11 Home, version 24H2, mouse Logitech G309. 
get an improvement when change mouse way of connection from wifi (like lightspeed mode) to bluetooth. Now, the weird thing is that I put it back on Wi-Fi, and it doesn't get worse, it seems like it just got better on its own. I don't know if it will come back.

**Comment by BarkenBark** [comment]
Seems like dealing with high mouse polling rates on Windows is quite difficult. Perhaps anyone has some insight on how this has been dealt with in other engines or competitive games where mice with high polling rates are popular?

**Comment by clayjohn** [comment]
> Seems like dealing with high mouse polling rates on Windows is quite difficult. Perhaps anyone has some insight on how this has been dealt with in other engines or competitive games where mice with high polling rates are popular?

The short answer is "not well". Many games and engines have similarly poor support to Godot. That is not to say that this isn't a solvable problem. I'm sure there is a solution. It's just a problem that not many people in the industry have invested time in solving and the Godot community appears to be no different.

Unfortunately we are waiting for the perfect combination of a person to take an interest in solving this. They need to develop on or for Windows, have a high polling rate mouse, and have an interest in input APIs. There are very few developers who meet that criteria, which explains why this report has languished as long as it has. 

Further reading for those interested:
https://ph3at.github.io/posts/Windows-Input/

https://learn.microsoft.com/en-us/windows/win32/dxtecharts/taking-advantage-of-high-dpi-mouse-movement

**Comment by GlitchAnims** [comment]
I did some research regarding [this message](https://github.com/godotengine/godot/issues/60646#issuecomment-2471372498) on the thread.
In case anyone's wondering, the easiest solution (that breaks GUI highlight) is going to this method:
`LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)`
And adding this to the first line:
`if (uMsg == WM_MOUSEMOVE || uMsg == WM_INPUT) return 0;`
If you compile like this, you'll get no more weird lag issues when moving your mouse in Windows. However, the above problems will also occur. To be fair, though, it's not a big deal, and you'll only expect WM_INPUT (raw input) to be relevant on first person perspective with MOUSE_MODE_CAPTURED enabled, which locks the mouse to the center of the screen.
Additionally, you can emulate WM_MOUSEMOVE signals through GDS itself by checking how much the mouse has moved on every "visual" frame.

Now,
Windows has "Mouse ballistics", which is just some mouse smoothing shit on their side. So, WM_MOUSEMOVE signal is used for highlighting buttons in Godot, since it assumes the cursor is VISIBLE, and usable as a pointer. Disabling WM_MOUSEMOVE signal by returning 0 early breaks that part.
So, this leads to... Obviously, you don't want to use an altered motion signal for precise motion like First Person Shooter games... Perhaps selectively disabling WM_MOUSEMOVE when in first person mode and disabling WM_INPUT when in UI mode would be a good hack solution, or at least a good start.

I assume WM_INPUT, which is the raw input, is handled badly by Windows when you have a high poll rate mouse.
I don't know much about this shit. But until someone smarter than us can provide a proper solution, you can probably disable one or both of these signals if your game does not require it at all. Personally, I don't need either, so I'll go with the early return 0. Multiplayer is compatible even with different export templates across Linux and Windows, so you won't have to worry about that either. I've tested it.

**Comment by jitspoe** [comment]
I wonder if it would be possible to "bundle up" and defer the mouse movement events.  Rather than just returning early, have some really simple logic to add up the mouse movements, then, if those have been modified, execute the logic that normally happens on those message events on a regular update so the hover logic and whatnot is only executing once per frame.

**Comment by Calinou** [comment]
> I wonder if it would be possible to "bundle up" and defer the mouse movement events. Rather than just returning early, have some really simple logic to add up the mouse movements, then, if those have been modified, execute the logic that normally happens on those message events on a regular update so the hover logic and whatnot is only executing once per frame.

This is already what Godot does with `Input.use_accumulated_input`, which is `true` by default. The issue still occurs with the default setting, so it needs to be fixed at a lower level in the Windows-specific code (the issue doesn't occur on any other platforms). This is what https://ph3at.github.io/posts/Windows-Input/ describes.

I now have a mouse that can go up to 8,000 Hz so I can test branches/PRs that aim to fix the issue, but I don't have time to write code for this in the near future.

**Edit:** I've been able to reproduce the issue on the following setup:

<details open>

<summary>PC specifications</summary>

- **CPU:** AMD Ryzen 9 9950X3D
- **GPU:** NVIDIA GeForce RTX 5090
- **RAM:** 64 GB (2×32 GB DDR5-6000 CL30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Windows 11 24H2
- **Mouse:** ASUS ROG Harpe Ace Extreme (2.4 GHz wireless)
</details>

When V-Synced to 240 Hz, it will drop to ~10 FPS when rapidly moving the mouse with 8,000 Hz polling rate. Less significant FPS drops to 190-200 occur with 4,000 Hz polling rate, and while 2,000 Hz is mostly unaffected on this CPU, it will lead to less stable frametimes that are noticeable in a 480 Hz V-Sync scenario.

**Comment by clayjohn** [comment]
@dmaz if you want to help, you can test the linked PR https://github.com/godotengine/godot/pull/109639 and confirm whether it fixes the issue

**Comment by Poobslag** [comment]
This is still a problem in Godot 4.6.2. I have a Corsair mouse and "worked around" the problem by lowering my mouse polling rate from 1000 Hz to 250 Hz, and by enabling VSync to keep my frame rate at 60 FPS.

I really don't want to have to tell players, "contact your mouse manufacturer for steps to lower your mouse polling rate to play my game," so I hope this is addressed in the future.

**Comment by sorenhoyer** [comment]
I'm also building an FPS game in Godot where the enthusiasts really can tell the difference between 1K 4K and 8K mouse polling rate. And in Godot anything above 1K hz is not really feasable atm. Hopefully that will change in the future.

**Comment by Calinou** [comment]
If you have a mouse with a 2,000 Hz polling rate or higher, please test the updated version of https://github.com/godotengine/godot/pull/109639 on your own projects using the binaries provided in the PR description.

cc @sorenhoyer @Poobslag
