### ISSUE TITLE
New error poped up in 3.5 beta 5 which isn't present in beta 4 with navigation in 3d.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#60735]
### Godot version

3.5b5 mono

### System information

Windows 10, Nvidia gtx 1660Ti, latest drivers, GLES3

### Issue description

I have a test scene with the new navigation in 3d to see how it works.
I moved from beta 4 to beta 5 today and now I get this error which doesn't show in beta 4 (I went back to b4 to double check it).

Everything is in the video here: https://youtu.be/LWD3xOZgDWk

It occurs more when I lower the Target Desired Distance of the NavigationAgent I use.

I don't know if this is a problem with my code or a bug since it appears only in the newer build (b5).

![Godot 3 5b5](https://user-images.githubusercontent.com/33526847/166568979-0cb654bd-7f1c-4b47-9faf-2585668ff24f.png)

### Steps to reproduce

1. Open the project (Beta5 mono version!).
2. Run the project.
3. Let the agents move and then check the debugger, leave them around the end point for a bit with lower desired distance to get the error more times.

Open the project in Beta4 and repeat the steps above to see no error.

### Minimal reproduction project

[NavTest.zip](https://github.com/godotengine/godot/files/8614394/NavTest.zip)

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
I'm presuming you have physics interpolation switched on?

This is a new set of optional warnings introduced in beta 5 in #60531. They can be disabled in `project_settings/debug/settings/physics_interpolation/enable_warnings`, and they only appear in debug builds.

However they are indicating that a VisualInstance (that is interpolated) is having `set_transform()` called during `_process()` (a lot). This will give incorrect results with physics interpolation, and is indicating to you that you should fix this.

See the preliminary docs : https://github.com/lawnjelly/Misc/blob/master/FTIDocs/FTI.md
(I'm currently finishing these to go in the official docs).

Objects that are interpolated generally should only have their transforms set during `_physics_process()` and not `_process()`. Turning physics interpolation on is not always a simple case of switching it on, you often have to make changes to the project in order for it to work correctly.

User game logic code should be moved to `_physics_process()`. In addition, if you are using nodes / features that automatically move interpolated nodes, these must currently also be set to work in `physics` mode rather than `idle`.

Some that have come up as culprits during testing so far are:
* Tween node
* Animation player

It is very possible the navigation node also assumes it can move objects during `_process()`. This is not the case with physics interpolation, and either it needs to be toggled to operate on the physics tick, or we need to add a mode to do this before 3.5 stable.

Another option I have been discussing with @RPicster is whether we can simply have these nodes automatically change to physics process when they are being used with an interpolated node.

This is probably something we will aim to perfect before 3.5 stable, the fact that there was no warning previously did not mean there was not a problem in earlier builds (you just may not have seen it).

One further point, the warning is currently rather "dumb". It just detects a threshold number of calls outside of the physics tick. If you are for example, teleporting objects in `_process()`, or at startup of a level, this is not necessarily a problem, the problem comes with continuously using `set_transform()` on a per frame basis. This is why the warning says "possibly benign".

**Comment by viksl** [comment]
@lawnjelly 
Well, I'll try to keep this brief :).

I just checked and it's true that unchecking the physics interpolation ledas to no errors in the debugger.

When it comes to gdscrip,t I'm in C# so if needed I guess I could change it to gdscript (if really necessary) but since this is a problem that poped up on a mono build and I use C# I added the test scene so it's as close to my own setting as possible.

In case you decide to check the test demo it's only navigatoin with some navigation agents and meshes but the agents themselves are RigidBodies so I don't use any transforms directly anywhere at all, I also don't use Tweens or Animation player.

Maybe my script is flawed in this but from other use cases I understood this is how you use it:

```
// Ready override
_navigationAgent.SetNavigation(navigation);
_navigationAgent.SetTargetLocation(_target.GlobalTransform.origin);

// PhysicsProcess override
var velocity = GlobalTransform.origin.DirectionTo(_target.GlobalTransform.origin) * _speed;

if (!_navigationAgent.IsTargetReached())
{
    _navigationAgent.SetVelocity(velocity);
}

private void OnVelocityComputed(Vector3 safeVelocity)
{
    LinearVelocity = safeVelocity;
}
```

All the examples so far I've seen used it like this, the RigidBody is set to Character mode with Physics Material override to 0 friction.

Maybe setting the LinearVelocity in the OnVelocityComputed method (connected to the appropriate signal in NavigationAgent) should be made differently, because since I don't really have anything else I don't see what transforms could be changing then?

I tried a deferred call instead like this:
```
    private void SetVelocityDeferred(Vector3 safeVelocity)
    {
        LinearVelocity = safeVelocity;        
    }

    private void OnVelocityComputed(Vector3 safeVelocity)
    {
        CallDeferred(nameof(SetVelocityDeferred), safeVelocity);
    }
```
But the result is the same I still get the errors, I do not use Process at all so that's also out of the question at least from my side.
(I have a process on the main scene node to dispaly fps as a text in a label to be precise but that has no influence on the matter even if I remove it).

I've gone through all the nodes and their Inspector but I can't find where I'd be able to switch them to physics from idle, at least not on RigidBody which I'd expect does this automatically, MeshInstance, NavigationAgent or Camera. I don't use other nodes (well apart from my camera setting and some UI container to Stick the fps label to the screen but I've removed all these nodes completely from the scene and the error still popups.

I'm sorry I'm probably just dumb but I don't know where else to look to fix this? I mean I don't change Transforms anywhere at all in my scripts and the demo is really just made to test the basic navigation it's not even from my game with some extra code or so.

Would you please mind telling me what I've overlooked, I'm really probably just stupid here?
Thank you very much.

**Comment by lawnjelly** [comment]
Without a gdscript MRP and being able to debug it, there are a lot of things that could be causing it, very likely the core navigation might need tweaking (rather than a problem on your side). This is why we have betas! :slightly_smiling_face:

If anyone can make a MRP with a simple navigation example in gdscript, with physics interpolation switched on that shows the warning I can investigate and fix this.

**Comment by viksl** [comment]
@lawnjelly I'll make the gdscript example and post it today here in the comments I guess?

**Comment by viksl** [comment]
@lawnjelly 
I think I set the project the same here in gdscript, I hope I didn't miss something, I don't use GDScript so let me know if you feel there's something completely off please :).
The error still pops up
[NavTestGDS.zip](https://github.com/godotengine/godot/files/8624860/NavTestGDS.zip)
.

**Comment by lawnjelly** [comment]
Thanks the project is working great. :+1: 

I'm just debugging, may have to finish tomorrow morning. I suspect we may need to flush the transform notifications after running the physics server when using interpolation, it will be something like that. I don't think there is a problem in your code.

**Comment by akien-mga** [comment]
Fixed by #60763.
