### ISSUE TITLE
SurfaceTool normals can't be smooth when UVs are added

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6146]
Tested on Godot 2.1 beta and 2.1 stable, Windows 10 64 bits

When generating a surface with `SurfaceTool` and the `add_smooth_group(true)` method, it's impossible to get smooth normals if UVs are added to vertices.
I found that it specifically happens when UVs are not increasing from one vertice to another. So if every quad of a surface has UVs going from 0 to 1, the quad will be rendered with hard face normals.
Because of this I am forced to generate normals myself.

Not sure if it's a bug because I believe it was implemented so it does that. But as I said, it's possible to have smooth normals even in that case, so this can be enhanced.

Repro:
[SurfaceToolSmoothShading.zip](https://github.com/godotengine/godot/files/416672/SurfaceToolSmoothShading.zip)
Launch the main scene, see the generated surface on the left with UVs has hard faces, the one on the right doesn't and has smooth faces, while both have a smooth group.

**Comment by Toshiwoz** [comment]
HI @Zylann I was googling in search of the correct way to smooth a code generated mesh and I stumbled upon this.
I am using godot 3.0.4 and, using add_smooth_group as you are I am getting it correctly rendered, with UV.
As it is an old issue it may be that it is not an issue anymore (that it was already fixed)?

**Comment by Calinou** [comment]
@Zylann Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
It still happens:
[SurfaceToolSmoothShading.zip](https://github.com/godotengine/godot/files/4742932/SurfaceToolSmoothShading.zip)

I believe it happens because `SurfaceTool` assumes smoothing can only happen if vertices are shared, and to be shared vertices must have equal attributes. While it's true this case makes them have different UVs, smoothing should still be possible with two vertices with different UV, but two normals having the same value.

**Comment by y0nd0** [comment]
Same here. Is there a workaround to smooth the normals? 

```py
surface_tool.create_from(plane_mesh, 0)
var array_mesh = surface_tool.commit()
data_tool.create_from_surface(array_mesh, 0)
# ...
data_tool.commit_to_surface(array_mesh)
surface_tool.begin(Mesh.PRIMITIVE_TRIANGLES)
surface_tool.add_smooth_group(true)
surface_tool.create_from(array_mesh, 0)
surface_tool.generate_normals()
```

**Comment by y0nd0** [comment]
Same here. Is there a workaround to smooth the normals?
```py
surface_tool.create_from(plane_mesh, 0)
var array_mesh = surface_tool.commit()
data_tool.create_from_surface(array_mesh, 0)
# ...
data_tool.commit_to_surface(array_mesh)
surface_tool.begin(Mesh.PRIMITIVE_TRIANGLES)
surface_tool.add_smooth_group(true)
surface_tool.create_from(array_mesh, 0)
surface_tool.generate_normals()
```
![image](https://user-images.githubusercontent.com/68586847/94995394-4aa17900-059e-11eb-97e6-1de2225163b6.png)

**Comment by akien-mga** [comment]
Fixed by #68034.
