### ISSUE TITLE
Files disappear randomly from favorites

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61937]
### Godot version

126e4d0

### System information

Windows 10 x64

### Issue description

When you add file to favorites, it will eventually disappear after opening the project few times. I don't know what is triggering it yet, might be related to opening the project in multiple editor instances at once.

### Steps to reproduce

1. Right-click file and add it to favorites
2. Wait a couple of days (?)
3. The file is no longer there

**Comment by tricheco** [comment]
Noticed this in `v3.5.rc4.mono.official [e047c5006]` Windows 11 64bit

I am using one editor at a time.

Anecdotal notes:
- it doesn't affect folders
- it doesn't happen when reopening a project (through "Quit to project list")
  - it only happens on reboots over here

**Comment by Leukai** [comment]
Have also noticed this on 3.5 stable (Windows 10 x64) and some prior release candidates.
Seems to only occur after a restart.

**Comment by cosmoddd** [comment]
noticed this in the 4.0 beta 1 as well

**Comment by pink-ink** [comment]
Noticed this in version 3.5.1

**Comment by DamienKusters** [comment]
(Using the Steam version)
After opening a few of the included demo projects, and closing them with CTRL+SHIFT+Q to head back to the Project Manager, all my projects that where stored in a different location where gone from the list. This includes both favorited and non-favorited projects.

**Comment by Calinou** [comment]
> (Using the Steam version)
After opening a few of the included demo projects, and closing them with CTRL+SHIFT+Q to head back to the Project Manager, all my projects that where stored in a different location where gone from the list. This includes both favorited and non-favorited projects.

This is an unrelated issue, as favorite projects are stored differently: https://github.com/godotengine/godot/issues/40968

**Comment by hsandt** [comment]
Confirmed on Linux Ubuntu 22.04, so probably not OS-related.

It happens to me every day or even during a day after project reopen.
Since favorites are stored locally on user machine I suppose, I don't see them on VCS so it takes me some time to realize that it happened, and I cannot describe a specific thing I did just before. I suppose I could temporarily track the favorite folders though, if I know its path.

**Comment by damvcoool** [comment]
It's also happening in 4.1.1.
I only had 1 favorite material, while I create a pipeline of assets, and the material keeps disappearing from Favorites.

**Comment by luislodosm** [comment]
I confirm that it happens in 4.1.1. After some app reboots, randomly. MacOS.

**Comment by passivestar** [comment]
Facing this in Godot v4.1.1.stable - macOS 13.5.2

Doesn't seem to require app reboots.

My minimal reproduction steps:

1. Create a new empty project
2. Create a new script in the FileSystem dock and add it to favourites
3. Create root node in your scene and save the scene
4. The script is gone from favorites!

**Comment by hsandt** [comment]
Where are favorites stored? They must be outside project or we would have spot it with VCS diff (unless I inadvertently put them in .gitignore?). Once we get their location we can setup some diff tracking to stop the exact moment favorites are cleared.

I see a PR is in the works but it also says it's not sure to fix the issue; diff tracking could also help see if the PR solves the issue (if repro is reliable).

**Comment by nikywilliams** [comment]
Confirmed as issue on v4.1.1. Been fighting with it for the last week or so since I started using the Favorites folder.
Windows 10

**Comment by passivestar** [comment]
I no longer have this problem btw, shouldn't this be closed with #82537 ?

**Comment by akien-mga** [comment]
It should, but @KoBeWi used "Solves" which is not one of GitHub's [auto-closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), so it was missed. :upside_down_face: 

Fixed by #82537.

**Comment by KoBeWi** [comment]
That's because I didn't intend to close this issue:
> The issue seems older than that PR, so this probably doesn't solve the original problem.

I identified the bug I fixed as a regression from a PR newer than this issue. There's a chance it's still reproducible.

**Comment by akien-mga** [comment]
Ah indeed. Should we reopen, or assume the older bug might also have been fixed and see if it ever pops up again in 4.2+?

**Comment by KoBeWi** [comment]
Leave it closed. If someone runs into it again, they can comment here or open a new issue.
