### ISSUE TITLE
`always_on_top` breaks non-embedded popups

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62382]
### Godot version

307dfa9

### System information

Windows 10 x64

### Issue description

![godot windows tools 64_NhcQL7sMNX](https://user-images.githubusercontent.com/2223172/175603332-8ca0b109-a3c3-4f43-8af7-d3f14becac0b.gif)
I guess sub-windows should inherit the `always_on_top` flag.

### Steps to reproduce

1. Add any node with popup menu (e.g. TextEdit)
2. Enable `always_on_top` in project settings
3. Disable `embed_subwindows`
4. Run
5. Open the popup menu (right-click TextEdit etc)

**Comment by rainlizard** [comment]
Is this the same issue?

Enabling the `Always on Top` checkbox of a `FileDialog` window makes it so I can't switch the hard drive!

![Untitled](https://user-images.githubusercontent.com/15337628/230762107-54d2ebb0-108f-4774-9c5b-d5521ddb9d73.png)

**Comment by YuriSizov** [comment]
cc @Sauermann you may be interested in this.

**Comment by DmitriySalnikov** [comment]
PowerToys `Always on Top` also breaks popups

https://github.com/godotengine/godot/assets/7782218/e491bbc8-9071-4911-b4e9-5dc1e69bc656

**Comment by AlexOtsuka** [comment]
I was taking a look at this issue last night, and while I wasn't able to come up with a clean fix, here are a few things I've learned that might be helpful to know.

First off, all the previously mentioned issues are still current, and can be consistently reproduced on current master.
Both normal windows and popup menus are `Window` objects. Another important thing to note is that popups are always transient, and a transient window is not allowed to also be on top. For some reason, it's possible to enable both `transient` and `always_on_top` on `FileDialog`, but it does output an error message, at least in Windows:

![image](https://github.com/godotengine/godot/assets/109620202/cf119989-b2b2-4385-9de9-f70776440e36)

Here's a reference for the hierarchy trees below, so that we're on the same page as to which windows I'm referring to.
![image](https://github.com/godotengine/godot/assets/109620202/59a48fc1-9637-4ab4-8336-cd7aeae523e6)

The red arrow represents the drawing order, and the black lines are the parent-child relationships between each window. I use the setup from OP in my example, but the bug mentioned in [one of the comments above](https://github.com/godotengine/godot/issues/62382#issuecomment-1501073547) happens for the exact same reason.

Using the default settings, the windows are drawn according to their hierarchy, and siblings in the order they were created. For this setup, the result is very straightforward:

![image](https://github.com/godotengine/godot/assets/109620202/998236f1-f8a4-4271-9544-47e52dcc96c6)

When `always_on_top` is set to true on a window, it'll always be drawn after every window without that setting, although hierarchy still takes precedence. That means that since transient popups are still children objects of the `always_on_top` main window, they're still drawn in the correct order;

![image](https://github.com/godotengine/godot/assets/109620202/2a162b1c-3316-491d-aa17-913036ddc1bc)

When `embed_subwindows` is disabled, new pop-ups aren't associated with the main window anymore. Instead, I believe they are considered direct children of the screen they're drawn on. However, when the `always_on_top` setting is false, the draw order remains unchanged:

![image](https://github.com/godotengine/godot/assets/109620202/a373059d-548a-4de2-9ff7-1c3bdc84ee53)

When `always_on_top` is true and `embed_subwindows = false` is when it all breaks. This is because as there is no longer a relationship between the main window and its popup windows, the draw order takes precedence and we end up with something like this:

![image](https://github.com/godotengine/godot/assets/109620202/19f9e99d-4c47-4832-9cb4-9a7269ab8814)

One thing I've attempted that looked somewhat promising, was to set `transient` to false and `always_on_top` to true whenever a popup window isn't embedded. While it looked okay, it completely broke submenu popups which is why I mentioned those in this comment. Note that this is a VERY crude approach and completely breaks editor popups as well:

https://github.com/godotengine/godot/blob/655e93d5846b2ef8ebb7d22c8878f51b8f22b312/scene/main/window.cpp#L1811

changed to

```
set_transient(is_embedded());
set_flag(Flags::FLAG_ALWAYS_ON_TOP, !is_embedded());
```

I don't believe this is the way to go at all, but it's how far I've gotten for now.

Perhaps, forcing the parent `Viewport` to embed a transient popup no matter what, or at the very least, figuring out a clean way for it to be taken into consideration when determining the draw order might be an acceptable solution.

Contextual popups are used everywhere in Godot, it's very important for them to be transient, some of this stuff is potentially OS specific and I'm not sure what the correct approach to the problem is. Would love to hear your thoughts and ideas.

**Comment by KoBeWi** [comment]
Seems fixed in 4.3.

**Comment by CsloudX** [comment]
> Seems fixed in 4.3.

Seems it not fixed in 4.3 rc2.
plese test: https://github.com/godotengine/godot/issues/73335

**Comment by KoBeWi** [comment]
Yeah it's not fixed. I probably didn't test enough, sorry.

**Comment by Delsin-Yu** [comment]
Any reason this was postponed to 4.x? This is a pretty serious issue.

**Comment by Sauermann** [comment]
Moving the issue from 4.3 to 4.x was just a way to let people know, that this issue was not resolved during 4.3, so it was just a "documentation"-update.

Godot is a community-driven project, where most bugfixes and enhancements are created by volunteers who try to improve the engine in their spare time. There is no way to guess, when someone from the community finds a way to fix this specific issue.

**Comment by KoBeWi** [comment]
Note that the issue originally had 4.1 milestone. If the milestone is only going to be bumped with every release, there is no reason for assigning specific one.

**Comment by Delsin-Yu** [comment]
I once thought a milestone meant the Godot Officials considered it needed to be done before the associated version; thanks for the explanation.
I guess this issue is `help wanted` for now.

**Comment by KoBeWi** [comment]
> I once thought a milestone meant the Godot Officials considered it needed to be done before the associated version

This mostly applies to recent regressions. If e.g. there is a new bug introduced in 4.4, it will get regression label and 4.4 milestone, with the intention that it's going to be fixed soon (and it mostly is). Recent regressions are also easier to fix, because it's easy to identify what exactly caused them and the original contributor is usually available to fix it.

For older issues though, the milestones were assigned more arbitrarily and we had many cases where they were just bumped with each release. This particular issue is likely as old as DisplayServer changes in Godot 4.0 and is missing someone who would be able to investigate and fix it.

**Comment by bruvzg** [comment]
Reproducible on macOS as well.
