### ISSUE TITLE
Broken hints/tool tips on XWayland and X11 (EditorHelpBit)

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot#62496]
### Godot version

4.0.alpha10

### System information

Fedora 35 Linux (KDE, Wayland), r5 3400g (Vega 11), Vulkan 1.2.0

### Issue description

Tool tips/hints are broken when hovering over properties no matter where (inspector or settings) and it looks like this:
![Screenshot_20220628_224232](https://user-images.githubusercontent.com/71460040/176284001-6cbb9dcc-44a5-4bb6-b899-17be5c6cd35f.png)

### Steps to reproduce

Hover on property.

**Comment by Calinou** [comment]
Did you change the background mode to Canvas in WorldEnvironment?

**Comment by Lasuch69** [comment]
> Did you change the background mode to Canvas in WorldEnvironment?

No. Normal 3D scene

**Comment by Calinou** [comment]
Can you reproduce this in an X11 session? Godot doesn't have native Wayland support, so it relies on XWayland to work (which may have its own bugs).

**Comment by Lasuch69** [comment]
Yes. Output is exactly the same
![Screenshot_20220630_171752](https://user-images.githubusercontent.com/71460040/176714355-ab9b3921-6328-436f-af6e-a9a3c79e38e8.png)

**Comment by Calinou** [comment]
> Yes. Output is exactly the same

It doesn't seem to be exactly the same, according to the screenshots you posted :slightly_smiling_face: 

On XWayland, the bottom part of the tooltip is black. On X11, the bottom part of the tooltip is transparent.

**Comment by Karthik-Dulam** [comment]
The tooltips on buttons seem fine. It could be due to them all being one-liners.
But they still  do persist on other windows similar to this image.
![image](https://user-images.githubusercontent.com/59601648/176847495-7b00d915-907f-4d01-b05a-8d0dca3ee556.png)

**Comment by Lasuch69** [comment]
> Can you reproduce this only with EditorHelpBits (i.e. "fancy" tooltips shown when hovering property names or project settings), or also with simple black tooltips that appear when hovering generic buttons in the editor?

Do you mean for example configuring world environment buttons (in the inspector)? If so then yeah i have problems with those ones too.

**Comment by akien-mga** [comment]
I can reproduce it on Mageia 9, it's a regression introduced between 4.0 alpha 8 (good) and alpha 9 (bad).
A similar issue existed in earlier alphas and was fixed a few months ago, it seems something broke that fix again.

**Comment by akien-mga** [comment]
Random guess, I wonder if that would be due to cfcdfc38e275d8766e69621a001422030e515173 @bruvzg? So when the min size is calculated the RTL is not

**Comment by bruvzg** [comment]
> Random guess, I wonder if that would be due to https://github.com/godotengine/godot/commit/cfcdfc38e275d8766e69621a001422030e515173

Threaded mode should be enabled only for the main help RTL and licenses in the "About" dialog, the rest of controls (including tooltips should not use it).

**Comment by bimmlerd** [comment]
At least related to #61712, if not a duplicate.

**Comment by joao-pedro-braz** [comment]
Still happening with Alpha 13 on:
KDE neon 5.25
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.15.0-41-generic (64-bit)
Graphics Platform: X11

The issue seems to happen only with multiple window support enabled, because otherwise it doesn't happen, as can be seen below.

Without "Single Window Mode":
![image](https://user-images.githubusercontent.com/37230465/181622155-0e6532b8-0f11-4f8b-8ef7-b6980927fcb4.png)

With "Single Window Mode":
![image](https://user-images.githubusercontent.com/37230465/181622263-4d9d6468-9906-424c-b20c-5058107ff5a3.png)

**Comment by akien-mga** [comment]
Duplicate of #61712.
