### ISSUE TITLE
[GDExtension] Vector4 missing functions

### ISSUE THREAD

**Issue by ninfur** [godotengine/godot#65997]
### Godot version

4.0.beta1

### System information

Ubuntu 20.04

### Issue description

I'm trying out GDExtension and found that Vector4 seems to be missing a couple of member functions. The same functions are working on both Vector2 and Vector3.

Compiling the following lines of code results in the errors shown below:
```
    Vector3(1, 2, 3).round();
    Vector3(1, 2, 3).floor();
    Vector3(1, 2, 3).ceil();
    Vector3(1, 2, 3).sign();
    Vector3(1, 2, 3).abs();
    Vector3(1, 2, 3).length();
    Vector3(1, 2, 3).length_squared();
    Vector3(1, 2, 3).lerp(Vector3(6, 7, 8), 0.5);
    Vector3(1, 2, 3).normalized();

    Vector4(1, 2, 3, 4).round();
    Vector4(1, 2, 3, 4).floor();
    Vector4(1, 2, 3, 4).ceil();
    Vector4(1, 2, 3, 4).sign();
    Vector4(1, 2, 3, 4).abs();
    Vector4(1, 2, 3, 4).length();
    Vector4(1, 2, 3, 4).length_squared();
    Vector4(1, 2, 3, 4).lerp(Vector4(6, 7, 8, 9), 0.5);
    Vector4(1, 2, 3, 4).normalized();
```
![compile_errors](https://user-images.githubusercontent.com/100017684/190868595-89ef578b-5db5-431e-abf8-18c47d468a13.png)

I'm not entirely sure how the cpp function binding/wrapping works, but I've verified that the functions it's complaining about exist both in the main godot project (godot/core/math/vector4.h + vector4.cpp):
![vector4](https://user-images.githubusercontent.com/100017684/190869130-8b918b4c-0203-46af-b999-e22322036155.png)

And in the "godot-headers/extension_api.json":
![extension_api](https://user-images.githubusercontent.com/100017684/190869125-7ee19f24-f2b2-492d-a8bc-a24c35c17c6d.png)

Branches: 
godot-cpp: master [3276688] (latest)
godot-headers: master [62e5472] (latest)

### Steps to reproduce

Get the latest master branch of both the [godot-cpp](https://github.com/godotengine/godot-cpp) and [godot-header](https://github.com/godotengine/godot-headers) repositories.

Compile godot-cpp using scons, as described here: https://godotengine.org/article/introducing-gd-extensions

Add the following lines of code anywhere in the example project (for example, godot-cpp/test/src/example.cpp::simple_func()):
```
    Vector4(1, 2, 3, 4).round();
    Vector4(1, 2, 3, 4).floor();
    Vector4(1, 2, 3, 4).ceil();
    Vector4(1, 2, 3, 4).lerp(Vector4(6, 7, 8, 9), 0.5);
```

Compile the example project using scons.

**Comment by touilleMan** [comment]
Hi @ninfur,

It seems those methods were missing in the bindings not so long ago: 7006f7d69318f72017bcfbe21d9fb87cb96b5d7d

So this is most likely an issue with an old version of godot-cpp that have generated it bindings before this fix was merged

**Comment by ninfur** [comment]
Hi @touilleMan,

I cloned the godot-cpp and godot-headers repositories today, and I've verified that they are up to date with the latest commits in the master branch [3276688]/[62e5472]. 

I've also tried to update the bindings again by running "scons target=debug generate_bindings=yes" in the godot-cpp directory, but the problem persists.

I'm not too familiar with generating bindings though. Is there something I'm missing? I have not cloned the main godot repository yet, where the actual Vector4 definitions are located. Do I need to clone that repo and the generate new bindings for godot-cpp somehow?

**Comment by ninfur** [comment]
I  just found that  those functions seem to be missing from godot-cpp/include/godot_cpp/variant/vector4.hpp. Do I manually add them there, or are they auto generated?

**Comment by ninfur** [comment]
I tried manually adding the missing functions to vector4.hpp and got it to compile. However, it now fails to load the compiled gdextension library with error "undefined symbol: _ZNK5godot7Vector45roundEv". Will continue investigating tomorrow.

**Comment by touilleMan** [comment]
> I just found that those functions seem to be missing from godot-cpp/include/godot_cpp/variant/vector4.hpp. Do I manually add them there, or are they auto generated?

I don't know much about the Godot-cppp extension but I think the builtins types are not autogenerated, so you should open a PR to fix this (and they will be able to help you with the undefined error ^^)

**Comment by ninfur** [comment]
The undefined symbol error was simply because I only provided the header definition and not the actual function implementation in godot-cpp/src/variant/vector4.cpp (or inlined in the .hpp). I kind of assumed it would use the same implementation as the main godot project somehow.

However, even then godot crashes when loading the project, with the following error:
![project_load_error](https://user-images.githubusercontent.com/100017684/190896199-5b4e5cf8-6b7f-44b7-84c5-b3b6997527f2.png)

The function in question looks like this:
```
Variant::PTROperatorEvaluator Variant::get_ptr_operator_evaluator(Operator p_operator, Type p_type_a, Type p_type_b) {
	ERR_FAIL_INDEX_V(p_operator, Variant::OP_MAX, nullptr);
	ERR_FAIL_INDEX_V(p_type_a, Variant::VARIANT_MAX, nullptr);
	ERR_FAIL_INDEX_V(p_type_b, Variant::VARIANT_MAX, nullptr);
	return ptr_operator_evaluator_table[p_operator][p_type_a][p_type_b];
}
```

If anyone has any clues, please let me know. In the meanwhile I put up a draft pull request over here: https://github.com/godotengine/godot-cpp/pull/847

By the way, I guess this issue should actually belong to the godot-cpp repository. If anyone has permission to transfer it, then feel free to do so.

**Comment by ninfur** [comment]
Scratch that, I had managed to mess up my godot-headers repository. Resetting it to it's original state fixed that error.

With the changes in the PR I'm now able to both compile and load the gdextension library. Changing it to ready for review.
