### ISSUE TITLE
Shaders using a shader include are not reloaded after editing the include

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#66075]
### Godot version

Godot 4.0 master 90879530

### System information

Windows 10, 64bit

### Issue description

When I edit a shader include and save it I expect all shaders depending on it to be reloaded. It does not happen in practice and there seem to be no manual way to reload shaders, other then editing them one by one manually.

### Steps to reproduce

- Open the attached project.
- Open Scene, it has a sphere using the `Shader` shader
- Open `Include.gdshaderinc` for editing
- Change the color, the sphere on the scene will not change color

**Workaround**
- Open all dependent shaders as well in the editor
- Changing the include files will not reload the shaders

This either need to be fixed or documented as known behavior.

### Minimal reproduction project

[ShaderIncludeNoReload.zip](https://github.com/godotengine/godot/files/9595328/ShaderIncludeNoReload.zip)

**Comment by tinmanjuggernaut** [comment]
There's a high priority element to this issue: first time compiling. On multiple occasions, I've pushed shaders w/ includes to our git repository and my team opens the project to find broken shaders. They have to manually open up the shader plus the includes for them to compile and work. It's very frustrating for teams. I can only imagine this will produce broken games for end users as well.

We get stupid errors like this:

![image](https://user-images.githubusercontent.com/632766/210203461-8a8cc3aa-5e28-4e63-bbdc-cfeaaa159cdb.png)
```
:15 - Tokenizer: Unknown character #35: '#'
  Shader compilation failed.
  ./servers/rendering/renderer_rd/shader_rd.h:140 - Condition "!version" is true. Returning: RID()
```

**Comment by TokisanGames** [comment]
@akien-mga Can this get a bump in priority. It's not `major inconvenience`. It is a `breaking bug` or a `release blocker` for teams and end users as described above, and keeps happening to my team every time we make a major change to shaders with includes.

![image](https://user-images.githubusercontent.com/632766/212084307-d86469e9-ccec-4570-b803-724983b2ebb8.png)

**Comment by Chaosus** [comment]
Alternatively, you can use `Reload Saved Scene` option in the main menu:
![image](https://user-images.githubusercontent.com/3036176/212127539-d7830cc6-46e1-4778-b4ec-fd1a582b38c9.png)

**Comment by TokisanGames** [comment]
Does that option load all shader includes and compile them? I haven't tried it in this situation. If so that's not clear from the name. The problem isn't that the scene or engine needs to be reloaded. Neither of those fix it. It's solely that the first time compile doesn't happen unless the shader include is manually opened. I expect an exported project will also fail.

**Comment by TokisanGames** [comment]
@clayjohn Why was this removed from the issues roadmap and milestones after I asked for higher priority? It's still an issue in GD4 beta 14. 

```
SHADER ERROR: Tokenizer: Unknown character #35: '#'
          at: (null) (:14)
ERROR: Shader compilation failed.
   at: (servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:137)
```

Then I get this error message repeating every second:
```
ERROR: Condition "!version" is true. Returning: RID()
   at: version_get_shader (./servers/rendering/renderer_rd/shader_rd.h:140)
```

Opening up the shader and includes compiles the shader and allows it to work fine, even after a restart without saving anything.

Also @bitsawer 's PR #71878 does not yet fix the issue.

**Comment by bitsawer** [comment]
@TokisanGames I might have a small hunch about what is causing your issues, but I would need a test project to confirm any fixes. It might have something to do with conditonal includes (that is, if an include-directive can be sometimes removed/added by other preprocessor statements. This might throw the resource dependency tracking off sometimes. If I'm right, it's not directly related to this issue, although they are similar. But this is just an educated guess.

**Comment by clayjohn** [comment]
> @clayjohn Why was this removed from the issues roadmap and milestones after I asked for higher priority? It's still an issue in GD4 beta 14.

We can't promise that any particular bug will be fixed in any particular release. The question we ask ourselves when flagging issues as "release blocker" is "are we willing to delay release an indeterminate amount of time while we wait  for this bug to be fixed?" If the answer is "yes", then the bug is a release blocker, if the answer is "no" then we bump to 4.x. 4.x means it can be merged anytime (including for 4.0) It does not mean the bug won't be fixed for 4.0, it just means that we are willing to release without a fix in place if it comes to that.

**Comment by chaeyan** [comment]
this issue still occurs on 4.0.2 stable (7a0977ce2)
<img width="782" alt="Ekran Resmi 2023-05-03 12 11 08" src="https://user-images.githubusercontent.com/32681723/235876470-232fe7d7-2381-4dfa-83ad-7981b1503528.png">
<img width="715" alt="Ekran Resmi 2023-05-03 12 11 21" src="https://user-images.githubusercontent.com/32681723/235876523-e1214e2c-5a45-4f24-873b-11dfd3387b92.png">

**Comment by bitsawer** [comment]
@chaeyan You can create a new issues for that. That specific problem is actually unrelated to this issue, it was just discussed here, so it would be good idea to make a dedicated issue for that.

Also, try to create a minimal test project that demonstrates this problem when you make the issue if you can. There seems to be something specific that triggers this, so fixing it without a test project will be hard. If you manage to make a reproducible test project I can try to take a look at it.

**Comment by TokisanGames** [comment]
The second image shows you have gdscript in your shader file. You must write glsl in shaders, not gdscript. Set_shader_params goes in a gdscript file. 

This is a user error, unrelated to this issue. The issue seems to be resolved for me.
