### ISSUE TITLE
GPUParticles3D broken

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#66267]
### Godot version

v4.0.beta.custom_build [8e14f9ba2]

### System information

windows 10

### Issue description

I can't get any GPUParticles3D to work at all.  Any already existing or even opening a new project.  I'm seeing no errors in verbose debug or debug_release builds.  will pull earlier build to try and find fault 

### Steps to reproduce

for a new test

1. create a scene with with a root GPUParticles3D.
2. in process_material add a ParticleProcessMaterial.
3. in draw_passes/pass1 add a mesh (boxmesh).

**Comment by clayjohn** [comment]
I can reproduce this in latest master (62792eeb9fac4f44272f59f95ec8eb3abc0432a7) but not in beta 1, so this is a recent regression

**Comment by dmaz** [comment]
I've not been able to find a working commit... what I thought was for sure a bug is looking more like maybe an issue with the local build on windows.  I downloaded the built beta and it shows GPU particles fine aside from the fixed "!multimesh" spam.   I pulled multiple versions and non will render a GPU particle though everything else "seems" fine.  I've run both scons clean and git cleans with no difference.  I've removed editor_settings-4 so it's rebuilt.

**Comment by clayjohn** [comment]
> I've not been able to find a working commit... what I thought was for sure a bug is looking more like maybe an issue with the local build on windows. I downloaded the built beta and it shows GPU particles fine aside from the fixed "!multimesh" spam. I pulled multiple versions and none will render a GPU particle though everything else "seems" fine. I've run both scons clean and git cleans with no difference. I've removed editor_settings-4 so it's rebuilt.
> 
> If I build the beta I still get none

I've just reached the same conclusion, I built the beta in debug and have the same issue. I'm now trying to build release_debug from the beta commit and we'll see if that helps. Its not a windows-specific bug as I am on PopOS.

**Comment by dmaz** [comment]
2d9583fa3b works

**Comment by clayjohn** [comment]
> [2d9583f](https://github.com/godotengine/godot/commit/2d9583fa3bf2426dabbdd9e9d9b8fd9725b9436c) works... I'm going to work back up from there

In that case there is a good chance that https://github.com/godotengine/godot/pull/65418 is the culprit

**Comment by dmaz** [comment]
yeah I was wondering... I just pulled the one earlier to test

**Comment by dmaz** [comment]
yep... a9b04b936e works and f709596631 has the issue

**Comment by Calinou** [comment]
>  why does the released beta work I wonder?

Release builds are compiled with LTO enabled, whereas self-compiled builds are not unless you pass `lto=full` SCons option (or the `production=yes` shorthand).

**Comment by dmaz** [comment]
ok trying that...  yeah latest master with lto=full which took a long time to link, still no luck, no particles

**Comment by clayjohn** [comment]
Got a fix figured out. Initialized memory bugs are always a pain :(

**Comment by dmaz** [comment]
I pulled that pr and it doesn't seem to fix the issue.  as mentioned above I also built with lto and that didn't work for me.

**Comment by dmaz** [comment]
wait hold on

**Comment by clayjohn** [comment]
@dmaz do you have more than one particles node in the scene? I've noticed another issue with MultiMesh/particles where they sometimes don't appear in the scene if there is only one node. But seem to always render fine if 2 or more nodes are in the scene.

**Comment by akien-mga** [comment]
I merged the fix for uninitialized memory, I would suggest opening a new issue to keep track of remaining problems with MultiMeshes and particles.

**Comment by dmaz** [comment]
@clayjohn these tests were generally just done with single node scenes.  I do though have a few that were multinode and I'm pretty sure they were having this render issue as well.  I know they are currently having other ender issues.  Also yes, there are a more issues now that I will describe in another ticket.

**Comment by dmaz** [comment]
oh the size issue mentioned above... it seems default size for quads changed to "2"

**Comment by A-Lamia** [comment]
This was closed but particle collisions are still broken and attracter is also not working. 

Tested on #66303.

**Comment by akien-mga** [comment]
That's a separate issue, please open a new bug report.

This report was about particles not rendering at all.
