### ISSUE TITLE
Custom resource as element in exported array in another resource - not saving

### ISSUE THREAD

**Issue by Eks2** [godotengine/godot#66698]
### Godot version

4.0 beta 2

### System information

mac OS 12.6

### Issue description

Hello,

I'm attempting to set an in-built custom resource (`MyResource` below) via the editor inside an array of another parent resource `MyArrayResource`.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/8243388/193404466-f6e87768-920d-4f45-8264-aef4ee02b7fe.png">

When I add one in and make changes to it (changing the default `My Int` from `42` to `43`), it gets added as a `Resource` type - (perhaps I would be expecting a `MyResource` type instead?)

<img width="430" alt="image" src="https://user-images.githubusercontent.com/8243388/193404551-4d27c036-4bc1-4723-9f5a-799a7ea8bf1d.png">

This change doesn't get saved though - when I refresh the view by navigating away from the resource then navigating back, it's now empty

<img width="430" alt="image" src="https://user-images.githubusercontent.com/8243388/193404660-c16beff1-fc3b-4c25-99ff-8664038d7ac9.png">

I've attempted this as a simple field of type `MyResource` instead of an array and it does persist the change successfully.

Last thing - when I try to save an implementation of `MyResource` to a file and load that in (instead of it being in-built) I'm greeted by this message: `The selected resource (Resource) does not match any type expected for this property (MyResource).` 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/8243388/193404800-a0db4778-3cc0-4da6-9003-1889d23b6d19.png">

Just realised - I am able to get this semi-working if I export an `Array[Resource]` instead which is a decent workaround.

### Steps to reproduce

See above, attached a sample project as well

### Minimal reproduction project

[Resource Array Bug Report.zip](https://github.com/godotengine/godot/files/9690082/Resource.Array.Bug.Report.zip)

**Comment by TamerSoup625** [comment]
The bug still persist on 4.0 beta 4, however I also get it with a node's exported array and I get a different error than yours:
```
Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'MyResource' and its derivatives.
```
The bug also _no longer happens_ after reloading the editor.

**Comment by felbecker** [comment]
Just stumbled over this issue in beta 12. I can assign `MyResource`s via the editor to the array, however, when running the project, the array will be empty when accessed in code. The array is shown correctly when I check the remote tree via the editor. I tried the mentioned workaround to export `Array[Resource]` rather than `Array[MyResource]` but with no effect. 

Has someone figured out another workaround since this is progress breaking for my current project unfortunately.

**Comment by vnen** [comment]
I can't reproduce in current master. There has been many fixes for typed arrays, so this one might have been fixed along the way.

**Comment by YouveBeen** [comment]
I believe i have this issue.
This is weird, cause i save my resources as .tres files, my ressource is like so:
CustomResource
¦-CustomResource
¦--Array[CustomResource]

This is weird because i save my resources with a @tool and the array of customresource is saved, i can even load it with my @tool script and it get loaded just fine, but at runtime it doesn't get loaded.
I'll investigate more to see if it's not a mistake on my part but for no it doesn't seemm so. Also i'm using the same function to load the resources in editor and at runtime.

**Comment by YouveBeen** [comment]
Some test:
If i nest my resource like so:
CustomResource
¦-CustomResource
¦-Array[CustomResource]

(So instead my array of custom resources inside another custom resources is directly a child of the root custom resources) it does work.
I still don't understand why my first method works in editor but not at runtime.
I'll try with dictionary now

**Comment by YouveBeen** [comment]
CustomResource
¦-CustomResource
¦--Dictionary{String:CustomResource}

Doesn't work either. Look like some limitation on the "recursiveness" of the resource loading? but only at runtime? Everything is fine in the .tres files tho.
