### ISSUE TITLE
Some issues with custom class documentation generated from comments

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#67704]
### Godot version

v4.0.beta.custom_build [72b845b28]

### System information

Linux Mint 21

### Issue description

The documentation generated from a script has some issues, below is the list of what I noticed so far:

* No line breaking unless using `[br]` (I assume this is on purpose to avoid unwanted line breaks - as a side note, `[br]` adds spacing to the new line)
* Private properties appear in Property Descriptions even though they don't in the Properties list
* Typed arrays always appear as `Array`
* Signal parameters always appear as `Variant`, even when explicitly typed
* Array properties do not show their default values
* Typed arrays cannot be displayed in descriptions by typing `[Array[int]]` for instance, this will only highlight `[int]` and keep the brackets around `Array`.
* I suppose having `virtual` appear next to virtual methods would be nice, but since other private methods are hidden, this should not be an issue.

See MRP for some screenshots of the issues.

### Steps to reproduce

Create a new script, add signals, enums, properties, methods as wanted, then open the help page of the created class.

### Minimal reproduction project

[GeneratedDocumentation.zip](https://github.com/godotengine/godot/files/9837194/GeneratedDocumentation.zip)

I wrote a dummy class to test the documentation feature, here are some screenshots of the issues mentioned above:
* Missing `Array` variable default value:
![image](https://user-images.githubusercontent.com/53737317/197151362-95ebb377-3c1f-4226-bdd4-6d60f7b4c0fb.png)
* Private property in Property Descriptions (also note the descriptions show up even though none of the properties has one):
![image](https://user-images.githubusercontent.com/53737317/197151455-70719728-1610-4094-b117-09bb06b4a713.png)
* Signal parameters are always `Variant`:
![image](https://user-images.githubusercontent.com/53737317/197151985-b13547eb-d833-418c-a579-7befc144c5c8.png)
* Typed arrays as arguments or method return value show up as `Array` (should be `Array[float]` here):
![image](https://user-images.githubusercontent.com/53737317/197152306-19e9476c-5c6f-4004-b841-f27f11a622b9.png)

**Comment by Cykyrios** [comment]
I had a look at the code and found this in editor_help.cpp when populating Property Descriptions:
https://github.com/godotengine/godot/blob/72b845b28773dd40adf6f55b226fb732910cbf14/editor/editor_help.cpp#L1488-L1491
But when creating the Properties list, we have this:
https://github.com/godotengine/godot/blob/72b845b28773dd40adf6f55b226fb732910cbf14/editor/editor_help.cpp#L794-L798
I think we should either check whether the property is private here as well, or filter the list beforehand, as it is done for methods in `_update_method_descriptions`.

As a test, I copy-pasted the above code and it fixes this particular issue, private properties no longer appear in Property Descriptions.

**Comment by dalexeev** [comment]
> * No line breaking unless using `[br]`

This is intentional and [documented](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html).

![](https://github.com/godotengine/godot/assets/47700418/4882c999-c10a-4281-ad48-c7e1e61e3945)

> * `[br]` adds spacing to the new line

* Fixed by #75043.

> * Private properties appear in Property Descriptions even though they don't in the Properties list

* Fixed by #67707.

> * Typed arrays always appear as `Array`

> * Signal parameters always appear as `Variant`, even when explicitly typed

> * Array properties do not show their default values

* Will be fixed by #79366.

> * Typed arrays cannot be displayed in descriptions by typing `[Array[int]]` for instance, this will only highlight `[int]` and keep the brackets around `Array`.

TODO. This is an Editor Help issue. You can use `[Array][[int]]` as a workaround.

> * I suppose having `virtual` appear next to virtual methods would be nice, but since other private methods are hidden, this should not be an issue.

I didn't quite understand what you meant. Perhaps the point is outdated and it has been fixed?

![](https://github.com/godotengine/godot/assets/47700418/57d9d041-b341-4565-a308-c35d2a4be347)

**Comment by Cykyrios** [comment]
> > * I suppose having `virtual` appear next to virtual methods would be nice, but since other private methods are hidden, this should not be an issue.
> 
> I didn't quite understand what you meant. Perhaps the point is outdated and it has been fixed?
> 
> ![](https://user-images.githubusercontent.com/47700418/254252615-57d9d041-b341-4565-a308-c35d2a4be347.png)

This last point is only true for built-in virtual functions, I think. If I make a custom script and document a function that has an underscore as its first character, it is treated as a normal function. (see last screenshot in the OP, this still appears the same after pulling the latest commits on the master branch, but I do see "virtual" next to built-in Node functions like in your screenshot)

**Comment by dalexeev** [comment]
I still don't understand what you mean, sorry.

All non-static GDScript functions are [virtual](https://en.wikipedia.org/wiki/Virtual_function), since the method implemented in the derived class is called (static functions have some issues: #72973, #77895). Adding the qualifier to the user documentation makes no sense and can be confusing since the `virtual` keyword (unlike `static`) is not present in GDScript.

When overriding a virtual built-in method, the user documentation no longer displays the `vitual` qualifier. In my opinion, this is also correct.

```gdscript
## _ready() override.
func _ready() -> void:
    pass
```

![](https://github.com/godotengine/godot/assets/47700418/ce0f94dd-a9d0-423d-bc9d-5b12342f27af)

**Comment by Cykyrios** [comment]
I agree it is correct not to show "virtual" next to an overridden method, and as it would probably be too much of a hassle to determine if a method is supposed to be overridden in the parent class, this point is probably moot. I was just thinking it could be nice to _know_ in the custom documentation if a method was virtual or not.

**Comment by dalexeev** [comment]
> it could be nice to _know_ in the custom documentation if a method was virtual or not.

Do you mean the "overrides [class name]" text (like for the properties) and the blue arrow indicator? If so, then this is more of a proposal than a bug.

![](https://github.com/godotengine/godot/assets/47700418/f157af2f-a9a7-4aea-aed9-af62e9eefb5d)
![](https://github.com/godotengine/godot/assets/47700418/b3a2adfe-438f-4725-b80a-11fe980d110f)

**Comment by Cykyrios** [comment]
What I meant initially was just having "virtual" next to the method, just like the built-in ones in the Node class that you showed in your screenshot (when documenting a script with a method that you intend to be overridden). Pretty much in the same way that methods starting with an underscore are private by convention, those starting with an underscore, but documented, could be considered virtual by convention as well. I agree though this is more of a proposal than a bug either way.
