### ISSUE TITLE
Texture2D "convert_colors_with_editor_theme" import flag seems to do nothing

### ISSUE THREAD

**Issue by SleepyTonia** [godotengine/godot#67929]
### Godot version

4.0 beta 3

### System information

Linux Manjaro 6.0.3 (KDE Plasma 5.26.1 X11), AMD Ryzen 2500U, Radeon Vega 8

### Issue description

I'm working on an editor plugin which adds various controls and types, all with their own svg icons. I follow the same color palette [used by Godot's own icons](https://github.com/godotengine/godot/blob/475592a3bc2d2150dcbd9179fff653e3c55505a1/editor/editor_themes.cpp#L152-L254) and have turned on the `scale_with_editor_scale` and `convert_colors_with_editor_theme` flags [from this merged pull request](https://github.com/godotengine/godot/pull/64938) before re-importing all those icons. While the icons do scale up properly when I change the editor's scale (200% looks hilarious on my 1080p monitors) the colors don't change as they should when I switch between light and dark modes, whether the icon is given to an editor button, added in a class description with `[img]` or used as a class icon with `@icon`. Even when restarting the editor either with a dark or light icon theme. I've also tried borrowing Dialogic's own icon to see if I was doing something wrong on that end and it didn't work either.

### Steps to reproduce

Create a project and give it plugin buttons or classes with a properly imported (With `convert_colors_with_editor_theme` set to true) svg icon following the proper color palette, then alternate between dark and light modes. The attached reproduction project has just that.

### Minimal reproduction project

[Icons_64938.zip](https://github.com/godotengine/godot/files/9875608/Icons_64938.zip)

**Comment by YuriSizov** [comment]
The most likely culprit is the format in which the colors are stored. The system for color replacement in SVGs in the Godot editor is very rudimentary and doesn't work with arbitrary SVGs. It looks specifically for attributes, expressed like this:

```cpp
	if (p_color_map.size()) {
		_replace_color_property(p_color_map, "stop-color=\"", p_string);
		_replace_color_property(p_color_map, "fill=\"", p_string);
		_replace_color_property(p_color_map, "stroke=\"", p_string);
	}
```

It seems your icons have colors inside of the `style` attribute instead, using CSS format. This is not supported at the moment.

**Comment by SleepyTonia** [comment]
Following the documentation I found there: 
[https://docs.godotengine.org/en/latest/development/editor/creating_icons.html](https://docs.godotengine.org/en/latest/development/editor/creating_icons.html)
I shrank down one of my SVG icons to this: (With added line breaks for readability)
```svg
<svg height="16" viewBox="0 0 4.2333332 4.2333335" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="m3 0c-.5539988 0-1 .44600109-1 1v13c0 .554.4460012 1 1 1h5.0000001 4.9999999c.553999 0 1-.446001 1-1v-4.9999999-8.0000001c0-.55399891-.446-1-1-1zm0 1h10v1h-10zm0 2h10v1.0000001h-10zm0 2.0000001h10v1h-10zm0 2h10v1h-10zm0 2h5.0000001 1.9999999 1 2v.9999999h-4.9999999-5.0000001zm0 1.9999999h5.0000001 4.9999999v1h-4.9999999-5.0000001zm0 2h5.0000001 4.9999999v1h-4.9999999-5.0000001z" fill="#e0e0e0" fill-rule="evenodd" stroke-dashoffset="4.2" stroke-linecap="square" stroke-width="2.5" transform="scale(.26458333)"/>
<path d="m2.38125 2.116667h1.058333v.79375h-1.058333z" fill="none"/>
</svg>
```
And even when I re-import with the flag set to off, then back to on, then reload the editor (Godot 4.0 Beta 5 as of now) nothing changes. I understand the expected constraints and I'm more than happy to work with those! No big deal when it's for a niche purpose such as this. I just still seem to be getting something wrong…

**Comment by scriptsengineer** [comment]
![image](https://user-images.githubusercontent.com/1673249/232215405-cb27d4ad-5206-4314-88b5-33c7cfb2107a.png)
It worked for me when choosing this option in inkscape (Save as optimized svg)

**Comment by scriptsengineer** [comment]
Still investigating that some icons which have additional colors like my icon contains (+) symbol (5fff97) color did not convert even though the same editor icon did convert.
![image](https://user-images.githubusercontent.com/1673249/232223511-ced2bfd6-2934-4eab-9c1f-1f2a5047faf7.png)

**Comment by andrejp88** [comment]
I'm seeing the same thing, but scaling is affected too. Oddly enough, both scale and color conversion is applied in the icon's thumbnail in the FileSystem dialog, but not in the SceneTree or in the list of nodes when adding a new node. I had to run the icons through `svgcleaner` to even get to this point though. Before that they didn't even show up right in the FileSystem dock.

I also notice that the editor's current scale and color theme are stored in those icons' corresponding `.import` files. That sort of stuff is going to vary between installations, but to my understanding `*.import* files are supposed to be committed to version control, so it seems like the sort of thing that would cause some annoyance when committing files.

**Comment by YuriSizov** [comment]
> I also notice that the editor's current scale and color theme are stored in those icons' corresponding `.import` files. That sort of stuff is going to vary between installations, but to my understanding `_.import_ files are supposed to be committed to version control, so it seems like the sort of thing that would cause some annoyance when committing files.

This oversight has been reported already, there is a PR: https://github.com/godotengine/godot/pull/75949

> Oddly enough, both scale and color conversion is applied in the icon's thumbnail in the FileSystem dialog, but not in the SceneTree or in the list of nodes when adding a new node.

Both tweaks are applied upon the import, not upon usage. Everything uses the same texture, so you shouldn't see any differences. Unless you change something, then you might need to manually hit the Reimport button or restart the editor. There are also some issues with the editor support of icons for custom types, but it should be fixed in 4.1: https://github.com/godotengine/godot/pull/75472

**Comment by andrejp88** [comment]
> it should be fixed in 4.1

I just compiled Godot on the master branch and tried it out, and can confirm that I'm not seeing the problem anymore. All custom class icons work perfectly, colors and scaling are adjusted flawlessly.

It's such a nice feeling when you learn a bug was fixed before you even get the chance to notice it, and when the project's development is transparent enough for that to happen :) Thanks for the great work and for the quick response!

**Comment by SleepyTonia** [comment]
I just compiled the current master and it's still present in my case for the most part… The icons for my addon now *do* change colors with the editor theme as expected, but only in the filesystem dock and svg preview in the inspector. Not in the editor's interface. Re-importing from the editor or restarting the editor didn't help either…  
  
The color change also only happens when the svg file has been modified and re-loaded by the editor. Going in the Import dock to try and force the editor to re-import the image does nothing.

In light text/icon mode:
![image](https://user-images.githubusercontent.com/74564818/232335125-d80d6fab-5b28-4223-a99b-cbb98c3b96dc.png)
And in dark mode:
![image](https://user-images.githubusercontent.com/74564818/232334834-2450501f-9895-4c15-afe0-2c58265a52fe.png)

However any other changes, the most important ones, don't seem to happen properly.
![image](https://user-images.githubusercontent.com/74564818/232334850-978e39a4-2a28-4095-8579-d272b608bb2e.png)
![image](https://user-images.githubusercontent.com/74564818/232334907-0ea5183e-a92e-49a4-b9f1-aed57bcdc959.png)
![image](https://user-images.githubusercontent.com/74564818/232335315-6d1fbc2d-f7fd-49e5-820a-a3ac5def2f7e.png)
