### ISSUE TITLE
Latest commit breaks debugging

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#6933]
**Operating system or device - Godot version:**
macOS 10.12 (Sierra) - Godot-master c67e3a485dedae96b82c3356d5f45ab0509d7759

**Issue description** (what happened, and what was expected):
This commit somehow broke debugging: when playtesting, nothing gets printed in the console and nothing gets shown in the debug window.

I had to revert to the commit before this one in order to get debugging working again.

**Steps to reproduce:**
Just play test _any_ scene.

**Comment by akien-mga** [comment]
CC @punto- and @Faless.

**Comment by vnen** [comment]
Note that debugging runs over network (even in the same machine). That's likely the "somehow.

**Comment by Keyaku** [comment]
@vnen Gah, silly me.

How do I make that work, then?

**Comment by akien-mga** [comment]
@Keyaku He meant that for potential developers that would fix the bug, not as a hint for you that you might be doing something wrong ;) Your best bet is to waiting for the bug to get fixed by whoever knows how to do it :)

**Comment by bojidar-bg** [comment]
Can confirm :smile:

**Comment by bojidar-bg** [comment]
Ok, finally found the issue.. the editor listens on IPv4, while the game polls on IPv6... :open_mouth: 
It mainly comes from here: [`drivers/unix/tcp_server_posix.h:43`](https://github.com/godotengine/godot/blob/master/drivers/unix/tcp_server_posix.h#L43) or here: [`tools/editor/script_editor_debugger.cpp:1103`](https://github.com/godotengine/godot/blob/master/tools/editor/script_editor_debugger.cpp#L1103)

@punto- any reason listen has ipv4 as default? (or @Faless, if you know)

**Comment by UgisBrekis** [comment]
Can confirm as well on Windows 10, 914015f3b63dd956e72ea937d46ea4b2db005ada

**Comment by olsonjeffery** [comment]
Repro'd on OSX Sierra, 8321e48a .. also looks like print calls aren't printing to the Output window in the editor (they still appear in the terminal output when godot is ran from the CLI, tho)
