### ISSUE TITLE
Clicking an empty/<Unnamed Material> material slot in advanced import settings for a GLB crashes the editor

### ISSUE THREAD

**Issue by jss2a98aj** [godotengine/godot#69741]
### Godot version

4.0 beta 7

### System information

Windows 7, Linux Mint 21 Xfce

### Issue description

When trying to assign a material in the advanced import options menu for a GLB that has an empty material slot the editor crashes. Impacted slots are always labeled \<Unnamed Material\>, although in this case they had names set in Blender before being exported from it. This happens on both my Windows 7 and Linux Mint systems.

### Steps to reproduce

1: Open the minimal reproduction project.
2: Double click the wall_hedge_crawl_end.glb file in the FileSystem toolbox to open the advanced import settings menu.
3: Click the materials tab.
4: Click on one of the <Unnamed Material> materials.
The editor should hang and then crash or just crash immediately.

### Minimal reproduction project

[GLBCrashReproduction.zip](https://github.com/godotengine/godot/files/10180847/GLBCrashReproduction.zip)

**Comment by Calinou** [comment]
This was supposedly fixed by https://github.com/godotengine/godot/pull/59834 (see https://github.com/godotengine/godot/issues/54807).

**Comment by akien-mga** [comment]
I can reproduce the bug with the above steps in 4.0-beta7 and current `master` (a7937fe54cd2c1f407a529e46e2708aea5ce7243).

Stacktrace:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x00000000085addf8 in CowData<TreeItem::Cell>::_get_size (this=0x190) at ./core/templates/cowdata.h:81
81                      if (!_ptr) {

(gdb) bt
#0  0x00000000085addf8 in CowData<TreeItem::Cell>::_get_size (this=0x190) at ./core/templates/cowdata.h:81
#1  0x00000000085a7994 in CowData<TreeItem::Cell>::size (this=0x190) at ./core/templates/cowdata.h:131
#2  0x00000000085a0d60 in Vector<TreeItem::Cell>::size (this=0x188) at ./core/templates/vector.h:90
#3  0x0000000008577b07 in TreeItem::select (this=0x0, p_column=0) at scene/gui/tree.cpp:1030
#4  0x00000000079935f7 in SceneImportSettings::_select (this=0x120b6190, p_from=0x12162b10, p_type=..., p_id=...) at editor/import/scene_import_settings.cpp:738
#5  0x0000000007993db2 in SceneImportSettings::_material_tree_selected (this=0x120b6190) at editor/import/scene_import_settings.cpp:808
#6  0x00000000079ab123 in call_with_variant_args_helper<SceneImportSettings>(SceneImportSettings*, void (SceneImportSettings::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (
    p_instance=0x120b6190, p_method=(void (SceneImportSettings::*)(SceneImportSettings * const)) 0x7993c1c <SceneImportSettings::_material_tree_selected()>, p_args=0x0, r_error=...)
    at ./core/variant/binder_common.h:262
#7  0x00000000079aad8a in call_with_variant_args<SceneImportSettings> (p_instance=0x120b6190, 
    p_method=(void (SceneImportSettings::*)(SceneImportSettings * const)) 0x7993c1c <SceneImportSettings::_material_tree_selected()>, p_args=0x0, p_argcount=0, r_error=...) at ./core/variant/binder_common.h:376
#8  0x00000000079aaaa4 in CallableCustomMethodPointer<SceneImportSettings>::call (this=0x121a4130, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:104
#9  0x0000000009e9282f in Callable::callp (this=0x2542c238, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#10 0x000000000a194a30 in Object::emit_signalp (this=0x12162b10, p_name=..., p_args=0x0, p_argcount=0) at core/object/object.cpp:1046
#11 0x0000000006287fd5 in Object::emit_signal<>(StringName const&) (this=0x12162b10, p_name=...) at ./core/object/object.h:868
#12 0x00000000085899dd in Tree::select_single_item (this=0x12162b10, p_selected=0x121ae530, p_current=0x121ae530, p_col=0, p_prev=0x0, r_in_range=0x0, p_force_deselect=false) at scene/gui/tree.cpp:2514
#13 0x0000000008589c6b in Tree::select_single_item (this=0x12162b10, p_selected=0x121ae530, p_current=0x7fffa0001f20, p_col=0, p_prev=0x0, r_in_range=0x0, p_force_deselect=false) at scene/gui/tree.cpp:2551
#14 0x000000000858b374 in Tree::propagate_mouse_event (this=0x12162b10, p_pos=..., x_ofs=0, y_ofs=0, x_limit=284, p_double_click=false, p_item=0x121ae530, p_button=MouseButton::LEFT, p_mod=...)
    at scene/gui/tree.cpp:2780
#15 0x000000000858c1a4 in Tree::propagate_mouse_event (this=0x12162b10, p_pos=..., x_ofs=0, y_ofs=0, x_limit=284, p_double_click=false, p_item=0x7fffa0001f20, p_button=MouseButton::LEFT, p_mod=...)
    at scene/gui/tree.cpp:2942
#16 0x00000000085900fe in Tree::gui_input (this=0x12162b10, p_event=...) at scene/gui/tree.cpp:3647
#17 0x0000000008308c5f in Control::_call_gui_input (this=0x12162b10, p_event=...) at scene/gui/control.cpp:1713
#18 0x0000000008205c74 in Viewport::_gui_call_input (this=0x120b6190, p_control=0x12162b10, p_input=...) at scene/main/viewport.cpp:1326
#19 0x0000000008206b6b in Viewport::_gui_input_event (this=0x120b6190, p_event=...) at scene/main/viewport.cpp:1559
#20 0x000000000820e74e in Viewport::push_input (this=0x120b6190, p_event=..., p_local_coords=false) at scene/main/viewport.cpp:2796
#21 0x000000000824cd68 in Window::_window_input (this=0x120b6190, p_ev=...) at scene/main/window.cpp:1096
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x0000000008272e60 in call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul> (p_instance=0x120b6190, 
    p_method=(void (Window::*)(Window * const, const Ref<InputEvent> &)) 0x824c976 <Window::_window_input(Ref<InputEvent> const&)>, p_args=0x7fffffffc8d8, r_error=...) at ./core/variant/binder_common.h:262
#23 0x00000000082703ed in call_with_variant_args<Window, Ref<InputEvent> const&> (p_instance=0x120b6190, 
    p_method=(void (Window::*)(Window * const, const Ref<InputEvent> &)) 0x824c976 <Window::_window_input(Ref<InputEvent> const&)>, p_args=0x7fffffffc8d8, p_argcount=1, r_error=...) at ./core/variant/binder_common.h:376
#24 0x000000000826d146 in CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call (this=0x120bfed0, p_arguments=0x7fffffffc8d8, p_argcount=1, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:104
#25 0x0000000009e9282f in Callable::callp (this=0x7fffffffc880, p_arguments=0x7fffffffc8d8, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#26 0x00000000052cd227 in DisplayServerX11::_dispatch_input_event (this=0xbf933c0, p_event=...) at platform/linuxbsd/x11/display_server_x11.cpp:3297
#27 0x00000000052ccf9f in DisplayServerX11::_dispatch_input_events (p_event=...) at platform/linuxbsd/x11/display_server_x11.cpp:3268
#28 0x0000000009e37c05 in Input::_parse_input_event_impl (this=0xb943670, p_event=..., p_is_emulated=false) at core/input/input.cpp:663
#29 0x0000000009e38f0e in Input::flush_buffered_events (this=0xb943670) at core/input/input.cpp:885
#30 0x00000000052d1c20 in DisplayServerX11::process_events (this=0xbf933c0) at platform/linuxbsd/x11/display_server_x11.cpp:4294
#31 0x00000000052b4710 in OS_LinuxBSD::run (this=0x7fffffffd1a0) at platform/linuxbsd/os_linuxbsd.cpp:874
#32 0x00000000052ac180 in main (argc=2, argv=0x7fffffffd718) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

**Comment by trollodel** [comment]
The cause (and the stacktrace) is different from #54807 which should still be fixed (tested with a similar MRP).
Seems to happen because the mesh has 2 surfaces with empty materials, but I need to investigate more.

**Comment by TerraDev64** [comment]
This issue still exists in Beta 14.

I'm sorry but I can't post the logs (like the one from Akien) of the crash, because I don't know where to find them.
Where do I find the crash logs?
