### ISSUE TITLE
Vulkan Mobile: Changing 3D scaling amount with Bilinear/FSR scaling modes creates multiple errors on Output console/Debugger

### ISSUE THREAD

**Issue by wokeraccoon** [godotengine/godot#70093]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Fedora Linux 37, AMD RX 6600, AMD Ryzen 7 3700x

### Issue description

When using the `mobile` renderer instead of the `forward_plus` renderer and then increasing or decreasing the scaling, the Output console print these error messages on what I'm assume is every frame:

`  All textures in a framebuffer should be the same size.`
`./servers/rendering/renderer_rd/effects/../storage_rd/../framebuffer_cache_rd.h:170 - Condition "rid.is_null()" is true. Returning: rid`

![image](https://user-images.githubusercontent.com/13603525/207768247-c6705cec-534c-45a3-a3bc-e77b07f8ddcf.png)

When running an scene, the engine prints similar errors to the Debugger in the Errors tab:

![image](https://user-images.githubusercontent.com/13603525/207768422-b86e44c4-fa83-4cc9-90e3-5f58a76aaa54.png)

Using `forward_plus` does not exhibit the same problems.

### Steps to reproduce

1.  Create a new project with a 3D Scene with at least one camera
2.  Go to Project Settings, enable Advanced Settings and go to `rendering/renderer/rendering_method` and switch from `forward_plus` to `mobile`
3. Go to `rendering/scaling_3d/scale` and increase or decrease the slider
4. Watch the Output console overflow with the same two errors
5. Run the scene
6. Watch the Errors tab in the debugger overflow with the same errors

### Minimal reproduction project
[test-bug.zip](https://github.com/godotengine/godot/files/10233588/test-bug.zip)

Open the project. It's already set up with a camera, lighting and a cube mesh and the renderer is already using the `mobile` renderer with the scaling set to 0.64. The console should be already outputting the same errors.

**Comment by Calinou** [comment]
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
I'll have a look at this next week, I've been wanting to dive back into this to implement that proposal I did a while ago to properly type things. There must be a place in the code where we're forgetting to resize a buffer.

**Comment by lattalayta** [comment]
I am also getting this error when using the mobile renderer and adjusting the render3D scaling in Godot 4.0.2

**Comment by marius-se** [comment]
Does this have any effects, besides console spam? I'm getting the same error messages.

**Comment by Bimbam360** [comment]
Chipping in to add the following error spam on the latest 4.1.dev when using a non 1.0 scaling amount:

E 0:00:04:0691   get_color_fbs: Condition "target_size != internal_size" is true. Returning: RID()
  <C++ Source>   servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:256 @ get_color_fbs()

**Comment by clayjohn** [comment]
Looks like this issue was fixed for 4.0 and then re-introduced into 4.0.1 with https://github.com/godotengine/godot/pull/74150

But looking at the code, I can't understand why

CC @BastiaanOlij

**Comment by Calinou** [comment]
In my experience, 2D MSAA also looks broken in the Forward+ renderer when using 3D Scaling.

**Comment by BastiaanOlij** [comment]
I'll see if I can dive into this over the weekend, currently trying to get some momentum going with some of the other changes I'm working on :)

**Comment by Janblu** [comment]
I'm getting this error in 4.1.stable, setting the rendering/scaling_3d/scale to 1 and not changing it at runtime removes the error.

**Comment by Delocop** [comment]
I'm on 4.1 Stable and I'm still getting this problem. Moving my project to forward+ does remove the error spam.

**Comment by mahdisml** [comment]
This error is happening again in 4.1.1 Mobile Renderer (When i Change the Scale Value to 0.5) :

![image](https://github.com/godotengine/godot/assets/1758504/5e5bf983-c1a1-4d38-b398-8f6e92f5102c)

**Comment by Calinou** [comment]
> This error is happening again in 4.1.1 Mobile Renderer (When i Change the Scale Value to 0.5) :

The pull request hasn't been cherry-picked to `4.1` yet, and no 4.1.x release has been made with the pull request either.
