### ISSUE TITLE
GDScript 2.0: type assignment is broken with Godot4 beta9

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#70364]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Windows 10

### Issue description

After upgrade from Godot4 beta 8 to beta 9, my scripts are broken by script parsing errors.
It looks like the type assignment are broken.

![image](https://user-images.githubusercontent.com/347037/208750482-40e7ada0-0745-4d1c-abf4-89602a9b4cbd.png)

### Steps to reproduce

Godot Engine v4.0.beta9.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:61 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  res://test.gd:6 - Parse Error: Could not infer the type of the variable "arg_default" because the initial value is a variant. Use explicit "Variant" type if this is intended.
  res://test.gd:11 - Parse Error: Could not infer the type of the variable "x2" because the initial value is a variant. Use explicit "Variant" type if this is intended.

### Minimal reproduction project

[assign_bug.zip](https://github.com/godotengine/godot/files/10271850/assign_bug.zip)

**Comment by anvilfolk** [comment]
The two errors appear to be two different issues caused by two different commits.

The first error `var arg_default := UNDEFINED` appears to be due to #69471 cc @rune-scape who can probably fix it way faster than I could :)

Will bisect the other issue and come back :)

I will dig into the second one

**Comment by anvilfolk** [comment]
Second issue is from #69518 cc @rune-scape

Sorry to keep throwing stuff at you :) At least I hope some of these are helpful to track stuff down. I don't know that I have it in me for right now.

**Comment by vonagam** [comment]
I have #69163 which should fix the second issue.

**Comment by anvilfolk** [comment]
Good stuff, sounds like we're well on our way to getting these issues fixed :)

**Comment by rune-scape** [comment]
as for the first one, i didn't change the code responsible for that error, it should have given the same error in the last beta based on this:
https://github.com/godotengine/godot/blob/2a04b18d37de6c6e621db5a9dfd1cd0da5ccb015/modules/gdscript/gdscript_analyzer.cpp#L825-L826
and this:
https://github.com/godotengine/godot/blob/2a04b18d37de6c6e621db5a9dfd1cd0da5ccb015/modules/gdscript/gdscript_analyzer.cpp#L1755-L1756
it seems like collapsing this `is_variant()` and the `has_no_type()` branch into an `is_hard_type()` check would make more sense,

**Comment by vonagam** [comment]
I have not touched the first issue in that PR because the error explicitly said that inference should not work with `Variant` (it does not say anything about explicitly or implicitly specified). So I left it as it is. Cool if it will be allowed for explicit variants.

**Comment by rune-scape** [comment]
> I have #69163 which should fix the second issue.
@vonagam i tested the build artifact with the MRP and it doesn't fix the issue, you'd need to check if they are reduced constants, then check the type of the reduced value
but i think reverting the null as variant part of https://github.com/godotengine/godot/pull/69518 
instead of adding a null check to `reduce_binary_op()` would be better

**Comment by anvilfolk** [comment]
> as for the first one, i didn't change the code responsible for that error, it should have given the same error in the last beta based on this:

I did test that it worked on beta 8 and didn't on beta 9, and did a git bisect which did identify the out-of-order member resolution PR as the introduction of regression for the first thing. I was really confused too, because being able to resolve things in different orders shouldn't change their types :/

**Comment by vonagam** [comment]
It was working before but now that `null` is not built-in Nil other things are broken too:
```gdscript
var x := null
```
It works now (when it should not), because other parts of code expect `null` to be `kind == GDScriptParser::DataType::BUILTIN && builtin_type == Variant::NIL`.

So yeah, this change in `type_from_variant` needs to be reverted. 

But "adding a null check to `reduce_binary_op()`" would be necessary to fix the second issue in any case.

**Comment by anvilfolk** [comment]
@vonagam might be worth tagging this as partially closed in your PR as well! I just reviewed that and it looks good, plus partially deals with this situation! 👍

**Comment by MikeSchulze** [comment]
👍

**Comment by MikeSchulze** [comment]
This bug is still dear in beta 10!
v4.0.beta10.official [d0398f62f]

```
extends Node

const UNDEFINED :Variant = "<-NO_ARG->"

static func _extract_args() -> void:
	var arg_default := UNDEFINED

```

**Comment by vonagam** [comment]
Well, there were two errors, they were fixed in two different PRs. 
One of them got merged and that close the issue.
Another one - #69163 - is still waiting for that.

**Comment by MikeSchulze** [comment]
gotcha 👍
