### ISSUE TITLE
beta14 AnimationTree not working correctly compared to beta13

### ISSUE THREAD

**Issue by gianpiero-bozza** [godotengine/godot#71870]
### Godot version

28a24639c

### System information

Linux Mint 20.3

### Issue description

I updated today to the beta14 and the project that yesterday was working correctly, just a basic prototype with a sprite moving in 4 directions, using a Sprite2D, AnimationPlayer and AnimationTree with a state machine, today in beta14 is not working, when moving around only the first frame of the animation was played, both in Idle mode (no input) and in Walk mode (user input).
Again, yesterday it was working correctly, today it wasn't. The only change was to run the project with beta14

Sorry if this is unclear, it's my first issue created and I'm also very new to game development.

### Steps to reproduce

1. create a sprite 2d with idle and walk animation sprite sheet texture
2. create an animation player and set idle and walk animation for all 4 directions
3. create an animation tree, set state machine behaviour and 2 nodes for idle and walk, both blend space 2d with the cardinal points using the related animations from the animation player
4. enable the animation tree
5. execute the scene, only the first frame of the animations plays

### Minimal reproduction project

[playground.zip](https://github.com/godotengine/godot/files/10475046/playground.zip)

**Comment by JustKievn** [comment]
ran into same issue the other day. Issue is w/ the state_machine.travel(). It's constantly traveling to the same state and restarting animation back at frame 0. I just temp fixed it by checking state_machine's current state to avoid it spamming travel("Idle/Walk").

**Comment by TokageItLab** [comment]
Fixed by #71840. The `travel()` should not generally be spammed, but can be avoided in the following ways in next beta:

```gdscript
func pick_new_state():
	if (velocity != Vector2.ZERO):
		state_machine.travel("Walk", state_machine.get_current_node() != "Walk")
	else:
		state_machine.travel("Idle", state_machine.get_current_node() != "Idle")
```

**Comment by gianpiero-bozza** [comment]
> Fixed by #71840. The `travel()` should not generally be spammed, but restarting can be avoided by the following ways in next beta:
> 
> ```gdscript
> func pick_new_state():
> 	if (velocity != Vector2.ZERO):
> 		state_machine.travel("Walk", state_machine.get_current_node() != "Walk")
> 	else:
> 		state_machine.travel("Idle", state_machine.get_current_node() != "Idle")
> ```

Hi, thanks for the clarification.
I noticed, while trying to debug my script with some prints, the travel() method was spammed unnecessarily.
But your proposed code didn't work for me, back to beta 14, but the following works:

```
func pick_new_state():
	if (velocity != Vector2.ZERO):
		if (state_machine.get_current_node() != "walk"):
			state_machine.travel("walk")
	else:
		if (state_machine.get_current_node() != "idle"):
			state_machine.travel("idle")

```
I had to extract the condition in a dedicated if statement to make it work in beta 14.
Regards

**Comment by TokageItLab** [comment]
Yes, it was just merged and will be effective with beta15.

**Comment by Shidoengie** [comment]
> Yes, it was just merged and will be available after beta15.

So it's beta16 and the behavior present in betas 1 to 13 is still not present does this mean that it won't come back and I'll have to rewrite my animation playing to code to check if it's not spamming it?

**Comment by TokageItLab** [comment]
Yes. Transition requests should not be spammed.

**Comment by Zireael07** [comment]
Can this bit about NOT spamming requests be added somewhere EXTRA visible in AnimationTree docs?

**Comment by Shidoengie** [comment]
> Yes. Transition requests should not be spammed.

it didnt cause issues before why did it change?!
Now ill have to rewrite something that didnt cause issues before....

**Comment by Shidoengie** [comment]
One of the main reasons i use animation trees is that i can spam it and it would work normally and i wouldnt have to write code that would break or simply not work...
