### ISSUE TITLE
Sprite2d shows corrupted image in editor - Godot 4.0 beta 14

### ISSUE THREAD

**Issue by DSangyy** [godotengine/godot#71951]
### Godot version

Godot 4.0 beta 14

### System information

Debian 11, X11 Nvidia proprietary driver, GLES3 Compatibility

### Issue description

When creating a new scene and add a Sprite2D node, the node image becomes corrupted when selecting the root node.
The problem is gone after saving & re-opening the editor.

![Screenshot from 2023-01-24 12-19-24](https://user-images.githubusercontent.com/94308700/214218462-979ed804-6128-4fbb-87d3-286de9db9e7f.png)

Selecting the root node:
![Screenshot from 2023-01-24 12-19-35](https://user-images.githubusercontent.com/94308700/214218528-944083f4-f5fc-4088-a6c8-7702215ce1a0.png)

The resource preview is wrong too.
![Screenshot from 2023-01-24 12-19-48](https://user-images.githubusercontent.com/94308700/214218557-34177eba-98cc-46aa-86f3-9f613899137a.png)

### Steps to reproduce

Pretty straightforward.

### Minimal reproduction project

Any sprite will do, i think.

**Comment by clayjohn** [comment]
I can't reproduce based on your reported steps. I tried with a Sprite2D as a child of a Node2D and as a child of a StaticBody2D. In both cases selecting the root node had no impact on the Sprite2D. 

Could you please upload an MRP with a project that consistently reproduces this issue so that others can reproduce and debug the issue?

**Comment by DSangyy** [comment]
As mentioned, the problem is fixed after saving, so uploading my project can't help reproduce this issue.
This is the sprite that I use.
![tree](https://user-images.githubusercontent.com/94308700/214222762-6ae71e45-99fa-46f5-be18-afe880fbc8cc.png)

I've tried with a new project and using the Godot icon, same problem occurred.
![Screenshot from 2023-01-24 13-05-10](https://user-images.githubusercontent.com/94308700/214223235-7d18a517-fdc1-41b1-9dec-9d037399d424.png)

The Vulkan backend doesn't have this problem.

**Comment by stephannv** [comment]
This happend to me too (using some beta version, I don't remember, but it was 10~13), but I could not reproduce.

**Comment by DSangyy** [comment]
Strangely, this problem doesn't happen when I drag & drop the image directly into the texture box, instead of import it via load option.

**Comment by Masheepcian** [comment]
This happens to me too. I'm on Windows 10 with a Nvidia RTX 2060 and latest drivers.
From everything I could test I've gathered that:
* It only happens on the Compatibility rendering mode. And only in the editor.
* Happens in Sprite2D and TextureRect.
* You don't even need to add a sprite. Using the godot svg works too.
* The first time I've seen it was on Beta 13 and it's still present in Beta 16. But I can reproduce it on Beta 4 too if I open a project created on the later ones. Those are the only ones I tried it on.
* Saving and reloading the scene _sometimes_ fixes it. And sometimes it makes other parts of the UI glitch out.
![wtf](https://user-images.githubusercontent.com/103336314/215229531-aa9414a1-4c7a-4689-9b7f-4f85e3628985.PNG)
* If you right-click while the image is glitched it will use the popup as a texture.
![lol](https://user-images.githubusercontent.com/103336314/215230052-76a1644c-aa2d-44d9-a555-36d2c5a2615e.jpg)

Here's a video of it:

https://user-images.githubusercontent.com/103336314/215230120-8e2f061f-f157-467d-a158-1e6ded437b9d.mp4

**Comment by clayjohn** [comment]
@Masheepcian Are you also on Windows 11 with an NVidia GPU?

**Comment by Masheepcian** [comment]
> @Masheepcian Are you also on Windows 11 with an NVidia GPU?

The GPU is from NVidia but I'm on Windows 10.

**Comment by FireCatMagic** [comment]
![Godot_v4 0-beta13_win64_uzp4q2HcLZ](https://user-images.githubusercontent.com/40964335/215240111-b7d54812-005c-4cb3-b418-94d2dd060df5.gif)
Something similar had occurred with me too xd, when using a placeholdertexture

**Comment by popcar2** [comment]
Bump. I can confirm this still happens in beta 16, it's certainly an odd bug. Closing Godot and opening it back up makes the sprite appear normal again.
![image](https://user-images.githubusercontent.com/16920817/215355461-16048cc6-16d6-40a9-ba07-0d0758d7f38a.png)

**Comment by hydroper** [comment]
As you can see it also happens to me in Windows 11 with `gl_compatibility` render.

**Comment by clayjohn** [comment]
I just tested Beta 16 on Windows 11 Intel UHD graphics 620 and was able to reproduce the issue

**Comment by DSangyy** [comment]
I can confirm this fix works on Debian 11 with the latest master build.
