### ISSUE TITLE
AnimationPlayer crashes editor 

### ISSUE THREAD

**Issue by RuthgerD** [godotengine/godot#72397]
### Godot version

4.0.dev (c309de53997feff3286295fb2d71657f112a15db)

### System information

Linux, Nvidia, Vulkan

### Issue description

Editor segfaults when certain conditions are met when using the AnimationPlayer editor.

### Steps to reproduce

1. Create multiple animations, saved into a animation collection
2. Open an existing animation, then make a new empty animation
3. Change from seconds to fps, or add a new property to animate ()
4. Editor crashes

NOTE: It is slightly random and I have not found a perfect repro

### Minimal reproduction project

N/A (TBD?)

**Comment by lyuma** [comment]
Hi!
Thanks for the issue report. I suspect this issue is outdated, because it's based on a one week old godot version. An absolutely ginormous number of bugs were fixed in the past few days alone, so my guess is this issue was already fixed in master.

Would it be possible to update to the latest master version and test again?

If you're unable to compile latest master, it may be best to wait until the next beta and try again.

**Comment by lyuma** [comment]
Duplicate of #72065 
I'm going to close this and keep the other one open since it has a repro project. I *think* it was fixed in beta16 anyway

**Comment by RuthgerD** [comment]
>  I think it was fixed in beta16 anyway

Got a commit to reference by any chance? Guess ill have to try and trigger the crash again..

**Comment by RuthgerD** [comment]
Still crashes on latest master / latest release candidate...
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.rc.custom_build (44b41ded82229ca7614403f74234a4282002458b)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38f50) [0x7fde5eb49f50] (??:0)
[2] bin/godot.linuxbsd.editor.x86_64.llvm(+0x238f6ba) [0x55642d8156ba] (/home/ruthgerd/.data/Sources/godot/editor/animation_track_editor.cpp:5086)
[3] bin/godot.linuxbsd.editor.x86_64.llvm(+0x23519fa) [0x55642d7d79fa] (/home/ruthgerd/.data/Sources/godot/./core/object/ref_counted.h:212)
[4] bin/godot.linuxbsd.editor.x86_64.llvm(+0x234cc1d) [0x55642d7d2c1d] (/home/ruthgerd/.data/Sources/godot/editor/animation_track_editor.cpp:?)
[5] bin/godot.linuxbsd.editor.x86_64.llvm(+0x234fd3a) [0x55642d7d5d3a] (/home/ruthgerd/.data/Sources/godot/./core/object/ref_counted.h:220)
[6] bin/godot.linuxbsd.editor.x86_64.llvm(+0x4c2c57e) [0x5564300b257e] (/home/ruthgerd/.data/Sources/godot/core/object/object.cpp:792)
[7] bin/godot.linuxbsd.editor.x86_64.llvm(+0x2866092) [0x55642dcec092] (/home/ruthgerd/.data/Sources/godot/./scene/scene_string_names.h:52)
[8] bin/godot.linuxbsd.editor.x86_64.llvm(+0x16c2d8f) [0x55642cb48d8f] (/home/ruthgerd/.data/Sources/godot/./core/variant/binder_common.h:?)
[9] bin/godot.linuxbsd.editor.x86_64.llvm(+0x484dcd8) [0x55642fcd3cd8] (/home/ruthgerd/.data/Sources/godot/core/variant/callable.cpp:?)
[10] bin/godot.linuxbsd.editor.x86_64.llvm(+0x4c27ec7) [0x5564300adec7] (/home/ruthgerd/.data/Sources/godot/core/object/message_queue.cpp:230)
[11] bin/godot.linuxbsd.editor.x86_64.llvm(+0x4c2819c) [0x5564300ae19c] (/home/ruthgerd/.data/Sources/godot/core/object/message_queue.cpp:?)
[12] bin/godot.linuxbsd.editor.x86_64.llvm(+0x2909180) [0x55642dd8f180] (/home/ruthgerd/.data/Sources/godot/scene/main/scene_tree.cpp:432)
[13] bin/godot.linuxbsd.editor.x86_64.llvm(+0x4dc6f4) [0x55642b9626f4] (/home/ruthgerd/.data/Sources/godot/main/main.cpp:3107)
[14] bin/godot.linuxbsd.editor.x86_64.llvm(+0x4674bd) [0x55642b8ed4bd] (/home/ruthgerd/.data/Sources/godot/platform/linuxbsd/os_linuxbsd.cpp:880)
[15] bin/godot.linuxbsd.editor.x86_64.llvm(+0x45c59c) [0x55642b8e259c] (/home/ruthgerd/.data/Sources/godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[16] /usr/lib/libc.so.6(+0x23790) [0x7fde5eb34790] (??:0)
[17] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fde5eb3484a] (??:0)
[18] bin/godot.linuxbsd.editor.x86_64.llvm(+0x45c3e5) [0x55642b8e23e5] (??:?)
```

All you do is start the editor, navigate to an animation player, select an animation and change from seconds to fps; and up in smoke it goes.

My PR still stands as a fix.
