### ISSUE TITLE
Editor rendering glitch caused by certain environment setup

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#72857]
### Godot version

4.0 a05670c

### System information

Windows 10 x64

### Issue description

Notice the weird black/white/rainbow glow just above the bottom dock.
![ezgif com-optimize](https://user-images.githubusercontent.com/2223172/217369247-90daedf6-fb5a-4c56-bfb7-f5bfba9f5e15.gif)
(the glitches inside the dock itself are caused by GIF quality 🙃)

### Steps to reproduce

See MRP. I didn't make extensive testing. It disappears when you disable SSIL, but most likely there are multiple factors.

### Minimal reproduction project

https://ufile.io/bxeoy5o7

**Comment by clayjohn** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/72838. Right now that PR only fixes SSIL. Would be good if you could test and confirm

**Comment by KoBeWi** [comment]
Nope, it doesn't fix it.

**Comment by clayjohn** [comment]
CC @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Not sure if there there is more that I need to enable, or whether a change I did today managed to fix it, but with the updated #72838 applied I'm not getting any weird issues after tabbing through to trigger viewport resizes:

![image](https://user-images.githubusercontent.com/1945449/217407899-92aa9281-d80d-4587-9a69-e1e050b509ec.png)

**Comment by KoBeWi** [comment]
I just grabbed the newest version of that PR and I can still reproduce the issue. Did you try the MRP? The glitch appears after you rotate the camera a bit.

**Comment by clayjohn** [comment]
@KoBeWi what type of GPU can you reproduce this on?

**Comment by BastiaanOlij** [comment]
Goes wrong for me as well but I have to make the display really flat...

![image](https://user-images.githubusercontent.com/1945449/217434546-bb5baeda-4081-4acb-a203-a8ffd9ecac94.png)

**Comment by BastiaanOlij** [comment]
Also it only fails if half size is on.

I think this could be because for our linear depth we're keeping 5 mipmap levels, but the logic actually needs 6. We're reusing the last layer. Note the code in:
https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/effects/ss_effects.cpp#L450

```
int depth_index = use_half_size ? 1 : 0;

	RD::get_singleton()->draw_command_begin_label("Downsample Depth");
	if (p_invalidate_uniform_set || use_full_mips != ss_effects.used_full_mips_last_frame || use_half_size != ss_effects.used_half_size_last_frame || use_mips != ss_effects.used_mips_last_frame) {
		if (ss_effects.downsample_uniform_set.is_valid() && RD::get_singleton()->uniform_set_is_valid(ss_effects.downsample_uniform_set)) {
			RD::get_singleton()->free(ss_effects.downsample_uniform_set);
			ss_effects.downsample_uniform_set = RID();
		}

		Vector<RD::Uniform> uniforms;
		{
			RD::Uniform u;
			u.uniform_type = RD::UNIFORM_TYPE_IMAGE;
			u.binding = 0;
			u.append_id(p_depth_mipmaps[depth_index + 1]);
			uniforms.push_back(u);
		}
		{
			RD::Uniform u;
			u.uniform_type = RD::UNIFORM_TYPE_IMAGE;
			u.binding = 1;
			u.append_id(p_depth_mipmaps[depth_index + 2]);
			uniforms.push_back(u);
		}
		{
			RD::Uniform u;
			u.uniform_type = RD::UNIFORM_TYPE_IMAGE;
			u.binding = 2;
			u.append_id(p_depth_mipmaps[depth_index + 3]);
			uniforms.push_back(u);
		}
		if (use_full_mips) {
			RD::Uniform u;
			u.uniform_type = RD::UNIFORM_TYPE_IMAGE;
			u.binding = 3;
			u.append_id(p_depth_mipmaps[4]);
			uniforms.push_back(u);
		}
		ss_effects.downsample_uniform_set = RD::get_singleton()->uniform_set_create(uniforms, ss_effects.downsample_shader.version_get_shader(ss_effects.downsample_shader_version, use_full_mips ? 6 : 2), 2);
	}
```

Note how with halfsize `depth_index` will be 1, so the 3rd and 4th mipmap we're adding here are both mipmap level 4.

I'll see if the issue goes away with an extra mipmap.

**Comment by KoBeWi** [comment]
> what type of GPU can you reproduce this on?

Nvidia GTX 1060

**Comment by BastiaanOlij** [comment]
Ok, I may have found the issue. I noticed in renderdoc that when I reproduced the issue, each quadrant of our linear depth buffer had this nice dotted line:
![image](https://user-images.githubusercontent.com/1945449/217720891-f8dc5840-d5a5-498e-aad5-69c149bb6892.png)

Now in this case I had resized my viewport until the issue appeared, and I ended up with a viewport resolution of 1152x97.

When we create our linear depth buffer the following line of code calculates the size:
```
Size2i size((full_screen_size.x + 1) / 2, (full_screen_size.y + 1) / 2);
```
This gives us a buffer size of 576x49 for each quadrant.
We have mips of resp: 288x24, 144x12, 72x6, 35x3 and 18x1

So far so good.

But now when we run our compute shader the size is calculated like this:
```
Size2i size(MAX(1, full_screen_size.x >> (use_half_size ? 2 : 1)), MAX(1, full_screen_size.y >> (use_half_size ? 2 : 1)));
```
So for full size this gives a resolution of 576x48, one pixel short
And for half size this gives a resolution of 288x24, which in this case would fit

So if both SSIL and SSAO are half size, this works, but if either one or the other is full size, we render a pixel too little, then when the mips are calculated that fault perpetuates and gets worse on each mip level.
