### ISSUE TITLE
[Android] Can't render Armature in compatibility (OpenGL)

### ISSUE THREAD

**Issue by rodolpheh** [godotengine/godot#74074]
### Godot version

4.0-rc6.0

### System information

Android, XR, GLES3, Lynx-R1

### Issue description

I have an issue with rendering Armatures representing hand that are tracked on an Android platform. This platform doesn't support Vulkan completely yet so I have to use OpenGL compatibility. The debug console is being spammed with this message when my hands should be in view:

```
02-23 17:55:52.261  4554  4611 E godot   : USER ERROR: GL ERROR: Source: OpenGL	Type: Error	ID: 2147483647	Severity: High	Message: Mismatch between shader number of views and FBO number of views
02-23 17:55:52.261  4554  4611 E godot   :    at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:167)
```

I can see in the logs that it does not completely support OpenGL 3.3 but OpenGL 3.2:

```
02-23 17:55:24.068  4554  4611 I godot   : OpenXR: Requested OpenGL version exceeds the maximum version this runtime has been tested on and is known to support.
02-23 17:55:24.068  4554  4611 I godot   : - desired_version  3.3.0
02-23 17:55:24.068  4554  4611 I godot   : - minApiVersionSupported  2.0.0
02-23 17:55:24.068  4554  4611 I godot   : - maxApiVersionSupported  3.2.1023
```

I've made sure that the Armatures have a basic material, checked with another object in the scene that there is no issue with the material, used another 3d model, to no effect.

The platform isn't well supported yet and is in the process of being tested (see [here](https://github.com/GodotVR/godot_openxr_loaders/pull/28) for details). Sorry for not giving more details and minimal example yet, I'll make sure I can produce one.

### Steps to reproduce

* Setup an XR project for Lynx-R1
* Add rigged hands (I've used the Valve hands from the Godot3.x OpenXR plugin)
* Play and check your hands

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@rodolpheh Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by clayjohn** [comment]
I think that there is likely a few things going on here, 

Taking a look at the GL_ERROR, it seems that the OpenGL renderer only supports 1 or 2 views. It also appears that openXR always requests 2 views. So something must be happening with the shader where num views isn't getting set to 2 correctly. Here is the relevent code:
https://github.com/godotengine/godot/blob/0cd148313213e2923004be65bafd6a3781c917ec/drivers/gles3/shader_gles3.cpp#L183-L197

Perhaps the GL_OVR_multiview2 or GL_OVR_multiview extension is missing? Or maybe ``USE_MULTIVIEW`` isn't getting added when it should.

CC @dsnopek

**Comment by dsnopek** [comment]
A reproduction project would help a lot! My main question is if this a custom shader and how it's being used in the project?

The `USE_MULTIVIEW` define needs to be integrated into each of the glsl shaders from Godot, and we've so far integrated it into scene.glsl and sky.glsl. My thought is that perhaps you're using a shader type we haven't addressed yet?

**Comment by rodolpheh** [comment]
Sorry I wasn't able to post a project today, will do as soon as I can. When I opened the issue, I was using a default StandardMaterial3D.

**Comment by rodolpheh** [comment]
I have added a minimal project to reproduce it on the first comment of this issue. I had to change the hands because the Valve hands were too heavy (30Mb per texture and mesh). I took some hands from the OpenXR tools but doesn't seem to be properly rigged to be used directly with the OpenXRHand. So please don't mind the weird deformations of the hands.

**Comment by BastiaanOlij** [comment]
Please test in the stable release, I fixed something around this this week.

**Comment by BastiaanOlij** [comment]
The hands in XR tools aren't build for hand tracking so you probably can't use those here. One of the guys on the discord was experimenting with adjusting them to match.

You should be able to use the Valve hands without textures and they should work fine, but on SteamVR. I've only tested SteamVR and Metas OpenXR runtimes with this but even between these two there are critical differences in the skeleton. There are differences between the skeletons provided and what the OpenXR spec demands that will hopefully be resolved and make things better. One of the main ones that seems to be causing issue is the position of the palm joint and the way that the palm to wrist bone is in the opposite direction as all the other bones, while the OpenXR spec demands the orientation to be the same.

There are also issues that are just a fact of life and we need to improve on our side, especially around peoples hands being of different sizes and some of the tracking solutions reacting to this.

I'm planning an enhancement that I hope to do in the next couple of days so you get access to the raw hand tracking data.

**Comment by rodolpheh** [comment]
I'll try with the latest version. Very excited that it got release, it's a wonderful milestone, congratulation to everyone involved!

I usually use the Valve Hands with Ultraleap's hand tracking and Monado and they work like a charm (although there is an offset which might be due to the origin of the wrist). In this case though I couldn't as they are too heavy to be put in a project then uploaded on GitHub (limit is 25MB). I found the hands from the XR tools yesterday while frantically looking for a pair of hands to replace the Valve's one.

Having access to the raw data sounds great, since I've started trying Godot and OpenXR I was missing this. I've been doing myself a GDExtension to integrate natively Ultraleap's hand tracking in Godot (for non-XR use-cases, and access to raw data), and have been fiddling with rigging and skeletons (and scaling of the hand! Just discovered the other day I might be doing it wrong). I'll be looking closely at any change on this subject and will help if I can.

Really appreciative of all the work being done.

**Comment by BastiaanOlij** [comment]
@rodolpheh you know that years ago I wrote an LeapMotion GDNative external for Godot right ? :P

I've always used the Valve hands too, I really wonder why you're having so much trouble with them.

OWH hang on, that's right, Valve embedded those mega textures inside of the GLB files.. Thats so annoying, I wish the put some versions online without the large textures.

**Comment by rodolpheh** [comment]
Just checked out the latest version of Godot and I still have this rendering issue. I also seem to have issues with rendering in a Pico 4 but the error is different, I'll try to capture this issue to see if it could be related.

@BastiaanOlij I did not know that, Googled it and indeed I've found your article on the Godot blog about it, and the source code. That is really cool. I decided to do the same in GDExtension because I wanted to learn making GDExtensions and that was a good reason I think. What I've done is more complex (and awful in term of code...) but it's because it gives access to almost all features: camera images, multi-devices, switching between tracking modes etc.. I should publish it one day...

**Comment by dsnopek** [comment]
I tried the test project on my Quest 2 (because I don't have Lynx R1). I've never used hand tracking, so I'm not sure how to actually get that going, but after a few seconds I do see the error spammed to adb:

```
03-02 14:40:01.877 13731 13774 E godot   : USER ERROR: GL ERROR: Source: OpenGL Type: Error     ID: 2147483647  Severity: High  Message: Mismatch between shader number of views and FBO number of views
03-02 14:40:01.878 13731 13774 E godot   :    at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:167)
```

When I have a chance, I'm going to do some more debugging and attempt to see which shader is generating this error.

**Comment by BastiaanOlij** [comment]
Cheers David,

Its a little outdated but you might also be able to use: https://github.com/BastiaanOlij/godot4_openxr_demo/pull/9
It has the Valve hands in it and if you run it over SteamVR it should work. Just need to switch it to OpenGL :)

**Comment by dsnopek** [comment]
Thanks @BastiaanOlij! However, per my last comment I am able to reproduce the error, even if hand tracking isn't actually working. Just need to find the time to debug further!

**Comment by rodolpheh** [comment]
Didn't have access to the Lynx headset for some time. Retried today with the latest Godot (4.2-dev5) and now the hands are showing! I'm not sure what update fixed it, if anyone can check on their side to confirm, I'm happy to close this issue.
