### ISSUE TITLE
Editor window suddenly minimizes on Gnome (Linux)

### ISSUE THREAD

**Issue by vvvvvvitor** [godotengine/godot#74336]
### Godot version

4.0

### System information

Fedora 37 (Workstation), Wayland, Mesa Intel® UHD Graphics (ICL GT1), Vulkan

### Issue description

The editor window automatically minimizes without my input making it unusable.
[Gravação de tela de 2023-03-04 00-31-09.webm](https://user-images.githubusercontent.com/119557151/222873855-44a00414-16d0-4ec8-b4a3-1497e2c77e98.webm)

### Steps to reproduce

I honestly don't know why it happens, it seems completely random but it looks like it generally happens after I go to another workspace.

### Minimal reproduction project

Can happen with any project, even on the project list.

**Comment by AntonioDell** [comment]
This also happens on Pop OS! 22.04 with Pop shell as window manager on Gnome.

**Comment by hakro** [comment]
Happened to me a couple of times as well, but quite randomly on PopOS! I'm not sure under what circumstances it's triggered though. I had to restart the engine.

**Comment by naturally-intelligent** [comment]
Are you using Compiz? I've had the same thing happen on Ubuntu 20.04 MATE but it's rare

Wonder if setting 'interface/editor/single_window_mode' helps any

**Comment by hakro** [comment]
I'm not using Compiz on my side. Just a plain PopOS! and its version of Gnome.
I recently enabled single window mode, didn't have the issue yet, but I can't conclude if it's related to that or not, since it didn't happen all the time when using multi-window mode.

**Comment by vvvvvvitor** [comment]
> Are you using Compiz? I've had the same thing happen on Ubuntu 20.04 MATE but it's rare
> 
> Wonder if setting 'interface/editor/single_window_mode' helps any

Nope, just standard Fedora.

**Comment by AntonioDell** [comment]
@hakro the bug is happening for me with single window mode too.

**Comment by naturally-intelligent** [comment]
For me it's only happening after I minimize. 

Then, when I try to restore from taskbar, it looks like it is unminimizing, but minimizes right after.

**Comment by vvvvvvitor** [comment]
Can someone check if it also happens on Xorg?

**Comment by vvvvvvitor** [comment]
> Are you using Compiz? I've had the same thing happen on Ubuntu 20.04 MATE but it's rare
> 
> Wonder if setting 'interface/editor/single_window_mode' helps any

Also happens in Single Window Mode.

**Comment by naturally-intelligent** [comment]
> Can someone check if it also happens on Xorg?

I'm using X11 with Ubuntu MATE 22 and it happens. It's pretty consistent for me. If I minimize Godot it gets stuck minimized forever until force-closed.

**Comment by binarysafari** [comment]
Fedora 37/GNOME 43.3/X11/Nvidia

To me it looks like there is some issue with the window (focus) state (not specifically with how the minimized state is tracked). I can get the editor back to normal if I'm able to bring the keyboard focus to the editor window. After e.g. hitting F5 to run the game everything is back to normal. If I have the code editor open when this happens typing some characters did also work. This also happens to **all** open Godot 4.0 editors at the same time. This did also happen in compatibility mode using the single window switch.

Side-note: Right before this problem happens some of the keyboard shortcuts are not working anymore e.g. CTRL+S is not saving the scene and code (just typing the letter s). I think there was a regression issue which was fixed for the 4.0 release (or a later RC). Could be related, maybe not. Editor auto minimize, shortcuts sometimes not working, sluggish window dragging performance (when editor is not running in compatibility mode) - I have them all - I guess that's a bingo;)

**Comment by dkaste** [comment]
Probably a duplicate of https://github.com/godotengine/godot/issues/72728

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/72728.

**Comment by hunterloftis** [comment]
I don't believe this is a duplicate; it still happens in `Godot v4.1.1.rc1 - Fedora Linux 38 (Workstation Edition) - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1280P (20 Threads)`.

It also does make godot literally unusable, because some windows will sometimes refuse to re-focus (they minimize as soon as they are focused). In that case, the only way out is to force kill the godot process and hope you didn't lose much work since the last save.

All godot windows are prone to this: create a new node, delete a node confirmation, etc.

**Comment by Calinou** [comment]
@hunterloftis See https://github.com/godotengine/godot/issues/77333.

**Comment by Keawy-Dev** [comment]
I'm still experiencing this bug in 4.3, any fix?
