### ISSUE TITLE
Strange code fragments

### ISSUE THREAD

**Issue by mjunix** [godotengine/godot#74344]
### Godot version

31eccb5501

### System information

Windows 10

### Issue description

Some strange code fragments found in the code. I do not know if these are actual bugs.

1. Identical expression `array->get_typed_class_name() == native_type` on both sides of `&&` operator:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/modules/gdscript/gdscript_vm.cpp#L777
2. Identical expression `array->get_typed_class_name() != native_type` on both sides of `||` operator:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/modules/gdscript/gdscript_vm.cpp#L1255
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/modules/gdscript/gdscript_vm.cpp#L1255
3. Identical expression `pose.orientation.y != 0` on both sides of `||` operator (perhaps one of these should be `pose.orientation.z != 0`?):
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/modules/openxr/scene/openxr_hand.cpp#L219
4. Identical expression `a.lower` on both sides of `-` operator:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/thirdparty/embree/kernels/bvh/bvh_node_obb_mb.h#L55
5. Identical expression `font_main.is_valid()` on both sides of `&&` operator:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/editor/import/dynamic_font_import_settings.cpp#L861
6. Identical expression `bold_font.is_valid()` on both sides of `&&` operator:
7. https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/editor/import/dynamic_font_import_settings.cpp#L1095
8. Variable `scansym_map[0x57]` assigned twice:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/platform/windows/key_mapping_windows.cpp#L318-L319
9. 'if'-statement is equivalent to the 'else'-statement:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/scene/resources/text_paragraph.cpp#L496-L500
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/scene/resources/text_paragraph.cpp#L646-L650
10. Shouldn't `sizeof(long_filename_buff)` be replaced with `file_info.size_filename` since `sizeof(long_filename_buff)` is the size of the pointer and not the buffer?:
https://github.com/godotengine/godot/blob/31eccb5501ddc92b4a17fd6ae33dca4ad217702c/modules/zip/zip_reader.cpp#L69-L70

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
`5.` is in third-party code. Please report it to the Embree developers :slightly_smiling_face:

**Comment by bitsawer** [comment]
Some look like obvious bugs. worth investigating. I noticed `10.` earlier, but it should be fixed by https://github.com/godotengine/godot/pull/69677.

**Comment by BastiaanOlij** [comment]
3. is valid, will fix, thanks!

**Comment by yedpodtrzitko** [comment]
@mjunix just curious - did you find these issues manually or by using some kind of tool?

**Comment by YuriSizov** [comment]
One issue remaining but I'm going to close this report as complete. The remaining issue has a PR that provides all the necessary context, way beyond this report. Thanks everyone!
