### ISSUE TITLE
Multiple Light2D Masks on the Same Sprite Behave Badly

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#7485]
**Operating system or device - Godot version:** Godot_v2.1.1-stable_win64.exe

**Issue description** (what happened, and what was expected):
My game has a darkness image, which fades to 100% opacity as time progresses.
![maska](https://cloud.githubusercontent.com/assets/10686700/21776140/ef91da88-d64d-11e6-9a5b-be8626ba3f1c.png)

Fire allows one to still see, by masking out a portion of that parent image.
![maskb](https://cloud.githubusercontent.com/assets/10686700/21776149/fe5c2154-d64d-11e6-968d-362b9f590282.png)

But if I have a second fire instance, the lighting behaves unexpectedly if they're both over the darkness image simultaneously.
![maskanim](https://cloud.githubusercontent.com/assets/10686700/21776170/1cd49652-d64e-11e6-818d-66fdaa2f393a.gif)

Intuitively, one would expect masks to only affect the area covered by the Light2D's sprite. Instead, the whole image blacks out as soon as more than one mask overlaps an image.

**Steps to reproduce:**
Create some image and a Light2D that masks it. Add another masking Light2D and watch it wig out when they're both within the bounds of the target image.

**Link to minimal example project** (optional but very welcome): 
[Mask.zip](https://github.com/godotengine/godot/files/694202/Mask.zip)

**Comment by eon-s** [comment]
This issue is present in master too (tested in b21a1232b)

**Comment by khinbaptista** [comment]
just bumped into this working on my project, don't know yet how to work aroung it

**Comment by reduz** [comment]
problem with this is that lights are done in multiple passes. This could be
fixed by drawing them in a single pass, but then it would limit the size of
light textures as they would need to go to an internal atlas. Not really
sure if much can be done to fix it (and keep it compatible on low end
hardware and mobile).

**Comment by eon-s** [comment]
@khinbaptista the only workaround I can think of (via scripting) is to modify the image data every time the light sources are moving (use instead a single light as mask on the screen and stamp the images to the texture), may hit performance and perhaps not too android friendly.

I have no experience with light shaders so no idea if something better can be done with these.

**Comment by reduz** [comment]
oh you can always use a viewport as a light texture for masking btw.

**Comment by fossegutten** [comment]
Still having this problem in 3.0.2, when using a light mask in the scene. It is totally random if the other lights will work or not. Need to reset the game until all lights are working. 
However it works when i use the canvasmodulate with solid black, just like the official 2D lighting demo does with a lighter grey.
Dont really know how to do the viewport thing that reduz suggested.

**Comment by eon-s** [comment]
@fossegutten this issue is not solved yet, check related https://github.com/godotengine/godot/issues/8685#issuecomment-342995695

**Comment by reduz** [comment]
This should be solvable on Vulkan eventually since we will be able to do
this as single pass

**Comment by eon-s** [comment]
@reduz any chance to get something on GLES2?

**Comment by th1z** [comment]
> oh you can always use a viewport as a light texture for masking btw.

I don't think that's possible right now, because of: #17067 

Is there currently any other options to have multiple lights(2d) with masking or to combine multiple textures to a light mask?

**Comment by akien-mga** [comment]
I'll merge this issue together with the related #8685.
