### ISSUE TITLE
[3.x] The anchor to the grid does not work well.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#77041]
### Godot version

v3.6.beta1.official [632a544c6]
v3.6.stable.official [de2f0f147]

### System information

w10 64

### Issue description

What can I say, the anchor seems out of place and the grid is not well positioned.

I don't know what information I can provide. The grid and the anchors are simply not coherent.

Watch the video.
The anchor changes when I change the grid dimensions.
At 16x16 the anchor is in one place.
After I change the grid to 8x8, now the anchor has been moved slightly, this should not be the case, the anchor should be the same as 16x16, the difference is now one more step (8x8) has been added.

https://github.com/godotengine/godot/assets/19652075/7178814b-c9a0-4d4e-8fb5-e8ce6dad6f4e

Problem, the anchor to the grid is positioned in a different place depending on whether the grid is 8x8 or 16x16 in size.

Solution, place the node just at the 0,0 coordinates of the editor, the error does not occur there.
The error is a small offset that is added to the grid when it moves away from the 0,0 coordinate, that's what it seems to me at first.
But it's not a solution because I need the grid to be correct at any point to position and resize my nodes.

### Steps to reproduce

Watch the video

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11472074/project.zip)

**Comment by Calinou** [comment]
What grid size do you have set in pixels?

@Torguen Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Torguen** [comment]
Here's a scene to prove it.
No need to run.

Watch the video.
The anchor changes when I change the grid dimensions.
At 16x16 the anchor is in one place.
After I change the grid to 8x8, now the anchor has been moved slightly, this should not be the case, the anchor should be the same as 16x16, the difference is now one more step (8x8) has been added.

https://github.com/godotengine/godot/assets/19652075/7178814b-c9a0-4d4e-8fb5-e8ce6dad6f4e

[project.zip](https://github.com/godotengine/godot/files/11472070/project.zip)

**Comment by Torguen** [comment]
In my project I have all these sprite nodes that should be anchored perfectly but then I realized that something strange was going on and I reported this bug.
Hopefully someone can fix it soon.

![Captura4](https://github.com/godotengine/godot/assets/19652075/75b28102-350d-465a-b13e-7d09fa032200)

**Comment by kleonc** [comment]
Likely a duplicate of #70186, see https://github.com/godotengine/godot/issues/70186#issuecomment-1368829042; seems like #70428 is not yet cherry-picked so the bug is present in v3.6.beta1.official [632a544c6] which includes https://github.com/godotengine/godot/commit/9ac09dfb64346f782a90319e2d8df03804e95b00.

**Comment by Torguen** [comment]
An example, in the corner 0,0 the grid is correct.
Then I scrolled down and the grid slowly drifts.
Grid anchors malfunction.


https://github.com/godotengine/godot/assets/19652075/9b7ef8a6-0cac-4352-8560-667743f12e18

**Comment by Torguen** [comment]
This is a good problem.
I hope it is fixed in 3.6 because it creates graphical defects like the one seen in the screenshot.
The wooden box does not fit properly in the hole due to this problem.

![enemigoVerdeDirecto](https://github.com/godotengine/godot/assets/19652075/4f04f996-0e0d-4447-a80b-db56540be564)

**Comment by Torguen** [comment]
I thought the fix for this issue had been applied to 3.6, but I see that it’s still present in:
v3.6.stable.official [de2f0f147]

**Comment by Torguen** [comment]
Objects completely misaligned with the tilemap and the grid, it's a mess.  
Apologies if I insist on this, but I rely heavily on snapping to the grid, and this issue leaves everything misplaced.

![Image](https://github.com/user-attachments/assets/2c19abed-5524-4a01-8343-602fb17b2dbe)

**Comment by lawnjelly** [comment]
As @kleonc says, this is likely already fixed by #65101 which we will aim to cherry pick to 3.6 for 3.6.1.

You should be able to try any of the newer 3.x artifacts (after that PR was merged) and test whether it fixed it, although any saved editor grid settings might need to be set to a new value for it to "take effect" (otherwise it might be relying on saved incorrect grid settings).

**Comment by Torguen** [comment]
Sorry, but I'm not sure I understand.  
Are you saying that I need to compile this?
https://github.com/godotengine/godot/tree/3.x

**Comment by lawnjelly** [comment]
> Sorry, but I'm not sure I understand.
> Are you saying that I need to compile this?

https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html

Just go to https://github.com/godotengine/godot/tree/3.x

Click the green tick by the latest commit in 3.x. It gives you a list of builds with green ticks. Click `details`.

Click `Summary` next to the home icon in the top left.

Then it should give you a list of pre-made builds for different platforms that you can download. These are called `artifacts` in github parlance.

These are pretty good for testing PRs. You can in some cases use these while waiting for an official build (e.g. 3.6.1 or 3.7 alpha), but you won't likely be able to export with them.

For the actual current build you either need to compile from source, or wait for next official build. We should probably aim for a 3.6.1 in the not too distant future, the grid problem was one of the major bugs to solve.

**Comment by Torguen** [comment]
Ok, I'm looking at this, but it's a bit of a mess for me.

**Comment by lawnjelly** [comment]
> Ok, I'm looking at this, but it's a bit of a mess for me.

3.6.1 is on the todo list, it is probably overdue actually. There's a few PRs to cherry pick to 3.6 and I believe Akien is working on some changes to update some libraries. The grid problem does seem to be one of the more annoying problems with 3.6 stable.

**Comment by Torguen** [comment]
If I use this artifact, will it negatively affect me when exporting, or what implications will it have compared to 3.6 stable official?
https://github.com/godotengine/godot/actions/runs/14157112187
I’d like to use it because the issue is resolved there, but I don’t know how it will affect me.

**Comment by lawnjelly** [comment]
Afaik in this particular case, as it is only affecting the grid, you could use the artifact, then probably export it using regular 3.6 stable and get the best of both worlds.

Don't hold me to that 😁 , but I was getting the impression from other's comments that the grid snapping gets baked into the objects, so when you load them in 3.6 they shouldn't get "re-snapped". You could test this out presumably.

**Comment by Torguen** [comment]
Ok, I'm using it v3.7.dev.custom_build [5155fe5a4] and so far it's working well.

**Comment by PabloDevGit** [comment]
This issue persists up to v4.6.dev6.official [dec5a373d]

Watch the video.
Initially, the tile is placed correctly. Then I move to the far right of the map, and now the tile has a terrible offset and is placed incorrectly. The grid has had issues since version 3 in they X axis.

https://youtu.be/Vp2c6T1F0pY

This issue cannot be reproduced in a new project. I can send my project privately.

**Comment by PabloDevGit** [comment]
Ok, I was able to create a minimal project.
Simply scroll to the far right of the TileMap, zoom in, and notice that the grid is misaligned on the X axis.

Important: I haven’t been able to reproduce this from scratch. This is my project after removing everything unnecessary. It is not a project specifically made to reproduce the issue.

[test.zip](https://github.com/user-attachments/files/23996421/test.zip)

Can anyone tell me why this grid misalignment happens?
Can I fix it myself, or is it a Godot issue?

**Comment by kleonc** [comment]
> [test.zip](https://github.com/user-attachments/files/23996421/test.zip)
> 
> Can anyone tell me why this grid misalignment happens? Can I fix it myself, or is it a Godot issue?

The issue is the scale of the scene root node (approx `(1.000754714012146, 1.000000000000000)`). Reset to the default `(1, 1)`.

<img width="552" height="300" alt="Image" src="https://github.com/user-attachments/assets/34ee7d15-72fe-42f7-a8f7-1b3ce75739b5" />

**Comment by PabloDevGit** [comment]
> > [test.zip](https://github.com/user-attachments/files/23996421/test.zip)
> > Can anyone tell me why this grid misalignment happens? Can I fix it myself, or is it a Godot issue?
> 
> The issue is the scale of the scene root node (approx `(1.000754714012146, 1.000000000000000)`). Reset to the default `(1, 1)`.
> 
> <img alt="Image" width="552" height="300" src="https://private-user-images.githubusercontent.com/9283098/523360064-34ee7d15-72fe-42f7-a8f7-1b3ce75739b5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUwNTIyMTcsIm5iZiI6MTc2NTA1MTkxNywicGF0aCI6Ii85MjgzMDk4LzUyMzM2MDA2NC0zNGVlN2QxNS03MmZlLTQyZjctYThmNy0xYjNjZTc1NzM5YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDZUMjAxMTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU4NmNiNWJmNmZjYTVhMGMyNjIwNWM4ZjBhMjFmOWExZTZhYjMyNTUyZWQ4YzQ5MzQzZjRiMWFmN2E0NDNmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HrlPSeWFl2rIzBcA3flN3fIa0lyTlweBHN3enAO5yQ8">

Wow, I don’t remember ever touching that, I guess it must have been accidental or something like that.
Thanks!

**Comment by lawnjelly** [comment]
Forgot to close this, I think it should be fixed by #65101 which was cherry picked and #100459 .

Let us know if there are any more problems here (it seems the above mention was due to scaling of the root node).
