### ISSUE TITLE
Window flickering

### ISSUE THREAD

**Issue by d0n3val** [godotengine/godot#77337]
### Godot version

4.0.3-stable, I've tested it also on 4.0.2 and 4.0.0

### System information

Windows 10, NVidia 4070 latest drivers 

### Issue description

Only by clicking on the window I get a weird flickering on the screen. It happens even before selecting any project, in the launcher, but it is more apparent opening an empty project. It seems to react to just clicking with the mouse on the screen, but in the end it happens by itself.

https://github.com/godotengine/godot/assets/627698/694dfe93-6423-46ce-a69d-45815731da8d

### Steps to reproduce

Just open the launcher and click on it, you will start seeing black frames
Open an empty project, click in the editor also will give black frames.
Run an empty project, the window will start showing (not responding) in the title as you just click on it

### Minimal reproduction project

No need, it already happens in the launcher. It is more apparent with a full empty project running (check video)

**Comment by Calinou** [comment]
Can you reproduce this after switching to the Mobile or Compatibility rendering methods in the top-right corner?

Can you reproduce this after enabling **Single Window Mode** in the Editor Settings, then restarting the editor?

**Comment by d0n3val** [comment]
I can confirm it still happens in Mobile and Compatibility rendering method.
I tried also switching Single Window Mode in and out and it does not affect the outcome.

Feels to me like a 4070 driver bug. My old 2070 was working fine.

How can I be of more help ?

**Comment by Calinou** [comment]
> Feels to me like a 4070 driver bug. My old 2070 was working fine.

It works just fine for me on a RTX 4090 and a recent NVIDIA driver downloaded from nvidia.com (not sure which one exactly, I'm not on Windows right now). Make sure to use a driver from nvidia.com, not Windows Update.

**Comment by d0n3val** [comment]
I have tried the nvidia drivers 531.79 and the two previous ones.
I am right now on nvidia studio driver 531.61.

The problem persist in all those.

I have a software to handle multiple desktops called SylphyhornPlus - I've tried to remove but problem still persist. A part from that is a recently installed window 10, not much more software on it.

My problem seems similar but unrelated with #32990 since the flickering is not when using pop-ups, just by clicking on the screen anywhere.

**Comment by d0n3val** [comment]
I have tried the last three nvidia drivers, right now testing the studio drivers but no luck, it still happens. I've also uninstall th nvidia drivers and I still have it. Perhaps it is not tied to graphics drivers after all. It seems connected to just receiving input.

It specifically happens when I click on the empty window. Looking at the performance, you can see those peaks are when I just go to the empty window and spam left-mouse click in it:

![image](https://github.com/godotengine/godot/assets/627698/86aca2db-c1f5-4d6a-acce-186836c08fff)

**Comment by lazaromenezes** [comment]
I'm seeing a similar issue with Mobile renderer, but with the game debug window. I haven't try Compatibility yet. It happens the most when I start the xbox screen recorder. 

https://github.com/godotengine/godot/assets/8123916/816823e8-91e2-4df9-bc00-0946fa33b44c

I'm running it into a Windows 11 box, with a 3060 and driver version 535.50.

I just got started with the engine so I don't know which kind of details could be usefull, please let me know if there's any usefull data I could provide :)

**Comment by fractilegames** [comment]
I have seen very similar looking black flickering on Godot 3.6 beta 3 on Linux (with Intel integrated GPU). It happens randomly. Sometimes days go by without seeing it and when it appears it usually passes after a while without doing anything.

I initially though it only affected the editor and didn't worry about it too much but I have now seen it happen on Steam Deck too (of course while showing my game in public).

Unfortunately I don't have any information that helps tracking this down right now.

**Comment by valkyrienyanko** [comment]
I have similar issue except the black flickering only occurs while in-game and it happens at random. Sometimes it's there, sometimes it's not.

My specs:
- Windows 11
- GPU: RX 6600 CPU: 10400
- 16 GB RAM

**Comment by fractilegames** [comment]
I saw this flickering again and this time I managed to capture a screenshots at the right time (two consecutive screenshots):

![image](https://github.com/godotengine/godot/assets/2310335/f9f88533-0b51-49e4-9ddc-34854def4617)
![image](https://github.com/godotengine/godot/assets/2310335/194103e7-c614-4223-acc8-d5ddab8f1944)


It looks like only the 3D viewport is flickering while 2D UI rendered in the root viewport is not. So my case seems to be quite different to the others here.

**Comment by Calinou** [comment]
Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) whether https://github.com/godotengine/godot/pull/80566 resolves this?

**Comment by fractilegames** [comment]
> Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) whether #80566 resolves this?

I can't because this is happening in Godot 3.6 beta3.

**Comment by jupiterbjy** [comment]
Just confirming, happening at 4.1.3 stable - not happening in 4.1.2 stable, could this be a regression bug?

## Video

To make sure this isn't display issue, added white image at background for clear comparison.

This can't be recorded on OBS despite with 120Hz capture rate, only visible over display.

https://github.com/godotengine/godot/assets/26041217/13acf904-326f-4424-9941-19daba6f4671

## Reproducible file

Reproducible file is not required, this literally happen as soon as I create new project, and happen on almost every mouse-hove between panels.

## System info

- OS: Win11 Education 64bit 22H2 (22621.2428)
- CPU: R5 5800X
- GPU: RTX 3070
- Affected Godot version: 4.1.3 stable
- Display running at 240Hz

## Additional notes

![image](https://github.com/godotengine/godot/assets/26041217/9d2c6a9e-167a-438e-b1c2-0b53c86ec5d3)

Issue is resolved by setting 'continuous editor update' which forces the editor updates.

As enabling that gives a warning popup that using this as workaround is not recommended and one should bug report if such is required, hence here I am!

Lemme know if there's more resource like logs, etc I can share.

**Comment by d0n3val** [comment]
Let me add that I re-installed Linux with NVidia drivers in the same computer and the problem is now gone.

**Comment by jupiterbjy** [comment]
So this could be just NVidia being Nvidia? I don't see any update on Windows driver yet so guess I should wait with continuous update on.

What's driver version you're having on linux? Mine reports 546.01

**Comment by ix-56h** [comment]
> Just confirming, happening at 4.1.3 stable - not happening in 4.1.2 stable, could this be a regression bug?
> ## Video
> 
> To make sure this isn't display issue, added white image at background for clear comparison.
> 
> Flicker happen on almost every mouse-hover between panels or window switch.
> 20231106_071121.mp4
> ## Reproducible file
> 
> Reproducible file is not required, this literally happen as soon as I create new project.
> ## System info
> 
>     * OS: Win11 Education 64bit 22H2 (22621.2428)
> 
>     * CPU: R5 5800X
> 
>     * GPU: RTX 3070
> 
>     * Affected Godot version: 4.1.3 stable
> 
>     * Display running at 240Hz
> 
> 
> ## Additional notes
> 
> ![image](https://user-images.githubusercontent.com/26041217/280558991-9d2c6a9e-167a-438e-b1c2-0b53c86ec5d3.png)
> 
> Issue is resolved by setting 'continuous editor update' which forces the editor updates.
> 
> As enabling that gives a warning popup that using this as workaround is not recommended and one should bug report if such is required, hence here I am!
> 
> Lemme know if there's more resource like logs, etc I can share.

I had the same issue, it has been solved after disabling freesync on my monitor settings.

**Comment by Calinou** [comment]
If it's *only* the Godot window flickering, this is likely due to the same cause as https://github.com/godotengine/godot/issues/84137.

If you entire monitor is flickering, this is likely VRR flicker which is a hardware issue that can't be fixed by Godot. Disable VRR by disabling G-Sync or FreeSync in your monitor settings, or change settings to make VRR only effective in fullscreen applications.

**Comment by jupiterbjy** [comment]
It was impossible to capture the black frames with OBS even at 120Hz(monitor at 240) so I used phone camera to capture that only godot window is flickering. That indicate it may not be on godot side, will wait for new nvidia driver and update about the issue.

Or should I be better just straight up testing with 4.2 master branch? lemme know what you prefer!

**Comment by juse4pro** [comment]
I also got this bug since I switched my PC setup to a RTX4060 and a 144Hz G-Sync compatible Screen (single). The screen is actually the same and everything worked perfectly before I got the new GPU. Had a 1660 Ti before.

Setting the Hz to 60 or disabling G-Sync entirely did not fix the problem unfortunately. Not only in the editor but also games made with Godot have this issue when clicking.

Tested on 4.3.

**Comment by juse4pro** [comment]
> Just confirming, happening at 4.1.3 stable - not happening in 4.1.2 stable, could this be a regression bug?

I also checked this. This bug happens with all Godot-made games (but also some(!) others like e.g. Cossacks 3). It happens with 4.0, 4.4 and it also happens with 3.5

https://github.com/user-attachments/assets/b342cf47-e436-4e37-a1f6-0f08ccf5a9d9

I en/disabled free sync, no effect. I en/disabled GPU scheduling, no effect. I forced dedicated GPU / enabled continuous update, no effect.

I tried all different renderers and rendering modes, no effect.

I attached a video because it shows some other side effects.
* The window somehow get re-created as you can see in the task bar
* Only happens on click
* Sometimes the app doesn't even recognize the click (e.g. when trying to resize the window)

Maybe it helps to mention my hardware because for a moment I thought it might be the CPU / GPU combination (always had Intel + Nvidia but I switched to this):
* CPU - AMD Ryzen 9 7900X 12-Core Processor - 12 Cores
* GPU - NVIDIA GeForce RTX 4060
* Windows 11 (Update 23H2 / KB4023057)

**Comment by sherwoodjm** [comment]
> Can you reproduce this after switching to the Mobile or Compatibility rendering methods in the top-right corner?
> 
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings, then restarting the editor?

I was having a similar issue on my Linux desktop (Mint 21.3, using X11 with integrated Intel graphics), and enabling Single Window Mode resolved the issue for Godot 4.4 and 4.4.1.

**Comment by DenilsonDesigns** [comment]
> > Just confirming, happening at 4.1.3 stable - not happening in 4.1.2 stable, could this be a regression bug?
> 
> I also checked this. This bug happens with all Godot-made games (but also some(!) others like e.g. Cossacks 3). It happens with 4.0, 4.4 and it also happens with 3.5
> 
>  R3RQfu6TRN.mp4 
> I en/disabled free sync, no effect. I en/disabled GPU scheduling, no effect. I forced dedicated GPU / enabled continuous update, no effect.
> 
> I tried all different renderers and rendering modes, no effect.
> 
> I attached a video because it shows some other side effects.
> 
> * The window somehow get re-created as you can see in the task bar
> * Only happens on click
> * Sometimes the app doesn't even recognize the click (e.g. when trying to resize the window)
> * Happens more often, of the frame rate is lower
> * Does not happen at all for most other apps like Google Chrome, Windows Explorer, etc
> 
> Maybe it helps to mention my hardware because for a moment I thought it might be the CPU / GPU combination (always had Intel + Nvidia but I switched to this):
> 
> * CPU - AMD Ryzen 9 7900X 12-Core Processor - 12 Cores
> * GPU - NVIDIA GeForce RTX 4060
> * Mainboard - B650 Gaming Plus Wifi MS-7E26
> * Windows 11 (Update 23H2 / KB4023057)

I also am experiencing this on a RTX 4060 (AMD Ryzen 7), but I have used Godot 4 on other (Intel/Nvidia) hardware with no issue. 

Godot is effectively unusable in this state. 

I don't think its a monitor issue, as it happens on the laptop screen and also the extended monitor. 

- I've tried various combinations of enabling/disabling G-SYNC, `Update Continuously` on/off. 

- Have also tried running Godot with `--fixed-fps` flags. 

- Have tried running Godot with `--rendering-driver opengl3`.

- Have tried `Single Window Mode`

I'm on 4.4, but I also downloaded 4.4.1 and same issue. I also downloaded Godot 3.6.1 to test, and same issue. 

So I believe it's some issue with the combination of Godot/Nvidia Gpu.

**Comment by Prashanna135** [comment]
i am also experiencing this issue where if i right click on the editor it starts to flicker. I have updated drivers  ran it on compatibility mode and also done  everything mentioned above but still no fix , has anyone managed to fix it ?
  
https://youtu.be/4PMMgje09v4

**Comment by DenilsonDesigns** [comment]
> i am also experiencing this issue where if i right click on the editor it starts to flicker. I have updated drivers ran it on compatibility mode and also done everything mentioned above but still no fix , has anyone managed to fix it ?
> 
> https://youtu.be/4PMMgje09v4

Not completely, but I can mitigate it to a large degree to the point that Godot is usable. These are the settings I put in `Interface` -> `Editor`:

`Low Processor Mode Sleep`: `1`
`Unfocused Low Processor Mode Sleep`: 10000

It still flickers every now and then, but not every time I click around or something, its especially bad on the project select screen and I normally have to click on the project I want to open a few times before the click registers. However once I am in editor it is pretty manageable with the above settings. Looking at your video your issue appears to be the same as mine.

**Comment by dozsolti** [comment]
Go to `Editor` > `Editor Settings` > `Check Advanced Settings` > Set `Low Processor Mode Sleep (µsec)` to a low number, like 10 or 1

**Comment by JJBocanegra** [comment]
I know this bug is for Windows but if someone else as me arrived here looking how to solve the issue in Linux, I had the same issue in CachyOS and what helped me is going to `Editor settings > Run > Platforms > Prefer Wayland` and activate it
