### ISSUE TITLE
Renaming file in file explorer not working on lost focus

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78789]
### Godot version

4.1.rc.1

### System information

Windows 11

### Issue description

When you try to rename a file in file explorer, if the focus is lost from the file explorer it does not work.
Although, it works when the file explorer is in focus.

https://github.com/godotengine/godot/assets/84369217/53cf3353-bcda-49ae-ac58-4014fe49f464

All other functionalities like "Duplicate..." works even if the focus is not there.

Note: Also the name of the Rename menu should remove three dots after name as it does not invoke a dialog anymore, if we are following standards.

### Steps to reproduce

Select a file in the file explorer and click on the text editor to ensure focus is lost (highlighted color border should not be there on file explorer)
Now right click the file in file explorer and click "Rename..."

Nothing happens

### Minimal reproduction project

N.A

**Comment by KoBeWi** [comment]
The is a check for focus when renaming. It should probably check visibility:
https://github.com/godotengine/godot/blob/9a09ee5d0217c4d5e5668fccddfa477bf16af357/editor/filesystem_dock.cpp#L2139-L2152

**Comment by Sauermann** [comment]
Possibly this might get solved by #75062

**Comment by tokengamedev** [comment]
IMO removing context menu when focus is not there is really bad, since it will impact other existing functionalities that work.

Although https://github.com/godotengine/godot/pull/75062 will resolve the main issue, also consider changing the name in the menu itself.

**Comment by quinnyo** [comment]
Note that the scene tree dock doesn't have this issue. It does exhibit an odd focusing behaviour, however. When you activate "Rename..." in a Node's context menu, the scene tree dock grabs keyboard focus, presumably to facilitate typing the new name. Obviously the keyboard events must be captured somehow, but the dock then retains KB focus after the interaction ends. Renaming is *the only* context menu action that does this.

> Though the fact that the dock is not focused when context menu opens is a bug.

I can't speak for the intended behaviour, but I thought it was by design that KB focus is not given to the docks unless absolutely necessary, so as to not interfere with the main editor. For example, starting in the script editor, you can right click on a property/node/file, copy its name/path and then paste it in the script (using the keyboard) without having to manually move focus back to the script editor.

The only Control that gets KB focus when you open a context menu (that I can find) is TextEdit/LineEdit, which is a fairly common pattern in desktop GUI applications.

**Comment by daveTheOldCoder** [comment]
I'm just confirming that this issue still exists in 4.2-dev3 on Linux.

**Comment by Sauermann** [comment]
This seems to be fixed in v4.2.dev5.official [e3e2528ba]

**Comment by KoBeWi** [comment]
Right, it was fixed by #80440 Right-clicking a file focuses the dock now.

**Comment by servel333** [comment]
Why not change it so that a right click in this panel puts the focus on this panel?
