### ISSUE TITLE
Changing the node type requires a scene restart to display the new node type icon on the scene tab

### ISSUE THREAD

**Issue by pablogila** [godotengine/godot#79226]
### Godot version

4.1.stable

### System information

Windows 10, intel hd 620 integrated graphics

### Issue description

Changing the type of a CharacterBody2D to a Node2D will still show the miniature of a CharacterBody2D, and the scene needs to be closed and opened again to show the Node2D miniature.

### Steps to reproduce

Here are the steps I followed that lead to this bug: Create a new project, with a CharacterBody2D as a root node. Add a Sprite2D and CollisionShape2D as childs. Now create a new CharacterBody2D as a child of the first one, and move the sprite and collision nodes inside the nested CharacterBody2D node. Finally, change the type of the original parent node from CharacterBody2D to Node2D. The node icon will still indicate a CharacterBody2D node, although now it is a Node2D. The scene has to be restarted to indicate the new node type correctly.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
Failed to reproduce:

https://github.com/godotengine/godot/assets/47700418/cf16ad29-1d38-4a72-82b3-e42b59f99e9a

**Comment by KoBeWi** [comment]
Might be related to #78670 and fixed by #79203
Also can't reproduce though.

**Comment by venilark** [comment]
I noticed it too.

**Comment by dalexeev** [comment]
> I noticed it too.

Please provide Godot version and describe the steps to reproduce. Are they the same as in the first post or different?

**Comment by venilark** [comment]
> > I noticed it too.
> 
> Please provide Godot version and describe the steps to reproduce. Are they the same as in the first post or different?

4.1 stable
It's not happening now but when it happened I changed the parent node from Node3D to RigidBody3D. Scene was previously saved.
If I manage to reproduce it and know exactly when it happens I'll write again.

**Comment by venilark** [comment]
Still don't know how to replicate it but I had a instance in a scene which was an Area3D, and without changing type or doing anything with it, it had the "Node" icon. I had to close the instance tab and the scene that had it inside and then the Area3D icon returned.

**Comment by KoBeWi** [comment]
Seems like duplicate of #76983
Your node has a script attached.

**Comment by pablogila** [comment]
That's it! Thank you. Closing the thread now.
