### ISSUE TITLE
SpotLight3D shadows don't affect Volumentric Fog

### ISSUE THREAD

**Issue by dreadlocks-dude** [godotengine/godot#80039]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.3667) - 13th Gen Intel(R) Core(TM) i5-13600K (20 Threads)

### Issue description

SpotLight3D shadow option has no effect on FogVolume.
![image](https://github.com/godotengine/godot/assets/86929275/ac2b37b9-9c0f-4aeb-8bd8-b6dfb46775eb)

Omni Light and directional light work fine:
![image](https://github.com/godotengine/godot/assets/86929275/ebf1cd28-739d-4f95-b1a1-509cae986b4a)
![image](https://github.com/godotengine/godot/assets/86929275/e8050b66-4f3a-4157-bbba-ad1007aea2e1)
Also default energy of SpotLight3D affects fog light way less than other light sources, you have to set Energy to 8 or even 10 to get same brightness as Omnilight with 1

### Steps to reproduce

Create FogVolume with any shape and default settings
Light it with SpotLight3D, shadows on
Put an occluding object in front of the light

### Minimal reproduction project

[SpotLight3DShadowIssue.zip](https://github.com/godotengine/godot/files/12208364/SpotLight3DShadowIssue.zip)

**Comment by clayjohn** [comment]
Can you please compare the results with 4.0.3 to see if they are the same? I remember we had a few important fixes to spotlight shadows early in 4.0.x, so I suspect something has regressed in 4.1.x

**Comment by dreadlocks-dude** [comment]
> Can you please compare the results with 4.0.3 to see if they are the same? I remember we had a few important fixes to spotlight shadows early in 4.0.x, so I suspect something has regressed in 4.1.x

I tried 4.0.3 - Same. Both the light strength and absence of shadows.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/57722.

**Comment by bitsawer** [comment]
Looks like increasing the SpotLight Range fixes the shadow issue, the shadow starts to appear as the range increases. You can actually see this very, very faint SpotLight shadow in the first post picture. Might have been indirectly fixed by https://github.com/godotengine/godot/pull/73919, although I'm not sure why increasing the range helps. Maybe there is some fade calculation etc. involved and it needs some room to kick in? There might still be a bug somewhere in the calculation, but at least it looks like this works as a workaround.

![spot](https://github.com/godotengine/godot/assets/22456603/95134ad9-d3f3-4dbb-9197-49b5a629b01a)

**Comment by Robert-K** [comment]
This appears to still be a problem in 4.4.1-stable:

![Image](https://github.com/user-attachments/assets/1dfc893c-7f72-44cf-98b9-9ffc112aa9f7)

**Comment by Robert-K** [comment]
I should add that changing the range (or any other setting) did not make any SpotLight3D shadows appear in the  volumetric fog.

**Comment by karlji** [comment]
The problem is still happening in Godot 4.5.1. Tweaking settings doesn't seem to help.
