### ISSUE TITLE
GDExtension: _ready, _enter_tree, _process, etc. not being called anymore

### ISSUE THREAD

**Issue by minoaut** [godotengine/godot#82377]
### Godot version

v4.2.dev.custom_build [7e67b496f]

### System information

Ubuntu 23.04 Lunar Lobster

### Issue description

After the latest Godot rebuild from git none of these virtual functions are called anymore:
    void _ready() override;
    void _enter_tree() override;
    void _exit_tree() override;
    void _process(double delta) override;
    void _physics_process(double delta) override;

My project is borked, won't even start anymore. I'll include simple sample code below. I suppose all GDExtension code is affected.

Is this related to https://github.com/godotengine/godot/pull/80284? If yes how can I turn  reloading of GDExtensions off?

### Steps to reproduce

- unzip sample code
- cd gdextension_notifications_not_called
- make
- godot -e
- godot

expected output:
TestMesh::TestMesh()
TestMesh::_enter_tree()
TestMesh::_ready()
TestMesh::_process()
TestMesh::_physics_process()
...

actual output:
TestMesh::TestMesh()

### Minimal reproduction project

[gdextension_notifications_not_called.zip](https://github.com/godotengine/godot/files/12728715/gdextension_notifications_not_called.zip)

**Comment by dsnopek** [comment]
Which commit of godot-cpp are you using? You need to use https://github.com/godotengine/godot-cpp/commit/bf2f9e2f554bd22d127c744ca3d1a077b7bb5a63 in order for it to be compatible with the latest Godot `master`.

I've definitely tested `_ready` and `_process` together with the hot reloading PRs, and they should be working fine.

**Comment by dsnopek** [comment]
I just checked in the MRP attached to this issue, and it's using https://github.com/godotengine/godot-cpp/commit/c44c3d5ebf9826214efc971f0cbe047789af2575 (one commit behind `master`) which is probably the source of the problem.

I also quickly retested with one of my test projects and the latest `master` of both Godot and godot-cpp, and `_process` and `_ready` were working fine!

**Comment by dsnopek** [comment]
> I only ever fetch from latest Godot master. The latest commit was [7e67b49](https://github.com/godotengine/godot/commit/7e67b496ff7e35f66b88adcbdd5b252d01739cbb). It's in the godot version above.

I'm talking about godot-cpp `master`. In your MRP, you've got godot-cpp at https://github.com/godotengine/godot-cpp/commit/c44c3d5ebf9826214efc971f0cbe047789af2575 whereas you need to use https://github.com/godotengine/godot-cpp/commit/bf2f9e2f554bd22d127c744ca3d1a077b7bb5a63 for it to be compatible with Godot `master`.

**Comment by minoaut** [comment]
I pulled https://github.com/godotengine/godot-cpp fresh before I posted. But I see there's a new commit now. Let me try.

**Comment by minoaut** [comment]
Yep, sample gets notifications again. Big project still crashes on Intel but runs now on NVIDIA at least. Different issue. 
I guess I picked an unlucky time to upgrade. Thanks for your help.
