### ISSUE TITLE
Webgl export crashes on AMD graphics cards 

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#82814]
### Godot version

4.1.1.stable

### System information

One person with AMD gfx card running Linux, another one chimed in who also had AMD gfx card

### Issue description

My ludum dare 54 game does allegedly not run for people with AMD gfx cards.
I don't have one myself, but they showed the error on stream and it said something about array length must be greater than zero when compiling shaders. 

### Steps to reproduce

On a machine with AMD gfx card, try and run the game. The source is linked too.
I can't reproduce myself, and if none of you guys can do it either then I guess we just hope for a replacement of the html5 export sometime soon! :)
I realize this bug report is really bad, sorry.

### Minimal reproduction project

https://ldjam.dev/events/ludum-dare/54/king-of-the-gloaming-castle

**Comment by akien-mga** [comment]
Tested on Linux (Mageia 9) with Radeon RX Vega M, it's working fine for me in Firefox 115.2.1esr, Firefox Nightly 120.0a1, and Chromium 117.0.5938.132.

Could you ask those users to copy the logs from the browser's developer console after the game crashes?

**Comment by Wiggan** [comment]
I've asked, but he's still streaming. Hopefully he can check afterwards. Thanks for testing!

**Comment by sonic2kk** [comment]
Works for me on Arch Linux using a 7900XTX, with Firefox Developer Edition 119.0b4, running Mesa 23.2.1 (latest stable at time of writing afaik). However, I _am_ seeing the array error in the console. When trying to expand, I couldn't see any extra information, so this is the only errors I could see. When filtering in the Firefox Developer Console, these were the only errors since page load.

![image](https://github.com/godotengine/godot/assets/7917345/a9fcce45-0cee-4ac3-a78a-2b18dd6a0360)

Despite this, the game is running as intended (I believe?)

![image](https://github.com/godotengine/godot/assets/7917345/d0c65844-74b8-4a43-893b-cded32823a54)

**Comment by bitsawer** [comment]
Works for me using NVIDIA GTX 970 on Windows.

This seems to be the same issue fixed by https://github.com/godotengine/godot/pull/80909. So, updating to Godot 4.1.2 should fix it.

**Comment by Wiggan** [comment]
![image](https://github.com/godotengine/godot/assets/6214882/446705e6-545f-4b7f-9eb8-94f16e6d6747)
This is what it's supposed to look like. The printscreen looks very dark in your post @sonic2kk

**Comment by sonic2kk** [comment]
From looking at the PR and context, am I correct in assuming the visual discrepancy I'm seeing is a result of the shader compilation issue? Even though the game loads for me it seems the shader still doesn't compile properly, which could explain why everything is so dark.

I would be happy to do a follow-up test a version built with a newer Godot version, if necessary :-)
