### ISSUE TITLE
Corrupted Scenes due to Caching in .godot

### ISSUE THREAD

**Issue by dekaravanhoc** [godotengine/godot#83187]
### Godot version

4.1.2 stable

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Basically, I get corrupted scenes all the time. With the scenes and all resources completely ok and working. (Build works without Problems.)
Also there is no Info why they are corrupted/cant be opened.. In 3.x at least you always could open the scene and fix dependencies etc. But thats another topic.

So the main problem is, that rebasing in git basically corrupts my project (several scenes in it) everytime.
It worked fine before the rebase.
To fix this I need to delete the .godot folder. I load the project - still getting corrupted scenes issues (probably due to some weird racing conditions, without caches in .godot) - reload it again and then everything works.

This workaround works basically all the time when something goes corrupt.

Sorry if this already exists I looked through the issues and did not found anything (which is a little bit weird, as I guess it should happen to nearly everyone who uses git with rebase.

### Steps to reproduce

Have a more or less complex project.
Rebase in Git.

### Minimal reproduction project

Not really. Did not try out at which complexity stage of a project this happens. Or what needs to be done with a scene to trigger this behavior.
Maybe I find the time to do it.

**Comment by KoBeWi** [comment]
> In 3.x at least you always could open the scene and fix dependencies etc. But thats another topic.

This is fixed by #83024

> So the main problem is, that rebasing in git basically corrupts my project (several scenes in it) everytime.

Rebasing the project should not have any effect on its stability, unless you happen to break some dependencies or track the `.godot` folder (which is not recommended).

**Comment by dekaravanhoc** [comment]
.godot is not tracked
The rebase does not change anything (i.e. just squashing commits).
Opened Scripts and Scenes in Godot also get an update that something changed after a rebase (even so no content changed).

**Comment by KoBeWi** [comment]
Rebase will affect modified time of the files and Godot will detect that, even if their content is the same. It should not have any effect.

**Comment by jdies** [comment]
Godot 4.1 - I just fixed a corrupt scene by copying the scene somewhere to save it, git revert the scene, overwrite the unchanged scene. Just putting this here, might open a proper issue report later, can't put time in a reproduction project right now.

1. Had many RigidBody2D in the scene moving at high pace and, while the game was running, changed Project Settings > Physics > 2D > Solver Iterations from 16 to 64 
2. Game started slowing down significantly, I killed the Godot editor with task manager
3. Reopened project, the scene that was previously opened was now corrupted and couldn't be opened anymore

Again, here is how I fixed it
1. Copy the corrupted scene somewhere 
2. git revert the corrupted scene
3. open project, open the previously corrupted scene - works now
4. close project, replace the now working scene with the one before the git revert
5. open project, open the scene. Everything works + my changes are there again

**Comment by charliewhitfield** [comment]
> Maybe a button for the user to nuke all caches really is a good idea as a first step. Even if rebuilding these caches takes some minutes, it still would be faster than googling.

+1 for that. Or, what I really want is a button to nuke '.godot/global_script_class_cache.cfg' without nuking all of my imported assets. (Note: deleting 'global_script_class_cache.cfg' by itself breaks the project. The only option seems to be to delete the entire .godot directory.)

**Comment by dekaravanhoc** [comment]
Hey,

I got some updates and narrowed the problem down in my case after some research and sparse information on this matter.
I think the biggest Problem is, that the error messages from the engine are so opaque...

But back to my case. 
The issue resolved around preloading of resources and seemingly resulting cyclic references based on Static Typing, that lead to corrupt scenes.
And also preloading the same resource (tscn) twice from different code parts)

First Case: So I got Class A that preloads Class B.
Class A also has a static var holding the instance of itself, when it gets instantiated (only happens once and to remove the need for a singleton and the need to pass some reference around.)
Class B uses that instance.
After deletion of .godot I get the error (Class B) could not be loaded correctly.
After restarting this issue is seemingly resolved as I do net get any more errors in the console. But it is not.
As using this Class B in Scene of Class C (preloading/@export) seems to over time corrupts Scene C. 

Second Case: I got Class A and it gets preloaded in Class B and Class C.
Also Class C references Class B and uses the preloaded Class indirectly through Class B and directly through preloading it.
A least there I get an error - that Class A gets loaded from a different place, when starting without .godot
Also after restarting the editor the error is gone.
Only the same issues arise.
Solved when one preload is changed to load.

I only got there because I did a little Refactoring and starting Scenes by itself in the process. Leading to error messages that did not come up, when the game was loaded by starting the main scene. These error messages where still not helpful, but at least I had a starting point for some digging.

So there seem to be two problems.
Cyclic referencing due to Code interpretation of the editor when using preload?
Preloading a Scene from different Classes. (That might also only be the case, when there is also a reference between the classes.)
The thing is, that these Scenes work fine. They run and you can open them without problems. So exerything seems fine. Only if you use these Scenes for other Scenes the problem arises, as these scenes get broken and you do not know why, because the tscene file is correct and every ressource and reference is working too and it works when you run the game....

I am not quite shure how the rebasing fits in there, but nuking the caches did not really solve the problem, it just posponed it until some Scene gets corrupted beyond obvious repair (Using one of the Classes/Scenes desrcibed above i.e. Inheriting from a Scene or preloading it.

Hope that helps.

**Comment by RpxdYTX** [comment]
Still happening on 4.2.1.stable.arch_linux. whats i found interesting (and what led me to this issue) is that the editor panics with a corrupt file but the preload doesn't (meaning that it's anoying to edit the scene, but should stiil work on release). Reloading the cache for a specific file could be a good fallback for when the engine finds a corrupt file, making so that the error only appears if the actual file is corrupted, not the cached one.

**Comment by MayaKerr** [comment]
> If I'm not mistaken, this seems related to #83395. In that issue, one creates a class error by duplicating a file. Well, the error is perfectly expected. However, unlike Godot 3.x, the editor can't seem to resolve these errors without the user manually deleting .godot.

I'm having this issue with the duplicated classes-- would it resolve my class issues if I deleted the .godot in my project, or will this screw my project up more?

**Comment by MEELOJEELO** [comment]
Im having the same issue here, has there been any kind of fix?

**Comment by KoBeWi** [comment]
It should be fixed in 4.3.

**Comment by voidexp** [comment]
@KoBeWi can you link the PR/commit by which this is fixed? I'd like to give it a couple of runs, because seem to experience this issue a lot in after-rebase scenarios.

**Comment by KoBeWi** [comment]
#92303 fixes script issues.
#85159 and the follow-up fixes issues with corrupted scenes that can't be opened.
