### ISSUE TITLE
scene/main/node.cpp:2006 - Parameter "common_parent" is null.

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#83304]
### Godot version

4.2.Beta 1

### System information

Windows 11

### Issue description

When saving all scenes "scene/main/node.cpp:2006 - Parameter "common_parent" is null."  will appear 6 times in Output.

### Steps to reproduce

Save all Scenes or run the game

### Minimal reproduction project

n/a

**Comment by Ciapas-Linux** [comment]
Hi
Under Linux Debian it is the same:
scene/main/node.cpp:2006 - Parameter "common_parent" is null.

**Comment by wjagodfrey** [comment]
`MacOS 12.3, 4.2-beta1` as well. Happens once or twice when running project (Cmd+B).

**Comment by wenqiangwang** [comment]
Godot 4.1.2 has the same issue but the error message is instead "scene/main/node.cpp:1994 - Parameter "common_parent" is null." - only the line number is different, which seems the same line in Node::get_path_to.

The repro is in saving a branch as a scene like below:

Create scene structure:
Node3D
- Node3D 
  - AnimationPlayer 

Add a script for the middle Node3D, within which has "@export var animation_player : AnimationPlayer". No other code is needed.

Now right click on the middle Node3D node and click "Save Branch as Scene", hit the OK button in the popup dialog and it repros.

**Comment by theraot** [comment]
I'm getting `scene/main/node.cpp:2006 - Parameter "common_parent" is null.` in Godot 4.2.beta2 when using "Save All Scenes" with multiple scenes open. Seems to appear once per `AnimationPlayer` in scenes others than the currently edited one.

**Comment by mikeklubnika** [comment]
"scene/main/node.cpp:1988 - Parameter "common_parent" is null."
I got this every single time I saved. Very confusing, but managed to re-create it: 

1. @export var thing Node3D, to get a field in the inspector.
2. add a Node3D to the field as you do
3. delete the Node3D from the scene.
4. the field in the inspector is now empty, but the engine seems confused because if it were empty it would say 'Assign ...', instead there is simply a blank rectangle and the 'Clear' button is still visible on the right.
5. saving the scene now throws the same error message mentioned before, until the field is actually cleared.

**Comment by theraot** [comment]
@mikeklubnika Please mention the version of Godot you were using.

**Comment by paxer** [comment]
4.2.Beta 3, macOS 14, happens when  running a scene or a project

**Comment by KoBeWi** [comment]
Getting the same error in 4.2 beta4. It appears randomly when running the project (so all scenes are saved), seems to depend on a combination of open scenes/scripts. I can't reproduce it reliably, even with the steps described above.

**Comment by YuriSizov** [comment]
Removing regression because there are confirmations of this from 4.1.

**Comment by KoBeWi** [comment]
Ok, got a stack trace:
```
Node::get_path_to(const Node * p_node, bool p_use_unique_path) Line 2007 (c:\godot_source\scene\main\node.cpp:2007)
AnimationMixer::reset() Line 1996 (c:\godot_source\scene\animation\animation_mixer.cpp:1996)
AnimationMixer::apply_reset(bool p_user_initiated) Line 1979 (c:\godot_source\scene\animation\animation_mixer.cpp:1979)
_reset_animation_mixers(Node * p_node, List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator> * r_anim_backups) Line 1737 (c:\godot_source\editor\editor_node.cpp:1737)
_reset_animation_mixers(Node * p_node, List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator> * r_anim_backups) Line 1745 (c:\godot_source\editor\editor_node.cpp:1745)
EditorNode::_save_scene(String p_file, int idx) Line 1766 (c:\godot_source\editor\editor_node.cpp:1766)
EditorNode::_save_all_scenes() Line 1911 (c:\godot_source\editor\editor_node.cpp:1911)
EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) Line 2662 (c:\godot_source\editor\editor_node.cpp:2662)
EditorNode::_menu_option(int p_option) Line 1371 (c:\godot_source\editor\editor_node.cpp:1371)
EditorNode::try_autosave() Line 1868 (c:\godot_source\editor\editor_node.cpp:1868)
EditorRunBar::_run_scene(const String & p_scene_path) Line 230 (c:\godot_source\editor\gui\editor_run_bar.cpp:230)
EditorRunBar::play_main_scene(bool p_from_native) Line 271 (c:\godot_source\editor\gui\editor_run_bar.cpp:271)
call_with_variant_args_helper<EditorRunBar,bool,0>(EditorRunBar * p_instance, void(EditorRunBar::*)(bool) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 308 (c:\godot_source\core\variant\binder_common.h:308)
call_with_variant_args<EditorRunBar,bool>(EditorRunBar * p_instance, void(EditorRunBar::*)(bool) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 418 (c:\godot_source\core\variant\binder_common.h:418)
CallableCustomMethodPointer<EditorRunBar,bool>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 105 (c:\godot_source\core\object\callable_method_pointer.h:105)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
CallableCustomBind::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 145 (c:\godot_source\core\variant\callable_bind.cpp:145)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
Object::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1127 (c:\godot_source\core\object\object.cpp:1127)
Node::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 3609 (c:\godot_source\scene\main\node.cpp:3609)
```
Seems to be caused by RESET track taking effect in another scene.

**Comment by YuriSizov** [comment]
@dev-bre Could you provide a reproduction project that demonstrates the issue with 4.2 stable?

**Comment by Pr1nce3** [comment]
> This is still happening in 4.2 stable release.

did you try reloading project mine got fixed by reloading. it started happening when i deleted timer node

**Comment by KanoAlgiz** [comment]
Getting this error on v4.2.1.stable.mono when trying to ctrl-c - ctrl-v a button node with existing 'pressed' signal.

**Comment by AdriaandeJongh** [comment]
Also seeing this error in v4.2.1.stable after duplicating a node, and it reappears after restarting the editor.

**Comment by KoBeWi** [comment]
You need to compile the engine and use C++ debugger to get a stack trace.

https://github.com/godotengine/godot/blob/c8c483cf57a768110fce57e509f9b855e69d34b7/scene/main/node.cpp#L2019
Put a breakpoint at this line and add `if (!common_parent)` above.

Do you get it on every duplicate though? Is it specific to some scene/project?

**Comment by griessbreilp** [comment]
Maybe that helps, maybe not.
Had the same error.
What I did:
- Create a Scene with a Control Node.
- Add an Area2D Child
- Add a Shape
- Connect the area_entered() signal to a script on the Control Node
- Add a TextureRect -> Make it the parent of the Scene -> Attach the Script of the Control Node to it -> Delete the Control Node

Now I got the error every time I saved something, loaded, or what ever.

What I oberserved:
- Area2D claims to have a connected Signal, and if pressed "Go To Method" goes into the TextureRect Script at the correct spot, BUT the Script itself didn't show a connected signal

How I resolved it:
- Disconnect the signal, reconnect the signal

Maybe that helps to troubleshoot it more.
Otherwise I really think that if a signal is connected to a Node that gets deleted, the signal should just disconnect? Dunno^^

**Comment by AThousandShips** [comment]
Please provide a minimum reproduction project:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- If the reproduction steps are not project dependent (e.g. the bug is visible in a brand new project), you can write "N/A" in the field.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by KoBeWi** [comment]
I reproduced it, but it's unrelated to the original issue. It's very similar to #46881

**Comment by jjoshpoland** [comment]
I was getting this in 4.2.2 mono as well. Confirmed that resetting the export property in the inspector cleared the error.

> `"scene/main/node.cpp:1988 - Parameter "common_parent" is null."` I got this every single time I saved (4.1.1 stable). Very confusing, but managed to re-create it:
> 
>     1. `@export var thing : Node3D`, to get a field in the inspector.
> 
>     2. add a Node3D to the field as you do.
> 
>     3. delete the Node3D from the scene.
> 
>     4. the field in the inspector is now empty, but the engine seems confused because if it were empty it would say 'Assign ...', instead there is simply a blank rectangle and the 'Clear' button is still visible on the right.
> 
>     5. saving the scene now throws the same error message mentioned before, **until the field is actually cleared.**

**Comment by glenw83** [comment]
Had this error in GD 4.2.1 stable. Fixed by reloading current project.

**Comment by Klaim** [comment]
Just hit this exact same issue in 4.3.0. Fixed by reloading the project.

**Comment by bbroens** [comment]
I had this happen in 4.3 Stable Mono after I had changed an [Export] private **Sprite2D** into an [Export] private **PackedScene** and then trashing the Sprite2D configured for that field. This resulted in the export field in the editor being empty, and showing this error when saving the scene. The error went away when I plugged a new node into the export field.

What I think is happening, is that this bug comes from the type-changed [Export] field. Somehow it still expected the trashed previous node.

**Comment by Mr-PASTER** [comment]
Good evening, found the cause of the error. The error occurs when you try to save the project with variables not assigned in the inspector. If you create a node in an empty project, add a script with “@export var tratatata:Node3D”, and then just do not specify Node3D in Editor, this error will be repeated.
GODOT 4.3 Stabile

**Comment by KoBeWi** [comment]
Can't reproduce it.

https://github.com/user-attachments/assets/76fc1cb1-7c01-479a-b259-4a2485261d17

**Comment by LordMcMutton** [comment]
I can't find why this is closed- it's still happening in 4.4.1

Does this error even serve any purpose? Can't we just delete it?

**Comment by KoBeWi** [comment]
It's closed, because the original issue was fixed. If the error still appears, it has a different cause and should get a new issue with updated reproduction steps.
