### ISSUE TITLE
C#: ResourceUID methods (e.g. `IdToText` and `CreateId`) throws exceptions

### ISSUE THREAD

**Issue by juse4pro** [godotengine/godot#84385]
### Godot version

v4.2.dev3.mono.official [013e8e3af]

### System information

Windows 11

### Issue description

Using  static methods of class `ResourceUid` throw exceptions (see ![image](https://github.com/godotengine/godot/assets/7323098/3c16461e-6d93-4daa-ac2f-1a638102d73d)).

It also does not matter if the ID actually exists in `res://`. That is also not necessary because it is a pure conversion as far as I understand it.

The GDScript version works like expected.

### Steps to reproduce

* Create a C# based Godot project
* Create any script (autoload or node script) and put e.g. `GD.Print(ResourceUid.IdToText(7));` into the ready method
* Run and get exceptions
* The GDScript version of `ResourceUid.id_to_text(7)` on the other hand returns `uid://h` like expected

### Minimal reproduction project

[ResourceUidBug.zip](https://github.com/godotengine/godot/files/13245156/ResourceUidBug.zip)

**Comment by raulsntos** [comment]
Thanks for trying the 4.2 preview, dev 3 is a bit old now and I remember similiar issues being fixed during the betas. Can you try the latest preview release ([4.2 beta 4](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-4/)) and see if this is already fixed?

**Comment by juse4pro** [comment]
Tried 4.2-beta4 now and it actually is working there. Good to know. Thanks for the tipp! Unfortunately we are still not able to push the version for our game due to this very critical bug: https://github.com/godotengine/godot/issues/82279.

But this is a different topic and therefore obsolete. :)
