### ISSUE TITLE
Empty test project fails to successfully export to Xcode in Godot 4.1.3

### ISSUE THREAD

**Issue by scripturial** [godotengine/godot#84923]
### Godot version

Godot 4.1.3

### System information

Mac Sonoma 14.0, Xcode 15.0.1 (Latest of everything as far as I can tell)

### Issue description

An empty test project with a simple Node2D and a Table fails to export for iOS with the following message:

    /Users/scripturial/Downloads/ios/TempTestDeleteMe.xcodeproj: error:
    "TempTestDeleteMe" requires a provisioning profile. Select a provisioning
    profile in the Signing & Capabilities editor. (in target 'TempTestDeleteMe'
    from project 'TempTestDeleteMe')
    ** ARCHIVE FAILED **

The project is half exported, and this half exported project half works, but it is incomplete. (For example, if I add the SQLite plugin, the plugin files don't appear to be copied into Xcode and SQLite does not work.

### Steps to reproduce

 - Create an empty project with a simple label
 - Add some icons to make sure the exporter doesn't get upset about the icons
 - Use the Export panel to create an iOS export
 - do an export.
 
 It doesn't seem like it matters what export settings I enter, it always produces the error. But here is what I have in my test project:
 
 
<img width="471" alt="image" src="https://github.com/godotengine/godot/assets/138373494/d6095e91-58c3-4bf3-ad65-0d5f72f7f61a">

### Minimal reproduction project

It's literally an empty project? Should I upload it?

**Comment by bruvzg** [comment]
> It doesn't seem like it matters what export settings I enter, it always produces the error. But here is what I have in my test project

You should have valid team ID and bundle ID for export to work.

And app bundle identifier should be registered in the Apple Developer account, you can do it manually. Or you can open and build the exported project in Xcode (needed only once for ID) and it will do it for you (this is the only way if you are testing with free Apple Developer account).

**Comment by scripturial** [comment]
Thanks for your reply. Yes I did use a valid Team ID and Bundle ID, I just changed them for the screenshot, so they weren't in the issue tracker. But I will double check right now.

**Comment by scripturial** [comment]
Thanks for your reply. Yes I did use a valid Team ID and Bundle ID, I just changed them for the screenshot, so they weren't in the issue tracker.  I have copied and pasted the Team ID and Bundle ID from the Godot 3 version of the project exactly, so I know I haven't made a mistake with typing them out.
<img width="641" alt="image" src="https://github.com/godotengine/godot/assets/138373494/81888298-4dee-4b7c-8a3d-ed280ddfe133">

**Comment by scripturial** [comment]
Just to follow up on this, in case anyone else is encountering this error. I have moved forward on my non-test (actual real) project by removing SQLite and I am now able to just ignore this error as far as I can tell. (Tested app completely on a range of devices, and its in the Apple waiting for approval queue.)

**Comment by fatduckling** [comment]
I'm having the same issue with Godot 4.2 RC2. I'm getting the 'select a provisioning profile in the Signing & Compatibilities editor' error.

As a workaround, I removed the Provisioning Profile UUID fields and set the Export Method to App Store. At least now the IPA can get created to test it out manually until this bug is fixed. 

Thanks

**Comment by scripturial** [comment]
I just generated and uploaded a new iOS release using 4.2 RC2, and I too am still having this problem.

(Although as with 4.1.3, I ignored the error, tested on 6 different iOS devices and pushed to apple, and it was just approved by apple.)

**Comment by OlMeiserGaff** [comment]
I am having this exact same problem using v4.2.stable.official [46dc27791]
Exporting with 'Export with Debug' option checked works fine.
It is the release version that is throwing the error and interrupting the export of the project, not letting it export everything required.
In XCode I can manually fix the signing issues, but then the project is missing files.

AFAIK I have all the certificates and provisioning profiles setup correctly.
Does anyone have an answer to this?

I'd like to put my game on the app store.

**Comment by scripturial** [comment]
I can't remember how I fixed this. It might have been some corrupted internal Godot pre-rendered/cached images files. At one point I deleted all the cached data files and reopened Godot.

**Comment by fatduckling** [comment]
This is still an issue in 4.3 stable unfortunately.

**Comment by LMSSonos** [comment]
@fatduckling did you find a solution? I have the same problem, running on a clean install in github actions

**Comment by fatduckling** [comment]
Hey @LMSSonos  This is still an issue in Godot 4.3 unfortunately.
I managed to get around this problem by exporting it in debug mode, which has the 'Export debug method' set to 'Development' and 'Export method release' to 'App store'.

Ideally, 'Development' should be set (it should be App store) but due to this bug, I'm not able to export to that. However, my game I'm working on won't be ready until 1-2 years so hopefully this issue is resolved by then. In the meantime, I'm just exporting in debug mode.

Hope that helps

**Comment by LMSSonos** [comment]
@fatduckling thanks, I found out when activating the `export_project_only` flag it also works with release

**Comment by Iscalej** [comment]
How can you not fix this error yet? I'm stuck with the same thing.

**Comment by LMSSonos** [comment]
> How can you not fix this error yet? I'm stuck with the same thing.

@Iscalej instead of complaining that something is not working in a free product, did you try the workaround mentioned by @fatduckling? for me it worked.
