### ISSUE TITLE
Godot Editor v4.2 Won't Start on Windows due to Nahimic Audio Driver

### ISSUE THREAD

**Issue by aggiechris** [godotengine/godot#85608]
### Godot version

4.2.stable

### System information

Windows 10 Home 22H2 (19045.3693), Intel Core i7-7700HQ, NVIDIA GeForce GTX 1060 (driver 546.01)/Intel HD Graphics 630

### Issue description

Godot v4.2 will not start on my Windows 10 machine. 

Attempts to open Godot_v4.2-stable_win64.exe result in an open process in Task Manager, but the project selection window does not open, and the open process just hangs.

When attempting to open Godot_v4.2-stable_win64_console.exe from the command line, it just hangs without exiting.

I am happy to debug but have no idea where to go from here.

I am not running any 3rd party security software on this machine that would be impacting this.

Reboots do not resolve.

3.5.x and 4.1.x are not affected.

### Steps to reproduce

Attempt to open Godot v4.2 on Windows (either standard or .NET build)

In the screenshot, the multiple instances are multiple attempts to open.

![Screenshot 2023-12-01 082054](https://github.com/godotengine/godot/assets/5872162/b60d77a6-a218-4d00-b3d7-08ca4f7555ae)

### Minimal reproduction project

Cannot even get to the project selection window.

**Comment by akien-mga** [comment]
Are you using godot-jolt by any chance? If so there's a known issue with its older versions making Godot 4.2 crash.

You should delete the version you have, and install the latest 0.10.0 which seems to work with Godot 4.2.

**Comment by aggiechris** [comment]
I am not using godot-jolt (or any other extensions).

**Comment by aggiechris** [comment]
Running `Godot_v4.2-stable_win64.exe --rendering-driver opengl3` does not resolve. Same behavior.

**Comment by Brixenaut** [comment]
![image](https://github.com/godotengine/godot/assets/152750461/2abd9465-80af-453d-b9c0-129a1a35ba0d)

Having the same issue and adding for attention to it. There is also the folder on the bottom left as shown in the image flickering for some reason, not sure if related but when I move the mouse around the screen it flickers quickly while I can only interact with the top window bar.

**System Info:**
_Windows 10 Home, Intel Core i9-9990K, NVIDIA GeForce RTX 2070 (non-super)/64GbRam 2TB SSD

**Comment by Brixenaut** [comment]
> Running `Godot_v4.2-stable_win64.exe --rendering-driver opengl3` does not resolve. Same behavior.

**Do you happen to have an FPS display or overlay, or some sort of window status that shows the apps fps? I had one and turned it off, which seemed to have helped so far. This is not a solution, as I am still testing it out!**

I am new to the project space for Godot, so I am learning with ya on how to help here.

Something I have tried is running as an admin, and also examining the task manager performance window as I move around the window to see what causes the heavy freezing and spikes in resource consumption.

**Comment by aggiechris** [comment]
@Brixenaut I’m not sure you and I are having the same problem

I can’t even get a window to open at all (the project selector or the editor)

I do not have any sort of FPS overlay

**Comment by bk4928412** [comment]
same issue here. i've been trying to figure out what is happening but no luck yet. older builds are still working without any issues. i even cleared everything about the engine including registry keys.

**Comment by saierXP** [comment]
@bk4928412 Can you find out which 4.2 development version introduced the regression? Previous development versions can be downloaded from [here](https://godotengine.org/download/archive/), thank you.

**Comment by bk4928412** [comment]
> @bk4928412 Can you find out which 4.2 development version introduced the regression? Previous development versions can be downloaded from [here](https://godotengine.org/download/archive/), thank you.

hey, its 4.2 dev3 build. the 4.2-dev2 and below that version works fine

**Comment by frnkre** [comment]
I have also a Windows 10 machine (Windows 10 Pro, 22H2, Build 19045.3803) where Godot 4.2 don't start, but simply stopped without error or notification.

I can confirm that 4.2-dev2 works fine, 4.2-dev3 and following refuse to start.

As a workaround, if commenting out the execution of `GetSystemFontCollection` and `GetSystemFontFallback` during initialization Godot 4.2 starts, but (without surprise) the handling of system fonts is messed up

https://github.com/godotengine/godot/blob/2d0ee20ff30461b6b10f6fdfba87511a0ebc6642/platform/windows/os_windows.cpp#L207-L224

**Comment by borjafac** [comment]
Exactly the same behavior for me, any fixes yet? It is my first time trying to open Godot and this happens, what a nice first impression xD.

**Comment by bk4928412** [comment]
> Exactly the same behavior for me, any fixes yet? It is my first time trying to open Godot and this happens, what a nice first impression xD.

you can use the latest build we mentioned above.

**Comment by frnkre** [comment]
It seems as if the issue begins with commit https://github.com/godotengine/godot/pull/79693

If the `COINIT_APARTMENTTHREADED` in line 1717 is reverted back to the former `COINIT_MULTITHREADED`, the editor starts as expected

https://github.com/godotengine/godot/blob/048a16408383a9f8dcf2b53299cfe10d8182cb8f/platform/windows/os_windows.cpp#L1714-L1717

**Comment by saierXP** [comment]
Is it possible to start it using the `godot.exe --single-window` command line, or just open the editor `godot.exe --single-window -e --path project-path `.

Failure to launch the editor should be fixed first, and the previous "COINIT_MULTITHREADED "mode was also used to fix the inability to launch the editor.
Modified to `COINIT_APARTMENTTHREADED` mode due to a problem with the palm input method application not working (unpopular Chinese input method).

IMO, we can change back to `COINIT_MULTITHREADED `and reopen the original Chinese input method not working problem, what's your opinion? @bruvzg

**Comment by bruvzg** [comment]
> MO, we can change back to COINIT_MULTITHREADED and reopen the original Chinese input method not working problem, what's your opinion?

IIRC, it was breaking more than just input. Also, previous fix was not changing to `COINIT_MULTITHREADED`, but removing excessive calls.

**Comment by aggiechris** [comment]
> Is it possible to start it using the godot.exe --single-window command line, or just open the editor godot.exe --single-window -e --path project-path .

This doesn't seem to help anything.

**Comment by saierXP** [comment]
https://github.com/godotengine/godot/issues/18320#issuecomment-1702831672
Will changing the anti-aliasing in the Nvidia control Panel to app control solve the problem? @aggiechris 
Four months ago I had a friend come across godot running in the background invisible but with sound and input. Found that changing the anti-aliasing Settings to be controlled by the application itself solved the problem.

**Comment by aggiechris** [comment]
> Can the methods mentioned here solve the problem? [#18320 (comment)](https://github.com/godotengine/godot/issues/18320#issuecomment-1702831672) Will changing the anti-aliasing in the Nvidia control Panel to app control solve the problem? @aggiechris Four months ago I had a friend come across godot running in the background invisible but with sound and input. Found that changing the anti-aliasing Settings to be controlled by the application itself solved the problem.

@saierXP I already had mine set to application-controlled, so no - it doesn't seem to resolve the issue.

**Comment by lukenothing** [comment]
I got same problem. And I have almost same configurations about the OS, GTX1060 as [aggiechris](https://github.com/aggiechris)'

Win10 22H2, 19045,.4170, GTX1060 driver 551.86, Intel HD Graphics 630

4.2.1 Can not be launched.

3.5.3, 4.1.3 are OK.

**Comment by bk4928412** [comment]
> Can the methods mentioned here solve the problem? [#18320 (comment)](https://github.com/godotengine/godot/issues/18320#issuecomment-1702831672) Will changing the anti-aliasing in the Nvidia control Panel to app control solve the problem? @aggiechris Four months ago I had a friend come across godot running in the background invisible but with sound and input. Found that changing the anti-aliasing Settings to be controlled by the application itself solved the problem.

interesting but it didnt help. also the problem continues on build 4.3dev5.

**Comment by saierXP** [comment]
> Win10 22H2, 19045,.4170, GTX1060 driver 551.86, Intel HD Graphics 630

@lukenothing Have you tried to update Intel's latest graphics driver from the [official website](https://www.intel.com/content/www/us/en/support/detect.html)?

**Comment by lukenothing** [comment]
> > Win10 22H2, 19045,.4170, GTX1060 driver 551.86, Intel HD Graphics 630
> 
> @lukenothing Have you tried to update Intel's latest graphics driver from the [official website](https://www.intel.com/content/www/us/en/support/detect.html)?

Hello, I just upgraded intel hd 630 driver from 31.0.101.2114 to the latest one 31.0.101.2127. Nothing changed.

And because of using external screen as main screen for my laptop which is connected with HDMI port managed by the GTX1060, I disconnected the hdmi line, only using laptop's screen, then tried to lanunch the godot 4.2.1 but got the same result.

**Comment by syshcndr** [comment]
Tried multiple but these only workedfor me Godot_v4.2-dev2_win64, Godot_v4.0-beta7_win64

**Comment by bk4928412** [comment]
it seems like this issue also affects games made with 4.2 dev3 and later.

need someone to confirm.

**Comment by Dark-Occultist** [comment]
Was having this same issue, found a solution that worked for me over on the Godot forums
https://forum.godotengine.org/t/godot-wont-launch-or-open-but-its-running-in-task-manager-fix/47502/2
Check to see if you are running Nahemic Audio Driver, if so exit out and see if that works

**Comment by bk4928412** [comment]
> Was having this same issue, found a solution that worked for me over on the Godot forums https://forum.godotengine.org/t/godot-wont-launch-or-open-but-its-running-in-task-manager-fix/47502/2 Check to see if you are running Nahemic Audio Driver, if so exit out and see if that works

can confirm it works

**Comment by frnkre** [comment]
> Was having this same issue, found a solution that worked for me over on the Godot forums https://forum.godotengine.org/t/godot-wont-launch-or-open-but-its-running-in-task-manager-fix/47502/2 Check to see if you are running Nahemic Audio Driver, if so exit out and see if that works

I too can confirm that this works. As soon as the Nahemic Audio Driver is stopped, the editor starts as expected.

Many thanks for the hint!

**Comment by aggiechris** [comment]
> Was having this same issue, found a solution that worked for me over on the Godot forums https://forum.godotengine.org/t/godot-wont-launch-or-open-but-its-running-in-task-manager-fix/47502/2 Check to see if you are running Nahemic Audio Driver, if so exit out and see if that works

Yep, works for me too

**Comment by lukenothing** [comment]
> Was having this same issue, found a solution that worked for me over on the Godot forums https://forum.godotengine.org/t/godot-wont-launch-or-open-but-its-running-in-task-manager-fix/47502/2 Check to see if you are running Nahemic Audio Driver, if so exit out and see if that works

Woo~~~, It's OK for me too.

**Comment by akien-mga** [comment]
Related to #13208.
