### ISSUE TITLE
Godot 4.2 C# generate and attach Debug Symbols Always in AOT compilation (with all debugging options disabled)

### ISSUE THREAD

**Issue by joined72** [godotengine/godot#85612]
### Godot version

4.2-stable-mono

### System information

Ubuntu 22.04

### Issue description

Creating a simple empty Godot 4.2 C# project and disabling ALL Debug Options, in the final binary folder created together to the executable file you will find a debug symbols file. If you will use to Pack all into a single file, these Debug Symbols File will increase the final file size!

This is a screenshot...

![Screenshot](https://github.com/godotengine/godot/assets/19651914/7d19ccf0-d92a-49ae-955e-082a7b52f7db)

and this is the MSBuild log...

```sh
Running:  /usr/bin/dotnet publish /home/fabio/Test/Test.csproj -c ExportRelease -r linux-x64 --self-contained true -v normal -l:GodotTools.BuildLogger.GodotBuildLogger,/home/fabio/Desktop/Godot_v4.2-stable_mono_linux_x86_64/GodotSharp/Tools/GodotTools.BuildLogger.dll;/home/fabio/.local/share/godot/mono/build_logs/beed5fedac353dfc7d858b70d70cb119_ExportRelease -p:DebugType=None -p:DebugSymbols=false -p:GodotTargetPlatform=linuxbsd -o /tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64
MSBuild version 17.4.8+6918b863a for .NET
Build started 12/1/2023 5:05:27 PM.
Project "/home/fabio/Test/Test.csproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/7.0.114/trustedroots/codesignctl.pem'.
  X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/7.0.114/trustedroots/timestampctl.pem'.
  Restoring packages for /home/fabio/Test/Test.csproj...
  Writing assets file to disk. Path: /home/fabio/Test/.godot/mono/temp/obj/project.assets.json
  Restored /home/fabio/Test/Test.csproj (in 448 ms).
  
  NuGet Config files used:
      /home/fabio/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
Done Building Project "/home/fabio/Test/Test.csproj" (Restore target(s)).
Project "/home/fabio/Test/Test.csproj" on node 1 (Publish target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreGenerateAssemblyInfo:
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
  /usr/lib/dotnet/dotnet exec "/usr/lib/dotnet/sdk/7.0.114/Roslyn/bincore/csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,IL2121,1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:7 /define:GODOT;GODOT_LINUXBSD;GODOT_PC;GODOT4;GODOT4_2;GODOT4_2_0;GODOT4_OR_GREATER;GODOT4_0_OR_GREATER;GODOT4_1_OR_GREATER;GODOT4_2_OR_GREATER;GODOT4_2_0_OR_GREATER;TRACE;EXPORTRELEASE;NET;NET7_0;NETCOREAPP;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NET7_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER /preferreduilang:en /highentropyva+ /reference:/home/fabio/.nuget/packages/godotsharp/4.2.0/lib/net6.0/GodotSharp.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/Microsoft.CSharp.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/Microsoft.VisualBasic.Core.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/Microsoft.VisualBasic.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/Microsoft.Win32.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/Microsoft.Win32.Registry.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/mscorlib.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/netstandard.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.AppContext.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Buffers.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Collections.Concurrent.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Collections.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Collections.Immutable.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Collections.NonGeneric.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Collections.Specialized.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.Annotations.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.DataAnnotations.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.EventBasedAsync.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ComponentModel.TypeConverter.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Configuration.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Console.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Core.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Data.Common.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Data.DataSetExtensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Data.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.Contracts.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.Debug.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.DiagnosticSource.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.FileVersionInfo.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.Process.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.StackTrace.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.TextWriterTraceListener.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.Tools.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.TraceSource.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Diagnostics.Tracing.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Drawing.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Drawing.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Dynamic.Runtime.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Formats.Asn1.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Formats.Tar.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Globalization.Calendars.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Globalization.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Globalization.Extensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Compression.Brotli.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Compression.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Compression.FileSystem.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Compression.ZipFile.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.FileSystem.AccessControl.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.FileSystem.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.FileSystem.DriveInfo.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.FileSystem.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.FileSystem.Watcher.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.IsolatedStorage.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.MemoryMappedFiles.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Pipes.AccessControl.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.Pipes.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.IO.UnmanagedMemoryStream.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Linq.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Linq.Expressions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Linq.Parallel.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Linq.Queryable.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Memory.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Http.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Http.Json.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.HttpListener.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Mail.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.NameResolution.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.NetworkInformation.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Ping.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Quic.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Requests.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Security.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.ServicePoint.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.Sockets.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.WebClient.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.WebHeaderCollection.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.WebProxy.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.WebSockets.Client.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Net.WebSockets.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Numerics.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Numerics.Vectors.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ObjectModel.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.DispatchProxy.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Emit.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Emit.ILGeneration.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Emit.Lightweight.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Extensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Metadata.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Reflection.TypeExtensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Resources.Reader.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Resources.ResourceManager.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Resources.Writer.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.CompilerServices.Unsafe.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.CompilerServices.VisualC.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Extensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Handles.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.InteropServices.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.InteropServices.JavaScript.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.InteropServices.RuntimeInformation.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Intrinsics.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Loader.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Numerics.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Serialization.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Serialization.Formatters.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Serialization.Json.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Serialization.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Runtime.Serialization.Xml.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.AccessControl.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Claims.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.Algorithms.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.Cng.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.Csp.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.Encoding.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.OpenSsl.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.Primitives.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Cryptography.X509Certificates.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Principal.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.Principal.Windows.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Security.SecureString.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ServiceModel.Web.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ServiceProcess.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.Encoding.CodePages.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.Encoding.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.Encoding.Extensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.Encodings.Web.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.Json.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Text.RegularExpressions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Channels.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Overlapped.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Tasks.Dataflow.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Tasks.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Tasks.Extensions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Tasks.Parallel.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Thread.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.ThreadPool.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Threading.Timer.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Transactions.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Transactions.Local.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.ValueTuple.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Web.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Web.HttpUtility.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Windows.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.Linq.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.ReaderWriter.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.Serialization.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.XDocument.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.XmlDocument.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.XmlSerializer.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.XPath.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/System.Xml.XPath.XDocument.dll /reference:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/ref/net7.0/WindowsBase.dll /debug- /filealign:512 /optimize+ /out:/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/Test.dll /refout:/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/refint/Test.dll /target:library /warnaserror- /utf8output /deterministic+ /langversion:11.0 /analyzerconfig:/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/Test.GeneratedMSBuildEditorConfig.editorconfig /analyzerconfig:/usr/lib/dotnet/sdk/7.0.114/Sdks/Microsoft.NET.Sdk/analyzers/build/config/analysislevel_7_default.editorconfig /analyzer:/usr/lib/dotnet/sdk/7.0.114/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll /analyzer:/usr/lib/dotnet/sdk/7.0.114/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll /analyzer:/usr/lib/dotnet/sdk/7.0.114/Sdks/Microsoft.NET.Sdk/targets/../analyzers/ILLink.CodeFixProvider.dll /analyzer:/usr/lib/dotnet/sdk/7.0.114/Sdks/Microsoft.NET.Sdk/targets/../analyzers/ILLink.RoslynAnalyzer.dll /analyzer:/home/fabio/.nuget/packages/godot.sourcegenerators/4.2.0/analyzers/dotnet/cs/Godot.SourceGenerators.dll /analyzer:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll /analyzer:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll /analyzer:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll /analyzer:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll /analyzer:/usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.14/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll Main.cs "/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" /home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/Test.AssemblyInfo.cs /warnaserror+:NU1605,SYSLIB0011
  CompilerServer: server - server processed compilation - 0bd59ed5-5fc6-4349-951a-a551fb00f4be
CopyFilesToOutputDirectory:
  Copying file from "/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/Test.dll" to "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/Test.dll".
  Test -> /home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/Test.dll
SetupOSSpecificProps:
  command -v "clang"
  command -v "llvm-objcopy"
  command -v "objcopy"
IlcCompile:
  Generating native code
  "/home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/tools/ilc" @"/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/native/Test.ilc.rsp"
/home/fabio/.nuget/packages/godotsharp/4.2.0/lib/net6.0/GodotSharp.dll : warning IL2104: Assembly 'GodotSharp' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/fabio/Test/Test.csproj]
/home/fabio/.nuget/packages/godotsharp/4.2.0/lib/net6.0/GodotSharp.dll : warning IL3053: Assembly 'GodotSharp' produced AOT analysis warnings. [/home/fabio/Test/Test.csproj]
LinkNative:
  "clang" "/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/native/Test.o" -o "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so" -Wl,--version-script=/home/fabio/Test/.godot/mono/temp/obj/ExportRelease/linux-x64/native/Test.exports /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/sdk/libbootstrapperdll.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/sdk/libRuntime.WorkstationGC.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/framework/libSystem.Native.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/framework/libSystem.Globalization.Native.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/framework/libSystem.IO.Compression.Native.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/framework/libSystem.Net.Security.Native.a /home/fabio/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.14/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -Wl,--strip-debug -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -Wl,-e0x0 -pthread -lstdc++ -ldl -lm -lz -lrt -shared -Wl,-z,relro -Wl,-z,now -Wl,--require-defined,NativeAOT_StaticInitialization -Wl,--discard-all -Wl,--gc-sections
  chmod 644 "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so"
  
          "llvm-objcopy" --only-keep-debug "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so" "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so.dbg" &&
          "llvm-objcopy" --strip-debug --strip-unneeded "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so" &&
          "llvm-objcopy" --add-gnu-debuglink="/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so.dbg" "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so"
_CopyResolvedFilesToPublishPreserveNewest:
  Copying file from "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so" to "/tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64/Test.so".
Publish:
  Test -> /tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64/
CopyNativeBinary:
  Deleting file "/tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64//Test.so".
  Copying file from "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so" to "/tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64/Test.so".
  Copying file from "/home/fabio/Test/.godot/mono/temp/bin/ExportRelease/linux-x64/native/Test.so.dbg" to "/tmp/godot-publish-dotnet/4299-ExportRelease-linux-x64/Test.so.dbg".
Done Building Project "/home/fabio/Test/Test.csproj" (Publish target(s)).

Build succeeded.

"/home/fabio/Test/Test.csproj" (Publish target) (1:7) ->
(IlcCompile target) -> 
  /home/fabio/.nuget/packages/godotsharp/4.2.0/lib/net6.0/GodotSharp.dll : warning IL2104: Assembly 'GodotSharp' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/fabio/Test/Test.csproj]
  /home/fabio/.nuget/packages/godotsharp/4.2.0/lib/net6.0/GodotSharp.dll : warning IL3053: Assembly 'GodotSharp' produced AOT analysis warnings. [/home/fabio/Test/Test.csproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:01:07.19
```

### Steps to reproduce

In a simple empty Godot 4.2 C# project, activating the AOT build with the following .csproj file:

```xml
<Project Sdk="Godot.NET.Sdk/4.2.0">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <!-- Use NativeAOT. -->
    <PublishAOT>true</PublishAOT>
  </PropertyGroup>
  <ItemGroup>
    <!-- Root the assemblies to avoid trimming. -->
    <TrimmerRootAssembly Include="GodotSharp" />
    <TrimmerRootAssembly Include="$(TargetName)" />
  </ItemGroup>
</Project>
```
PS: I used the .NET 7.0 but the problem is presents with .NET 8 too
 
DISACTIVATE the following Options:

1. "Project/Export/Options/Dotnet/Include Debug Symbols"
2. "Project/Export/Export Project/Export with Debug"

Export the project and in the output binary folder created together to the executable file you will find a binary lib **_and its debug symbols file!!!_** 

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/13528375/Test.zip)

**Comment by joined72** [comment]
I found a viable workaround adding the following lines to the .csproj file:

```xml
  <Target Name="DeleteDebugSymbols" BeforeTargets="CopyNativeBinary" Condition="$(Configuration.Contains('Release'))">
    <ItemGroup>
      <DebugSymbols Include="**\*.dbg;**\*.pdb;**\*.dSYM"/>
    </ItemGroup>
    <Delete Files="@(DebugSymbols)" />
  </Target>
```

These lines delete all generated Debug Symbols Files (Linux, Windows, MacOSX, Androind, iOS) but only in the Release configuration.

**Comment by raulsntos** [comment]
When exporting a .NET project we add the following properties if debug symbols are not enabled:
- `/p:DebugSymbols=false`
- `/p:DebugType=None`

This should be enough to avoid generating the debug symbols file (`.dbg`). However, it seems there was a bug upstream:
- https://github.com/dotnet/runtime/issues/88780
- https://github.com/dotnet/sdk/issues/34959

It should have been fixed in .NET 8 so try using a newer SDK and target `net8.0`.

**Comment by foxwr** [comment]
The problem still persists even with the latest release of dotnet (8.0.401) which dates to 15-aug-2024, while targeting net8.0

**Comment by raulsntos** [comment]
@foxwr We don't do anything special when compiling so if it works for a dotnet console application, it should work the same way for a godot project. You can try enabling `Create Binary Log` in `Editor Settings > Dotnet`, and then check the values of those properties in the binary log.
