### ISSUE TITLE
Remote debugger fails on MacOS with status code 2

### ISSUE THREAD

**Issue by zanew** [godotengine/godot#8563]
**Operating system or device - Godot version:**
v2.1.3 stable official 15" MBP retina gen 2 OS X El Cap 10.11.6

**Issue description:**

Ran a scene. Expected the scene to build and run. Didn't. Got error in the debugger with text Remote debugger: connection failed with status code 2" retrying in 1 sec.

**Steps to reproduce:**
Follow steps of hello world tutorial.

**Link to minimal example project:**

**Comment by volzhs** [comment]
what value do you have at Settings > Network > Debug Host?

**Comment by zanew** [comment]
6c6f:3000:0:0:0:0:0:0

**Comment by tooldoctor** [comment]
I was doing a tutorial from http://codetuto.com/tag/godot/ and it was working fine until I added the first script, then the same problem occurred on my Retina Mac Book Pro 15 running  OSX El Capitan 10.11.16.  

I was able to fix it by editing the engine.cfg file and added:

[debug]

debug_port=3000

After doing that, I was able to see the debug_port property in the Project Settings UI for section Debug.  (screenshot was edited to show only relevant information)
![image](https://user-images.githubusercontent.com/4412511/27521328-6b89241a-59d0-11e7-99d1-03b7c86432cc.png)

I had the same problem on a Mac Book Pro 13 running Sierra.  Interesting, I saw the debug_port property in the settings and was able to change it on the UI directly.  Perhaps it's a different version of Godot that has the fix mentioned above.  The About screen says it's the same Godot Engine v2.1.3.stable.official

**Comment by akien-mga** [comment]
@Faless, any idea? I think we might have messed things up with a cherry-pick of your master edits, looks like `debug/debug_port` is not being defined as it's expected to be.

**Comment by Zireael07** [comment]
I'll chime in to say it's not specific to MacOS, see #8744 (and the fact that debugger errors can prevent you from running a project AT ALL is a major annoyance when it does, intermittently, happen)

**Comment by Faless** [comment]
This seems to only apply to 2.1 branch can someone confirm that? @akien-mga @Zireael07 @zanew 

I think we should just get rid of the debug_port as a project variable and use it as an editor variable like we do for the debug_host. Seeing it there is too misleading. They can be passed as command line options anyway for builds without the editor.

I'll have some time to investigate the issue further next week, I've been quite busy with work lately.

**Comment by pakchano** [comment]
Actually @akien-mga, @Faless this bug is not present in the **beta v2.1.4** under the same specifications mentioned in my issue #9635 
![screenshot1](https://user-images.githubusercontent.com/9617583/28252874-42e46f4c-6a6a-11e7-9d2f-f623eaec37ae.jpg)

Hope this alleviates some of that heavy lifting.
Saluti,

**Comment by Faless** [comment]
@zanew @Zireael07 can somebody with a Mac check if this issue happens on the current `2.1` branch?

**Comment by Zireael07** [comment]
@Faless I don't have a Mac, I'm on Windows, and the issue seems to have disappeared for me (the debugger connects nicely)

**Comment by Faless** [comment]
> I don't have a Mac, I'm on Windows

Right, my bad.

> and the issue seems to have disappeared for me

@Zireael07  can you close #8744 then?

**Comment by Faless** [comment]
@bojidar-bg since you are in this discussion, I think this can be closed alongside #9635 which was reported as fixed by original author. This appears to be the same problem. Current `2.1` branch should be unaffected, like `2.1.4` beta.

**Comment by pakchano** [comment]
Yes @Faless, the beta does input the Debugger and prints correctly.

**Comment by vnen** [comment]
Closing as fixed then.

**Comment by retendo** [comment]
Mac user here. I still get the error in stable version 2.1.4

For me it is easily reproducible by just
- creating a new project
- adding a root node2d
- save scene and set it as main scene
- run
-> Error: Remote debugger: connection failed with status code 2

**Comment by Faless** [comment]
@retendo can you check what is the value you see in `Settings -> Editor Settings -> Network -> Debug Host`, and `Settings -> Editor Settings -> Network -> Debug Port` and report them here?

> This is a bit weird as per documentation:
> STATUS_CONNECTED = 2 — A status representing a StreamPeerTCP that is connected to a host.
> 
> And I get Connection failed with status: 2

Weird indeed... Do you get `status: 2` three times or only the last one? What are the previous messages?
It might be that it connected (`status: 2`) only during the delay of the last try. In that case we might just raise the number of tries.

**Comment by chenzhekl** [comment]
We still observed the message `Connection failed with status: 2` on 2.1.4 on macOS. The debug port was 6096, and the message just appeared once. After that, the debugger seemed to work fine...

**Comment by aragalie** [comment]
Guys, i'm still getting this issue (2.1.4) on macOS (HighSierra 10.13.2). It's the first time i'm using Godot btw......not sure if it matters now anyways with 3.0 coming out in a few days, but just wanted to let you know this is still an issue.

**Comment by Faless** [comment]
@aragalie the proper fix for this issue was merged on September 19th, Godot `2.1.4` was released in August. Either compile latest `2.1` branch from source or set `Settings -> Editor Settings -> Network -> Debug Host` to `127.0.0.1`

**Comment by clayheaton** [comment]
@Faless I just downloaded 3.0.2.stable.official on High Sierra and I get this same error while trying to follow the [official Godot tutorial](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html). Changing the debug host and/or port do not alleviate the problem. The window does not appear anywhere for me.

```
** Debug Process Started **
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: AMD Radeon Pro 460 OpenGL Engine
** Debug Process Stopped **
```

**Comment by samgreen** [comment]
I think the issue might be here:

https://github.com/godotengine/godot/blob/18c28c159d12c9d3227c2199998b271f7c5e5998/main/main.cpp#L637

Can you post your editor log when you play a scene? I show something like this on Windows 10:

```
Running: Godot_v3.0.2-stable_win64.exe --path Documents/Godot/hello_world --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 13796 --position 768,240
running cmdline: "Godot_v3.0.2-stable_win64.exe" "--path" Documents/Godot/hello_world" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "13796" "--position" "768,240"
```

Can test OS X tomorrow.

**Comment by clayheaton** [comment]
@samgreen The only thing that appears in the editor Output is what I included in the post above.

**Comment by jtuttle** [comment]
@samgreen I'm also experiencing this problem with 3.0.3 on OSX 10.12.5. My output window shows the same as @clayheaton 's:

```
** Debug Process Started **
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: Intel Iris Pro OpenGL Engine
** Debug Process Stopped **
```

**Comment by clayheaton** [comment]
@Faless @vnen This issue needs to be reopened.

**Comment by Faless** [comment]
> I'm also experiencing this problem with 3.0.3

Was it also present in 3.0.2?

**Comment by clayheaton** [comment]
@Faless 

A few things -- I compiled from the branch you linked but I'm getting a permissions-related crash when I try to create a new project. The system never asks me if the app can have permission to run. How do I get around that?

Back to the topic of this issue:

At home, when I've encountered this problem, I have 1 external monitor. The arrangement is the MBP laptop on the left and the external monitor on the right.

Right now, I'm at work, where i have 2 external monitors chained to a MBP. The arrangement is:

![screen shot 2018-06-21 at 9 17 10 am](https://user-images.githubusercontent.com/205364/41721452-e90dd8fc-7533-11e8-8036-921b0c6e72e3.png)

When I download 3.0.3 and run a simple test, with Godot in the center monitor in the image above (create a new project, create & save a scene, click Play Scene), the play window appears at the bottom left corner, mostly off-screen, on the right-most monitor. 

Is it possible that Godot is trying to open the play scene on a monitor to the right that doesn't exist? (which would make sense for why it works on my setup at my office where I have an additional monitor to the right).

**Comment by clayheaton** [comment]
Followup... with Default Editor settings under Run, the play window appears here when it should appear in the center:

![screen shot 2018-08-08 at 3 29 21 pm 3](https://user-images.githubusercontent.com/205364/43860220-065b954e-9b21-11e8-9b2e-e1656bb034cd.png)

If I change the setting to Top Left

![screen shot 2018-08-08 at 3 38 24 pm](https://user-images.githubusercontent.com/205364/43860258-1f8afbae-9b21-11e8-9f6d-c2ec624b2b5c.png)

then it appears almost in the center of the screen:

![screen shot 2018-08-08 at 3 38 59 pm 3](https://user-images.githubusercontent.com/205364/43860278-31e86d18-9b21-11e8-91c0-6a85670c0aeb.png)

**Comment by AdamantGaming** [comment]
@Faless I am also experiencing this problem on 3.0.6 from a MacBook Pro.  No external displays connected currently, but I used to use 3 monitors.  I tried changing the debug_host, debug_port to no avail.  I also tried enabling and disabling the "Deploy With Remote Debugger" option, and every combination of options listed, and all had the same result:

`** Debug Process Started **
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine
** Debug Process Stopped **`

Any troubleshooting I can do to help figure this out?  I am planning to start getting heavily invested in this version of Godot, and myself and my team almost exclusively work from Macbook Pros.

**Comment by reduz** [comment]
It seems odd that the debugger connection fails, maybe a way to check if the port is in use? though if this is the case, I think Godot tries to open another port..

**Comment by Faless** [comment]
@AdamantGaming as mentioned in above comments, your issue (and this GH issue in general) is likely unrelated to any network code.
As the log says, the debugger fails, retry, and then succeed when retrying after 1 ms (and in fact, you get the first line of the log: ` OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine`).
Your problem is somewhere else.
I'm thinking about remove that debug line ` Remote Debugger: Connection failed with status: '2', retrying in 1 msec.` as it seems no one understands it, and is always misinterpreted as a network error (like in this case, where it's not).

**Comment by AdamantGaming** [comment]
@Faless - Yeah I completely misunderstood that.  My bad.

Rather than removing the initial message, maybe a more clearly defined success message would be beneficial?  Such as a line between the connection failed message, and the first line of the log that says "Retry Successful - now displaying debug log."?

**Comment by Faless** [comment]
> Such as a line between the connection failed message, and the first line of the log that says "Retry Successful - now displaying debug log."?

Yes, good idea! :+1:
