### ISSUE TITLE
PS4/Dual Shock 4 controller analogue input causes actions to ignore other connected controllers' analogue input events

### ISSUE THREAD

**Issue by SophieH** [godotengine/godot#86272]
### Tested versions

Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Dual Shock 4 (PS4 controller) + other controllers (I used xbox, PS5, etc). Copied info: Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 Threads)

### Issue description

With multiple controllers connected, if one is a PS4/DS4 controller, other controllers' analogue inputs for an action shared by the PS4/DS4 will often be ignored when getting the action strength.

Getting the action strength seems to behave correctly exactly when a controller changes its axis value, but the action strength quickly zeroes again, presumably related to how 'flickery' the raw DS4 analogue input is.

To be clear:
- digital (non-analogue) inputs are not interrupted
- playing with a controller is fine if the DS4 is not connected
- playing with a DS4 is fine even if other controllers are connected
- using Input.get_joy_axis() behaves as expected even when the DS4 is interfering with action strength

I assume this is related to a previous bug where the PS4 controller would make keyboard input actions cut out despite being stronger. It may have existed then too and just not been noticed.

sorry if this report isn't the best, I'm not used to doing this! I'll help more if I can.

### Steps to reproduce

Attach my code to a label, have a "Left" action in the InputMap with an event listening for analogue stick left.
You'll need the PS4/DS4 controller and at least one other kind of controller, both connected.

You'll notice the "Input Action" will frequently go to 0 when using a non-DS4 controller while the DS4 is connected, and works fine if the DS4 is unplugged. The DS4 itself seems to work fine.
As you can see from the get_joy_axis() values, all controllers are reporting their values correctly, the issue is with the action strength.

### Minimal reproduction project (MRP)

```
extends Label

func _process(delta):
	var actionName = "Left"
	# cuts to 0 sometimes if a DS4 is connected:
	text = "Input Action:" + str(Input.get_action_strength(actionName)) 

	# inputs from specific gamepads still report correctly
	var events:Array[InputEvent] = InputMap.action_get_events(actionName)
	var analogueInput:InputEventJoypadMotion
	for e in events:
		if e is InputEventJoypadMotion:
			analogueInput = e

	for j in Input.get_connected_joypads():
		text += "\n" + Input.get_joy_name(j) + str(Input.get_joy_axis(j, analogueInput.axis))
```

**Comment by Calinou** [comment]
> I assume this is related to a previous bug where the PS4 controller would make keyboard input actions cut out despite being stronger. It may have existed then too and just not been noticed.

https://github.com/godotengine/godot/issues/45628 should definitely have been fixed since 4.2.

**Comment by slumberface** [comment]
I think this is the same issue I detailed on #45628. in 4.2.1, if build is started with dual sense plugged in it will add tiny incorrect values to digital keyboard inputs. Instead of 0 you will get stuff like -.01545. Still bugged.

Steps to reproduce plug in a dual sense, start build, print keyboard values on input

**Comment by Calinou** [comment]
@slumberface Can you test this project? https://github.com/godotengine/godot/files/12480268/test_analog_and_digital_input_2.zip

**Comment by slumberface** [comment]
@Calinou if these readouts are correct, than that project is working correctly for keyboard. I can start that build with either a current-gen xbox controller connected, or a ps5 controller, and still get 0% read outs on keyboard when no input is being pressed. Although I sporadically have seen small default values on both of the game pad inputs. Not sure if this is to be expected given the current test or if this a relevant symptom
![image](https://github.com/godotengine/godot/assets/41273849/3f17c97e-7cf5-4d6d-a71a-fa2a7da53ff9)

**Comment by slumberface** [comment]
@Calinou Hey I just posted a reply that said this fixes it but it doesn't. The test doesn't reveal the conditions that cause this error to surface for me. With this code the bug comes up. If a dual sense is also plugged in, then pressing up on the keyboard (y axis) will also give you small floating point values in the x axis
![image](https://github.com/godotengine/godot/assets/41273849/164ca915-8cc8-4d79-8337-6fac37527a84)
![image](https://github.com/godotengine/godot/assets/41273849/baaa8513-451e-48aa-9bbe-d79d9cf15591)

Maybe this isn't the best way to be polling for input in the first place, but does this illuminate the issue a bit more?

**Comment by slumberface** [comment]
@Calinou replied to other thread. this might be a problem with Input.get_vector specifically (using the 5th parameter doesn't help). Polling this way doesn't run into the same issue:
![image](https://github.com/godotengine/godot/assets/41273849/81534b42-71ee-4ac1-9c80-009d57ee4401)

**Comment by MJacred** [comment]
Related to
* https://github.com/godotengine/godot/issues/105209

**Comment by SophieH** [comment]
@Nintorch It seems to be fixed! I tested with the steps I mentioned above in v4.5.1.stable.official [f62fdbde1]

The DS4 analog inputs still seem to have a very small "flicker" to them, but it doesn't pull from a stronger input on another controller (I tested with a dual sense and an xbox 360 controller). The flicker I assume is just part of how the DS4 works, but it's not noticeable unless you're actually looking a few decimals into the floating point value. If any issue actually remains with how Godot is handling the DS4 input I can't see it right now!

(github related note: I see I have the option to close with this comment, not sure if I'm supposed to do that or leave it to someone on the project? I'll leave it for now but if you do need anything else from me just say!)
