### ISSUE TITLE
tileMap keeps crashing

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#88054]
### Tested versions

4.3 dev2, also used to happen in prev version 4.2, 4.1

### System information

windows 10 vulkan

### Issue description

The engine closes without errors

### Steps to reproduce

doing various diferents this, like
- adding new tile layer
- changing layer color
- copy / paste tiles
- changing something on the right menu like "layer name" or pressing mouse middle button to close the color menu, or move the level with middle mouse.

console: Once it starts to build up crash !!!, I dont have any rects on tiles, just basic drawing.

![tileCrash](https://github.com/godotengine/godot/assets/77213594/c3ff3eef-09be-43e4-95af-db14e2323ee7)

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment]
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/86226

Which has been solved, can you test in [4.2.2.rc1](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-1/) which contains this fix? Or build yourself from source, this is very likely fixed

**Comment by jonSP12** [comment]
Is there some kind of tutorial, on how to compile from source ? Using visual studio code ? I dont think the one writen in the manual works very well

**Comment by jonSP12** [comment]
just a small update when the engine is not responding before crashing... After pressing "enable" on "layer" grass. 
It shows a diferent error

![tileCrash2](https://github.com/godotengine/godot/assets/77213594/5b8e57d7-3749-4ef4-a18f-943a494a354a)

**Comment by jonSP12** [comment]
i had to modified my game and upLoaded. I could not get the error on a new project...
I think the erros are related to this - new tileMap node / quick load / tileDefault.tres... As soon as i did that it crashed right away, but it didnt happen after...


![crashUP](https://github.com/godotengine/godot/assets/77213594/591a21e2-6225-4a7a-beab-0c1d28d12646)

https://drive.google.com/file/d/12hzDILBgN1uTPOvt8kGJSyBvTaaaDpND/view?usp=drive_link

**Comment by AThousandShips** [comment]
I can't access that file, please upload the file directly

**Comment by jonSP12** [comment]
It just crashed right now on level B1 by selecting TileMap node, and adding a new tileMap node on top of that one... either way i have no idea...
![crashksdjhfjksdhfkjd](https://github.com/godotengine/godot/assets/77213594/30fc8d27-8a0d-40c5-b54d-1c4986ce5458)

**Comment by AThousandShips** [comment]
You need to create a smaller project, or upload it in a way that others can access, the way you uploaded required permission to open

**Comment by jonSP12** [comment]
> You need to create a smaller project, or upload it in a way that others can access, the way you uploaded required permission to open

my mistake... i think it should work now...
https://drive.google.com/file/d/12hzDILBgN1uTPOvt8kGJSyBvTaaaDpND/view?usp=sharing

**Comment by AThousandShips** [comment]
That's too big, you need to reduce the size of your project, 150 MB is far too big for a minimal project

So please try to create a project that just contains what's needed to show the bug, not a project of yours, see the instructions above

**Comment by AThousandShips** [comment]
Yes, see the instructions above :) keep that in mind in the future!

**Comment by AThousandShips** [comment]
The instructions are vague so I can't necessarily confirm, but I can't get this to crash, reverted the thread fixes and this now does crash

So this has been fixed in latest and 4.2.2.rc1, please try either 4.2.2.rc1 or wait for 4.3.dev3 to confirm

Closing as resolved as the crash is fixed in my testing :)

**Comment by AThousandShips** [comment]
You can test with the [4.3.dev3](https://github.com/godotengine/godot-builds/releases/tag/4.3-dev3) release to confirm :)

**Comment by jonSP12** [comment]
I think 4.3 dev3 its good, it only showed the error 1 one time. When copying pasteing tiles into the pattern box.
After that it ran normal without the errors pileing up..

![err01](https://github.com/godotengine/godot/assets/77213594/e162d1e3-b6a7-40c3-9574-f45076c8c452)

_________

![err02](https://github.com/godotengine/godot/assets/77213594/9e82a796-c863-4e7a-bd4b-231a1e922d76)

**Comment by jonSP12** [comment]
it seems it still crashes not many times has it was before....
**This time i was able to prevent the engine from haging ( not responding )** by changing the console window size.
the errors showed up in the output after.
![err03](https://github.com/godotengine/godot/assets/77213594/c2fed8f6-3741-4951-93a0-f185dc2f5d98)

**Comment by AThousandShips** [comment]
Please open a separate report with details on how to cause this :)
