### ISSUE TITLE
When there's no audio output device, AudioStreamPlayer `finished` signal isn't emitted

### ISSUE THREAD

**Issue by novalis** [godotengine/godot#88775]
### Tested versions

v4.2.1.stable.official.b09f793f5

### System information

Windows 11 VM from Microsoft, in VirtualBox

### Issue description

I'm running Godot using VirtualBox from a Windows 11 VM guest, Linux host. I haven't got audio set up yet, so there are no audio devices on the guest.  I am playing a sound using:
```
	var player = AudioStreamPlayer.new()
	player.bus = "Foley"
	add_child(player)
	player.stream = load("res://example.mp3")
	player.play()
	await player.finished
```
On my Linux host, it works fine.  On the Windows guest (with no audio device), `finished` is never emitted and the game just hangs in the `await`.  Please insert Samuel Beckett joke here.

If I could detect the no-audio condition, I could avoid waiting on the signal, but I don't see a way to do that.

### Steps to reproduce

I've attached a repro project; it's slightly different in that it doesn't use gdscript to await the signal, but the effect is the same: the `finished` signal is never fired.  

The startup messages:
```
C:\Users\User\Desktop\no-audio>..\Godot_v4.2.1-stable_win64. exe --rendering-driver opengl3

C:\Users\User\Desktop\no-audio>Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org

Mesa: SVGA3D; build: RELEASE;

Mesa: mesa-21.3.8
OpenGL API 4.1 (Core Profile) Mesa mesa-21.3.8 - Compatibility - Using Device: Mesa - SVGA3D; build: RELEASE;
ERROR: Condition "hr != ((HRESULT)0x00000000)" is true. Returning: ERR_CANT_OPEN
   at: audio_device_init (drivers/wasapi/audio_driver_wasapi.cpp:275)
ERROR: WASAPI: init_output_device error
   at: init (drivers/wasapi/audio_driver_wasapi.cpp:562)
```

### Minimal reproduction project (MRP)

[no-audio.zip](https://github.com/godotengine/godot/files/14394118/no-audio.zip)

I'm using the VirtualBox VM from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ on a Linux host.

**Comment by AThousandShips** [comment]
As you can see it shows a clear error that it can't initialize audio, so I think it's expected that audio just doesn't work, I'm not sure how this should be solved or if any audio code should be running in this case

**Comment by novalis** [comment]
Thanks for finding that previous issue.  I just tried 4.3.dev3, but it doesn't work.  I do see " WARNING:All audio drivers failed, falling back to the dummy driver.", so something has changed, but I still don't get the `finished` signal in my test project.  Would you like me to keep this one open, or should we move the discussion to #71640?

**Comment by AThousandShips** [comment]
Let's keep this open and see what else is needed there

**Comment by Calinou** [comment]
`audio_finished` should definitely be emitted if there are no audio devices (or in headless mode), as it's frequently used to impact gameplay (e.g. `queue_free()` an enemy scene once their death sound is done playing).

**Comment by shandralor** [comment]
just confirmed this, through trial and error that every line below the audio_finished is never run if no sound device is attached or found. Is there any type of error handling that could be used to catch this?

**Comment by akien-mga** [comment]
Tested on 4.3-dev5, it seems to work as expected for me when using `--headless` or `--audio-driver Dummy`.

I modified the MRP to autoplay and print the state in the terminal to test:
[no-audio.zip](https://github.com/godotengine/godot/files/14893134/no-audio.zip)

I haven't tried in a Windows VirtualBox VM though, but if the fallback to the Dummy audio driver works correctly, it should work.

Could you test both with the automatic fallback when WASAPI fail (just running Godot normally), and with `--audio-driver Dummy` to see if there's a difference?

**Comment by akien-mga** [comment]
I installed a Windows 11 VM in VirtualBox to test, but I missed that there were custom ones on https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ and I did a plain Windows 11 Pro install from the main install ISO. The VM has working audio, so I can't reproduce the bug either :upside_down_face:

**Comment by akien-mga** [comment]
Fixed by #71640.

**Comment by novalis** [comment]
Confirmed that with or without `--audio-driver Dummy` this works in dev5 on my win11-virtualbox-with-broken-audio.

Thanks for the quick fix!
