### ISSUE TITLE
[4.x] Problem with displaying menu tips (Tooltip)

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#88898]
### Tested versions

Reproducible in all versions starting from 4.0+, the problem is not observed in 3.x+

### System information

Windows 10, Radeon RX 560 Series

### Issue description

When we hover the mouse over the menu, a tooltip window appears; after the cursor leaves the button in the menu, the tooltip does not disappear until we leave the entire open menu area
![223](https://github.com/godotengine/godot/assets/130399274/9eeb7d54-c575-4efe-b321-117f063f974f)

### Steps to reproduce

1. Click on the Debug menu at the top of the screen
2. Point your cursor at any menu where there is a hint, and wait until the hint appears
3. remove the cursor from the menu item

### Minimal reproduction project (MRP)

Not required, too easy to test

**Comment by Maran23** [comment]
Sounds like the problem that is fixed by https://github.com/godotengine/godot/pull/88392

**Comment by kitbdev** [comment]
Looks like a duplicate of https://github.com/godotengine/godot/issues/73926

**Comment by JekSun97** [comment]
> Sounds like the problem that is fixed by #88392

no, in 4.3 dev4 this problem is still present

**Comment by JekSun97** [comment]
@akien-mga I think the topic should be opened, since in 4.3 dev4 this problem is still relevant

**Comment by Maran23** [comment]
> no, in 4.3 dev4 this problem is still present

Because the issue is not fixed yet, the PR is only open, not merged.

**Comment by akien-mga** [comment]
> @akien-mga I think the topic should be opened, since in 4.3 dev4 this problem is still relevant

See:

> Looks like a duplicate of #73926

We close duplicates of the prior issue to keep track of the bug and its resolution in a single place. #73926 is still open, you should subscribe to that issue for updates.
