### ISSUE TITLE
Small but noticable rendering artifacts when using a projector texture with an OmniLight. 

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#89440]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) - Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 Threads)

### Issue description

![projector_bug_1](https://github.com/godotengine/godot/assets/781121/430deecc-2649-4174-a6a9-5db2038ab372)

![projector_bug_2](https://github.com/godotengine/godot/assets/781121/df44e9a2-8aab-48f1-9ba2-e899141705fd)

The same thing happens when I use a pure white texture for the projection.

### Steps to reproduce

I will update this issue with an MRP and reproduction steps later when I get the time for it.

### Minimal reproduction project (MRP)

To be added.

**Comment by Calinou** [comment]
I can confirm this on 4.3.dev 40b4130c9 (Linux, GeForce RTX 4090 with NVIDIA 550.78).

**Comment by clayjohn** [comment]
This looks like a filtering artifact. It can likely be resolved by dilating the image a bit when copying it to the atlas, or we can contract the UVs used for reading from the atlas a little bit

**Comment by EzraT** [comment]
> This looks like a filtering artifact. It can likely be resolved by dilating the image a bit when copying it to the atlas, or we can contract the UVs used for reading from the atlas by 0.5 pixels

I discovered this problem in a project that does not use filtering for decal textures, so that may not be related.

**Comment by EzraT** [comment]
> This looks like a filtering artifact. It can likely be resolved by dilating the image a bit when copying it to the atlas, or we can contract the UVs used for reading from the atlas by 0.5 pixels

Indeed it is, when I set the projector filtering to nearest in the project settings the artifacts dissapear.

**Comment by Calinou** [comment]
I can still reproduce this on 4.5.beta7, as seen in https://github.com/Calinou/godot-animated-omnilight3d. Fixing the issue would make it possible to have the projector GradientTexture be 1 pixel in width, making the texture generation much faster.
