### ISSUE TITLE
FileSystem scrolls when moving a dock tab below it

### ISSUE THREAD

**Issue by Cigam-HFden** [godotengine/godot#93755]
### Tested versions

v4.2.2.stable.official [15073afe3],v4.3.beta2.official [b75f0485b]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.5599) - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 Threads)

### Issue description

When rearranging the dockable tabs, if the filesystem tab is docked above others, then when moving a lower tab the filesystem will scroll down.

### Steps to reproduce

Have FileSystem tab on upper dock.
Any tab on lower dock, below FileSystem.
Then move that lower tab, and the scroll will occur.
Here is a video showing it with the MRP:

https://github.com/godotengine/godot/assets/43964088/a872e809-7a5e-4e64-b4cc-5e328ce20b1e

### Minimal reproduction project (MRP)

MRP from the video example with a folder of 100 empty txt files:
[MRP-filesystem-scroll.zip](https://github.com/user-attachments/files/16041910/MRP-filesystem-scroll.zip)

**Comment by Hilderin** [comment]
I think it's caused by a feature of the tree where the scroll is automatic when the dragged object is "near" the tree.
On my computer the `scroll_border` is 40 pixels:
![image](https://github.com/godotengine/godot/assets/81109165/288c26f1-1900-4266-bc73-b2a284cee5ab)

I'm not sure how or if this should be fixed.

https://github.com/godotengine/godot/assets/81109165/219b4c2d-0b50-4b8b-bca3-11cafcd80126

**Comment by Cigam-HFden** [comment]
@Hilderin I see what you mean. Not sure if there is a way to prevent non-files from causing the scroll, meaning have it only scroll for files, not everything. Or as an easy fix, can make an editor options toggle to turn off drag scroll. So if I am dragging something I can just scroll manually instead.

**Comment by Ayanakoji77** [comment]
Anybody  trying to solve this issue , i think i can have a look on the issue .  @KoBeWi

**Comment by Ayanakoji77** [comment]
https://github.com/user-attachments/assets/dfeb14e4-9940-49bf-9993-55b6117db83d 

https://github.com/user-attachments/assets/a2f91fd3-e8af-4c5e-a3e6-00296a5227f7
Hey as you can see half the issue is solved , if you drag any properties from the insepector , node , scene or other docks to the filesystem dock , there is no scroll. But the last issue remains is that if i take a filesystem file and move in scene mannger  it changes from a file type to a some node , so it is able to influence the scene manager for movement ,  other docks no movement . Final the issue lies that the scene manager dock can accept files and changes the type of drag. @KoBeWi
