### ISSUE TITLE
Tilesets no longer keep its collisions, with either CollisionPolygon2D or CollisionShape2D and character goes right through them

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9409]
**Operating system or device - Godot version:**
Windows 10 64bit Godot 3.0 commit 90592ccf03521cda14ee3a9576b671136da2021d

**Issue description:**
New Tilesets or old Tilesets with collisions defined and re-exported, loose their collisions and KinematicBody2D (character) goes right through, also their collisions are not being drawn

**Steps to reproduce:**
Get a Tileset scene from a couple of days ago that have working collisions or create a new one with a Sprite+StaticBody2D+CollisionPolygon2D, save the scene, export the scene as a Tileset
The collisions dont work anymore and the character can go right through the Tiles

**Comment by rubenjavier** [comment]
@karroffel 
maybe this should go to the 3.0 alpha and not the 3.0 milestone, this damage the usefulness os TileMaps/Tilesets almost completely, right now they are working only as background and every project using them to create a map no longer work

**Comment by rubenjavier** [comment]
@karroffel @bojidar-bg 
maybe this comes from the inclusion of the oneway collision on the TileMap/Tilesets and thatswhy the collisions are not being saved anymore
for each of the tiles this is what is missing:
(in this case is a square block)
```
[sub_resource type="ConvexPolygonShape2D" id=1]

custom_solver_bias = 0.0
points = PoolVector2Array( 32, -32, 32, 32, -32, 32, -32, -32 )
```

**Comment by eon-s** [comment]
I have tried exporting a project based on Kinematic Collision demo from 2.1.3 and didn't had any collision problem.

Just move seems to slide when not sliding but that is another issue.

**Comment by rubenjavier** [comment]
Did you re-exported de Tileset/Tilemap overwriting the old one?
when you re-export is when the .tres file changes to
```
0/shapes = [ {
"one_way": false,
"shape": null,
"shape_offset": Vector2( 0, 0 )
} ]
```
notice the shape = null

on a good export:
```
0/shapes = [ {
"one_way": false,
"shape": SubResource( 1 ),
"shape_offset": Vector2( 32, 32 )
} ]
```
where Subresource(1) has been saved on that same export:
```
[sub_resource type="ConvexPolygonShape2D" id=1]

custom_solver_bias = 0.0
points = PoolVector2Array( 32, -32, 32, 32, -32, 32 )
```

I fixed my .tres file manually and it works, but it was not exporting correctly

**Comment by alexzheng** [comment]
in the exported resource, there is no shapes:
0/shapes = [ null ]

**Comment by bojidar-bg** [comment]
As I mentioned in my PR (#9370), this happened even prior to it, because `sb->shape_owner_get_shape(E->get(), k)` results in a null.

**Comment by eon-s** [comment]
@AlexHolly No, I did't tried to make my own tileset on 3, just used old ones. 
I believe that I've got broken exported tilesets before too, need to test again and with more complex tiles.

**Comment by alexzheng** [comment]
is this bug  really fixed?
I built from the master branch and still have this bug.

**Comment by akien-mga** [comment]
Did you export your TileSet again?

**Comment by alexzheng** [comment]
of course,in the exported resource,the shape is null

**Comment by akien-mga** [comment]
Can you provide a zipped project that reproduces the issue?

**Comment by alexzheng** [comment]
Sorry,forget it.It's fixed.

**Comment by naturally-intelligent** [comment]
This bug still happens for me in 3.0.2 stable.

**Comment by eon-s** [comment]
@naturally-intelligent can you provide an example project to test the problem?

**Comment by MarianoGnu** [comment]
i'm almost sure this is because you are using RigidBody2D instead of StaticBody2D on your scene setup

**Comment by naturally-intelligent** [comment]
MarianoGnu - that is correct!  I don't know how/why I was using the wrong body type.  Solved now, thanks, please re-close the issue.  Glad this is an easy fix!  :)

FYI: use StaticBody2D

**Comment by volzhs** [comment]
so this can be closed again?

**Comment by sturm30** [comment]
on 3.1.1 Linux 64bit I can replicate the bug. 
Editing the tileSet from the inspector, I create a SingleTile and give it a collisionPolygonShape. I save the resource as .tres, and I attach it as a .txt
Nice to have the subResource id=1 defined, and used on the "shape" tile attribute. But why I am not seeing the collisionShape, when placing the tile on scene ?
(Debug->Show collision shape enabled, of course)
[newtile.grass.tilemap.txt](https://github.com/godotengine/godot/files/4217371/newtile.grass.tilemap.txt)

**Comment by eon-s** [comment]
@sturm30 I think thay your problem is different and this was closed like 2 years ago, open a new issue for it and fill the issue template, try to add as much information as you can.

**Comment by sturm30** [comment]
@eon-s I suppose I should try to replicate the issue on the Godot v3.2. Is it correct ?

**Comment by eon-s** [comment]
Yes, I do not know if 3.1 will get a fix for something like this, unless it is a simple cherry pick from latest stable fixes.
