### ISSUE TITLE
"Random" crash when not using compatibility render, with no debug info

### ISSUE THREAD

**Issue by Castro1709** [godotengine/godot#94112]
### Tested versions

This started happening when I first ran official 4.3 beta 1https://github.com/godotengine/godot/commit/a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0, since then it also happens in 4.3 beta 2 and even 4.2.2, mono 4.2.2, I tried 3.0 version and there's no issue. But it didn't happen before I ran beta 1

### System information

Windows 11, CPU/GPU AMD Ryzen 7 5700U

### Issue description

Whenever I create, open or run a project which is not in compatibility render, Godot crashes instantly.
But the crashes are random, meaning that the crash sometimes never happens in a ratio of 10% by some quick tests I made.
There's also no relevant info the the debug console, I had to record a video an screenshot it because the console also closes after the crash with just milliseconds to look at the console.
![image](https://github.com/godotengine/godot/assets/90205381/04f9444b-a6ed-4c11-9df0-e6121a6e9a62)

I also checked for similar crashes like https://github.com/godotengine/godot/issues/93862#issuecomment-2213552932 , https://github.com/godotengine/godot/issues/93410 or https://github.com/godotengine/godot/issues/93939
But the amount of ```[1] error(-1): no debug info in PE/COFF executable``` are different (in this is always 6) or the issue it's related to something inside the project, which is not the case here.

### Steps to reproduce

Unfortunately I'm really not sure, as I said it happened after I first ran beta 1, since then the steps to reproduce are literally just open, create or run a project.

### Minimal reproduction project (MRP)

Not needed, it happens even when just creating the project

**Comment by RealMadvicius** [comment]
Hello.
There is a feature on Windows that isnt enabled by default. It allows the system to auto generate a crash dump as soon as a specified app crashes. This is something I do use at my workplace, it is heaven savior for debugging these cases. Just remember to remove the entry in the registry once you are done debugging, else it will keep generate dumps at the specified location everytime the app crashes.

easier tutorial to follow, with picture reference:
[https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm)

the official microsoft documentation about the feature:
[https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps](https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)

Let us know if it works for you to get a dump with the call stack when the crash happens.

**Comment by Castro1709** [comment]
Sadly I tried all the tutorial out there and I used the official docs, but I wasn't able to get a dump file, so looking at similar errors, I tried to create a custom build of Godot with debug symbols.
This is what I got :/
![image](https://github.com/godotengine/godot/assets/90205381/bf9a63d5-699a-46f2-938b-7a69133aabbe)

**Comment by RealMadvicius** [comment]
You have only the iGPU from your CPU or do you also have a regular GPU aswell ?
Ideas crossing my mind as potential paths to explore for testing/research are:
- a driver issue 
- in case you have an iGPU and also a regular GPU in your laptop it could be linked to context switching, you know how the OS can pick one or the other depending your power usage settings or just your AMD settings per app to pick which GPU to use, in that case you could try to force using the discret GPU instead of iGPU or the other way around explicitly in your OS or AMD settings and see if it changes anything maybe

**Comment by Castro1709** [comment]
I only have iGPU and these kind of ideas crossed my mind too, So i tried troubleshooting with the drivers but It didn't help :/

**Comment by RealMadvicius** [comment]
mmmh I wonder if Godot create some kind of hidden folder with a cache for project/editor settings, that got corrupted with the beta somehow and now crashes the editor before it can open fully.
Maybe check in you AppData\Local\Godot or LocalLow, Roaming if you have godot files there, maybe just deleting those ( rename the folder with godot_bak just in case ) and with some luck you can launch again your editor after that

**Comment by Calinou** [comment]
You need to [compile Godot yourself](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_windows.html) to get debug symbols. Use MSVC for compiling if you want to use the Visual Studio Debugger or WinDbg; otherwise, using either MSVC or MinGW is fine.

**Comment by Castro1709** [comment]
> Sadly I tried all the tutorial out there and I used the official docs, but I wasn't able to get a dump file, so looking at similar errors, I tried to create a custom build of Godot with debug symbols. This is what I got :/ ![image](https://private-user-images.githubusercontent.com/90205381/347256903-bf9a63d5-699a-46f2-938b-7a69133aabbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDM3NTUsIm5iZiI6MTcyMDY0MzQ1NSwicGF0aCI6Ii85MDIwNTM4MS8zNDcyNTY5MDMtYmY5YTYzZDUtNjk5YS00NmYyLTkzOGItN2E2OTEzM2FhYmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDIwMzA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzliNGNjMjUxMjM5NjI4NDJlZDExMTY1MzY0NGQ4MjAwMzRiNGFiZGY1NTU5ZDM1NmQxMzA5MTJiNDhhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22cM0bYXc5r8bjHc78Wsh5478Qpf6FvEhrWb3FvFX10)

But I already tried doing the debug symbols here, this debug console is from the custom build with the debug symbols on, or did I miss something here?.
Also regarding the %appdata% folders, I just tried that and for a couple of minutes it looked like it worked but after trying for a few minutes it looks like it was just a coincidence because it is still crashing casually

**Comment by Castro1709** [comment]
I really thought maybe it was an issue on my pc so I reset it to factory settings, I didn't help... :/ Maybe an issue with vulkan on my end?

**Comment by Castro1709** [comment]
I fixed it, I used this reddit thread https://www.reddit.com/r/AMDHelp/comments/1aelvdm/mini_pc_ryzen_7_5800h_vulkan_suddenly_not_working/
"OpenCL™, OpenGL®, and Vulkan® Compatibility Pack".
Which basically I uninstall that app, I won't close the issue as the Godot team may be able to do something to fix this but it's understandable if not.
I still leave the comment in case it happens to anyone else in the future.

**Comment by JetPoweredGaming** [comment]
I'm having this issue with my engine, but mine only happens when loading into any of my 3D scenes in a specific project. 
I'm using 4.3.stable.official build, and I've tested this in Forward+, Compatibility & Mobile renderers and it still happens randomly. Sometimes I can load new scenes in my game a dozen or more times with no issue, but eventually it crashes and I get this error. I attempted to uninstall OpenCL, OpenGl & Vulkan compatibility pack but I don't have those programs in my Apps list in windows.

> CrashHandlerException: Program crashed with signal 11
> Engine version: Godot Engine v4.3.stable.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
> [1] error(-1): no debug info in PE/COFF executable
> [2] error(-1): no debug info in PE/COFF executable
> [3] error(-1): no debug info in PE/COFF executable
> [4] error(-1): no debug info in PE/COFF executable
> [5] error(-1): no debug info in PE/COFF executable
> [6] error(-1): no debug info in PE/COFF executable
> [7] error(-1): no debug info in PE/COFF executable
> [8] error(-1): no debug info in PE/COFF executable
> [9] error(-1): no debug info in PE/COFF executable
> [10] error(-1): no debug info in PE/COFF executable
> [11] error(-1): no debug info in PE/COFF executable
> [12] error(-1): no debug info in PE/COFF executable
> [13] error(-1): no debug info in PE/COFF executable
> [14] error(-1): no debug info in PE/COFF executable
> [15] error(-1): no debug info in PE/COFF executable
> [16] error(-1): no debug info in PE/COFF executable
> [17] error(-1): no debug info in PE/COFF executable
> [18] error(-1): no debug info in PE/COFF executable
> [19] error(-1): no debug info in PE/COFF executable
> [20] error(-1): no debug info in PE/COFF executable
> [21] error(-1): no debug info in PE/COFF executable
> [22] error(-1): no debug info in PE/COFF executable
> [23] error(-1): no debug info in PE/COFF executable
> [24] error(-1): no debug info in PE/COFF executable
> [25] error(-1): no debug info in PE/COFF executable
> [26] error(-1): no debug info in PE/COFF executable
> [27] error(-1): no debug info in PE/COFF executable
> [28] error(-1): no debug info in PE/COFF executable

**Comment by CLOUDEI** [comment]
> I'm having this issue as well, but mine only happens when loading into any of my 3D scenes in a specific project. I'm using 4.3.stable.official build, and I've tested this in Forward+, Compatibility & Mobile renderers and it still happens randomly. Sometimes I can load new scenes in my game a dozen or more times with no issue, but eventually it crashes and I get this error. I attempted to uninstall OpenCL, OpenGl & Vulkan compatibility pack but I don't have those programs in my Apps list in windows.


I think im also having roughly the same problem as well, when ever i try and run a scene in godot forward+, and mobile the scene instantly closes itself. it actually works fine in compatibility.

**Comment by Castro1709** [comment]
@JetPoweredGaming That doesn't sound like the same problem. Different amount of errors in the backtrace, different reproduction steps, and the solution didn't work for you, I would open a different issue.

**Comment by akien-mga** [comment]
That's very unlikely to be related to this old report about a rendering driver crash in Godot 4.2 and 4.3, which was solved by updating some user drivers.

Closing this issue as the title is too generic and OP solved their problem already.
