### ISSUE TITLE
Saving Files under Windows. (.tmp)

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#956]
Hi there,
this is something that bothered me for a long time. This issue is as far as I know only windows related. At least I tested under windows and linux, but under linux it doesn't occur.

When saving files in godot, godot creates .tmp files of the original, and then deletes the old file and renames the tmp file to its original name. At least the procedure should run similar as described.
But it happens relatively often that you remain the tmp file and that file is not renamed back to its original name. 
This can result in a few bugs/issues. On the one hand resources cannot be loaded. You start your game with F5 and suddenly it abords the game because some resources cannot be found resulting in nil objects.
Suddenly missing script files. And I now even discovered that the Editor settings can be completely deleted. I always wondered why my project list sometimes got deleted and I needed to reset all android export settings under windows. I now looked into the godot folder under app data and discovered that this tmp issue caused the problem. This error got me really mad xD
So, this saving issue can happen everywhere where godot saves files.

I would call this bug critical for a release, because new users would never know what happens there. It took me a very long time to discover that you just have to rename the tmp files back to the original name and everything works. Especially for a 1.0 release this should work!

**Comment by Slipyx** [comment]
I'm having this issue with the current public 1.1beta 32bit Windows release, it wasn't present in the previous 1.0stable. Files are created and saved correctly the first time, but when editing and then saving the file, it creates the new .tmp file but never renames it back to overwrite the original. The original and the updated .tmp stick around then and the editor only ever knows about the original created file. The console mentions a rename_error in the file 'file_access_windows.cpp' at line 133.

**Comment by reduz** [comment]
Josh: Are you on Windows XP?

**Comment by Slipyx** [comment]
Yeah, should have mentioned that, not seeing it reported a lot so that might be why.

**Comment by reduz** [comment]
yes this bug happens on windows XP, because atomic rename is not supported
so you risk losing files in a bad save.
there is also no desire to support windows XP by any of the developers at
this point, since it's officially dead

**Comment by akien-mga** [comment]
So is this issue fixed in the end for Windows releases newer than XP?

**Comment by mikica1986vee** [comment]
Last time I tested, it was :)

**Comment by akien-mga** [comment]
Thanks, closing then. Feel free to reopen if you stumble on it again.

**Comment by Poobslag** [comment]
I don't want to re-open this if I'm the only one encountering this issue, but I wanted to document that I'm still seeing this occasionally on Windows 8:

```
        src/main/puzzle/piece/piece-manager.gd~RF6588cbb3.TMP
        src/main/world/Overworld.tscn~RF2bdf4f55.TMP
        src/test/test-piece-kicks-qp.gd~RF2185afae.TMP
```

These are the only TMP files that are left over for the past two weeks on a medium-sized project (15,000 SLOC) on which I'm fairly active (30 commits). So suffice to say, leaving behind one temp file every 4-5 days isn't a dealbreaker.
