### ISSUE TITLE
[4.4.dev2] Animation Player data is stored in the parent scene if the node is in "Editable Children" mode

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#96899]
### Tested versions

Reproducible in version 4.4.dev.2 only. I checked, and beta1 is working well, as is version 4.3.

### System information

macOS Sonoma 14.6.1

### Issue description

Trying the 4.4.dev2 version, every scene that contains a child scene, with Editable Children mode on, that contains an animation node, the animation node's data will be stored in the parent scene, which results in duplicating data.

https://github.com/user-attachments/assets/76efccb2-3bfd-42d2-9b39-b2baa4a1afe1

### Steps to reproduce

- Create a scene named "Child"  
- Add a label  
- Add an animation node that animates the label (position, for example)  
- Create a scene named "Parent"  
- Instantiate the scene "Child" and add it to the "Parent" scene  
- Right-click on the instantiated "Child" scene and enable the Editable Children mode  
- Save  
- Check the ".tscn" file of the "Parent" scene; you will observe that the animation node data from the "Child" is saved inside

### Minimal reproduction project (MRP)

TODO: I will provide a project as soon as I have more time available.

**Comment by akien-mga** [comment]
CC @SaracenOne @TokageItLab @KoBeWi

**Comment by Cronos87** [comment]
By the way, now I have the `&` sign in front of my tracks in the last dev version. Is it normal?

![CleanShot 2024-09-12 at 13 44 38@2x](https://github.com/user-attachments/assets/e53da605-843d-4ca8-8cf9-99d5b3bcca66)

**Comment by Cronos87** [comment]
That's good to know, thank you!

**Comment by KoBeWi** [comment]
You can run an EditorScript to open and save all scenes, using `open_scene_from_path()` and `save_scene()`.

**Comment by Cronos87** [comment]
I'll give it a try later; thank you!

**Comment by Cronos87** [comment]
I can't reproduce this issue with a build from the master. If someone wants to double-check, feel free.

**Comment by KoBeWi** [comment]
Yep, fixed on master.

**Comment by Cronos87** [comment]
Thanks for the check! Glad to know it has been fixed!

**Comment by jitspoe** [comment]
Looks like there is a regression and this is happening again.  If I add a blend file to a scene, then enable editable children, and save the scene, the .tscn file will have all the animation keys stored in it, like so:

```
[sub_resource type="Animation" id="Animation_olkws"]
resource_name = "attack_left_WIP"
length = 0.33333334
tracks/0/type = "position_3d"
tracks/0/imported = true
tracks/0/enabled = true
tracks/0/path = NodePath("Armature/Skeleton3D:pelvis")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, -0.02692015, 1.6486676, 0.11324855, 0.033333335, 1, -0.026920147, 1.6401213, 0.11324853, 0.06666667, 1, -0.026920147, 1.619742, 0.11324853, 0.1, 1, -0.026920147, 1.5954186, 0.11324854, 0.13333334, 1, -0.026920147, 1.5750393, 0.11324854, 0.16666667, 1, -0.026920147, 1.566493, 0.11324852, 0.2, 1, -0.02692015, 1.5777551, 0.11324851, 0.23333333, 1, -0.02692015, 1.6046106, 0.11324853, 0.26666668, 1, -0.02692015, 1.6366639, 0.11324853, 0.3, 1, -0.026920151, 1.6635194, 0.113248535, 0.33333334, 1, -0.026920147, 1.6747814, 0.11324853)
....
```

Edit: Does not happen with 4.6-dev4, but happens with code I synced a few days ago: v4.6.dev.custom_build [5e317ce1c]

Edit2: Actually, this may be fixed after syncing to latest.  Testing further.

**Comment by TokageItLab** [comment]
@jitspoe Regarding serialization, there have been two changes in 4.6 dev https://github.com/godotengine/godot/pull/112692 https://github.com/godotengine/godot/pull/110502. Therefore, it is expected that the serialization path will change at least once due to actions like re-importing.

If the serialization path changes randomly after that, it is a bug. But if not, it is an intended change.

**Comment by jitspoe** [comment]
At a glance, I don't think those would cause the issue.  The issue is that all the animation data is stored in the .tscn file of a scene that includes a .blend file with editable children enabled.  I was able to quickly reproduce it, then synced to latest and it didn't happen, but it's still happening on my main project with the latest code, so I'm not sure what's up.  At least now I get a nice warning letting me know my .tscn file is massive when I go to save it and that something is probably wrong. 😅

**Comment by jitspoe** [comment]
Ok, I've figured out how to reproduce it.  If you have a scene from an old version of the engine, like 4.5, that has a .blend file that has editable children (for example, to add bone attachments on an imported model), then you open and save the scene in v4.6.dev.custom_build [b79fe2e02], it saves all the animation data.

If the scene was created in the current 4.6 build and editable children is set, then it will NOT save all the animation data.  This is going to be problematic for anybody updating the engine.  Should I open a new issue for this?

**Comment by TokageItLab** [comment]
@jitspoe The default AnimationLibrary of an imported animation player should be read-only unless you make the AnimationLibrary unique using the AnimationLibraryManager, even if you made it editable.

Are you saying there are cases where you can improperly add animations to a read-only AnimationLibrary after fix https://github.com/godotengine/godot/pull/110487?

**Comment by jitspoe** [comment]
I've created a new issue for this here: https://github.com/godotengine/godot/issues/113037
