### ISSUE TITLE
PackedInt32Array handling in Editor is broken, SoftBody almost unusable.

### ISSUE THREAD

**Issue by LastPhoen1x** [godotengine/godot#97155]
### Tested versions

Reproducible: 4.3 mono stable, 4.4.dev2 mono
Working: 4.1 mono

### System information

Windows 7 - Godot 4.3 stable mono

### Issue description

Editing PackedInt32Array from the editor (SoftBody3D pinned points in this example) is fundamentally broken, changing any value other than the last removes the last entry. Clicking on the pinned points does nothing. This makes SoftBody barely usable.

Am I the only one having those issues or this have gone unnoticed somehow?

### Steps to reproduce

1. Make a SoftBody3D with 3 pinned points.
2. Change the first or second point's index.
OR
3. Click on any point in the 3D view to add it to the array - does not work.

### Minimal reproduction project (MRP)

[softbodyisbroken.zip](https://github.com/user-attachments/files/17048765/softbodyisbroken.zip)

**Comment by imp0s5ible** [comment]
I can reproduce this in v4.3.stable.official on Win11 as well. It doesn't look like the issue exists for PackedInt32Arrays exported from scripts, so this might be specific to SoftBody3D somehow.

**Comment by BurryBurst** [comment]
Did some testing on the SoftBody3D. With 2 elements in the array it swaps the first and last entry. Maybe something to do with how the array gets copied when changes occur

**Comment by LastPhoen1x** [comment]
So it is not just me or Win 7.

The same behavior of last entry dissapearing happens to AnimationPlayer array of AnimationLibraries, that made me believe this is more global in scope.

**Comment by BurryBurst** [comment]
So I just build the current master 4.4 and clicking works. Editing the array is still a bit weird the array swapping doesnt happen but sometimes entries still disappear

**Comment by BurryBurst** [comment]
Okay so I found part of why this happens:
in SoftBody3D::_set_property_pinned_points_indices(const Array &p_indices)
![image](https://github.com/user-attachments/assets/501a1154-2394-4e4a-85e3-86921fe3723b)
Line 206: It tries to find the old point_index (8) but p_indices contains the already updated indices (I incremented it from 8 to 9)
As it doesn't find it it calls pin_point with "pin" set to false, this deletes the pinned_point from the array so the pinned_points.size is now 8 instead of 9.
Next in Line 212 it now calls pin_point with pin_insert_at set to 8 (4th parameter here i) which will immediaty fail as the p_insert_at is >= to pinned_points.size (Which is 8 as the element was removed before).
![image](https://github.com/user-attachments/assets/855e18c8-1409-42a2-bb10-78fdcf858ec4)
(Ignore the if statement did that for debugging)
So the element gets removed and never gets added back.
I don't know why it checks if the index was already in there though just to remove and add it back anyways?

**Comment by BurryBurst** [comment]
@LastPhoen1x I fixed the SoftBody Array's weird behaviour but before I create a pull request I'd like to take a look at the AnimationLibrary too. Can you maybe give more info on how to replicate that error?

**Comment by LastPhoen1x** [comment]
@BurryBurst Thank you.
[95647](https://github.com/godotengine/godot/issues/95647)

**Comment by wirelessfuture** [comment]
Can confirm I'm having the same problem on Godot 4.3 stable mono - Windows 10.

**Comment by aahmyu** [comment]
I just tried this on master, clicking the pins in the editor works now, but sometimes the pin doesn't get highlighted, modifying the packed array in the editor is still broken.
