### ISSUE TITLE
Editor loads GDNative libraries

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#9747]
Windows 10 x64, Godot 2a0c0db028c84c75f4a927d0fd400449f3236952

**Issue description:**
When opening project with a GDNative library in it, the editor loads the referenced libraries, even though they are not used by the editor. This is a significant problem when developing on Windows, because your build script cannot override the loaded DLL, so you have to close the editor and open it again which is a considerable waste of time.

Expected behaviour is that the DLL is only loaded if it's a part of editor plugin, not when it is a part of the application being developed.

**Steps to reproduce:**
1. Build a GDNative library (e.g. using [C++ bindings](https://github.com/GodotNativeTools/cpp_bindings)) and ensure you have the DLL specified in the library's .tres file as a part of your project.
2. Open the project in the editor.
3. Try to delete or replace the DLL. You will get access errors.

**Comment by Zylann** [comment]
The thing is, a GDNative library can contain custom scripts with variables and methods and all, and the only way to know these is to load the library, be it an editor plugin or not.

**Comment by endragor** [comment]
Hmm, yes, you are right. Do you have suggestions for improving development experience on Windows? This is not a problem on other systems, because they don't lock the loaded dynamic library files.

**Comment by Zylann** [comment]
What is the actual problem? Why do you need to overwrite the DLL in your project?

**Comment by endragor** [comment]
I develop game parts using GDNative. When I make changes I want to compile the code, run scene in the editor and test the changes. Currently on Windows you have to relaunch the editor to test the changes every time you make them.

**Comment by Zylann** [comment]
Unfortunately I don't have a quick solution in mind. Maybe Godot would have to unload the lib somehow, so that the OS releases the lock, then load it again. But because this has to happen before and after you build the lib, it can be still a bit cumbersome.

If the lib was copied by Godot in the .import folder (just like other resources), that would make this process automatic I guess.

**Comment by endragor** [comment]
Yeah, if Godot watched the library files for modifications and reloaded the libraries when they are changed, that would work. And, as you noted, it should load/unload not the original library, but some temporary file that is copied from the original one.

**Comment by Zylann** [comment]
Note that if it did that, dependency DLLs should also be moved, or located in some way.

**Comment by karroffel** [comment]
I think I know how to fix this.

There is a `GDNativeReloadNode` that I attach to the editor node to catch the even when the editor gets refocused. When that happens then I unload the library and load it again in case there was a recompilation.

I think this could be fixed by unloading the library when focus gets lost, then you can compile and do things, then you refocus and it should load it again. Should be a relatively easy patch.

**Comment by Zylann** [comment]
@karroffel unloading the lib when focus gets lost seems dangerous if the library is performing background tasks, isn't it?

**Comment by karroffel** [comment]
Only if it's a plugin or something, yes. That could be problematic.

**Comment by Zylann** [comment]
@karroffel that could be fixed by having a way to yield for library unload rather than expecting it to happen brutally in one go?

**Comment by karroffel** [comment]
There's `godot_gdnative_terminate()` which gets called when the library gets unloaded. I could extend it to return a value whether to unload or keep it loaded

**Comment by Zylann** [comment]
But how about yielding for task completion if any? Like, the library can probably terminate, just not immediately (if threading or network stuff is at stake).

**Comment by karroffel** [comment]
@endragor @Zylann feel free to play around and see what fixes this, I'm on Linux so I can't test.

This is the code that causes the library to stay loaded until refocus.

https://github.com/godotengine/godot/blob/master/modules/gdnative/gdnative.cpp#L1261

**Comment by karroffel** [comment]
I implemented reloading now like I proposed - unloading at focus loss and reloading at focus gain. Please test

**Comment by Zylann** [comment]
Some issues related to reload should be investigated too, since tool scripts can break easily already when they are reloaded: https://github.com/godotengine/godot/issues/5969

**Comment by akien-mga** [comment]
Assuming fixed as mentioned in https://github.com/godotengine/godot/issues/9747#issuecomment-317394058. Please comment if it's not the case.

**Comment by ligazetom** [comment]
Hey, I've been trying to do this for 3.1.2 and 3.2 beta compiled from source but it still does not let me copy the new .dll even if editor lost focus. Does it work for anyone?
